# Copyright (c) 1995, 3Dfx Interactive, Inc.
# All Rights Reserved.
#
# This is UNPUBLISHED PROPRIETARY SOURCE CODE of 3Dfx Interactive, Inc.;
# the contents of this file may not be disclosed to third parties, copied or
# duplicated in any form, in whole or in part, without the prior written
# permission of 3Dfx Interactive, Inc.
#
# RESTRICTED RIGHTS LEGEND:
# Use, duplication or disclosure by the Government is subject to restrictions
# as set forth in subdivision (c)(1)(ii) of the Rights in Technical Data
# and Computer Software clause at DFARS 252.227-7013, and/or in similar or
# successor clauses in the FAR, DOD or NASA FAR Supplement. Unpublished  -
# rights reserved under the Copyright Laws of the United States.
#

# ARCADE TOOLBOX COMPILATION FLAGS
#
# -DAT_BUILD_LIBRARY - Defined when building the library
#
# -DAT_DEBUGGING  - Enable parameter checking and bug catching code.
# -DAT_PRODUCTION - Disable parameter checking and debugging code.
#                   Use this with optimized builds
# -DAT_STATISTICS       - Include statistic tracking code.
# -DAT_PENTIUM_ASSEMBLY - Use pentium optimized assembly routines
# -DAT_CHECK_TRIS       - Check every triangle against screen
#

# Preprocessor Defines
!if "$(FX_COMPILER)"=="DJGPP"
LCDEFS    = -DAT_BUILD_LIBRARY -DAT_STATISTICS
!else
LCDEFS    = -DAT_BUILD_LIBRARY -DAT_STATISTICS
!endif

!if "$(DPRIMAPI)"=="1"
LCDEFS    = -DDPRIMAPI
LADEFS    = -DDPRIMAPI
!endif

!if "$(DEBUG)"=="1"
LCDEFS    = -DAT_DEBUGGING $(LCDEFS) 
!else
LCDEFS    = -DAT_PRODUCTION -DAT_PENTIUM_ASSEMBLY $(LCDEFS)
!endif

LCDEFS =  $(LCDEFS) -DAT_DRIVER_D3D

# Header paths
LCINCS    = -I. -I..\..\atr -I$(BUILD_ROOT_SST1)\include \
            -I$(BUILD_ROOT_SST1)\glide\src \
            -I$(BUILD_ROOT_SWLIBS)\include \
            -I$(BUILD_ROOT_ARCADE)\include \
            -I$(DIRECTXSDK)\inc

# sources TBD: reinclude this dependencies are hosed
#PRIVATE_HEADERS = atd3d.h d3dmain.h ddutil.h mipmap.h \
#                  d3dapp.h d3dinit.h \
#                  d3dappi.h d3dmacs.h d3dres.h

CFILES    = d3drend.c d3dclip.c d3dtcsrc.c \
            d3dapp.c  mipmap.c d3dcalls.c ddcalls.c \
            misc.c  atd3d.c

AFILES    = d3d.asm

SUBLIBRARIES = $(DIRECTXSDK)\lib\dxguid.lib $(DIRECTXSDK)\lib\ddraw.lib

# targets
INSTALL_DESTINATION = $(BUILD_ROOT_ARCADE)
LIBRARIES    = atd3d.lib

!include $(BUILD_ROOT_SWLIBS)/include/nmake/3dfx.mak
