#
# Copyright (c) 1995, 3Dfx Interactive, Inc.
# All Rights Reserved.
#
# This is UNPUBLISHED PROPRIETARY SOURCE CODE of 3Dfx Interactive, Inc.;
# the contents of this file may not be disclosed to third parties, copied or
# duplicated in any form, in whole or in part, without the prior written
# permission of 3Dfx Interactive, Inc.
#
# RESTRICTED RIGHTS LEGEND:
# Use, duplication or disclosure by the Government is subject to restrictions
# as set forth in subdivision (c)(1)(ii) of the Rights in Technical Data
# and Computer Software clause at DFARS 252.227-7013, and/or in similar or
# successor clauses in the FAR, DOD or NASA FAR Supplement. Unpublished  -
# rights reserved under the Copyright Laws of the United States.
#
# $Revision: 4 $
# $Date: 8/31/99 5:55p $
#

THISDIR = devel
SUBDIRS = swlibs 

# We branched glide starting w/ Voodoo2(aka CVG) so 
# make sure that the right thing happens. If this sort
# of branching happens again then add it to the list below.
!if (("$(FX_GLIDE_HW)" == "SST1") || ("$(FX_GLIDE_HW)" == "SST96"))
SUBDIRS = $(SUBDIRS) sst1
!else if "$(FX_GLIDE_HW)" == "CVG"
SUBDIRS = $(SUBDIRS) cvg
!else if "$(FX_GLIDE_HW)" == "H3"
SUBDIRS = $(SUBDIRS) h3
!else if "$(FX_GLIDE_HW)" == "H5"
SUBDIRS = $(SUBDIRS) h5
!else 
!error "The FX_GLIDE_HW environment variable is not set correctly (SST1, SST96, CVG, H3, H5)"
!endif

!include $(BUILD_ROOT_SWLIBS)/include/nmake/3dfx.mak
