/* -*-c++-*- */
/* $Header: ddcdefs.h, 2, 10/11/00 8:53:28 PM, Brent$ */
/*
** Copyright (c) 2000, 3Dfx Interactive, Inc.
** All Rights Reserved.
**
** This is UNPUBLISHED PROPRIETARY SOURCE CODE of 3Dfx Interactive, Inc.;
** the contents of this file may not be disclosed to third parties, copied or
** duplicated in any form, in whole or in part, without the prior written
** permission of 3Dfx Interactive, Inc.
**
** RESTRICTED RIGHTS LEGEND:
** Use, duplication or disclosure by the Government is subject to restrictions
** as set forth in subdivision (c)(1)(ii) of the Rights in Technical Data
** and Computer Software clause at DFARS 252.227-7013, and/or in similar or
** successor clauses in the FAR, DOD or NASA FAR Supplement. Unpublished  -
** rights reserved under the Copyright Laws of the United States.
**
** File name:   ddc.c
**
** Description: DDC generic definitions.
**
** $Revision: 2$
** $Date: 10/11/00 8:53:28 PM$
**
** $Log: 
**  2    3dfx      1.0.1.0     10/11/00 Brent           Forced check in to enforce
**       branching.
**  1    Napalm    1.0         06/02/00 Dan O'Connel    
** $
** 
**
*/

#ifndef _DDCDEFS_H_
#define _DDCDEFS_H_

#define A0_EDID_SIZE (128)
#define A2_EDID_SIZE (256)

#define DDC_ADDR_1 (0xA0)          // 128 byte EDID
#define DDC_ADDR_2 (0xA2)          // 256 Byte EDID

#endif
