#ifndef __H3_H__
#define __H3_H__

/*
** Copyright (c) 1997, 3Dfx Interactive, Inc.
** All Rights Reserved.
**
** This is UNPUBLISHED PROPRIETARY SOURCE CODE of 3Dfx Interactive, Inc.;
** the contents of this file may not be disclosed to third parties, copied or
** duplicated in any form, in whole or in part, without the prior written
** permission of 3Dfx Interactive, Inc.
**
** RESTRICTED RIGHTS LEGEND:
** Use, duplication or disclosure by the Government is subject to restrictions
** as set forth in subdivision (c)(1)(ii) of the Rights in Technical Data
** and Computer Software clause at DFARS 252.227-7013, and/or in similar or
** successor clauses in the FAR, DOD or NASA FAR Supplement. Unpublished  -
** rights reserved under the Copyright Laws of the United States.
**
** $Revision: 3$
** $Date: 10/11/00 8:53:17 PM$
*/

#include <3dfx.h>
#include <gdebug.h>
#include <h3regs.h>
#include <h3defs.h>
#include <h3gdefs.h>
#include <fxvid.h>
#include <fxhal.h>
#include <vector.h>

#if (DX == 8)
#define DIRECTDRAW_VERSION  0x0800 
#define DIRECT3D_VERSION    0x0800 
#endif
#endif /* !__H3_H__ */
