#
# Copyright (c) 1995, 3Dfx Interactive, Inc.
# All Rights Reserved.
#
# This is UNPUBLISHED PROPRIETARY SOURCE CODE of 3Dfx Interactive, Inc.;
# the contents of this file may not be disclosed to third parties, copied or
# duplicated in any form, in whole or in part, without the prior written
# permission of 3Dfx Interactive, Inc.
#
# RESTRICTED RIGHTS LEGEND:
# Use, duplication or disclosure by the Government is subject to restrictions
# as set forth in subdivision (c)(1)(ii) of the Rights in Technical Data
# and Computer Software clause at DFARS 252.227-7013, and/or in similar or
# successor clauses in the FAR, DOD or NASA FAR Supplement. Unpublished  -
# rights reserved under the Copyright Laws of the United States.

!if "$(FX_GLIDE_HW)" == "SST96"
GLIDE_SRC_BASE  =       sst1
!else
GLIDE_SRC_BASE  =       $(FX_GLIDE_HW)
!endif
LCINCS          =       $(LCINCS) -I$(BUILD_ROOT)\$(GLIDE_SRC_BASE)\include

!if "$(DEBUG)" == "1"
LCDEFS		=	-DDEBUG=1
!endif

CFILES 		=       oeminit.c
RCFILE          =       oeminit.rc
HEADERS 	=       oeminit.h
PRIVATE_HEADERS =	rcver.h
LIBRARIES 	=       fxoem2x.lib

INSTALL_DESTINATION =   $(BUILD_ROOT)\$(GLIDE_SRC_BASE)

# Make a static link library for things like the diags.
!if "$(FX_DLL_BUILD)" == "1"
FX_DLL_LIBRARY  =       1
!else
LCDEFS          =       $(LCDEFS) -DFX_STATIC_BUILD
!endif

LCDEFS          =       $(LCDEFS)

!include $(BUILD_ROOT)\swlibs/include/nmake/3dfx.mak

!if "$(FX_TARGET)" == "WIN32"
!if "$(FX_DLL_BUILD)" != ""
fxoem2x.dll:
!endif
!endif

fxbldno.exe: fxbldno.c $(HEADERS) $(PRIVATE_HEADERS)
	$(CC) -o $@ fxbldno.c $(GCDEFS) $(LCDEFS) $(VCDEFS) $(LCOPTS) $(LDFLAGS)

fxbldno.h: fxbldno.exe
        fxbldno > fxbldno.h

oeminit.res: rcver.h fxbldno.h
