/*
** Copyright 1997, Silicon Graphics, Inc.
** All Rights Reserved.
**
** This is UNPUBLISHED PROPRIETARY SOURCE CODE of Silicon Graphics, Inc.;
** the contents of this file may not be disclosed to third parties, copied or
** duplicated in any form, in whole or in part, without the prior written
** permission of Silicon Graphics, Inc.
**
** RESTRICTED RIGHTS LEGEND:
** Use, duplication or disclosure by the Government is subject to restrictions
** as set forth in subdivision (c)(1)(ii) of the Rights in Technical Data
** and Computer Software clause at DFARS 252.227-7013, and/or in similar or
** successor clauses in the FAR, DOD or NASA FAR Supplement. Unpublished -
** rights reserved under the Copyright Laws of the United States.
*/

#include "shell.h"


#ifdef GL_VERSION_1_1

enumCheckRec enum_Check1_1[] = {
    {
	"GL_INDEX_LOGIC_OP", GL_INDEX_LOGIC_OP, 3057
    },
    {
	"GL_COLOR_LOGIC_OP", GL_COLOR_LOGIC_OP, 3058
    },
    {
	"GL_MAX_CLIENT_ATTRIB_STACK_DEPTH", GL_MAX_CLIENT_ATTRIB_STACK_DEPTH,
	3387
    },
    {
	"GL_FEEDBACK_BUFFER_POINTER", GL_FEEDBACK_BUFFER_POINTER, 3568
    },
    {
	"GL_FEEDBACK_BUFFER_SIZE", GL_FEEDBACK_BUFFER_SIZE, 3569
    },
    {
	"GL_FEEDBACK_BUFFER_TYPE", GL_FEEDBACK_BUFFER_TYPE, 3570
    },
    {
	"GL_SELECTION_BUFFER_POINTER", GL_SELECTION_BUFFER_POINTER, 3571
    },
    {
	"GL_SELECTION_BUFFER_SIZE", GL_SELECTION_BUFFER_SIZE, 3572
    },
    {
	"GL_DOUBLE", GL_DOUBLE, 5130
    },
    {
	"GL_CLIENT_PIXEL_STORE_BIT", GL_CLIENT_PIXEL_STORE_BIT, 1
    },
    {
	"GL_CLIENT_VERTEX_ARRAY_BIT", GL_CLIENT_VERTEX_ARRAY_BIT, 2
    },
    {
	"GL_CLIENT_ALL_ATTRIB_BITS", GL_CLIENT_ALL_ATTRIB_BITS, -1
    },
    {
	"GL_POLYGON_OFFSET_FACTOR", GL_POLYGON_OFFSET_FACTOR, 32824
    },
    {
	"GL_POLYGON_OFFSET_UNITS", GL_POLYGON_OFFSET_UNITS, 10752
    },
    {
	"GL_POLYGON_OFFSET_POINT", GL_POLYGON_OFFSET_POINT, 10753
    },
    {
	"GL_POLYGON_OFFSET_LINE", GL_POLYGON_OFFSET_LINE, 10754
    },
    {
	"GL_POLYGON_OFFSET_FILL", GL_POLYGON_OFFSET_FILL, 32823
    },
    {
	"GL_ALPHA4", GL_ALPHA4, 32827
    },
    {
	"GL_ALPHA8", GL_ALPHA8, 32828
    },
    {
	"GL_ALPHA12", GL_ALPHA12, 32829
    },
    {
	"GL_ALPHA16", GL_ALPHA16, 32830
    },
    {
	"GL_LUMINANCE4", GL_LUMINANCE4, 32831
    },
    {
	"GL_LUMINANCE8", GL_LUMINANCE8, 32832
    },
    {
	"GL_LUMINANCE12", GL_LUMINANCE12, 32833
    },
    {
	"GL_LUMINANCE16", GL_LUMINANCE16, 32834
    },
    {
	"GL_LUMINANCE4_ALPHA4", GL_LUMINANCE4_ALPHA4, 32835
    },
    {
	"GL_LUMINANCE6_ALPHA2", GL_LUMINANCE6_ALPHA2, 32836
    },
    {
	"GL_LUMINANCE8_ALPHA8", GL_LUMINANCE8_ALPHA8, 32837
    },
    {
	"GL_LUMINANCE12_ALPHA4", GL_LUMINANCE12_ALPHA4, 32838
    },
    {
	"GL_LUMINANCE12_ALPHA12", GL_LUMINANCE12_ALPHA12, 32839
    },
    {
	"GL_LUMINANCE16_ALPHA16", GL_LUMINANCE16_ALPHA16, 32840
    },
    {
	"GL_INTENSITY", GL_INTENSITY, 32841
    },
    {
	"GL_INTENSITY4", GL_INTENSITY4, 32842
    },
    {
	"GL_INTENSITY8", GL_INTENSITY8, 32843
    },
    {
	"GL_INTENSITY12", GL_INTENSITY12, 32844
    },
    {
	"GL_INTENSITY16", GL_INTENSITY16, 32845
    },
    {
	"GL_R3_G3_B2", GL_R3_G3_B2, 10768
    },
    {
	"GL_RGB4", GL_RGB4, 32847
    },
    {
	"GL_RGB5", GL_RGB5, 32848
    },
    {
	"GL_RGB8", GL_RGB8, 32849
    },
    {
	"GL_RGB10", GL_RGB10, 32850
    },
    {
	"GL_RGB12", GL_RGB12, 32851
    },
    {
	"GL_RGB16", GL_RGB16, 32852
    },
    {
	"GL_RGBA2", GL_RGBA2, 32853
    },
    {
	"GL_RGBA4", GL_RGBA4, 32854
    },
    {
	"GL_RGB5_A1", GL_RGB5_A1, 32855
    },
    {
	"GL_RGBA8", GL_RGBA8, 32856
    },
    {
	"GL_RGB10_A2", GL_RGB10_A2, 32857
    },
    {
	"GL_RGBA12", GL_RGBA12, 32858
    },
    {
	"GL_RGBA16", GL_RGBA16, 32859
    },
    {
	"GL_TEXTURE_RED_SIZE", GL_TEXTURE_RED_SIZE, 32860
    },
    {
	"GL_TEXTURE_GREEN_SIZE", GL_TEXTURE_GREEN_SIZE, 32861
    },
    {
	"GL_TEXTURE_BLUE_SIZE", GL_TEXTURE_BLUE_SIZE, 32862
    },
    {
	"GL_TEXTURE_ALPHA_SIZE", GL_TEXTURE_ALPHA_SIZE, 32863
    },
    {
	"GL_TEXTURE_LUMINANCE_SIZE", GL_TEXTURE_LUMINANCE_SIZE, 32864
    },
    {
	"GL_TEXTURE_INTENSITY_SIZE", GL_TEXTURE_INTENSITY_SIZE, 32865
    },
    {
	"GL_TEXTURE_INTERNAL_FORMAT", GL_TEXTURE_INTERNAL_FORMAT, 4099
    },
    {
	"GL_PROXY_TEXTURE_1D", GL_PROXY_TEXTURE_1D, 32867
    },
    {
	"GL_PROXY_TEXTURE_2D", GL_PROXY_TEXTURE_2D, 32868
    },
    {
	"GL_TEXTURE_PRIORITY", GL_TEXTURE_PRIORITY, 32870
    },
    {
	"GL_TEXTURE_RESIDENT", GL_TEXTURE_RESIDENT, 32871
    },
    {
	"GL_TEXTURE_BINDING_1D", GL_TEXTURE_BINDING_1D, 32872
    },
    {
	"GL_TEXTURE_BINDING_2D", GL_TEXTURE_BINDING_2D, 32873
    },
    {
	"GL_VERTEX_ARRAY", GL_VERTEX_ARRAY, 32884
    },
    {
	"GL_NORMAL_ARRAY", GL_NORMAL_ARRAY, 32885
    },
    {
	"GL_COLOR_ARRAY", GL_COLOR_ARRAY, 32886
    },
    {
	"GL_INDEX_ARRAY", GL_INDEX_ARRAY, 32887
    },
    {
	"GL_TEXTURE_COORD_ARRAY", GL_TEXTURE_COORD_ARRAY, 32888
    },
    {
	"GL_EDGE_FLAG_ARRAY", GL_EDGE_FLAG_ARRAY, 32889
    },
    {
	"GL_VERTEX_ARRAY_SIZE", GL_VERTEX_ARRAY_SIZE, 32890
    },
    {
	"GL_VERTEX_ARRAY_TYPE", GL_VERTEX_ARRAY_TYPE, 32891
    },
    {
	"GL_VERTEX_ARRAY_STRIDE", GL_VERTEX_ARRAY_STRIDE, 32892
    },
    {
	"GL_NORMAL_ARRAY_TYPE", GL_NORMAL_ARRAY_TYPE, 32894
    },
    {
	"GL_NORMAL_ARRAY_STRIDE", GL_NORMAL_ARRAY_STRIDE, 32895
    },
    {
	"GL_COLOR_ARRAY_SIZE", GL_COLOR_ARRAY_SIZE, 32897
    },
    {
	"GL_COLOR_ARRAY_TYPE", GL_COLOR_ARRAY_TYPE, 32898
    },
    {
	"GL_COLOR_ARRAY_STRIDE", GL_COLOR_ARRAY_STRIDE, 32899
    },
    {
	"GL_INDEX_ARRAY_TYPE", GL_INDEX_ARRAY_TYPE, 32901
    },
    {
	"GL_INDEX_ARRAY_STRIDE", GL_INDEX_ARRAY_STRIDE, 32902
    },
    {
	"GL_TEXTURE_COORD_ARRAY_SIZE", GL_TEXTURE_COORD_ARRAY_SIZE, 32904
    },
    {
	"GL_TEXTURE_COORD_ARRAY_TYPE", GL_TEXTURE_COORD_ARRAY_TYPE, 32905
    },
    {
	"GL_TEXTURE_COORD_ARRAY_STRIDE", GL_TEXTURE_COORD_ARRAY_STRIDE, 32906
    },
    {
	"GL_EDGE_FLAG_ARRAY_STRIDE", GL_EDGE_FLAG_ARRAY_STRIDE, 32908
    },
    {
	"GL_VERTEX_ARRAY_POINTER", GL_VERTEX_ARRAY_POINTER, 32910
    },
    {
	"GL_NORMAL_ARRAY_POINTER", GL_NORMAL_ARRAY_POINTER, 32911
    },
    {
	"GL_COLOR_ARRAY_POINTER", GL_COLOR_ARRAY_POINTER, 32912
    },
    {
	"GL_INDEX_ARRAY_POINTER", GL_INDEX_ARRAY_POINTER, 32913
    },
    {
	"GL_TEXTURE_COORD_ARRAY_POINTER", GL_TEXTURE_COORD_ARRAY_POINTER, 32914
    },
    {
	"GL_EDGE_FLAG_ARRAY_POINTER", GL_EDGE_FLAG_ARRAY_POINTER, 32915
    },
    {
	"GL_V2F", GL_V2F, 10784
    },
    {
	"GL_V3F", GL_V3F, 10785
    },
    {
	"GL_C4UB_V2F", GL_C4UB_V2F, 10786
    },
    {
	"GL_C4UB_V3F", GL_C4UB_V3F, 10787
    },
    {
	"GL_C3F_V3F", GL_C3F_V3F, 10788
    },
    {
	"GL_N3F_V3F", GL_N3F_V3F, 10789
    },
    {
	"GL_C4F_N3F_V3F", GL_C4F_N3F_V3F, 10790
    },
    {
	"GL_T2F_V3F", GL_T2F_V3F, 10791
    },
    {
	"GL_T4F_V4F", GL_T4F_V4F, 10792
    },
    {
	"GL_T2F_C4UB_V3F", GL_T2F_C4UB_V3F, 10793
    },
    {
	"GL_T2F_C3F_V3F", GL_T2F_C3F_V3F, 10794
    },
    {
	"GL_T2F_N3F_V3F", GL_T2F_N3F_V3F, 10795
    },
    {
	"GL_T2F_C4F_N3F_V3F", GL_T2F_C4F_N3F_V3F, 10796
    },
    {
	"GL_T4F_C4F_N3F_V4F", GL_T4F_C4F_N3F_V4F, 10797
    },
    {
	"End of List", -1, -1
    }
};

enumTestRec enum_TextureInternalFormat[] = {
    "Component of 1", 1,
    "Component of 2", 2,
    "Component of 3", 3,
    "Component of 4", 4,
    "GL_ALPHA",  GL_ALPHA,
    "GL_LUMINANCE",  GL_LUMINANCE,
    "GL_LUMINANCE_ALPHA",  GL_LUMINANCE_ALPHA,
    "GL_RGB",  GL_RGB,
    "GL_RGBA",  GL_RGBA,
    "GL_ALPHA4", GL_ALPHA4,
    "GL_ALPHA8", GL_ALPHA8,
    "GL_ALPHA12", GL_ALPHA12,
    "GL_ALPHA16", GL_ALPHA16,
    "GL_LUMINANCE4", GL_LUMINANCE4,
    "GL_LUMINANCE8", GL_LUMINANCE8,
    "GL_LUMINANCE12", GL_LUMINANCE12,
    "GL_LUMINANCE16", GL_LUMINANCE16,
    "GL_LUMINANCE4_ALPHA4", GL_LUMINANCE4_ALPHA4,
    "GL_LUMINANCE6_ALPHA2", GL_LUMINANCE6_ALPHA2,
    "GL_LUMINANCE8_ALPHA8", GL_LUMINANCE8_ALPHA8,
    "GL_LUMINANCE12_ALPHA4", GL_LUMINANCE12_ALPHA4,
    "GL_LUMINANCE12_ALPHA12", GL_LUMINANCE12_ALPHA12,
    "GL_LUMINANCE16_ALPHA16", GL_LUMINANCE16_ALPHA16,
    "GL_INTENSITY", GL_INTENSITY,
    "GL_INTENSITY4", GL_INTENSITY4,
    "GL_INTENSITY8", GL_INTENSITY8,
    "GL_INTENSITY12", GL_INTENSITY12,
    "GL_INTENSITY16", GL_INTENSITY16,
    "GL_R3_G3_B2", GL_R3_G3_B2,
    "GL_RGB4", GL_RGB4,
    "GL_RGB5", GL_RGB5,
    "GL_RGB8", GL_RGB8,
    "GL_RGB10", GL_RGB10,
    "GL_RGB12", GL_RGB12,
    "GL_RGB16", GL_RGB16,
    "GL_RGBA2", GL_RGBA2,
    "GL_RGBA4", GL_RGBA4,
    "GL_RGB5_A1", GL_RGB5_A1,
    "GL_RGBA8", GL_RGBA8,
    "GL_RGB10_A2", GL_RGB10_A2,
    "GL_RGBA12", GL_RGBA12,
    "GL_RGBA16", GL_RGBA16,
    "End of List", -1
};

enumTestRec enum_CopyTextureInternalFormat[] = {
    "GL_ALPHA",  GL_ALPHA,
    "GL_LUMINANCE",  GL_LUMINANCE,
    "GL_LUMINANCE_ALPHA",  GL_LUMINANCE_ALPHA,
    "GL_RGB",  GL_RGB,
    "GL_RGBA",  GL_RGBA,
    "GL_ALPHA4", GL_ALPHA4,
    "GL_ALPHA8", GL_ALPHA8,
    "GL_ALPHA12", GL_ALPHA12,
    "GL_ALPHA16", GL_ALPHA16,
    "GL_LUMINANCE4", GL_LUMINANCE4,
    "GL_LUMINANCE8", GL_LUMINANCE8,
    "GL_LUMINANCE12", GL_LUMINANCE12,
    "GL_LUMINANCE16", GL_LUMINANCE16,
    "GL_LUMINANCE4_ALPHA4", GL_LUMINANCE4_ALPHA4,
    "GL_LUMINANCE6_ALPHA2", GL_LUMINANCE6_ALPHA2,
    "GL_LUMINANCE8_ALPHA8", GL_LUMINANCE8_ALPHA8,
    "GL_LUMINANCE12_ALPHA4", GL_LUMINANCE12_ALPHA4,
    "GL_LUMINANCE12_ALPHA12", GL_LUMINANCE12_ALPHA12,
    "GL_LUMINANCE16_ALPHA16", GL_LUMINANCE16_ALPHA16,
    "GL_INTENSITY", GL_INTENSITY,
    "GL_INTENSITY4", GL_INTENSITY4,
    "GL_INTENSITY8", GL_INTENSITY8,
    "GL_INTENSITY12", GL_INTENSITY12,
    "GL_INTENSITY16", GL_INTENSITY16,
    "GL_R3_G3_B2", GL_R3_G3_B2,
    "GL_RGB4", GL_RGB4,
    "GL_RGB5", GL_RGB5,
    "GL_RGB8", GL_RGB8,
    "GL_RGB10", GL_RGB10,
    "GL_RGB12", GL_RGB12,
    "GL_RGB16", GL_RGB16,
    "GL_RGBA2", GL_RGBA2,
    "GL_RGBA4", GL_RGBA4,
    "GL_RGB5_A1", GL_RGB5_A1,
    "GL_RGBA8", GL_RGBA8,
    "GL_RGB10_A2", GL_RGB10_A2,
    "GL_RGBA12", GL_RGBA12,
    "GL_RGBA16", GL_RGBA16,
    "End of List", -1
};

/* PixelFormat without COLOR_INDEX, STENCIL_INDEX, or DEPTH_COMPONENT */
enumTestRec enum_TextureFormat1_1[] = {
    "GL_RED", GL_RED,
    "GL_GREEN", GL_GREEN,
    "GL_BLUE", GL_BLUE,
    "GL_ALPHA", GL_ALPHA,
    "GL_RGB", GL_RGB,
    "GL_RGBA", GL_RGBA,
    "GL_LUMINANCE", GL_LUMINANCE,
    "GL_LUMINANCE_ALPHA", GL_LUMINANCE_ALPHA,
    "End of List", -1
};

/* PixelType without bitmap */
enumTestRec enum_TextureType1_1[] = { 
    "GL_BYTE", GL_BYTE,
    "GL_UNSIGNED_BYTE", GL_UNSIGNED_BYTE,
    "GL_SHORT", GL_SHORT,
    "GL_UNSIGNED_SHORT", GL_UNSIGNED_SHORT,
    "GL_INT", GL_INT,
    "GL_UNSIGNED_INT", GL_UNSIGNED_INT,
    "GL_FLOAT", GL_FLOAT,
    "End of List", -1
};

enumTestRec enum_TexTarget2D1_1[] = {
    "GL_TEXTURE_2D", GL_TEXTURE_2D,
    "GL_PROXY_TEXTURE_2D", GL_PROXY_TEXTURE_2D,
    "End of List", -1
};

enumTestRec enum_TexTarget1D1_1[] = {
    "GL_TEXTURE_1D", GL_TEXTURE_1D,
    "GL_PROXY_TEXTURE_1D", GL_PROXY_TEXTURE_1D,
    "End of List", -1
};

enumTestRec enum_Enable1_1[] = {
    "GL_INDEX_LOGIC_OP", GL_INDEX_LOGIC_OP,
    "GL_COLOR_LOGIC_OP", GL_COLOR_LOGIC_OP,
    "GL_POLYGON_OFFSET_POINT", GL_POLYGON_OFFSET_POINT,
    "GL_POLYGON_OFFSET_LINE", GL_POLYGON_OFFSET_LINE,
    "GL_POLYGON_OFFSET_FILL", GL_POLYGON_OFFSET_FILL,
    "End of List", -1
};

enumTestRec enum_EnableClientState1_1[] = {
    "GL_VERTEX_ARRAY", GL_VERTEX_ARRAY,
    "GL_NORMAL_ARRAY", GL_NORMAL_ARRAY,
    "GL_COLOR_ARRAY", GL_COLOR_ARRAY,
    "GL_INDEX_ARRAY", GL_INDEX_ARRAY,
    "GL_TEXTURE_COORD_ARRAY", GL_TEXTURE_COORD_ARRAY,
    "GL_EDGE_FLAG_ARRAY", GL_EDGE_FLAG_ARRAY,
    "End of List", -1
};

enumTestRec enum_GetTarget1_1[] = {
    "GL_INDEX_LOGIC_OP", GL_INDEX_LOGIC_OP,
    "GL_COLOR_LOGIC_OP", GL_COLOR_LOGIC_OP,
    "GL_MAX_CLIENT_ATTRIB_STACK_DEPTH", GL_MAX_CLIENT_ATTRIB_STACK_DEPTH,
    "GL_FEEDBACK_BUFFER_SIZE", GL_FEEDBACK_BUFFER_SIZE,
    "GL_FEEDBACK_BUFFER_TYPE", GL_FEEDBACK_BUFFER_TYPE,
    "GL_SELECTION_BUFFER_SIZE", GL_SELECTION_BUFFER_SIZE,
    "GL_TEXTURE_BINDING_1D", GL_TEXTURE_BINDING_1D,
    "GL_TEXTURE_BINDING_2D", GL_TEXTURE_BINDING_2D,
    "GL_VERTEX_ARRAY", GL_VERTEX_ARRAY,
    "GL_NORMAL_ARRAY", GL_NORMAL_ARRAY,
    "GL_COLOR_ARRAY", GL_COLOR_ARRAY,
    "GL_INDEX_ARRAY", GL_INDEX_ARRAY,
    "GL_TEXTURE_COORD_ARRAY", GL_TEXTURE_COORD_ARRAY,
    "GL_EDGE_FLAG_ARRAY", GL_EDGE_FLAG_ARRAY,
    "GL_VERTEX_ARRAY_SIZE", GL_VERTEX_ARRAY_SIZE,
    "GL_VERTEX_ARRAY_TYPE", GL_VERTEX_ARRAY_TYPE,
    "GL_VERTEX_ARRAY_STRIDE", GL_VERTEX_ARRAY_STRIDE,
    "GL_NORMAL_ARRAY_TYPE", GL_NORMAL_ARRAY_TYPE,
    "GL_NORMAL_ARRAY_STRIDE", GL_NORMAL_ARRAY_STRIDE,
    "GL_COLOR_ARRAY_SIZE", GL_COLOR_ARRAY_SIZE,
    "GL_COLOR_ARRAY_TYPE", GL_COLOR_ARRAY_TYPE,
    "GL_COLOR_ARRAY_STRIDE", GL_COLOR_ARRAY_STRIDE,
    "GL_INDEX_ARRAY_TYPE", GL_INDEX_ARRAY_TYPE,
    "GL_INDEX_ARRAY_STRIDE", GL_INDEX_ARRAY_STRIDE,
    "GL_TEXTURE_COORD_ARRAY_SIZE", GL_TEXTURE_COORD_ARRAY_SIZE,
    "GL_TEXTURE_COORD_ARRAY_TYPE", GL_TEXTURE_COORD_ARRAY_TYPE,
    "GL_TEXTURE_COORD_ARRAY_STRIDE", GL_TEXTURE_COORD_ARRAY_STRIDE,
    "GL_EDGE_FLAG_ARRAY_STRIDE", GL_EDGE_FLAG_ARRAY_STRIDE,
    "GL_POLYGON_OFFSET_FACTOR", GL_POLYGON_OFFSET_FACTOR,
    "GL_POLYGON_OFFSET_UNITS", GL_POLYGON_OFFSET_UNITS,
    "End of List", -1
};

enumTestRec enum_GetPointerTarget1_1[] = {
    "GL_VERTEX_ARRAY_POINTER", GL_VERTEX_ARRAY_POINTER,
    "GL_NORMAL_ARRAY_POINTER", GL_NORMAL_ARRAY_POINTER,
    "GL_COLOR_ARRAY_POINTER", GL_COLOR_ARRAY_POINTER,
    "GL_INDEX_ARRAY_POINTER", GL_INDEX_ARRAY_POINTER,
    "GL_TEXTURE_COORD_ARRAY_POINTER", GL_TEXTURE_COORD_ARRAY_POINTER,
    "GL_EDGE_FLAG_ARRAY_POINTER", GL_EDGE_FLAG_ARRAY_POINTER,
    "GL_FEEDBACK_BUFFER_POINTER", GL_FEEDBACK_BUFFER_POINTER,
    "GL_SELECTION_BUFFER_POINTER", GL_SELECTION_BUFFER_POINTER,
    "End of List", -1
};

enumTestRec enum_GetTextureLevelParameter1_1[] = {
    "GL_TEXTURE_RED_SIZE", GL_TEXTURE_RED_SIZE,
    "GL_TEXTURE_GREEN_SIZE", GL_TEXTURE_GREEN_SIZE,
    "GL_TEXTURE_BLUE_SIZE", GL_TEXTURE_BLUE_SIZE,
    "GL_TEXTURE_ALPHA_SIZE", GL_TEXTURE_ALPHA_SIZE,
    "GL_TEXTURE_LUMINANCE_SIZE", GL_TEXTURE_LUMINANCE_SIZE,
    "GL_TEXTURE_INTENSITY_SIZE", GL_TEXTURE_INTENSITY_SIZE,
    "End of List", -1
};

enumTestRec enum_GetTextureParameter1_1[] = {
    "GL_TEXTURE_PRIORITY", GL_TEXTURE_PRIORITY,
    "GL_TEXTURE_RESIDENT", GL_TEXTURE_RESIDENT,
    "End of List", -1
};

#endif
