##
##  Makefile for Windows NT
##


!include <ntwin32.mak>

CFLAGS   = -I$(GLUTHOME) -DWIN32 -nologo -W1 -O2

OBJS     = tdDecimate.obj tdError.obj tdDraw.obj tdFile.obj tdGenerate.obj \
	   tdMisc.obj tdOBJ.obj tdRGB.obj


td.lib	: $(OBJS)
	lib -nologo -out:td.lib $(OBJS)
