#
# Copyright (c) 1995, 3Dfx Interactive, Inc.
# All Rights Reserved.
#
# This is UNPUBLISHED PROPRIETARY SOURCE CODE of 3Dfx Interactive, Inc.;
# the contents of this file may not be disclosed to third parties, copied or
# duplicated in any form, in whole or in part, without the prior written
# permission of 3Dfx Interactive, Inc.
#
# RESTRICTED RIGHTS LEGEND:
# Use, duplication or disclosure by the Government is subject to restrictions
# as set forth in subdivision (c)(1)(ii) of the Rights in Technical Data
# and Computer Software clause at DFARS 252.227-7013, and/or in similar or
# successor clauses in the FAR, DOD or NASA FAR Supplement. Unpublished  -
# rights reserved under the Copyright Laws of the United States.
#

FX_DLL_BUILD = 1
FX_DLL_LIBRARY = 1

!if "$(FX_GLIDE3)" != ""
LCDEFS = $(LCDEFS) -DGLIDE3
LCINCS    = -I$(BUILD_ROOT_ARCADE)\include \
            -I$(BUILD_ROOT)\cvg\include
!else            

LCINCS    = -I$(BUILD_ROOT_ARCADE)\include \
            -I$(BUILD_ROOT_SST1)\include
!endif

RCFILE         = matui.rc

CFILES         = matdlg.c 
# targets
LIBRARIES      = matdlg.lib

!if "$(FX_GLIDE3)" != ""
LLDLIBS = $(BUILD_ROOT_ARCADE)\lib\atu.lib    \
          $(BUILD_ROOT_ARCADE)\lib\atm.lib    \
          $(BUILD_ROOT_ARCADE)\lib\atr.lib    \
          $(BUILD_ROOT_ARCADE)\lib\atg.lib    \
          $(BUILD_ROOT)\cvg\lib\glide3x.lib    
!else            
LLDLIBS = $(BUILD_ROOT_ARCADE)\lib\atu.lib    \
          $(BUILD_ROOT_ARCADE)\lib\atm.lib    \
          $(BUILD_ROOT_ARCADE)\lib\atr.lib    \
          $(BUILD_ROOT_ARCADE)\lib\atg.lib    \
          $(BUILD_ROOT_SST1)\lib\glide2x.lib    
!endif

!include $(BUILD_ROOT_SWLIBS)/include/nmake/3dfx.mak
