//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by matui.rc
//
#define IDD_DIALOG1                     101
#define IDC_TEXTURE                     1005
#define IDC_EDIT2                       1006
#define IDC_EDIT3                       1007
#define IDC_EDIT4                       1008
#define IDC_EDIT5                       1009
#define IDC_EDIT6                       1010
#define IDC_EDIT7                       1011
#define IDC_EDIT8                       1012
#define IDC_EDIT9                       1013
#define IDC_EDIT10                      1014
#define IDC_EDIT11                      1015
#define IDC_COMBO1                      1016
#define IDC_EDIT12                      1017
#define IDC_COMBO2                      1018
#define IDC_COMBO3                      1019
#define IDC_COMBO4                      1020
#define IDC_COMBO5                      1021
#define IDC_COMBO6                      1022
#define IDC_RADIO2                      1024

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1024
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
