#
# THIS SOFTWARE IS SUBJECT TO COPYRIGHT PROTECTION AND IS OFFERED ONLY
# PURSUANT TO THE 3DFX GLIDE GENERAL PUBLIC LICENSE. THERE IS NO RIGHT
# TO USE THE GLIDE TRADEMARK WITHOUT PRIOR WRITTEN PERMISSION OF 3DFX
# INTERACTIVE, INC. A COPY OF THIS LICENSE MAY BE OBTAINED FROM THE 
# DISTRIBUTOR OR BY CONTACTING 3DFX INTERACTIVE INC(info@3dfx.com). 
# THIS PROGRAM IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER 
# EXPRESSED OR IMPLIED. SEE THE 3DFX GLIDE GENERAL PUBLIC LICENSE FOR A
# FULL TEXT OF THE NON-WARRANTY PROVISIONS.  
# 
# USE, DUPLICATION OR DISCLOSURE BY THE GOVERNMENT IS SUBJECT TO
# RESTRICTIONS AS SET FORTH IN SUBDIVISION (C)(1)(II) OF THE RIGHTS IN
# TECHNICAL DATA AND COMPUTER SOFTWARE CLAUSE AT DFARS 252.227-7013,
# AND/OR IN SIMILAR OR SUCCESSOR CLAUSES IN THE FAR, DOD OR NASA FAR
# SUPPLEMENT. UNPUBLISHED RIGHTS RESERVED UNDER THE COPYRIGHT LAWS OF
# THE UNITED STATES.  
# 
# COPYRIGHT 3DFX INTERACTIVE, INC. 1999, ALL RIGHTS RESERVED
#
# $Revision: 9 $
# $Date: 6/26/96 12:35p $


# This makefile is intended to work *WITHOUT* the need for external environment
# variables (whether they be 3DFX or Microsoft DDK specific). This is whyc
# some of the DDK include files are duplicated here.
#
# Please don't introduce MS or 3Dfx dependencies here.
# 

AOPTS = -W2 -c -Cx -Zm -I. -nologo  #-coff
ADEFS = -DBLD_COFF -DMASM6 -DMINIVDD=1 -DVGASWITCH -DIS_32

#ADEFS = $(ADEFS) -DDEBLEVEL=1 -DDEBUG          # Enable for debug


all: incs 
debug: all                              # For MS: nmake debug
retail: all                             # for MS: nmake retail

clean:
   if exist *.obj del *.obj
   if exist *.ilk del *.ilk
   if exist *.sbr del *.sbr
   if exist *.pch del *.pch
   if exist *.pdb del *.pdb
   if exist *.map del *.map
   if exist *.exp del *.exp
   if exist *.lib del *.lib
   if exist *.exe del *.exe
   if exist *.vxd del *.vxd

neat:   clean
clobber: clean

install:

# These make 3dfx.mak happy when calling this directory recursively.
incs:
  xcopy /d/k/r/i fxmemmap.h $(BUILD_ROOT_SWLIBS)\include

libs:

bins: 

copy-sources: 

install-source-headers:
	xcopy /d/k/r/i fxmemmap.h $(KIT_INSTALL)\src\include
	attrib +r $(KIT_INSTALL)\src\include\fxmemmap.h
