/*
 * Copyright (c) 1997, 3Dfx Interactive, Inc.
 * All Rights Reserved.
 *
 */

/*++

Module Name:

    ntremap.h

Abstract:


Environment:

    kernel mode

Notes:


Revision History:

--*/


//
// Define the various device type values.  Note that values used by Microsoft
// Corporation are in the range 0-32767, and 32768-65535 are reserved for use
// by customers.
//

#define FILE_DEVICE_NTREMAP  0x0000a3df			// 3Dfx NTRemap
