hrmGetNumTargets
hrmGetTargetAtIndex
hrmGetExtension

hrmGetVersionInfo
hrmAddExtensions
hrmRemoveExtensions
hrmGetDeviceConfig
	  
hrmGetTargetFifoInfo
hrmFifoWrap
hrmHwFifoPtr
hrmFifoUpdate
hrmAllocWinContext
hrmFreeWinContext
hrmExecuteWinFifo
hrmGetAGPInfo

hrmDisableFifo2D
hrmEnableFifo2D

hrmSetExclusiveMode
hrmReleaseExclusiveMode
hrmSetVideoMode
hrmGetTargetBoardInfoExt

hrmGetPrefs
hrmSetPrefs
hrmSetModeFlags
hrmSetModePrefs

hrmCreateMemoryArea
hrmDeleteMemoryArea
hrmInvalidateMemoryBlocks
hrmAllocateBlock
hrmFreeBlock   

hrmLoadAccel
hrmUnloadAccel

hrm_InitPatchManager
hrm_RegisterPatches
hrm_DeregisterPatches

hrmSetVideoOverlay

hrm_GetPrefsTable
hrm_RegisterPrefsChanged
hrm_UnregisterPrefsChanged
hrm_ChangePrefs

hrm_GetSettingUL
hrm_SetSettingUL
hrm_GetSettingF
hrm_SetSettingF

hrm_Register3DClient
hrm_GetOpenGLEnvVars
hrm_GetGlideEnvVars
hrm_GetRaveEnvVars

hrmArbiterGet
hrmArbiterRelease
hrmArbiterQueue
