#
# Copyright (c) 1997, 3Dfx Interactive, Inc.
# All Rights Reserved.
#
# This is UNPUBLISHED PROPRIETARY SOURCE CODE of 3Dfx Interactive, Inc.;
# the contents of this file may not be disclosed to third parties, copied or
# duplicated in any form, in whole or in part, without the prior written
# permission of 3Dfx Interactive, Inc.
#
# RESTRICTED RIGHTS LEGEND:
# Use, duplication or disclosure by the Government is subject to restrictions
# as set forth in subdivision (c)(1)(ii) of the Rights in Technical Data
# and Computer Software clause at DFARS 252.227-7013, and/or in similar or
# successor clauses in the FAR, DOD or NASA FAR Supplement. Unpublished  -
# rights reserved under the Copyright Laws of the United States.
#
# $Revision: 5 $
# $Date: 3/29/96 7:40a $
#

LCDEFS	= -DH4 -DHAL_CSIM
LCOPTS	=
LCINCS	= -I$(BUILD_ROOT)/h5/include

CFILES	= cmdf.c driver.c error.c points.c lfbpaste.c blt.c chroma.c \
		lines.c poly.c rect.c tris.c

PROGRAMS = $(CFILES:.c=.exe)

LLDLIBS	= $(BUILD_ROOT)/h5/lib/h4hal.lib \
		$(BUILD_ROOT)/h5/lib/h4util.lib \
		$(BUILD_ROOT_SWLIBS)/lib/fxmisc.lib \
		$(BUILD_ROOT_SWLIBS)/lib/wing32.lib

include $(BUILD_ROOT_SWLIBS)/include/make/3dfx.mak

