#
# Copyright (c) 1995, 3Dfx Interactive, Inc.
# All Rights Reserved.
#
# This is UNPUBLISHED PROPRIETARY SOURCE CODE of 3Dfx Interactive, Inc.;
# the contents of this file may not be disclosed to third parties, copied or
# duplicated in any form, in whole or in part, without the prior written
# permission of 3Dfx Interactive, Inc.
#
# RESTRICTED RIGHTS LEGEND:
# Use, duplication or disclosure by the Government is subject to restrictions
# as set forth in subdivision (c)(1)(ii) of the Rights in Technical Data
# and Computer Software clause at DFARS 252.227-7013, and/or in similar or
# successor clauses in the FAR, DOD or NASA FAR Supplement. Unpublished  -
# rights reserved under the Copyright Laws of the United States.
#

# ARCADE TOOLBOX COMPILATION FLAGS
#
# -DAT_BUILD_LIBRARY - Defined when building the library
#
# -DAT_DEBUGGING  - Enable parameter checking and bug catching code.
# -DAT_PRODUCTION - Disable parameter checking and debugging code.
#                   Use this with optimized builds
# -DAT_STATISTICS       - Include statistic tracking code.
# -DAT_PENTIUM_ASSEMBLY - Use pentium optimized assembly routines
# -DAT_CHECK_TRIS       - Check every triangle against screen
#

# Preprocessor Defines
LCDEFS    = -DAT_BUILD_LIBRARY -DAPI_LEV4 -DAT_LOADER_MG

!if "$(DEBUG)"=="1"
LCDEFS    = -DAT_DEBUGGING $(LCDEFS) 
!else
LCDEFS    = -DAT_PRODUCTION $(LCDEFS)
!endif

!if "$(FX_GLIDE3)" != ""
LCDEFS    = -DGLIDE3 $(LCDEFS)
!endif

# Header paths
LCINCS    = -I$(BUILD_ROOT_ARCADE)\include -I$(BUILD_ROOT)\$(FX_GLIDE_HW)\include \
            -I$(MGSDK)\dist\inc 

# sources
HEADERS   = fltlod.h

CFILES    = loader.c

AFILES    = 

# targets
INSTALL_DESTINATION = $(BUILD_ROOT_ARCADE)
LIBRARIES = atcmg.lib

!include $(BUILD_ROOT_SWLIBS)/include/nmake/3dfx.mak
