#
# Copyright (c) 1995, 3Dfx Interactive, Inc.
# All Rights Reserved.
#
# This is UNPUBLISHED PROPRIETARY SOURCE CODE of 3Dfx Interactive, Inc.;
# the contents of this file may not be disclosed to third parties, copied or
# duplicated in any form, in whole or in part, without the prior written
# permission of 3Dfx Interactive, Inc.
#
# RESTRICTED RIGHTS LEGEND:
# Use, duplication or disclosure by the Government is subject to restrictions
# as set forth in subdivision (c)(1)(ii) of the Rights in Technical Data
# and Computer Software clause at DFARS 252.227-7013, and/or in similar or
# successor clauses in the FAR, DOD or NASA FAR Supplement. Unpublished  -
# rights reserved under the Copyright Laws of the United States.
#

# local defines, options, includes

LCDEFS  = 
LCOPTS  = -DGLIDE_HARDWARE
LCINCS  = -I$(BUILD_ROOT_ARCADE)\include -I$(BUILD_ROOT)\$(FX_GLIDE_HW)\include
LCINCS = $(LCINCS) -I$(BUILD_ROOT_SWLIBS)\include
LCINCS = $(LCINCS) -I$(BUILD_ROOT_GCI)\include

!if "$(FX_COMPILER)" == "MICROSOFT"
!else
!endif

# sources
HEADERS             = 3ds.h 3dschunk.h 3dsread.h 3dsmacro.h \
                      3dsanim.h 3dsutil.h 3dsinc.h 3dsvectr.h \
                      3dsmatrx.h
INSTALL_DESTINATION = $(BUILD_ROOT_SWLIBS)
CFILES              = 3ds.c 3dsread.c 3dsanim.c 3dsutil.c \
                      3dsmatrx.c 3dsvectr.c
#SUBLIBRARIES        = $(BUILD_ROOT_SWLIBS)\lib\gsim.lib \
#                      $(BUILD_ROOT_SWLIBS)\lib\sst.lib \
#                      $(BUILD_ROOT_SWLIBS)\lib\util.lib \
#                      $(BUILD_ROOT_SWLIBS)\lib\fxmisc.lib

# targets

LIBRARIES = 3ds.lib

!include $(BUILD_ROOT_SWLIBS)/include/nmake/3dfx.mak
