#
#	MAKEFILE - NMAKE script for EDIAG.EXE
#	Copyright (c) 1996-1998 Elpin Systems, Inc.
#	All rights reserved.
#
#	Written by:	Larry Coffey
#	Date:		3/9/98
#	Last modified:	5/7/98
#

all: crdir subdirs goal install

libs: all

# don't do anything for incs or bins

incs:
bins:

crdir:
	mkdir lib

##### Module Macros ####
NAME		= ediag
TSTSRCS	= main.cpp cmdline.cpp user.cpp file.cpp display.cpp \
		  mem.cpp tests.cpp
OBJS		=
LIBS		= elib.lib repdev.lib vgadata.lib ediag1.lib vgacore.lib
INCDIR		= C:\WATCOM\h
MAKE		= nmake

##### Include Macro #####
TSTINCLS	= $(NAME).h

##### DEBUG Macro Defined #####
# To include debugging information for symbolic debugging set DEBUG=1
DEBUG		= 1

##### Build Option Macros #####
!if $(DEBUG)
DDEF		= -DDEBUG
COPT		= -e25 -zq -d2 -mf -5r -hw -od -wx
LOPT		= SYS dos4g op m debug all op st=8192 op maxe=25 op q
!else
DDEF		=
COPT		= -w4 -e25 -zq -otexan -d1 -mf -5r
LOPT		= SYS dos4g op m op st=8192 op maxe=25 op q op symf
!endif

##### General Macros #####
DEF		= 

##### Tool Macros #####
CC		= wcc386 
# -bt=dos -i$(INCDIR) $(COPT) $(DDEF) $(DEF)
LINK		= wlink $(LOPT)

##### Inference Rules #####
.c.obj:
	SET WCC386=-s -otexan -Id:\3dfx\devel\swlibs\include;  -D__DOS32__ -w4 -e25 -7 -fp5 -zq -5s -ei -mf -bt#dos -Id:\3dfx\devel\swlibs\include -Id:\3dfx\devel\h5\include  -I..\lua\include -DBUILD_DIAGS	
	$(CC) $*.c

##### Main (default) Target #####
#goal:	$(NAME).exe
goal: $(NAME).lib

##### Dependents For Goal and Command Line #####
$(NAME).lib:	$(TSTSRCS:.cpp=.obj)
	!wlib $(NAME).lib -+$?

##### Dependents For Goal and Command Line #####
$(NAME).exe:	$(TSTSRCS:.cpp=.obj) $(LIBS)
	$(LINK) @<<
	NAME $(NAME)
	FIL $(TSTSRCS:.cpp=.obj,)$(LIBS:.lib=.lib,)
<<

##### Dependents #####
$(TSTSRCS:.cpp=.obj):	$(TSTINCLS) makefile

subdirs: $(SUBDIRS)
	cd vgadata
	$(MAKE)
	cd ..
	cd report
	$(MAKE)
	cd ..
	cd 3dfx
	$(MAKE)
	cd ..
	cd ediag1
	$(MAKE)
	cd ..
	cd vgacore
	$(MAKE)
	cd ..


install:
	copy /y $(NAME).lib lib

##### Clean Directory #####
clean:
	-if exist *.obj del *.obj
	-if exist $(NAME).exe del $(NAME).exe
	-if exist *.map del *.map
	-if exist *.sym del *.sym
	-if exist lib\*.lib del lib\*.lib
#
#	Copyright (c) 1996-1998 Elpin Systems, Inc.
#	All rights reserved.
#
