//
//		VGADATA.H - Defines for VGADATA.LIB
//		Copyright (c) 1994-1998 Elpin Systems, Inc.
//		All rights reserved.
//
//		Written by:		Larry Coffey
//		Date:				5/4/98
//		Last modified:	5/4/98
//
#ifndef BYTE
typedef	unsigned char			BYTE;
#endif

#ifndef _DATAFILE_
extern	BYTE			tblParameterTable[];
extern	BYTE			tbl16ColorDAC[];
extern	BYTE			tblCGADAC[];
extern	BYTE			tblMonoDAC[];
extern	BYTE			tbl256ColorDAC[];
extern	BYTE			tblFont8x14[];
extern	BYTE			tblFont8x16[];
extern	BYTE			tblFont8x8[];
extern	BYTE			tblFont9x14[];
extern	BYTE			tblFont9x16[];
extern	BYTE			tblSmallParameterTable[];
#endif

//
//		Copyright (c) 1994-1998 Elpin Systems, Inc.
//		All rights reserved.
//
