#
# Copyright (c) 1996, 3Dfx Interactive, Inc.
# All Rights Reserved.
#
# This is UNPUBLISHED PROPRIETARY SOURCE CODE of 3Dfx Interactive, Inc.;
# the contents of this file may not be disclosed to third parties, copied or
# duplicated in any form, in whole or in part, without the prior written
# permission of 3Dfx Interactive, Inc.
#
# RESTRICTED RIGHTS LEGEND:
# Use, duplication or disclosure by the Government is subject to restrictions
# as set forth in subdivision (c)(1)(ii) of the Rights in Technical Data
# and Computer Software clause at DFARS 252.227-7013, and/or in similar or
# successor clauses in the FAR, DOD or NASA FAR Supplement. Unpublished  -
# rights reserved under the Copyright Laws of the United States.
#
# $Revision: 1 $
# $Date: 8/10/98 7:01p $

LUA_TOP		= ..\lua
MDIAG_TOP 	= ..
ELIBDIR		= vgatst\lib

THISDIR = gplay
SUBDIRS = 

# local defines, options, includes
LCDEFS  = -DBUILD_DIAGS -DDIAG_BUILD
LCOPTS  =
LCINCS  = -I$(BUILD_ROOT_SWLIBS)\include -I$(BUILD_ROOT)\h5\include \
		-I$(LUA_TOP)\include

# sources
CFILES   = gplay.c hash.c trap.c
 
#PROGRAM = gplay.exe
LIBRARIES = gplay.lib
#GLIDELIB	= 	glide2x.lib

INSTALL_DESTINATION = $(MDIAG_TOP)

LLDLIBS = $(BUILD_ROOT)\h5\lib\$(GLIDELIB) 

!include $(BUILD_ROOT_SWLIBS)\include\nmake\3dfx.mak


