#
# Copyright (c) 1995, 3Dfx Interactive, Inc.
# All Rights Reserved.
#
# This is UNPUBLISHED PROPRIETARY SOURCE CODE of 3Dfx Interactive, Inc.;
# the contents of this file may not be disclosed to third parties, copied or
# duplicated in any form, in whole or in part, without the prior written
# permission of 3Dfx Interactive, Inc.
#
# RESTRICTED RIGHTS LEGEND:
# Use, duplication or disclosure by the Government is subject to restrictions
# as set forth in subdivision (c)(1)(ii) of the Rights in Technical Data
# and Computer Software clause at DFARS 252.227-7013, and/or in similar or
# successor clauses in the FAR, DOD or NASA FAR Supplement. Unpublished  -
# rights reserved under the Copyright Laws of the United States.
#

# Preprocessor Defines
LCDEFS  = -DAT_BUILD_LIBRARY

!if "$(DEBUG)"=="1"
LCDEFS  = -DAT_DEBUGGING $(VCDEFS) 
!else
LCDEFS  = -DAT_PRODUCTION $(VCDEFS)
!endif

# Header paths
LCINCS    =  -I$(BUILD_ROOT_ARCADE)\include \
             -I$(BUILD_ROOT_SST1)\include  \
             -I$(BUILD_ROOT_SWLIBS)\include

# Sources
HEADERS             = atgui.h
CFILES              = control.c minor.c

# Targets
INSTALL_DESTINATION = $(BUILD_ROOT_ARCADE)
LIBRARIES = atg.lib

!include $(BUILD_ROOT_SWLIBS)/include/nmake/3dfx.mak

