##
##  Makefile for Windows NT
##


all     :
        cd contrib
        nmake -nologo -f Makefile
        cd ..
        cd demos
        nmake -nologo -f Makefile
        cd ..
        cd examples
        nmake -nologo -f Makefile
        cd ..
        cd redbook
        nmake -nologo -f Makefile
        cd ..

clean   :
        cd contrib
        nmake -nologo -f Makefile clean 
        cd ..
        cd demos
        nmake -nologo -f Makefile clean
        cd ..
        cd examples
        nmake -nologo -f Makefile clean
        cd ..
        cd redbook
        nmake -nologo -f Makefile clean
        cd ..

