#
# Copyright (c) 1995, 3Dfx Interactive, Inc.
# All Rights Reserved.
#
# This is UNPUBLISHED PROPRIETARY SOURCE CODE of 3Dfx Interactive, Inc.;
# the contents of this file may not be disclosed to third parties, copied or
# duplicated in any form, in whole or in part, without the prior written
# permission of 3Dfx Interactive, Inc.
#
# RESTRICTED RIGHTS LEGEND:
# Use, duplication or disclosure by the Government is subject to restrictions
# as set forth in subdivision (c)(1)(ii) of the Rights in Technical Data
# and Computer Software clause at DFARS 252.227-7013, and/or in similar or
# successor clauses in the FAR, DOD or NASA FAR Supplement. Unpublished  -
# rights reserved under the Copyright Laws of the United States.
#


# ONLY COMPILE FOR WIN95, SKIP OTHERWISE
!if "$(FX_TARGET)" == "WIN32"

THISDIR=bench
SUBDIRS=matdlg

FX_TARGET_MINOR=WIN95

!if "$(FX_GLIDE3)" != ""
LCDEFS = $(LCDEFS) -DGLIDE3
!endif

!include $(BUILD_ROOT_ARCADE)\include\atdemo.mak

CFILES    = main.c bench.c
RCFILE    = benchui.rc

PROGRAM   = atrbench.exe

!include $(BUILD_ROOT_SWLIBS)\include\nmake\3dfx.mak


!endif

