//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Benchui.rc
//
#define IDD_DIALOG1                     101
#define IDC_EDIT1                       1000
#define IDC_NUMTESTSEDIT                1000
#define IDC_BUTTON1                     1001
#define IDC_GDTBUTTON                   1001
#define IDC_MTBUTTON                    1002
#define IDC_PROGRESS1                   1003
#define IDC_BUTTON2                     1004
#define IDC_RTSBUTTON                   1004
#define IDC_EDIT2                       1005
#define IDC_GDT_CPC                     1005
#define IDC_GDT_CPO                     1005
#define IDC_EDIT3                       1006
#define IDC_RTS_CPO                     1006
#define IDC_BUTTON3                     1007
#define IDC_MATBUTTON                   1007
#define IDC_EDIT4                       1008
#define IDC_MAT_CPO                     1008
#define IDC_BUTTON4                     1009
#define IDC_XFBUTTON                    1009
#define IDC_EDIT5                       1010
#define IDC_XF_CPO                      1010
#define IDC_BUTTON5                     1011
#define IDC_CLEAR                       1011
#define IDC_EDIT6                       1012
#define IDC_GDT_CPS                     1013
#define IDC_EDIT8                       1014
#define IDC_RTS_CPS                     1014
#define IDC_EDIT9                       1015
#define IDC_MAT_CPS                     1015
#define IDC_EDIT10                      1016
#define IDC_XF_CPS                      1016
#define IDC_GDT_TPS                     1017
#define IDC_EDIT12                      1018
#define IDC_RTS_TPS                     1018
#define IDC_EDIT13                      1019
#define IDC_MAT_TPS                     1019
#define IDC_EDIT14                      1020
#define IDC_XF_TPS                      1020
#define IDC_MT_CPC                      1021
#define IDC_MT_CPO                      1021
#define IDC_MT_CPS                      1022
#define IDC_MT_TPS                      1023
#define IDC_PROGRESS                    1025
#define IDC_RESULTS                     1026
#define IDC_GDTDETAILS                  1027
#define IDC_RTSDETAILS                  1028
#define IDC_PMDETAILS                   1029
#define IDC_MATDETAILS                  1029
#define IDC_NUMTESTSSLIDER              1030
#define IDC_PXFDETAILS                  1031
#define IDC_MTDETAILS                   1032

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        103
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1032
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
