TARGETOS = WIN95

!include <win32.mak>

TARGET = ogtst.exe

CFILES = \
	ctxsw.c \
	getopt.c \
	getstatecheck.c \
	imutil.c \
	info.c \
	inout.c \
	main.c \
	spec.c \
	sgilib.c \
	wind.c

OBJECTS	= $(CFILES:.c=.obj)

LIBS = \
	..\func\func.lib \
	..\lib\lib.lib

LLDLIBS	= glu32.lib opengl32.lib

LCINCS	= -I..\inc
LCDEFS	= -D__STDC__ -DWIN32
LCFLAGS	= $(LCDEFS) $(LCINCS)

all: $(TARGET)

.c.obj:
	$(cc) $(cdebug) $(LCFLAGS) $(cflags) $(cvars) $(scall) $*.c

$(TARGET): $(OBJECTS) $(LIBS)
	$(link) $(linkdebug) $(conlflags) -out:$@ $** $(LLDLIBS) $(guilibs)

clean:
	-rm -f $(OBJECTS) spec.c

clobber: clean
	-rm -f $(TARGET)

spec.c: spec.pl spec.ogtst
	perl spec.pl -arch architectures.h spec.ogtst > $@
