#
# Copyright (c) 1997, 3Dfx Interactive, Inc.
# All Rights Reserved.
#
# This is UNPUBLISHED PROPRIETARY SOURCE CODE of 3Dfx Interactive, Inc.;
# the contents of this file may not be disclosed to third parties, copied or
# duplicated in any form, in whole or in part, without the prior written
# permission of 3Dfx Interactive, Inc.
#
# RESTRICTED RIGHTS LEGEND:
# Use, duplication or disclosure by the Government is subject to restrictions
# as set forth in subdivision (c)(1)(ii) of the Rights in Technical Data
# and Computer Software clause at DFARS 252.227-7013, and/or in similar or
# successor clauses in the FAR, DOD or NASA FAR Supplement. Unpublished  -
# rights reserved under the Copyright Laws of the United States.
#

#--------------------------------------#
# Special Flags
#--------------------------------------#

FX_DLL_BUILD = 1
FX_DLL_LIBRARY = 1

#--------------------------------------#
# Special Defs
#--------------------------------------#
LCINCS              = -I$(BUILD_ROOT_SWLIBS)\include   \
                      -I$(BUILD_ROOT_SST1)\include
LCDEFS              = /D "_GDI32_"

LADEFS              =
LAINCS              =
LAOPTS              =
LCOPTS              = /nologo /MDd /W3 /Fp"OPENGL32.pch" /YX

LLDOPTS             = /DEF:opengl32.def
#LLDOPTS            = /DEF:opengl32.def /debugtype:both /debug /map

LCINCS    = -I$(BUILD_ROOT_ARCADE)\include \
            -I$(BUILD_ROOT_SST1)\include 

RCFILE         = fxgl.rc

CFILES         = \
	dllmain.c \
	glattrib.c \
	glaccum.c \
	glalpha.c \
	glarray.c \
	glclear.c \
	glclip.c \
	glcolor.c \
	glcontext.c \
	gldepth.c \
	gleval.c \
	glfeedback.c \
	glfog.c \
	glgen.c \
	glget.c \
	glindex.c \
	gllight.c \
	gllist.c \
	glmat.c \
	glmf.c \
	glnorm.c \
	global.c \
	glpick.c \
	glpixel.c \
	glprim.c \
	glraster.c \
	glrect.c \
	glscissor.c \
	glstencil.c \
	gltex.c \
	glvert.c \
	glview.c \
	nogl.c \
	fgl.c \
	wgl.c \
	wglfont.c \
	wglundoc.c

# targets
LIBRARIES      = opengl32.lib
SUBLIBRARIES        =  $(BUILD_ROOT_SST1)\lib\sst1init.lib \
                       $(BUILD_ROOT_SST1)\lib\glide2x.lib

!include $(BUILD_ROOT_SWLIBS)/include/nmake/3dfx.mak
