!ifndef VERBOSE
.SILENT :
!ifndef LOGO
LOGO = /nologo
!endif
!else
LOGO =
!endif

!include check.mk

!ifndef DO
DO = all
!endif


DIRS = \
	dd16 \
	dd32 \
	d3d \
	minivdd

#all: mystuff $(DIRS)

$(DIRS): $(@R)\nul
	cd $@
	$(MAKE) /nologo $(DO)
	cd ..

all: debug retail

debug retail: $@.mak

debug.mak:
	@ $(MAKE) /nologo DO=debug

retail.mak:
	@ $(MAKE) /nologo DO=retail

clean:
	@ $(MAKE) /nologo DO="clean"
	deltree/y bin

#mystuff:
#	@ echo KMW: doing stuff in this directory