/* $Header: verinfo.h, 164, 10/29/00 10:26:49 PM, sapphire$ */
/*
** Copyright (c) 1995-1999, 3Dfx Interactive, Inc.
** All Rights Reserved.
**
** File name:   verinfo.h
**
** Description: header file to define the build version.
**
** $Revision: 164$
** $Date: 10/29/00 10:26:49 PM$
**
** $History: verinfo.h $
** 
** *****************  Version 327  *****************
** User: Cwilcox      Date: 8/14/99    Time: 10:22a
** Updated in $/devel/h5/Win9x/dx
** Removed Banshee, added entry for Napalm, which will be set to Voodoo3
** until a product/driver name decision is made.
** 
** *****************  Version 325  *****************
** User: Sapphire     Date: 6/02/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 324  *****************
** User: Sapphire     Date: 6/01/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 323  *****************
** User: Sapphire     Date: 5/29/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 322  *****************
** User: Sapphire     Date: 5/28/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 321  *****************
** User: Sapphire     Date: 5/27/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 320  *****************
** User: Sapphire     Date: 5/26/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 319  *****************
** User: Sapphire     Date: 5/25/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 318  *****************
** User: Sapphire     Date: 5/24/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 317  *****************
** User: Sapphire     Date: 5/22/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 316  *****************
** User: Sapphire     Date: 5/21/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 315  *****************
** User: Sapphire     Date: 5/20/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 314  *****************
** User: Sapphire     Date: 5/19/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 313  *****************
** User: Sapphire     Date: 5/18/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 312  *****************
** User: Sapphire     Date: 5/17/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 311  *****************
** User: Sapphire     Date: 5/16/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 310  *****************
** User: Sapphire     Date: 5/15/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 309  *****************
** User: Sapphire     Date: 5/14/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 308  *****************
** User: Sapphire     Date: 5/13/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 307  *****************
** User: Sapphire     Date: 5/12/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 306  *****************
** User: Sapphire     Date: 5/11/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 305  *****************
** User: Sapphire     Date: 5/10/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 304  *****************
** User: Sapphire     Date: 5/08/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 303  *****************
** User: Sapphire     Date: 5/07/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 302  *****************
** User: Sapphire     Date: 5/06/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 301  *****************
** User: Sapphire     Date: 5/05/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 300  *****************
** User: Sapphire     Date: 5/04/99    Time: 11:45a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 299  *****************
** User: Sapphire     Date: 5/04/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 298  *****************
** User: Sapphire     Date: 5/03/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 297  *****************
** User: Sapphire     Date: 5/01/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 296  *****************
** User: Sapphire     Date: 4/30/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 295  *****************
** User: Sapphire     Date: 4/29/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 294  *****************
** User: Sapphire     Date: 4/28/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 293  *****************
** User: Sapphire     Date: 4/27/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 292  *****************
** User: Sapphire     Date: 4/25/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 291  *****************
** User: Sapphire     Date: 4/24/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 290  *****************
** User: Sapphire     Date: 4/23/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 289  *****************
** User: Sapphire     Date: 4/22/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 288  *****************
** User: Sapphire     Date: 4/21/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 287  *****************
** User: Sapphire     Date: 4/20/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 286  *****************
** User: Sapphire     Date: 4/19/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 285  *****************
** User: Sapphire     Date: 4/17/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 284  *****************
** User: Sapphire     Date: 4/16/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 283  *****************
** User: Sapphire     Date: 4/15/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 282  *****************
** User: Stb_srogers  Date: 4/14/99    Time: 8:25a
** Updated in $/devel/h3/win95/dx
** Removed icky STB Names stuff so that the only difference in the builds
** in the Version string and build number
** 
** *****************  Version 281  *****************
** User: Sapphire     Date: 4/14/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 280  *****************
** User: Sapphire     Date: 4/13/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 279  *****************
** User: Sapphire     Date: 4/12/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 278  *****************
** User: Sapphire     Date: 4/11/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 277  *****************
** User: Sapphire     Date: 4/10/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 276  *****************
** User: Sapphire     Date: 4/09/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 275  *****************
** User: Sapphire     Date: 4/08/99    Time: 12:50p
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 274  *****************
** User: Sapphire     Date: 4/08/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 273  *****************
** User: Sapphire     Date: 4/07/99    Time: 1:06p
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 272  *****************
** User: Sapphire     Date: 4/07/99    Time: 7:25a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 271  *****************
** User: Sapphire     Date: 4/07/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 270  *****************
** User: Sapphire     Date: 4/06/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 269  *****************
** User: Sapphire     Date: 4/05/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 268  *****************
** User: Sapphire     Date: 4/04/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 267  *****************
** User: Sapphire     Date: 4/03/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 266  *****************
** User: Sapphire     Date: 4/02/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 265  *****************
** User: Sapphire     Date: 4/01/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 264  *****************
** User: Sapphire     Date: 3/31/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 263  *****************
** User: Sapphire     Date: 3/30/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 262  *****************
** User: Sapphire     Date: 3/29/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 261  *****************
** User: Sapphire     Date: 3/28/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 260  *****************
** User: Sapphire     Date: 3/27/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 259  *****************
** User: Sapphire     Date: 3/26/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 258  *****************
** User: Sapphire     Date: 3/25/99    Time: 7:44a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 257  *****************
** User: Sapphire     Date: 3/24/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 256  *****************
** User: Sapphire     Date: 3/23/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 255  *****************
** User: Sapphire     Date: 3/21/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 254  *****************
** User: Sapphire     Date: 3/20/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 253  *****************
** User: Sapphire     Date: 3/19/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 252  *****************
** User: Michael      Date: 3/18/99    Time: 4:43p
** Updated in $/devel/h3/Win95/dx
** Fix PRS 5202.  Modify MANREVISION to 11 so internal version number is
** correct for DX6.
** 
** *****************  Version 251  *****************
** User: Sapphire     Date: 3/18/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 250  *****************
** User: Michael      Date: 3/17/99    Time: 7:56a
** Updated in $/devel/h3/Win95/dx
** Change "3dfx" to "3dfx Interactive" and "3dfx Interactive, Inc.", where
** appropriate.
** 
** *****************  Version 249  *****************
** User: Sapphire     Date: 3/17/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 248  *****************
** User: Michael      Date: 3/16/99    Time: 5:25p
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 2  *****************
** User: Michael      Date: 3/16/99    Time: 5:24p
** Updated in $/Releases/Voodoo3/MT2/3Dfx/devel/H3/Win95/DX
** Change all references from "3Dfx Interactive, Inc." to "3dfx".  Update
** copyright to 1999.
** 
** *****************  Version 247  *****************
** User: Sapphire     Date: 3/16/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 246  *****************
** User: Sapphire     Date: 3/15/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 245  *****************
** User: Sapphire     Date: 3/14/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 244  *****************
** User: Sapphire     Date: 3/13/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 243  *****************
** User: Sapphire     Date: 3/12/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 242  *****************
** User: Sapphire     Date: 3/11/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 241  *****************
** User: Sapphire     Date: 3/10/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 240  *****************
** User: Sapphire     Date: 3/09/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 239  *****************
** User: Sapphire     Date: 3/08/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 238  *****************
** User: Sapphire     Date: 3/07/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 237  *****************
** User: Sapphire     Date: 3/06/99    Time: 1:31a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 236  *****************
** User: Sapphire     Date: 3/05/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 235  *****************
** User: Sapphire     Date: 3/04/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 234  *****************
** User: Sapphire     Date: 3/03/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 233  *****************
** User: Sapphire     Date: 3/02/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 232  *****************
** User: Sapphire     Date: 3/01/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 231  *****************
** User: Sapphire     Date: 2/27/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 230  *****************
** User: Sapphire     Date: 2/26/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 229  *****************
** User: Sapphire     Date: 2/25/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 228  *****************
** User: Sapphire     Date: 2/24/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 227  *****************
** User: Sapphire     Date: 2/23/99    Time: 7:46a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 226  *****************
** User: Sapphire     Date: 2/22/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 225  *****************
** User: Sapphire     Date: 2/20/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 224  *****************
** User: Sapphire     Date: 2/19/99    Time: 1:44p
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 223  *****************
** User: Sapphire     Date: 2/19/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 222  *****************
** User: Sapphire     Date: 2/18/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 221  *****************
** User: Mconrad      Date: 2/17/99    Time: 10:36a
** Updated in $/devel/h3/Win95/dx
** Support for Banshee/Voodoo3 file properties based on HP= H3 or H4
** environment variable. Fixes PRSs #4087, #4088.
** 
** *****************  Version 220  *****************
** User: Sapphire     Date: 2/17/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 219  *****************
** User: Sapphire     Date: 2/16/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 218  *****************
** User: Sapphire     Date: 2/14/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 217  *****************
** User: Sapphire     Date: 2/13/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 216  *****************
** User: Sapphire     Date: 2/12/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 215  *****************
** User: Sapphire     Date: 2/11/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 214  *****************
** User: Sapphire     Date: 2/10/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 213  *****************
** User: Sapphire     Date: 2/09/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 212  *****************
** User: Sapphire     Date: 2/08/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 211  *****************
** User: Sapphire     Date: 2/07/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 210  *****************
** User: Sapphire     Date: 2/06/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 209  *****************
** User: Sapphire     Date: 2/05/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 208  *****************
** User: Sapphire     Date: 2/04/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 207  *****************
** User: Sapphire     Date: 2/03/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 206  *****************
** User: Sapphire     Date: 2/02/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 205  *****************
** User: Sapphire     Date: 2/01/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 204  *****************
** User: Sapphire     Date: 1/31/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 203  *****************
** User: Sapphire     Date: 1/30/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 202  *****************
** User: Sapphire     Date: 1/29/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 201  *****************
** User: Sapphire     Date: 1/28/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 200  *****************
** User: Sapphire     Date: 1/27/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 199  *****************
** User: Sapphire     Date: 1/26/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 198  *****************
** User: Sapphire     Date: 1/25/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 197  *****************
** User: Sapphire     Date: 1/23/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 196  *****************
** User: Sapphire     Date: 1/22/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 195  *****************
** User: Sapphire     Date: 1/21/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 194  *****************
** User: Sapphire     Date: 1/20/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 193  *****************
** User: Sapphire     Date: 1/19/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 192  *****************
** User: Sapphire     Date: 1/18/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 191  *****************
** User: Sapphire     Date: 1/16/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 190  *****************
** User: Sapphire     Date: 1/15/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 189  *****************
** User: Sapphire     Date: 1/14/99    Time: 1:30a
** Updated in $/devel/h3/Win95/dx
** 
** *****************  Version 188  *****************
** User: Michael      Date: 1/12/99    Time: 12:24p
** Updated in $/devel/h3/Win95/dx
** Add the STB customer specific code.  All STB added code is surrounded
** by "#ifdef INSTBCUST/#endif"
** 
*/

#define OFFICIAL                1
#undef FINAL
#define FINAL                   0

#define MANVERSION              4
#define MANREVISION             12

#ifdef RC_INVOKED

#ifdef H5
#define VERSIONPRODUCTNAME      "VSA 100\256 DirectX for Windows\256  95 and Windows\256  98 \0"
#define VERSIONCOPYRIGHT        "Copyright \251 3dfx Interactive, Inc. 2000\0"
#else
#ifdef H4
#define VERSIONPRODUCTNAME      "Voodoo3\256 DirectX for Windows\256  95 and Windows\256  98 \0"
#define VERSIONCOPYRIGHT        "Copyright \251 3dfx Interactive, Inc. 1999\0"
#endif // H4
#endif // H5
#endif

#define RELEASE_NUMBER          0000
#define BUILD_NUMBER            0675

#define VERSIONSTR              "4.12.01.0675"


/***********************************************************
 * PLEASE DO NOT CHANGE THIS!!!
 *   The following comment is for SAPPHIRE (the build tool).
 *----------------------------------------------------------
 *  SAPPHIRE_TIME_STAMP Sun-20001029-22:30:01
 ***********************************************************/

/***************************************************************************
 *  DO NOT TOUCH BELOW THIS LINE                                           *
 ***************************************************************************/

#ifdef RC_INVOKED

#define VERSIONCOMPANYNAME      "3dfx Interactive, Inc.\0"

/*
 *  Version flags 
 */

#undef VER_PRIVATEBUILD
#ifndef OFFICIAL
#define VER_PRIVATEBUILD        VS_FF_PRIVATEBUILD
#else
#define VER_PRIVATEBUILD        0
#endif

#undef VER_PRERELEASE
#ifndef FINAL
#define VER_PRERELEASE          VS_FF_PRERELEASE
#else
#define VER_PRERELEASE          0
#endif

#undef VER_DEBUG
#ifdef DEBUG
#define VER_DEBUG               VS_FF_DEBUG    
#elif RDEBUG
#define VER_DEBUG               VS_FF_DEBUG    
#else
#define VER_DEBUG               0
#endif

#define VERSIONFLAGS            (VER_PRIVATEBUILD|VER_PRERELEASE|VER_DEBUG)
#define VERSIONFILEFLAGSMASK    0x0030003FL
#endif
