#
# Copyright (c) 1995, 3Dfx Interactive, Inc.
# All Rights Reserved.
#
# This is UNPUBLISHED PROPRIETARY SOURCE CODE of 3Dfx Interactive, Inc.;
# the contents of this file may not be disclosed to third parties, copied or
# duplicated in any form, in whole or in part, without the prior written
# permission of 3Dfx Interactive, Inc.
#
# RESTRICTED RIGHTS LEGEND:
# Use, duplication or disclosure by the Government is subject to restrictions
# as set forth in subdivision (c)(1)(ii) of the Rights in Technical Data
# and Computer Software clause at DFARS 252.227-7013, and/or in similar or
# successor clauses in the FAR, DOD or NASA FAR Supplement. Unpublished  -
# rights reserved under the Copyright Laws of the United States.
#
# $Revision: 5 $
# $Date: 3/29/99 12:07p $

# local defines, options, includes
LCDEFS  = 
LCOPTS  =

# sources
HEADERS             = gpioctl.h fxptl.h 
INSTALL_DESTINATION = $(BUILD_ROOT_SWLIBS)

# targets
default::
        -net stop fxgpio
        -net stop fxptl
        xcopy /dkri fxgpio.sys $(SYSTEMROOT)\system32\drivers
        xcopy /dkri  fxptl.sys $(SYSTEMROOT)\system32\drivers
        regini fxgpio.ini
        regini fxptl.ini
        net start fxgpio
        net start fxptl
        @echo ******************** IMPORTANT NOTE *****************************
        @echo If you do not want the fxgpio and fxptl drivers to be started
        @echo automatically, then change the Start value in fxgpio.ini and
        @echo fxptl.ini from 2 to 3.  You can then start the drivers manually
        @echo using "net start fxgpio" and "net start fxptl"
        @echo *****************************************************************

!include $(BUILD_ROOT_SWLIBS)/include/nmake/3dfx.mak

install-driver: fxgpio.sys fxgpio.ini fxptl.sys fxptl.ini
    !$(INSTALL) $** $(KIT_INSTALL)\win32\driver
    !attrib +r $(KIT_INSTALL)\win32\driver\$**
