#
# Copyright (c) 1995, 3Dfx Interactive, Inc.
# All Rights Reserved.
#
# This is UNPUBLISHED PROPRIETARY SOURCE CODE of 3Dfx Interactive, Inc.;
# the contents of this file may not be disclosed to third parties, copied or
# duplicated in any form, in whole or in part, without the prior written
# permission of 3Dfx Interactive, Inc.
#
# RESTRICTED RIGHTS LEGEND:
# Use, duplication or disclosure by the Government is subject to restrictions
# as set forth in subdivision (c)(1)(ii) of the Rights in Technical Data
# and Computer Software clause at DFARS 252.227-7013, and/or in similar or
# successor clauses in the FAR, DOD or NASA FAR Supplement. Unpublished  -
# rights reserved under the Copyright Laws of the United States.
#

LCINCS  = -I$(BUILD_ROOT_SWLIBS)\include


LLDLIBS =   $(BUILD_ROOT_SWLIBS)\lib\bcstudp.lib \
            c:\msdev\lib\wsock32.lib

ADDLIB =    wsock32.lib

HEADERS = common.h
CFILES  = sample.c

!if "$(CLIENT)" == "1"
!if "$(SERVER)" == "1"
LCDEFS = $(LCDEFS) -DSERVER -DCLIENT
PROGRAM = sample.exe
!else
LCDEFS = $(LCDEFS) -DCLIENT
PROGRAM = client.exe
!endif
!else
!if "$(SERVER)" == "1"
LCDEFS = $(LCDEFS) -DSERVER 
PROGRAM = server.exe
!endif
!endif



!include $(BUILD_ROOT_SWLIBS)/include/nmake/3dfx.mak
