##
## $Header: /DEVEL/h5/Win9x/DX/minivdd/makefile 1     11/12/99 4:27p Skephart $
##
## Copyright (c) 1997, 3Dfx Interactive, Inc.
## All Rights Reserved.
##
## This is UNPUBLISHED PROPRIETARY SOURCE CODE of 3Dfx Interactive, Inc.;
## the contents of this file may not be disclosed to third parties, copied or
## duplicated in any form, in whole or in part, without the prior written
## permission of 3Dfx Interactive, Inc.
##
## RESTRICTED RIGHTS LEGEND:
## Use, duplication or disclosure by the Government is subject to restrictions
## as set forth in subdivision (c)(1)(ii) of the Rights in Technical Data
## and Computer Software clause at DFARS 252.227-7013, and/or in similar or
## successor clauses in the FAR, DOD or NASA FAR Supplement. Unpublished  -
## rights reserved under the Copyright Laws of the United States.
##
## $Revision: 1 $
## $Date: 11/12/99 4:27p $
##
## $Log: /DEVEL/h5/Win9x/DX/minivdd/makefile $
# 
# 1     11/12/99 4:27p Skephart
# 
# 86    9/07/99 2:16p Rbissell
# Deployed the new modularized I2C code.
# 
# 85    8/31/99 9:26a Andrew
# Changed to compile without WIN_CSIM with SLI_AA
# 
# 84    8/25/99 3:30p Adrians
# Changes for new build environment.
# 
# 83    8/20/99 4:20p Dalev
# Added file dfp.c to MiniVDD build.
# 
# 82    7/27/99 4:40p Andrew
# added sim.c
# 
# 81    7/01/99 6:42p Dalev
# Added 'vmipld.c' to 'OBJS' build list.
# 
# 80    6/25/99 9:59a Andrew
# Added new files to support SLI/AA
# 
# 79    6/18/99 3:13p Michael
# make HP= case insensitive (ie. H5 or h5, H4 or h4)
# 
# 78    6/17/99 12:42p Andrew
# Removed HAL_CSIM and other defines related to this
# 
# 77    6/04/99 1:04p Cwilcox
# Removed obsolete H3_AGP_WORKAROUND varaible.
# 
# 76    6/03/99 8:55a Michael
# Add -WX compiler option and clean up offending warnings.
# 
# 75    6/03/99 8:17a Andrew
# Added SLI_AA define
# 
# 73    5/24/99 4:48p Cwilcox
# Removed AGP texture download.
# 
# 72    5/19/99 3:57p Andrew
# Added LINEAR flag compile option
# 
# 71    5/14/99 1:35p Andrew
# Added Flag F2D to allow 2d operation to pass through to the hardware
# but 3d to go to the Simulator
# 
# 70    5/06/99 4:38p Andrew
# Added code for New Windows "C" Simulator
# 
# 69    4/09/99 12:39p Stb_bseitsin
# Added Napalm registers. Added ifdef H5.
# 
# 68    3/24/99 10:19a Xingc
# Add VMMCalls.c
# 
# 67    3/22/99 7:01a Stb_lpost
# V3TV ifdefs enablement
# 
# 66    3/10/99 4:31p Andrew
# Added Family_Type to masm assembler line
# 
# 65    2/25/99 1:42p Martin
# Turn agp texture download on by default
# 
# 64    2/18/99 11:49a Cwilcox
# Final removal of tiled/linear promotion.
# 
# 63    2/17/99 11:26a Mconrad
# Fix for file properties based on HP= H3 or H4 environment variable.
# 
# 62    2/16/99 4:19p Stb_srogers
# 
# 61    2/11/99 11:09a Mconrad
# Support for Banshee/Voodoo3 file names based on HP= H3 or H4
# environment variable. Fixes PRSs #4087, #4088, #4151.
# 
# 60    2/10/99 3:45p Cwilcox
# Linear versus tiled promotion removal.
# 
# 59    2/10/99 9:08a Andrew
# Changed DIRECTXDDK to DXDDKROOT to be consistent in the makefile
# 
# 58    1/29/99 8:08a Stb_srogers
# 
# 57    12/15/98 3:31p Stuartb
# Added xlcd.obj.
# 
# 56    12/08/98 9:16a Peter
# c-ified video memory fifo support stuff
# 
# 55    11/30/98 6:48p Peter
# query for possibly re-mapped base address
# 
# 54    9/15/98 1:39p Stuartb
# Restore; I previously tromped on Art G's  h3hal changes.
# 
# 52    8/28/98 5:02p Artg
# add vdd obj to h3hal.vxd obj list.
# 
# 51    7/23/98 4:04p Ken
# added agp command fifo.   not added to NT build.  currently not
# functional on non-win98 systems without running a special enable apg
# script first, see Ken for that.   agp command fifo is enabled by
# setting the environment variable ACF=1 , all other settings disable it.
# Only turned on interatively in debugger in InitFifo call.   
# 
# 50    7/17/98 3:37p Ken
# separated default clocks into independent default values settable from
# environment variables (GCLK for graphics clock), (MCLK for memory
# clock)
# 
# 2     7/17/98 3:24p Ken
# added separate graphics and memory clock defaults, settable in build
# from environment variables GCLK (graphics clock) and MCLK (memory
# clock)
# 
# 1     7/16/98 2:49p Admin
# 
# 49    7/11/98 5:51p Ken
# more b0 fixups for gateway
# 
# 47    7/09/98 6:39p Miriam
# Build option for B0 silicon.
# 
# 46    7/09/98 11:55a Ken
# added some NULLDRIVER ability as well as a performance measuring 
# technique PERFNOP (PERFNOP was here before, I'm just adding it
# officially to the makefile).
# 
# 45    6/30/98 4:58p Agus
# Added h3gblaxs.obj
# 
# 43    5/15/98 1:00p Ken
# added A2 to the h/w rev selection.  Semantics are: HR=A2 is A2, HR=A0
# is A0, anything else including undefined is A1
# 
# 42    4/30/98 8:47p Ken
# added auto-incrementing build # / version resources to all 3
# deliverable binaries
# 
# 41    4/29/98 9:10p Andrew
# Added environmental variable SE for Schematic_Error to makefile.
# Default is for NEW AGP style cards
# 
# 40    4/24/98 1:33p Ken
# first installment of FXENTER / FXLEAVE display driver drawing function
# work.  gdi32 only, no gdi16 yet.   works, but is slow, don't measure
# performance until all work is done, in about a week.
# also renamed fields in some blit parameter functions to be a bit more
# meaningful
# 
# 39    4/21/98 12:22a Ken
# changed sense of AW (agp workaround) to be on unless AW=0
# 
# 38    4/21/98 12:01a Ken
# added agp workaround (set ar=1) for readback unreliability
# 
# 37    4/15/98 6:41p Ken
# added unified header to all files, with revision, etc. info in it
# 
# 36    4/06/98 5:25p Andrew
# Added new files for DDC
# 
# 35    3/31/98 1:14p Miriam
# trace is on by default in debug builds.
# 
# 34    3/31/98 12:05p Miriam
# Make consistent with DD/D3D
# 
# 33    3/23/98 5:32p Ken
# removed textdbg.obj (makes my build barf, this file is not in use
# anyway)
# 
# 32    3/20/98 9:47a Andrew
# Multi-Monitor
# 
# 31    3/17/98 3:55p Ken
# added -DH3_A1  when compiling on A1.    changed h3cinit.c so that until
# the non-MS folks add an H3_A0 flag, when not compiling the H3 VDD, the
# absence of H3_A1 automatically defines H3_A0
# 
# 30    3/17/98 11:21a Ken
# placed A0 workarounds in #ifdef H3_A0.  updated makefiles to use
# environment variable HR for hardware rev.   if hardware rev is not
# HR=A1, then we build an A0 revision.   use #ifdef H3_A0 for A0
# workarounds
# 
# 29    3/11/98 1:20p Markl
# Remove String Caching, optimize.
# 
# 28    3/05/98 10:12a Andrew
# Added the power.obj file to be compiled.
# 
# 27    2/25/98 3:27p Ken
# disable IRQs unconditionally (until interrupt handler is written)
# 
# 26    2/19/98 5:28p Ken
# added p6stuff.obj
# 
# 25    2/18/98 8:45p Artg
# removed the _DNOMONOHOSTBLT FLAG from makefile
# 
# 24    2/18/98 11:41a Artg
# support for sendmonobltdata
# 
# 23    2/18/98 11:50a Ken
# changed file name of vdd to 3dfxvb.vxd
# 
# 22    2/17/98 6:27p Ken
# added polygon.obj
# 
# 21    2/17/98 7:50a Ken
# added -DWRITECOMBINE
# 
# 20    2/13/98 10:37a Ken
# put -DNOMONOHOSTBLITS into makefile for now, changed "DEMO" to
# 
# 19    2/12/98 11:19a Ken
# added IRQ=0 environment variable setting to not hook into the interrupt
# chain
# 
# 18    2/12/98 9:32a Ken
# removed BUILD_ROOT paths from includes
# 
# 17    2/11/98 10:42p Artg
# put in option for CT
# 
# 16    2/11/98 10:28p Artg
# put in hang check
# 
# 15    2/10/98 7:45p Artg
# outputdebugstring
# 
# 14    2/04/98 2:01p Ken
# fixed up debug/retail build options
# 
# 13    2/03/98 10:36p Ken
# added DF environment variable for debug command fifo
# 
# 12    1/30/98 10:58p Ken
# added dibblt.c, removed debugging echo
# 
# 11    1/30/98 8:50p Ken
# redone, now supports both h/w and csim builds
# 
# 9     1/27/98 6:04p Artg
# added stretchblts
# 
# 8     1/27/98 11:19a Markl
# Added 32-bit versions of DIB routines.
# 
# 7     1/21/98 11:26a Suninn
# add CF flag for command fifo compiling
##
#--------------------------------------------------------------------
# Define all macros

!ifndef VERBOSE
.SILENT :
!ifndef LOGO
LOGO = /nologo
!endif #!ifndef LOGO
!else #!ifndef VERBOSE
LOGO =
!endif #!ifndef VERBOSE

TARGETDESC = (Hardware)


#--------------------------------------------------------------------
# Define macros for the various compilers, assemblers, linkers
# and library managers.

RC   = $(COMP32)\bin\rc
LK   = $(COMP32)\bin\link
CL   = $(COMP32)\bin\cl
ML   = $(MASM)\bin\ml

SRCDIR   =  ..
INCLUDES = -I$(COMP32)\include
INCLUDES = $(INCLUDES)
INCLUDES = $(INCLUDES) -I$(SRCDIR)\..\inc
INCLUDES = $(INCLUDES) -I$(DDKDX)\inc -I$(DDK9X)\inc32  -I..

#--------------------------------------------------------------------
# Select our working directory, either DEBUG or RETAIL.

!if "$(DEBUG)"=="debug"
DIR = DEBUG
!else
DIR = RETAIL
!endif

#--------------------------------------------------------------------
# Define 32Bit macros for DEBUG or RETAIL build.

!if "$(DEBUG)"=="debug"

# Generic Debug build flags

COPT32 = -DDEBUG -Z7 -DTRACE
MOPT32 = -DDEBUG -D_DEBUG
ROPT32 = -DDEBUG -D_DEBUG
LOPT32  = -debug -debugtype:cv

    # Specific Debug build flags

!else

    # Generic Retail build flags

COPT32 = -Oxa -Z7
MOPT32 =
ROPT32 =
LOPT32 =

    # Specific Retail build flags

!endif

# DirectX version ...
!if ("$(DX)" == "")
DX = 6
!endif
DXTXT = (dx=$(DX))
DXDEF = -DDX=$(DX)

#--------------------------------------------------------------------
# Define our 32 Bit build flag macros

CDEFS32  = $(DXDEF) -D__MSC__ -DDUAL_HEAP -DGLIDE_MUTEX -D_X86_ -DIS_32 -DWIN32 -DDIRECTX
CINCS32  = -I..\..\inc -I..\..\dd32 -I..\..\d3d -I$(DDKDX)\inc -I$(DDK9X)\inc32 -I$(SDK32)\include -I$(COMP32)\include 
CFLAGS32 = $(LOGO) $(COPT32) $(CDEFS32) $(CINCS32) -G5s -FA -W3 -c -Zp -DMINIVDD -DNEC_98

MDEFS32  = $(DXDEF) -DWIN32 -DIS_32 -DSTD_CALL -DBLD_COFF -DMASM6 -D__MSC__
MINCS32  = 
MFLAGS32 = $(LOGO) $(MOPT32) $(MDEFS32) $(MINCS32) -Zp4 -coff -W3 -WX -Zd -c -Cx

RC16 = $(DDKDX)\bin16\rc
RINCS16  = -I..\.. -I$(DDK9X)\inc16
RFLAGS16 = $(RINCS16) -r $(BRDCFLAGS)

LINCS32  = -LIBPATH:..\..\d3d\$(DIR) -LIBPATH:$(DDKDX)\lib -LIBPATH:$(COMP32)\lib
LFLAGS32 = $(LOGO) $(LOPT32) $(LINCS32) -pdb:none -nodefaultlib -align:0x1000


#####################################################################
#--------------------------------------------------------------------
# Lets build everything NOW !!!!


debug:  debug.mak

retail: retail.mak

all:    debug retail

debug.mak retail.mak:
        $(MAKE) -nologo DEBUG=$(@B) build

VXDNAME = h3vdd

!if ("$(HP)" == "H5" || "$(HP)" == "h5")
HWPRODUCT_ECHO = (hp=$(HP)) VSA
VXDFILENAME = 3dfxvs
VXDDEFNAME = vsvdd
BRDCFLAGS  = $(BRDCFLAGS) -DH5
FAMILY_TYPE = -DH5
!elseif ("$(HP)" == "H4" || "$(HP)" == "h4")
HWPRODUCT_ECHO = (hp=$(HP)) Voodoo3
VXDFILENAME = 3dfxv3
VXDDEFNAME = v3vdd
BRDCFLAGS  = $(BRDCFLAGS) -DH4
FAMILY_TYPE = -DH4
!else
HWPRODUCT_ECHO = (hp=$(HP)) Banshee
VXDFILENAME = 3dfxvb
VXDDEFNAME = h3vdd
BRDCFLAGS  = $(BRDCFLAGS) -DH3
FAMILY_TYPE = -DH3
!endif

BUILDS = makedir cddir echo_target $(VXDFILENAME).vxd 

!ifdef SIW95
BUILDS = $(BUILDS) $(VXDFILENAME).nms
!endif

BUILDS = $(BUILDS) copy

build: $(BUILDS)

makedir :
        if not exist .\$(DIR)\nul md .\$(DIR)

cddir:
        cd .\$(DIR)

!if "$(CF)" == "1"
CMDFIFO = -DCMDFIFO
CMDFIFOECHO = (cf=1) YES
!else #!if "$(CF)" == "1"
CMDFIFO = 
CMDFIFOECHO = (cf=0) NO
!endif #!if "$(CF)" == "1"

!if "$(ACF)" == "1"
COPT32 = $(COPT32) -DAGP_CMDFIFO
AGPCMDFIFOECHO = (acf=1) ENABLED
!else #!if "$(ACF)" == "1"
AGPCMDFIFOECHO = (acf=0) DISABLED
!endif #!if "$(ACF)" == "1"

!if "$(DF)" == "1"
CMDFIFO = $(CMDFIFO) -DDEBUGFIFO
DEBUGCMDFIFOECHO = (df=1) YES
!else #!if "$(DF)" == "1"
DEBUGCMDFIFOECHO = (df=0) NO
!endif #!if "$(DF)" == "1"


!if "$(V3TV)" == "1"
COPT32 = $(COPT32) -DV3TV
!endif

!if "$(CT)" == "1"
COPT32 = $(COPT32) -DCRASH
CRASHECHO = (ct=1) YES
!else #!if "$(CT)" == "1"
CRASHECHO = (ct=0) NO
!endif #!if "$(CT)" == "1"

!if "$(IRQ)" == "1"
COPT32 = $(COPT32)
IRQECHO = (irq=1) ENABLED
!else #!if "$(IRQ)" == "0"
COPT32 = $(COPT32) -DNOIRQ
IRQECHO = (irq=0) DISABLED
#IRQECHO = DISABLED
!endif #!if "$(IRQ)" == "0"

!if "$(ND)" == "1"
COPT32 = $(COPT32) -DNULLDRIVER
NULLDRIVEREHCO = (nd=1) ENABLED
!else #!if "$(ND)" == "1"
COPT32 = $(COPT32)
NULLDRIVEREHCO = (nd=0) DISABLED
!endif #!if "$(ND)" == "1"

!if "$(PN)" == "1"
COPT32 = $(COPT32) -DPERFNOP
PERFNOPECHO = (pn=1) ENABLED
!else #!if "$(PN)" == "1"
PERFNOPECHO = (pn=0) DISABLED
!endif #!if "$(PN)" == "1"

!if "$(GCLK)" != ""
COPT32 = $(COPT32) -DH3_GRXCLOCK_IN_MHZ=$(GCLK)
!else
GCLK = 100
COPT32 = $(COPT32) -DH3_GRXCLOCK_IN_MHZ=100
!endif #!if "$(CLK)" != ""

!if "$(MCLK)" != ""
COPT32 = $(COPT32) -DH3_MEMCLOCK_IN_MHZ=$(MCLK)
!else
MCLK = 100
COPT32 = $(COPT32) -DH3_MEMCLOCK_IN_MHZ=100
!endif #!if "$(CLK)" != ""

!if ("$(HP)" == "H5")
COPT32 = $(COPT32) -DH5
!elseif ("$(HP)" == "H4")
COPT32 = $(COPT32) -DH4
!endif #!if ("$(HP)" == "H4")


##############################################
#
# h/w revision build target
#
##############################################

HWREV = hwrev_undefined_is_an_error
HWREV_ECHO = hwrev_undefined_is_an_error

!if "$(HR)" == "B0"
HWREV = -DH3_B0
HWREVECHO = (hr=$(HR)) B0
!elseif "$(HR)" == "A2"
HWREV = -DH3_A2
HWREVECHO = (hr=$(HR)) A2
!elseif "$(HR)" != "A0"
HWREV = -DH3_A1
HWREVECHO = (hr=$(HR)) A1
!else
HWREV = -DH3_A0
HWREVECHO = (hr=$(HR)) A0
!endif #!if "$(HR)" == "A2"

COPT32 = $(COPT32) $(HWREV)

########################################
#
# DDC board schematic build decision
#
########################################

!if "$(SE)" == "1"
COPT32 = $(COPT32) -DSCHEMATIC_ERROR
SCHEMATIC = (se=1) OLD
!else  
SCHEMATIC = (se=0) NEW
!endif #!if "$(SE)" != "1"

!if "$(WCS)" == "1"
WINCS = -DWIN_CSIM
WINSIM = (wcs=1) YES
!else
#WINCS = 
WINSIM = (wcs=0) NO
!endif #!if "$(WCS)" != "0"

!if "$(SA)" == "1"
SLI = -DSLI_AA
SLI_STUFF = (SA=1) YES
!else
#SLI = 
SLI_STUFF = (SA=0) NO
!endif #!if "$(WCS)" != "0"

!if "$(RA)" == "1"
RAE = -DRD_ABORT_ERROR
RD_STUFF = (RA=1) YES
!else
RD_STUFF = (RA=0) NO
!endif #!if "$(WCS)" != "0"

!if "$(RN)" == "1"
RLN = -DREAL_NET
RN_STUFF = (RN=1) YES
!else
RN_STUFF = (RN=0) NO
!endif #!if "$(RN)" != "0"

!if "$(F2D)" == "1"
!if "$(CF)" == "1"
!ERROR No Fast 2D support in CMDFIFO Mode
!endif
GOFAST = -DFAST2D
FASTECHO = (f2d=1) YES
!else
FASTECHO = (f2d=0) NO
!endif #!if "$(F2D)" != "0"

!if "$(LINEAR)" == "1"
LINEAROPT = -DLINEAR_ONLY
LINEARECHO = (LINEAR=1) YES
!else
LINEAROPT =
LINEARECHO = (LINEAR=0) NO
!endif

echo_target:
    @Echo ----- Creating $(DIR) $(VXDFILENAME).vxd $(TARGETDESC) -----
    @Echo Target hardware revision is $(HWREVECHO)
    @echo Target hardware product ... $(HWPRODUCT_ECHO)
    @Echo Command fifo is ........... $(CMDFIFOECHO)
    @Echo Debug Command fifo is ..... $(DEBUGCMDFIFOECHO)
    @Echo Crash check is ............ $(CRASHECHO)
    @Echo IRQs are .................. $(IRQECHO)
    @Echo DDC Board Type is ......... $(SCHEMATIC)
    @Echo NULL Driver testing is .... $(NULLDRIVEREHCO)
    @Echo Perf NOP command is ....... $(PERFNOPECHO)
    @Echo Default Graphics clock is . (GCLK=$(GCLK)) $(GCLK) MHz
    @Echo Default Memory clock is ... (MCLK=$(MCLK)) $(MCLK) MHz
    @Echo AGP command fifo is ....... $(AGPCMDFIFOECHO)
    @Echo Win CSIM  ................. $(WINSIM)
    @Echo SLI AA   .................  $(SLI_STUFF)
    @Echo Read Abort Error ...........$(RD_STUFF)
    @Echo Real Networks  .............$(RN_STUFF)
    @Echo Fast 2D  .................. $(FASTECHO)
    @Echo Linear  ................... $(LINEARECHO)
    @Echo ---------------------------------------------

copy :
        cd ..\..
        if not exist .\bin\nul md .\bin
        cd bin
        if not exist .\$(DIR)\nul md .\$(DIR)
        cd $(DIR)
        copy ..\..\minivdd\$(DIR)\$(VXDFILENAME).vxd $(VXDFILENAME).vxd
!ifdef SIW95
        copy ..\..\minivdd\$(DIR)\$(VXDFILENAME).nms $(VXDFILENAME).nms
!endif #!ifdef SIW95
        cd ..\..\minivdd\$(DIR)

#######################################################
# build our target vxd
#######################################################

LFLAGS = /nodefaultlib /VXD /DEF:..\$(VXDDEFNAME).def /OUT:$(VXDFILENAME).vxd \
       /PDB:"$(VXDFILENAME).pdb" /DEBUG  \
       /MACHINE:i386 /DEBUGTYPE:CV /nologo

AFLAGS     = -coff -DBLD_COFF -DIS_32 -W2 -Zi -c -Cx -DMASM6 $(DXDEF) \
                -DDEBLEVEL=1 -DDEBUG $(BRDAFLAGS) -DMINIVDD=1 -DNEC_98=1 $(FAMILY_TYPE)

AFLAGS2     = -Fl /Zi /coff /I. /c /Cp $(BRDAFLAGS)

CFLAGS = $(COPT32) -DWIN32 -D__WIN32__ $(LOGO) -W3 -G3 -c $(INCLUDES) \
        -Gs99999 -FAcs $(DXDEF) \
        -D__MSC__ -DFX_DLL_ENABLE -DTHUNK32 -DKERNEL \
        $(CMDFIFO)  -DWRITECOMBINE -DH3VDD $(BRDCFLAGS) $(WINCS) $(SLI) $(RAE) $(RLN) $(GOFAST) $(LINEAROPT)

#Treat Warnings as Errors
CFLAGS = $(CFLAGS) -WX


LINK = $(COMP32)\bin\link
CL = $(COMP32)\bin\cl
ML = $(MASM)\bin\ml

OBJS =  $(VXDNAME)ctrl.obj \
        agp.obj \
        access.obj \
        bitblt.obj \
        bltdata.obj\
        dbg32.obj\
        dfp.obj\
        dibblt.obj \
        entrleav.obj \
        hardware.obj \
        output.obj \
        p6stuff.obj \
        polygon.obj \
        realize.obj \
        strchblt.obj \
        support.obj \
        textout.obj \
        kmtv.obj \
        vmipld.obj \
        vmmcalls.obj \
        thunk32.obj \
		cpu.obj \
!ifdef SLI
        sliaa.obj\
!endif
        debug.obj\
        pci.obj\
        $(DDK9X)\lib\vxdwraps.clb

OBJS = $(OBJS) h3vdd.obj h3irq.obj h3gblaxs.obj h3cinit.obj calldbg.obj power.obj devtable.obj time.obj pent.obj bt868.obj ddc.obj lock.obj xlcd.obj nvram.obj gpio.obj

!ifdef OLDI2C
OBJS = $(OBJS) i2c.obj
!else
OBJS = $(OBJS) ds_i2c.obj di_i2c.obj
!endif

!ifdef WINCS
OBJS = $(OBJS) sim.obj
OBJS = $(OBJS) ..\lib\nlpvxd.lib
!endif


SRCDIR = ..

{$(SRCDIR)}.c.obj:
        $(CL) $(CFLAGS) -Fo$*.obj $<

!ifndef OLDI2C
ds_i2c.obj: ..\i2c\ds_i2c.c ..\i2c\di_i2c.h ..\i2c\ds_i2c.h ..\i2c\i2cmacro.h
		$(CL) $(CFLAGS) -Fods_i2c.obj ..\i2c\ds_i2c.c

di_i2c.obj: ..\i2c\di_i2c.c ..\i2c\di_i2c.h ..\i2c\ds_i2c.h ..\i2c\i2cmacro.h
		$(CL) $(CFLAGS) -Fodi_i2c.obj ..\i2c\di_i2c.c
!endif

p6stuff.obj: ..\$(@B).asm
        $(ML) $(AFLAGS) -I$(DDK9X)\inc32 ..\$(@B).asm

# STB Begin Changes
# Adding KMVT to the build process
kmvt.obj: ..\$(@B).asm
        $(ML) $(AFLAGS) -I$(DDKDX)\inc ..\$(@B).asm
# STB End Changes

pent.obj: ..\$(@B).asm
        $(ML) $(AFLAGS) -I$(DDK9X)\inc32 ..\$(@B).asm

calldbg.obj: ..\$(@B).asm
        $(ML) $(AFLAGS2) ..\$(@B).asm

$(VXDNAME)ctrl.obj: ..\$(@B).asm
        $(ML) $(AFLAGS)  -I$(DDKDX)\inc -I$(DDK9X)\inc32 ..\$(@B).asm

$(VXDFILENAME).res: ..\$*.rc
        $(RC16) $(RFLAGS16) -Fo$(@F) ..\$*.rc

$(VXDFILENAME).vxd: $(OBJS) $*.res ..\$(VXDDEFNAME).def
        $(LINK) $(LFLAGS) $(OBJS)
#        $(DDK9X)\bin\adrc2vxd.exe $*.vxd $*.res

!ifdef SIW95
NMSSRCPATH = 

$(VXDFILENAME).nms: $(@B).vxd
        $(SIW95)\nmsym /trans:always,package $(@B).vxd /prompt \
                /source:..;$(NMSSRCPATH)
!endif #!ifdef SIW95

clean:
        rem <<yes
y
<<
        if exist .\debug\*.* del .\debug <yes >nul
        if exist .\debug\nul rd .\debug >nul
        if exist .\retail\*.* del .\retail <yes >nul
        if exist .\retail\nul rd .\retail >nul
