AG		= ..\tools\ag\ag.exe



# Assembler Generator files 

AGFILES		= fr_og.c ras_og.c



TARGETS		= $(AGFILES)



all: $(TARGETS)



fr_og.c: fr_og.ag $(AG)

	$(AG) < fr_og.ag > fr_og.c



ras_og.c: ras_og.ag $(AG)

	$(AG) < ras_og.ag > ras_og.c

