#
# Copyright (c) 1995, 3Dfx Interactive, Inc.
# All Rights Reserved.
#
# This is UNPUBLISHED PROPRIETARY SOURCE CODE of 3Dfx Interactive, Inc.;
# the contents of this file may not be disclosed to third parties, copied or
# duplicated in any form, in whole or in part, without the prior written
# permission of 3Dfx Interactive, Inc.
#
# RESTRICTED RIGHTS LEGEND:
# Use, duplication or disclosure by the Government is subject to restrictions
# as set forth in subdivision (c)(1)(ii) of the Rights in Technical Data
# and Computer Software clause at DFARS 252.227-7013, and/or in similar or
# successor clauses in the FAR, DOD or NASA FAR Supplement. Unpublished  -
# rights reserved under the Copyright Laws of the United States.
#
# $Revision: 18 $
# $Date: 5/26/99 2:52p $
#

THISDIR = swlibs

SUBDIRS = binsrc libsrc incsrc bin include lib fxmisc fxmemmap

!if "$(FX_TARGET)" == "DOS"
SUBDIRS = $(SUBDIRS) FxDpmi dosdll
!else if "$(FX_TARGET)" == "WIN32"
SUBDIRS = $(SUBDIRS) fxntdrvr texus2
!else
!  error "Unknown value for FX_TARGET"
!endif

SUBDIRS = $(SUBDIRS) newpci fxremap fxagp

!include $(BUILD_ROOT_SWLIBS)/include/nmake/3dfx.mak
