#
# Copyright (c) 1995, 3Dfx Interactive, Inc.
# All Rights Reserved.
#
# This is UNPUBLISHED PROPRIETARY SOURCE CODE of 3Dfx Interactive, Inc.;
# the contents of this file may not be disclosed to third parties, copied or
# duplicated in any form, in whole or in part, without the prior written
# permission of 3Dfx Interactive, Inc.
#
# RESTRICTED RIGHTS LEGEND:
# Use, duplication or disclosure by the Government is subject to restrictions
# as set forth in subdivision (c)(1)(ii) of the Rights in Technical Data
# and Computer Software clause at DFARS 252.227-7013, and/or in similar or
# successor clauses in the FAR, DOD or NASA FAR Supplement. Unpublished  -
# rights reserved under the Copyright Laws of the United States.
#


LDIRT= *.exe *.map *.sys *.obj *.lib *.dll *.exp

!if "$(GLIDEPLAY_USE_GDENDTEST)" == "1"
LCDEFS          =       $(LCDEFS) -DGLIDEPLAY_USE_GDENDTEST=1
!endif

LCINCS  = $(LCINCS) -I$(BUILD_ROOT)\$(FX_GLIDE_HW)\include -I..\include -WX

GLIDELIB        =       glide3x.lib

LLDLIBS = $(LIBOBJS) ..\lib\gltrutil.lib $(BUILD_ROOT)\$(FX_GLIDE_HW)\lib\$(GLIDELIB)\

CFILES   = GlideTrap.c

PROGRAMS = glideplay.exe

FX_DLL_LIBRARY = 1

INSTALL_DESTINATION = $(BUILD_ROOT_SWLIBS)

!include $(BUILD_ROOT)\swlibs/include/nmake/3dfx.mak

GlidePlay: glideplay.obj $(LLDLIBS)
