#
# Copyright (c) 1995, 3Dfx Interactive, Inc.
# All Rights Reserved.
#
# This is UNPUBLISHED PROPRIETARY SOURCE CODE of 3Dfx Interactive, Inc.;
# the contents of this file may not be disclosed to third parties, copied or
# duplicated in any form, in whole or in part, without the prior written
# permission of 3Dfx Interactive, Inc.
#
# RESTRICTED RIGHTS LEGEND:
# Use, duplication or disclosure by the Government is subject to restrictions
# as set forth in subdivision (c)(1)(ii) of the Rights in Technical Data
# and Computer Software clause at DFARS 252.227-7013, and/or in similar or
# successor clauses in the FAR, DOD or NASA FAR Supplement. Unpublished  -
# rights reserved under the Copyright Laws of the United States.
#


LDIRT= *.exe *.map *.sys *.o *.a *.so

ifdef GLIDEPLAY_USE_GDENDTEST
LCDEFS := $(LCDEFS) -DGLIDEPLAY_USE_GDENDTEST
endif

LCINCS  := -I$(BUILD_ROOT)/$(FX_GLIDE_HW)/include -I../include

SYSLIBS = -L$(BUILD_ROOT_SST2)/lib -lgdiags -ltexus -lglide3x -lhwc -lsst2hwc -lsst2csim \
          $(BUILD_ROOT_SWLIBS)/lib/fxmisc.a $(HSLIM_LIB) \
          -L/home/mark/tcl/new/lib -ltk8.0 -ltcl8.0 \
          -L/usr/openwin/lib -lX11 -lm -lsocket -lnsl -ldl -lc

HSLIM_LIB = $(TDFX_CHIPROOT)/src/common/diags/tstbench_solaris.a

LLDLIBS = $(LIBOBJS) ../lib/gltrutil.a


CFILES   = glidetrap.c

PROGRAMS = glideplay

FX_DLL_LIBRARY = 1

INSTALL_DESTINATION = $(BUILD_ROOT_SWLIBS)

include $(BUILD_ROOT_SWLIBS)/include/make/3dfx.mak

#LLDLIBS := $(LLDLIBS) $(SYSLIBS)

glideplay: glideplay.o $(LLDLIBS)
	$(LINK) -o glideplay glideplay.o $(LDLIBS) $(SYSLIBS) $(LDFLAGS)
