#
# Copyright (c) 1995, 3Dfx Interactive, Inc.
# All Rights Reserved.
#
# This is UNPUBLISHED PROPRIETARY SOURCE CODE of 3Dfx Interactive, Inc.;
# the contents of this file may not be disclosed to third parties, copied or
# duplicated in any form, in whole or in part, without the prior written
# permission of 3Dfx Interactive, Inc.
#
# RESTRICTED RIGHTS LEGEND:
# Use, duplication or disclosure by the Government is subject to restrictions
# as set forth in subdivision (c)(1)(ii) of the Rights in Technical Data
# and Computer Software clause at DFARS 252.227-7013, and/or in similar or
# successor clauses in the FAR, DOD or NASA FAR Supplement. Unpublished  -
# rights reserved under the Copyright Laws of the United States.
#
# $Revision: 7 $
# $Date: 9/03/95 11:58a $
#

HEADERS = stwtri.h

CFILES	=	bigass.c        \
		cfestress.c     \
		cfereset.c	\
		compton.c	\
		download.c	\
		down2.c		\
		downperf.c	\
		floatstw.c	\
		fmt.c		\
		limits.c	\
		lod.c		\
		move.c		\
		pal.c		\
		simple.c	\
		tchroma.c	\
		tcu.c		\
		texmem.c	\
		tsustw.c	\
		tstress1.c	\
		tstress2.c	\
		perf.c		\
		fc_down1.c	\
		fc_lod.c	\
		fc_it1.c	\
		tfstress.c	\
		detail.c	\
		trilin.c        

OLD_CFILES =	reset.c

LIBOBJS	= stwtri.o ssttex.o
LIBSRC = $(LIBOBJS:.o=.c)

include ../diagsu.mak
