#
# Copyright (c) 1995, 3Dfx Interactive, Inc.
# All Rights Reserved.
#
# This is UNPUBLISHED PROPRIETARY SOURCE CODE of 3Dfx Interactive, Inc.;
# the contents of this file may not be disclosed to third parties, copied or
# duplicated in any form, in whole or in part, without the prior written
# permission of 3Dfx Interactive, Inc.
#
# RESTRICTED RIGHTS LEGEND:
# Use, duplication or disclosure by the Government is subject to restrictions
# as set forth in subdivision (c)(1)(ii) of the Rights in Technical Data
# and Computer Software clause at DFARS 252.227-7013, and/or in similar or
# successor clauses in the FAR, DOD or NASA FAR Supplement. Unpublished  -
# rights reserved under the Copyright Laws of the United States.
#
# $Revision: 9 $
# $Date: 3/11/98 11:37a $
#

CFILES	=	clut.c \
		vidtst.c \
		vidtst_bu.c \
                vidtst2x.c \
                vidtst2x_bu.c \
                vidnew.c \
                vid1.c	\
                vid24.c \
                vid32.c \
                vid_411.c \
		vid_bilerp.c \
		vid_bilerp2.c \
		vid_bilerp3.c \
		vid_chroma1.c \
		vid_chroma2.c \
		vid_dttiled.c \
		vid_indexed.c \
		vid_oltiled.c \
                vid_nodesktop.c \
                vid_nondither.c \
                vid_oly.c \
                vid_testimage.c \
                vid_testimage2.c \
                vid_point.c \
                vid_YUYVp.c \
                vid_YUYVb.c \
                vid_UYVYp.c \
                vid_UYVYb.c \
                vid_undither4.c \
                vid_undither2.c

!include ..\diags.mak
