#
# Copyright (c) 1997, 3Dfx Interactive, Inc.
# All Rights Reserved.
#
# This is UNPUBLISHED PROPRIETARY SOURCE CODE of 3Dfx Interactive, Inc.;
# the contents of this file may not be disclosed to third parties, copied or
# duplicated in any form, in whole or in part, without the prior written
# permission of 3Dfx Interactive, Inc.
#
# RESTRICTED RIGHTS LEGEND:
# Use, duplication or disclosure by the Government is subject to restrictions
# as set forth in subdivision (c)(1)(ii) of the Rights in Technical Data
# and Computer Software clause at DFARS 252.227-7013, and/or in similar or
# successor clauses in the FAR, DOD or NASA FAR Supplement. Unpublished  -
# rights reserved under the Copyright Laws of the United States.
#
# $Revision: 4 $
# $Date: 9/03/95 11:58a $
#

LCDEFS	= -DH4 -DGDBG_INFO_ON -DBUILD_DIAGS -DHAL_CSIM -DHAL_HSIM 
LCOPTS	=
LCINCS	= -I$(BUILD_ROOT)/h5/include -I$(TDFX_COMMONROOT)/src/tests/diags

HEADERS = fbi.h sstdiag.h udiag.h lfbutils.h hsimio.h allocate.h
PRIVATE_HEADERS = ../../csim/csim.h

CFILES	=	fbi.c		\
		random.c	\
		sstdiag.c	\
		sstgdiag.c	\
		ssttri.c	\
		tsumath.c	\
		udiag.c 	\
		histbuf.c	\
		lfbutils.c	\
		vidutils.c	\
		hsimio.c        \
                allocate.c     

# targets
LIBRARIES = diags.a

default: $(LIBRARIES)

include $(BUILD_ROOT_SWLIBS)/include/make/3dfx.mak
