#
# Copyright (c) 1995, 3Dfx Interactive, Inc.
# All Rights Reserved.
#
# This is UNPUBLISHED PROPRIETARY SOURCE CODE of 3Dfx Interactive, Inc.;
# the contents of this file may not be disclosed to third parties, copied or
# duplicated in any form, in whole or in part, without the prior written
# permission of 3Dfx Interactive, Inc.
#
# RESTRICTED RIGHTS LEGEND:
# Use, duplication or disclosure by the Government is subject to restrictions
# as set forth in subdivision (c)(1)(ii) of the Rights in Technical Data
# and Computer Software clause at DFARS 252.227-7013, and/or in similar or
# successor clauses in the FAR, DOD or NASA FAR Supplement. Unpublished  -
# rights reserved under the Copyright Laws of the United States.
#
# $Revision: 2 $
# $Date: 10/14/98 8:37p $

# local defines, options, includes

!if "$(FX_TARGET)" == "DOS"

!if "$(FX_PCI_TARGET)" == "PHARLAP"

LCDEFS  = -DPORTIO_DIRECT -DMAPPL_PHARLAP
LCOPTS  =

#EXTPCIFILES = fxphrlap.c

!else

LCDEFS  = -DPORTIO_DIRECT -DMAPPL_DPMI
LCOPTS  =

SUBLIBRARIES = $(BUILD_ROOT_SWLIBS)\lib\fxdpmi.lib

!endif

!else if "$(FX_TARGET)" == "WIN32"

!if "$(FX_PCI_TARGET)" == "WINRT"

LCDEFS  = -DPORTIO_WINRT -DMAPPL_WINRT
LCOPTS  =

#EXTPCIFILES = fxpcirt.c

!else if "$(FX_PCI_TARGET)" == "NT"

LCDEFS  = -DPORTIO_GPD -DMAPPL_MAPMEM_MINIPORT
LCOPTS  =

# UPDATE fxpcirt.c from fxpcirt.wc with "nmake winrt"

!else

# usual case

LCDEFS  = -DPORTIO_DIRECT -DMAPPL_MEMMAP_VXD
LCOPTS  =

!endif

!endif

INSTALL_DESTINATION = $(BUILD_ROOT_SWLIBS)

# sources
HEADERS             = fxremap.h
CFILES              = fxremap.c
FX_DLL_COMPILE      = 0

# targets
LIBRARIES = fxremap.lib

!include $(BUILD_ROOT_SWLIBS)\include\nmake\3dfx.mak

