TARGETOS = WINNT

!include <ntwin32.mak>

TARGET = lib.lib

CFILES = \
	alloc.c \
	check.c \
	defaultState.c \
	evaluator.c \
	getenv.c \
	gltst.c \
	imbuildutil.c \
	imgutil.c \
	matrix.c \
	pixutil.c \
	rand.c \
	readwrite.c \
	set.c \
	texsim.c \
	texutil.c \
	util.c

OBJECTS = $(CFILES:.c=.obj)

LCINCS = -I..\inc 
LCDEFS = -D__STDC__ -DWIN32
LCFLAGS = $(LCDEFS) $(LCINCS)

all: $(TARGET)

.c.obj:
    $(cc) $(cdebug) $(LCFLAGS) $(cflags) $(cvars) $(scall) $*.c

$(TARGET): $(OBJECTS)
    $(implib) -out:$*.lib $** 

clean:
    rm -f $(OBJECTS)

clobber: clean
    rm -f $(TARGET)
