##
##  Makefile for Windows NT
##


!include <ntwin32.mak>


#GLUTHOME = %GLUTHOME%
CFLAGS   = -I$(GLUTHOME) -DWIN32 -nologo -W1 -Z7
LIBS     = $(GLUTHOME)/glut.lib glu32.lib opengl32.lib $(guilibs)
EXES     = agv_example.exe fractals.exe gears.exe \
#hanoi.exe hanoi2.exe \
           lineblend.exe moth.exe noof.exe rings.exe steam.exe text3d.exe \
           worms.exe

all             : $(EXES)


agv_example.exe	: agv_example.obj agviewer.obj
        $(link) -nologo -debug -nodefaultlib:libcd -out:$@ agv_example.obj agviewer.obj $(LIBS)

fractals.exe	: fractals.obj fracviewer.obj
        $(link) -nologo -debug -nodefaultlib:libcd -out:$@ fractals.obj fracviewer.obj $(LIBS)

gears.exe	: gears.obj
        $(link) -nologo -debug -nodefaultlib:libcd -out:$@ gears.obj $(LIBS)

hanoi.exe	: hanoi.obj
        $(link) -nologo -debug -nodefaultlib:libcd -out:$@ hanoi.obj $(LIBS)

hanoi2.exe	: hanoi2.obj engine.obj
        $(link) -nologo -debug -nodefaultlib:libcd -out:$@ hanoi2.obj engine.obj $(LIBS)

lineblend.exe	: lineblend.obj
        $(link) -nologo -debug -nodefaultlib:libcd -out:$@ lineblend.obj $(LIBS)

moth.exe	: moth.obj
        $(link) -nologo -debug -nodefaultlib:libcd -out:$@ moth.obj $(LIBS)

noof.exe	: noof.obj
        $(link) -nologo -debug -nodefaultlib:libcd -out:$@ noof.obj $(LIBS)

rings.exe	: rings.obj
        $(link) -nologo -debug -nodefaultlib:libcd -out:$@ rings.obj $(LIBS)

steam.exe	: steam.obj
        $(link) -nologo -debug -nodefaultlib:libcd -out:$@ steam.obj $(LIBS)

text3d.exe	: text3d.obj
        $(link) -nologo -debug -nodefaultlib:libcd -out:$@ text3d.obj $(LIBS)

worms.exe	: worms.obj
        $(link) -nologo -debug -nodefaultlib:libcd -out:$@ worms.obj $(LIBS)

.c.obj:
	$(CC) $(CFLAGS) -c $<

clean:
        rm -f *.exe *.obj *.pdb $(EXES) *.ilk
