/* DO NOT EDIT - THIS FILE IS AUTOMATICALLY GENERATED */

/*
** Copyright 1992-1997 Silicon Graphics, Inc.
** All Rights Reserved.
**
** This is UNPUBLISHED PROPRIETARY SOURCE CODE of Silicon Graphics, Inc.;
** the contents of this file may not be disclosed to third parties, copied or
** duplicated in any form, in whole or in part, without the prior written
** permission of Silicon Graphics, Inc.
**
** RESTRICTED RIGHTS LEGEND:
** Use, duplication or disclosure by the Government is subject to restrictions
** as set forth in subdivision (c)(1)(ii) of the Rights in Technical Data
** and Computer Software clause at DFARS 252.227-7013, and/or in similar or
** successor clauses in the FAR, DOD or NASA FAR Supplement. Unpublished -
** rights reserved under the Copyright Laws of the United States.
*/

#include <windows.h>
#include <GL/gl.h>


#define __GL_PROC_COUNT 358

static char *__glProcNames[__GL_PROC_COUNT] = {
    "glNewList",
    "glEndList",
    "glCallList",
    "glCallLists",
    "glDeleteLists",
    "glGenLists",
    "glListBase",
    "glBegin",
    "glBitmap",
    "glEdgeFlag",
    "glEdgeFlagv",
    "glEnd",
    "glClipPlane",
    "glColorMaterial",
    "glCullFace",
    "glFogf",
    "glFogfv",
    "glFogi",
    "glFogiv",
    "glFrontFace",
    "glHint",
    "glLightf",
    "glLightfv",
    "glLighti",
    "glLightiv",
    "glLightModelf",
    "glLightModelfv",
    "glLightModeli",
    "glLightModeliv",
    "glLineStipple",
    "glLineWidth",
    "glMaterialf",
    "glMaterialfv",
    "glMateriali",
    "glMaterialiv",
    "glPointSize",
    "glPolygonMode",
    "glPolygonStipple",
    "glScissor",
    "glShadeModel",
    "glTexParameterf",
    "glTexParameterfv",
    "glTexParameteri",
    "glTexParameteriv",
    "glTexImage1D",
    "glTexImage2D",
    "glTexEnvf",
    "glTexEnvfv",
    "glTexEnvi",
    "glTexEnviv",
    "glTexGend",
    "glTexGendv",
    "glTexGenf",
    "glTexGenfv",
    "glTexGeni",
    "glTexGeniv",
    "glFeedbackBuffer",
    "glSelectBuffer",
    "glRenderMode",
    "glInitNames",
    "glLoadName",
    "glPassThrough",
    "glPopName",
    "glPushName",
    "glDrawBuffer",
    "glClear",
    "glClearAccum",
    "glClearIndex",
    "glClearColor",
    "glClearStencil",
    "glClearDepth",
    "glStencilMask",
    "glColorMask",
    "glDepthMask",
    "glIndexMask",
    "glAccum",
    "glDisable",
    "glEnable",
    "glFinish",
    "glFlush",
    "glPopAttrib",
    "glPushAttrib",
    "glMap1d",
    "glMap1f",
    "glMap2d",
    "glMap2f",
    "glMapGrid1d",
    "glMapGrid1f",
    "glMapGrid2d",
    "glMapGrid2f",
    "glEvalCoord1d",
    "glEvalCoord1dv",
    "glEvalCoord1f",
    "glEvalCoord1fv",
    "glEvalCoord2d",
    "glEvalCoord2dv",
    "glEvalCoord2f",
    "glEvalCoord2fv",
    "glEvalMesh1",
    "glEvalPoint1",
    "glEvalMesh2",
    "glEvalPoint2",
    "glAlphaFunc",
    "glBlendFunc",
    "glLogicOp",
    "glStencilFunc",
    "glStencilOp",
    "glDepthFunc",
    "glPixelZoom",
    "glPixelTransferf",
    "glPixelTransferi",
    "glPixelStoref",
    "glPixelStorei",
    "glPixelMapfv",
    "glPixelMapuiv",
    "glPixelMapusv",
    "glReadBuffer",
    "glCopyPixels",
    "glReadPixels",
    "glDrawPixels",
    "glGetBooleanv",
    "glGetClipPlane",
    "glGetDoublev",
    "glGetError",
    "glGetFloatv",
    "glGetIntegerv",
    "glGetLightfv",
    "glGetLightiv",
    "glGetMapdv",
    "glGetMapfv",
    "glGetMapiv",
    "glGetMaterialfv",
    "glGetMaterialiv",
    "glGetPixelMapfv",
    "glGetPixelMapuiv",
    "glGetPixelMapusv",
    "glGetPolygonStipple",
    "glGetString",
    "glGetTexEnvfv",
    "glGetTexEnviv",
    "glGetTexGendv",
    "glGetTexGenfv",
    "glGetTexGeniv",
    "glGetTexImage",
    "glGetTexParameterfv",
    "glGetTexParameteriv",
    "glGetTexLevelParameterfv",
    "glGetTexLevelParameteriv",
    "glIsEnabled",
    "glIsList",
    "glDepthRange",
    "glFrustum",
    "glLoadIdentity",
    "glLoadMatrixf",
    "glLoadMatrixd",
    "glMatrixMode",
    "glMultMatrixf",
    "glMultMatrixd",
    "glOrtho",
    "glPopMatrix",
    "glPushMatrix",
    "glRotated",
    "glRotatef",
    "glScaled",
    "glScalef",
    "glTranslated",
    "glTranslatef",
    "glViewport",
    0,   /* skip extension */
    0,   /* skip extension */
    0,   /* skip extension */
    0,   /* skip extension */
    0,   /* skip extension */
    0,   /* skip extension */
    0,   /* skip extension */
    0,   /* skip extension */
    0,   /* skip extension */
    0,   /* skip extension */
    0,   /* skip extension */
    0,   /* skip extension */
    0,   /* skip extension */
    0,   /* skip extension */
    0,   /* skip extension */
    "glArrayElement",
    "glColorPointer",
    "glDisableClientState",
    "glDrawArrays",
    "glDrawElements",
    "glEdgeFlagPointer",
    "glEnableClientState",
    "glGetPointerv",
    "glIndexPointer",
    "glInterleavedArrays",
    "glNormalPointer",
    "glTexCoordPointer",
    "glVertexPointer",
    "glPolygonOffset",
    "glCopyTexImage1D",
    "glCopyTexImage2D",
    "glCopyTexSubImage1D",
    "glCopyTexSubImage2D",
    "glTexSubImage1D",
    "glTexSubImage2D",
    "glAreTexturesResident",
    "glBindTexture",
    "glDeleteTextures",
    "glGenTextures",
    "glIsTexture",
    "glPrioritizeTextures",
    "glIndexub",
    "glIndexubv",
    "glPopClientAttrib",
    "glPushClientAttrib",
    0,   /* skip extension */
    0,   /* skip extension */
    0,   /* skip extension */
    0,   /* skip extension */
    0,   /* skip extension */
    0,   /* skip extension */
    0,   /* skip extension */
    "glVertex2d",
    "glVertex2dv",
    "glVertex2f",
    "glVertex2fv",
    "glVertex2i",
    "glVertex2iv",
    "glVertex2s",
    "glVertex2sv",
    "glVertex3d",
    "glVertex3dv",
    "glVertex3f",
    "glVertex3fv",
    "glVertex3i",
    "glVertex3iv",
    "glVertex3s",
    "glVertex3sv",
    "glVertex4d",
    "glVertex4dv",
    "glVertex4f",
    "glVertex4fv",
    "glVertex4i",
    "glVertex4iv",
    "glVertex4s",
    "glVertex4sv",
    "glColor3b",
    "glColor3bv",
    "glColor3d",
    "glColor3dv",
    "glColor3f",
    "glColor3fv",
    "glColor3i",
    "glColor3iv",
    "glColor3s",
    "glColor3sv",
    "glColor3ub",
    "glColor3ubv",
    "glColor3ui",
    "glColor3uiv",
    "glColor3us",
    "glColor3usv",
    "glColor4b",
    "glColor4bv",
    "glColor4d",
    "glColor4dv",
    "glColor4f",
    "glColor4fv",
    "glColor4i",
    "glColor4iv",
    "glColor4s",
    "glColor4sv",
    "glColor4ub",
    "glColor4ubv",
    "glColor4ui",
    "glColor4uiv",
    "glColor4us",
    "glColor4usv",
    "glIndexd",
    "glIndexdv",
    "glIndexf",
    "glIndexfv",
    "glIndexi",
    "glIndexiv",
    "glIndexs",
    "glIndexsv",
    "glNormal3b",
    "glNormal3bv",
    "glNormal3d",
    "glNormal3dv",
    "glNormal3f",
    "glNormal3fv",
    "glNormal3i",
    "glNormal3iv",
    "glNormal3s",
    "glNormal3sv",
    "glTexCoord1d",
    "glTexCoord1dv",
    "glTexCoord1f",
    "glTexCoord1fv",
    "glTexCoord1i",
    "glTexCoord1iv",
    "glTexCoord1s",
    "glTexCoord1sv",
    "glTexCoord2d",
    "glTexCoord2dv",
    "glTexCoord2f",
    "glTexCoord2fv",
    "glTexCoord2i",
    "glTexCoord2iv",
    "glTexCoord2s",
    "glTexCoord2sv",
    "glTexCoord3d",
    "glTexCoord3dv",
    "glTexCoord3f",
    "glTexCoord3fv",
    "glTexCoord3i",
    "glTexCoord3iv",
    "glTexCoord3s",
    "glTexCoord3sv",
    "glTexCoord4d",
    "glTexCoord4dv",
    "glTexCoord4f",
    "glTexCoord4fv",
    "glTexCoord4i",
    "glTexCoord4iv",
    "glTexCoord4s",
    "glTexCoord4sv",
    "glRasterPos2d",
    "glRasterPos2dv",
    "glRasterPos2f",
    "glRasterPos2fv",
    "glRasterPos2i",
    "glRasterPos2iv",
    "glRasterPos2s",
    "glRasterPos2sv",
    "glRasterPos3d",
    "glRasterPos3dv",
    "glRasterPos3f",
    "glRasterPos3fv",
    "glRasterPos3i",
    "glRasterPos3iv",
    "glRasterPos3s",
    "glRasterPos3sv",
    "glRasterPos4d",
    "glRasterPos4dv",
    "glRasterPos4f",
    "glRasterPos4fv",
    "glRasterPos4i",
    "glRasterPos4iv",
    "glRasterPos4s",
    "glRasterPos4sv",
    "glRectd",
    "glRectdv",
    "glRectf",
    "glRectfv",
    "glRecti",
    "glRectiv",
    "glRects",
    "glRectsv",
};


/***************************************************************************/

#include <stdio.h>
#include "context.h"
#include "imports.h"
#include "machdep.h"
#include "global.h"
#include "g_imfncs.h"
#include "dlistopt.h"
#include "g_disp.h"
#include "wglcmds.h"

#define __GDI_PROC_COUNT 5

static void *__gdiDispatchTable[__GDI_PROC_COUNT] = 
{
    oglChoosePixelFormat,
    oglDescribePixelFormat,
    oglGetPixelFormat,
    oglSetPixelFormat,
    oglSwapBuffers,
};

static char *__gdiProcNames[__GDI_PROC_COUNT] = {
    "ChoosePixelFormat",
    "DescribePixelFormat",
    "GetPixelFormat",
    "SetPixelFormat",
    "SwapBuffers",
};

#pragma warning ( disable : 4273 )
#pragma warning ( disable : 4035 )

__declspec(naked)
int   WINAPI ChoosePixelFormat(HDC hDC, CONST PIXELFORMATDESCRIPTOR *ppfd)
{
    __asm jmp __gdiDispatchTable+(4*0)
}

__declspec(naked)
int   WINAPI wglChoosePixelFormat(HDC hDC, CONST PIXELFORMATDESCRIPTOR *ppfd)
{
    __asm jmp __gdiDispatchTable+(4*0)
}

__declspec(naked)
int  WINAPI DescribePixelFormat(HDC hDC, int iPixelFormat, UINT nBytes,
				LPPIXELFORMATDESCRIPTOR ppfd)
{
    __asm jmp __gdiDispatchTable+(4*1)
}

__declspec(naked)
int  WINAPI wglDescribePixelFormat(HDC hDC, int iPixelFormat, UINT nBytes,
				   LPPIXELFORMATDESCRIPTOR ppfd)
{
    __asm jmp __gdiDispatchTable+(4*1)
}

__declspec(naked)
int   WINAPI GetPixelFormat(HDC hDC)
{
    __asm jmp __gdiDispatchTable+(4*2)
}

__declspec(naked)
int   WINAPI wglGetPixelFormat(HDC hDC)
{
    __asm jmp __gdiDispatchTable+(4*2)
}

__declspec(naked)
BOOL  WINAPI SetPixelFormat(HDC hDC, int iPixelFormat,
			    CONST PIXELFORMATDESCRIPTOR *ppfd)
{
    __asm jmp __gdiDispatchTable+(4*3)
}

__declspec(naked)
BOOL  WINAPI wglSetPixelFormat(HDC hDC, int iPixelFormat,
			       CONST PIXELFORMATDESCRIPTOR *ppfd)
{
    __asm jmp __gdiDispatchTable+(4*3)
}

__declspec(naked)
BOOL  WINAPI SwapBuffers(HDC hDC)
{
    __asm jmp __gdiDispatchTable+(4*4)
}

__declspec(naked)
BOOL  WINAPI wglSwapBuffers(HDC hDC)
{
    __asm jmp __gdiDispatchTable+(4*4)
}

#pragma warning ( default : 4273 )
#pragma warning ( default : 4035 )

/***************************************************************************/

#define __WGL_PROC_COUNT 19

static void *__wglDispatchTable[__WGL_PROC_COUNT] = {
    oglCreateContext,
    oglDeleteContext,
    oglGetCurrentContext,
    oglGetCurrentDC,
    oglGetProcAddress,
    oglMakeCurrent,
    oglShareLists,
    oglUseFontBitmapsA,
    oglUseFontBitmapsW,
    oglUseFontOutlinesA,
    oglUseFontOutlinesW,
    oglCopyContext,
    oglCreateLayerContext,
    oglDescribeLayerPlane,
    oglGetDefaultProcAddress,
    oglGetLayerPaletteEntries,
    oglRealizeLayerPalette,
    oglSetLayerPaletteEntries,
    oglSwapLayerBuffers,
};

static char *__wglProcNames[__WGL_PROC_COUNT] = {
    "wglCreateContext", 
    "wglDeleteContext", 
    "wglGetCurrentContext", 
    "wglGetCurrentDC", 
    "wglGetProcAddress", 
    "wglMakeCurrent", 
    "wglShareLists", 
    "wglUseFontBitmapsA", 
    "wglUseFontBitmapsW", 
    "wglUseFontOutlinesA", 
    "wglUseFontOutlinesW",
    "wglCopyContext",
    "wglCreateLayerContext",
    "wglDescribeLayerPlane",
    "wglGetDefaultProcAddress",
    "wglGetLayerPaletteEntries",
    "wglRealizeLayerPalette",
    "wglSetLayerPaletteEntries",
    "wglSwapLayerBuffers",
};

#pragma warning ( disable : 4273 )
#pragma warning ( disable : 4035 )

__declspec(naked)
HGLRC WINAPI wglCreateContext(HDC hDC)
{
    __asm jmp __wglDispatchTable+(4*0)
}

__declspec(naked)
BOOL  WINAPI wglDeleteContext(HGLRC hGLRC)
{
    __asm jmp __wglDispatchTable+(4*1)
}

__declspec(naked)
HGLRC WINAPI wglGetCurrentContext(VOID)
{
    __asm jmp __wglDispatchTable+(4*2)
}

__declspec(naked)
HDC   WINAPI wglGetCurrentDC(VOID)
{
    __asm jmp __wglDispatchTable+(4*3)
}

__declspec(naked)
PROC  WINAPI wglGetProcAddress(LPCSTR lpStr)
{
    __asm jmp __wglDispatchTable+(4*4)
}

BOOL  WINAPI wglMakeCurrent(HDC hDC, HGLRC hGLRC)
{
    extern __GLcontext *__wglGetCurrentGC(void);
    BOOL (WINAPI *makeCurrent)(HDC, HGLRC);

    (void) __wglGetCurrentGC();
    makeCurrent = __wglDispatchTable[5];

    return (*makeCurrent)(hDC, hGLRC);
}

__declspec(naked)
BOOL  WINAPI wglShareLists(HGLRC hGLRC1, HGLRC hGLRC2)
{
    __asm jmp __wglDispatchTable+(4*6)
}

__declspec(naked)
BOOL  WINAPI wglUseFontBitmapsA(HDC hDC, DWORD a, DWORD b, DWORD c)
{
    __asm jmp __wglDispatchTable+(4*7)
}

__declspec(naked)
BOOL  WINAPI wglUseFontBitmapsW(HDC hDC, DWORD a, DWORD b, DWORD c)
{
    __asm jmp __wglDispatchTable+(4*8)
}

__declspec(naked)
BOOL  WINAPI wglUseFontOutlinesA(HDC hDC, DWORD a, DWORD b, DWORD c, FLOAT d,
				 FLOAT e, int f, LPGLYPHMETRICSFLOAT g)
{
    __asm jmp __wglDispatchTable+(4*9)
}

__declspec(naked)
BOOL  WINAPI wglUseFontOutlinesW(HDC hDC, DWORD a, DWORD b, DWORD c, FLOAT d,
				 FLOAT e, int f, LPGLYPHMETRICSFLOAT g)
{
    __asm jmp __wglDispatchTable+(4*10)
}

__declspec(naked)
BOOL WINAPI wglCopyContext(HGLRC hglrcSrc, HGLRC hglrcDst, UINT mask)
{
    __asm jmp __wglDispatchTable+(4*11)
}

__declspec(naked)
HGLRC WINAPI wglCreateLayerContext(HDC hDC, int iLayerPlane)
{
    __asm jmp __wglDispatchTable+(4*12)
}

__declspec(naked)
BOOL WINAPI wglDescribeLayerPlane(HDC hDC, int iPixelFormat, int iLayerPlane,
				  UINT nBytes, LPLAYERPLANEDESCRIPTOR plpd)
{
    __asm jmp __wglDispatchTable+(4*13)
}

__declspec(naked)
PROC WINAPI wglGetDefaultProcAddress(LPCSTR lpszProc)
{
    __asm jmp __wglDispatchTable+(4*14)
}

__declspec(naked)
int WINAPI wglGetLayerPaletteEntries(HDC hDC, int iLayerPlane, int iStart,
				     int cEntries, COLORREF *par)
{
    __asm jmp __wglDispatchTable+(4*15)
}

__declspec(naked)
BOOL WINAPI wglRealizeLayerPalette(HDC hDC, int iLayerPlane, BOOL bRealize)
{
    __asm jmp __wglDispatchTable+(4*16)
}

__declspec(naked)
int WINAPI wglSetLayerPaletteEntries(HDC hDC, int iLayerPlane, int iStart,
				     int cEntries, const COLORREF *par)
{
    __asm jmp __wglDispatchTable+(4*17)
}

__declspec(naked)
BOOL WINAPI wglSwapLayerBuffers(HDC hDC, UINT fuPlanes)
{
    __asm jmp __wglDispatchTable+(4*18)
}

#pragma warning ( default : 4273 )
#pragma warning ( default : 4035 )


/***************************************************************************/

static GLboolean __glInitDispatchTable(HINSTANCE hInstance)
{
    int ii;
    void *proc;
    void **dispatchTable = (void **) &__gl_dispatch;

    for (ii = 0; ii < __GL_PROC_COUNT; ii++) {
	if (__glProcNames[ii]) {
	    proc = GetProcAddress(hInstance, __glProcNames[ii]);
	    if (NULL == proc)
		return GL_FALSE;
	    dispatchTable[ii] = proc;
	}
    }
    return GL_TRUE;
}

static GLboolean __gdiInitDispatchTable(HINSTANCE hInstance)
{
    int ii;
    void *proc;

    for (ii = 0; ii < __GDI_PROC_COUNT; ii++) {
	proc = GetProcAddress(hInstance, __gdiProcNames[ii]);
	if (NULL == proc)
	    return GL_FALSE;
	__gdiDispatchTable[ii] = proc;
    }
    return GL_TRUE;
}

static GLboolean __wglInitDispatchTable(HINSTANCE hInstance)
{
    int ii;
    void *proc;

    for (ii = 0; ii < __WGL_PROC_COUNT; ii++) {
	proc = GetProcAddress(hInstance, __wglProcNames[ii]);
	if (NULL == proc)
	    return GL_FALSE;
	__wglDispatchTable[ii] = proc;
    }
    return GL_TRUE;
}

BOOL __wglSetupMSDispatch(HINSTANCE hInstanceMS)
{
    GLboolean status;
    HINSTANCE hInstanceGDI;

    hInstanceGDI = LoadLibrary("Gdi32.dll");
    if (NULL == hInstanceGDI) {
	return FALSE;
    }

    status = __glInitDispatchTable(hInstanceMS);
    if (GL_FALSE == status)
	return FALSE;

    status = __wglInitDispatchTable(hInstanceMS);
    if (GL_FALSE == status)
	return FALSE;

    status = __gdiInitDispatchTable(hInstanceGDI);
    if (GL_FALSE == status)
	return FALSE;

    return TRUE;
}
