#, mlwp
# Copyright (c) 1995, 3Dfx Interactive, Inc.
# All Rights Reserved.
#
# This is UNPUBLISHED PROPRIETARY SOURCE CODE of 3Dfx Interactive, Inc.;
# the contents of this file may not be disclosed to third parties, copied or
# duplicated in any form, in whole or in part, without the prior written
# permission of 3Dfx Interactive, Inc.
#
# RESTRICTED RIGHTS LEGEND:
# Use, duplication or disclosure by the Government is subject to restrictions
# as set forth in subdivision (c)(1)(ii) of the Rights in Technical Data
# and Computer Software clause at DFARS 252.227-7013, and/or in similar or
# successor clauses in the FAR, DOD or NASA FAR Supplement. Unpublished  -
# rights reserved under the Copyright Laws of the United States.
#

# ARCADE TOOLBOX COMPILATION FLAGS
#
# -DAT_BUILD_LIBRARY - Defined when building the library
#
# -DAT_DEBUGGING  - Enable parameter checking and bug catching code.
# -DAT_PRODUCTION - Disable parameter checking and debugging code.
#                   Use this with optimized builds
# -DAT_STATISTICS       - Include statistic tracking code.
# -DAT_PENTIUM_ASSEMBLY - Use pentium optimized assembly routines
# -DAT_CHECK_TRIS       - Check every triangle against screen
#

# Preprocessor Defines
!if "$(FX_COMPILER)"=="DJGPP"
LCDEFS    = -DAT_BUILD_LIBRARY -DAT_STATISTICS
!else
LCDEFS    = -DAT_BUILD_LIBRARY -DAT_STATISTICS
!endif

!if "$(DEBUG)"=="1"
LCDEFS    = -DAT_DEBUGGING $(LCDEFS) 
!else
LCDEFS    = -DAT_PRODUCTION -DAT_PENTIUM_ASSEMBLY $(LCDEFS)
!endif

LCDEFS =  $(LCDEFS) -DAT_DRIVER_D3D


!if "$(FX_GLIDE3)" != ""
LCDEFS = $(LCDEFS) -DGLIDE3 
!endif


LCINCS    = -I. -I..\..\atr -I$(BUILD_ROOT)\$(FX_GLIDE_HW)\include \
            -I$(BUILD_ROOT_SWLIBS)\include \
            -I$(BUILD_ROOT_ARCADE)\include \
            -I$(DIRECTXSDK)\inc

!if "$(HWC_CSIM)" != ""
LCDEFS = $(LCDEFS) -DHWC_CSIM 
LCINCS = $(LCINCS) -I$(BUILD_ROOT)\$(FX_GLIDE_HW)\include
!endif

# sources TBD: reinclude this dependencies are hosed
PRIVATE_HEADERS = rglide.h

CFILES    = rglide.c grender.c gclip.c
            
AFILES    = xatr.asm


!if "$(FX_GLIDE3)" != ""
SUBLIBRARIES =  $(SUBLIBRARIES) $(BUILD_ROOT)\$(FX_GLIDE_HW)\lib\glide3x.lib
!else
SUBLIBRARIES =  $(SUBLIBRARIES) $(BUILD_ROOT)\$(FX_GLIDE_HW)\lib\glide2x.lib
!endif

# targets
INSTALL_DESTINATION = $(BUILD_ROOT_ARCADE)
LIBRARIES    = atglide.lib

!include $(BUILD_ROOT_SWLIBS)/include/nmake/3dfx.mak
