#
# Copyright (c) 1995, 3Dfx Interactive, Inc.
# All Rights Reserved.
#
# This is UNPUBLISHED PROPRIETARY SOURCE CODE of 3Dfx Interactive, Inc.;
# the contents of this file may not be disclosed to third parties, copied or
# duplicated in any form, in whole or in part, without the prior written
# permission of 3Dfx Interactive, Inc.
#
# RESTRICTED RIGHTS LEGEND:
# Use, duplication or disclosure by the Government is subject to restrictions
# as set forth in subdivision (c)(1)(ii) of the Rights in Technical Data
# and Computer Software clause at DFARS 252.227-7013, and/or in similar or
# successor clauses in the FAR, DOD or NASA FAR Supplement. Unpublished  -
# rights reserved under the Copyright Laws of the United States.
#
# $Revision: 5 $
# $Date: 3/29/96 7:40a $
#
THISDIR=watcrt
SUBDIRS=stub


LIBS= clib3s.lib math387s.lib math3s.lib

INSTALL_DESTINATION=$(BUILD_ROOT_SWLIBS)

INSTALL= xcopy /d /k /r /i /s /q

all: libs       

libs: $(LIBS)
        FOR %I IN ( $(LIBS) ) DO $(INSTALL) %I $(INSTALL_DESTINATION)\lib


clean:
	@echo make clean is locally overrided

clobber:
	@echo make clobber is locally overrided

bins:
	@echo make bins is locally overrided

incs:
	@echo make incs is locally overrided
