##
##  Makefile for Windows NT
##


!include <ntwin32.mak>


#GLUTHOME = ../../../lib/glut
CFLAGS   = -I$(GLUTHOME) -DWIN32 -nologo -W1 -Z7
LIBS     = $(GLUTHOME)/glut.lib glu32.lib opengl32.lib $(guilibs) \
           -nologo -debug -nodefaultlib:libcd

OBJS     = a.obj b.obj d.obj e.obj f.obj h.obj i.obj m.obj n.obj o.obj \
           p.obj r.obj s.obj t.obj w.obj draw_holder.obj draw_lamp.obj \
           draw_logo.obj draw_logo_line.obj draw_logo_shadow.obj track.obj
EXES     = ideas.exe


all     : $(EXES)


$(EXES) : $(OBJS)
        $(link) -out:$@ $(OBJS) $(LIBS)

.c.obj:
	$(CC) $(CFLAGS) -c $<

clean:
        rm -f $(EXES) *.obj *.pdb *.ilk *.ncb *.tpl
