
/* DO NOT EDIT - THIS FILE IS AUTOMATICALLY GENERATED */

/*
** Copyright 1992-1997 Silicon Graphics, Inc.
** All Rights Reserved.
**
** This is UNPUBLISHED PROPRIETARY SOURCE CODE of Silicon Graphics, Inc.;
** the contents of this file may not be disclosed to third parties, copied or
** duplicated in any form, in whole or in part, without the prior written
** permission of Silicon Graphics, Inc.
**
** RESTRICTED RIGHTS LEGEND:
** Use, duplication or disclosure by the Government is subject to restrictions
** as set forth in subdivision (c)(1)(ii) of the Rights in Technical Data
** and Computer Software clause at DFARS 252.227-7013, and/or in similar or
** successor clauses in the FAR, DOD or NASA FAR Supplement. Unpublished -
** rights reserved under the Copyright Laws of the United States.
*/

/* File generated by genvertarray.awk -- DO NOT EDIT!!! */
#include <assert.h>
#include "global.h"
#include "context.h"
#include "varray.h"

void __glDrawArraysV(GLenum mode, GLint first, GLsizei count)
{
    __GL_SETUP();
    assert(!glIsEnabled(GL_NORMAL_ARRAY_EXT));
    assert(!glIsEnabled(GL_COLOR_ARRAY_EXT));
    assert(!glIsEnabled(GL_TEXTURE_COORD_ARRAY_EXT));
    assert(!glIsEnabled(GL_INDEX_ARRAY_EXT));
    assert(!glIsEnabled(GL_EDGE_FLAG_ARRAY_EXT));
    assert(glIsEnabled(GL_VERTEX_ARRAY_EXT));
    {
	const char *vp = (const char *)gc->vertexArray.vertex_pointer
		+ first*gc->vertexArray.vp_stride;
	void (APIENTRY *v_func)(const char *) = gc->vertexArray.vp_call;
	int i;
	glBegin(mode);
	for (i = 0; i < count; i++) {
	    (*v_func)(vp); vp += gc->vertexArray.vp_stride;
	}
	glEnd();
    }
}

void __glDrawArraysNV(GLenum mode, GLint first, GLsizei count)
{
    __GL_SETUP();
    assert(glIsEnabled(GL_NORMAL_ARRAY_EXT));
    assert(!glIsEnabled(GL_COLOR_ARRAY_EXT));
    assert(!glIsEnabled(GL_TEXTURE_COORD_ARRAY_EXT));
    assert(!glIsEnabled(GL_INDEX_ARRAY_EXT));
    assert(!glIsEnabled(GL_EDGE_FLAG_ARRAY_EXT));
    assert(glIsEnabled(GL_VERTEX_ARRAY_EXT));
    {
	const char *np = (const char *)gc->vertexArray.normal_pointer
		+ first*gc->vertexArray.np_stride;
	void (APIENTRY *n_func)(const char *) = gc->vertexArray.np_call;
	const char *vp = (const char *)gc->vertexArray.vertex_pointer
		+ first*gc->vertexArray.vp_stride;
	void (APIENTRY *v_func)(const char *) = gc->vertexArray.vp_call;
	int i;
	glBegin(mode);
	for (i = 0; i < count; i++) {
	    (*n_func)(np); np += gc->vertexArray.np_stride;
	    (*v_func)(vp); vp += gc->vertexArray.vp_stride;
	}
	glEnd();
    }
}

void __glDrawArraysCV(GLenum mode, GLint first, GLsizei count)
{
    __GL_SETUP();
    assert(!glIsEnabled(GL_NORMAL_ARRAY_EXT));
    assert(glIsEnabled(GL_COLOR_ARRAY_EXT));
    assert(!glIsEnabled(GL_TEXTURE_COORD_ARRAY_EXT));
    assert(!glIsEnabled(GL_INDEX_ARRAY_EXT));
    assert(!glIsEnabled(GL_EDGE_FLAG_ARRAY_EXT));
    assert(glIsEnabled(GL_VERTEX_ARRAY_EXT));
    {
	const char *cp = (const char *)gc->vertexArray.color_pointer
		+ first*gc->vertexArray.cp_stride;
	void (APIENTRY *c_func)(const char *) = gc->vertexArray.cp_call;
	const char *vp = (const char *)gc->vertexArray.vertex_pointer
		+ first*gc->vertexArray.vp_stride;
	void (APIENTRY *v_func)(const char *) = gc->vertexArray.vp_call;
	int i;
	glBegin(mode);
	for (i = 0; i < count; i++) {
	    (*c_func)(cp); cp += gc->vertexArray.cp_stride;
	    (*v_func)(vp); vp += gc->vertexArray.vp_stride;
	}
	glEnd();
    }
}

void __glDrawArraysNCV(GLenum mode, GLint first, GLsizei count)
{
    __GL_SETUP();
    assert(glIsEnabled(GL_NORMAL_ARRAY_EXT));
    assert(glIsEnabled(GL_COLOR_ARRAY_EXT));
    assert(!glIsEnabled(GL_TEXTURE_COORD_ARRAY_EXT));
    assert(!glIsEnabled(GL_INDEX_ARRAY_EXT));
    assert(!glIsEnabled(GL_EDGE_FLAG_ARRAY_EXT));
    assert(glIsEnabled(GL_VERTEX_ARRAY_EXT));
    {
	const char *np = (const char *)gc->vertexArray.normal_pointer
		+ first*gc->vertexArray.np_stride;
	void (APIENTRY *n_func)(const char *) = gc->vertexArray.np_call;
	const char *cp = (const char *)gc->vertexArray.color_pointer
		+ first*gc->vertexArray.cp_stride;
	void (APIENTRY *c_func)(const char *) = gc->vertexArray.cp_call;
	const char *vp = (const char *)gc->vertexArray.vertex_pointer
		+ first*gc->vertexArray.vp_stride;
	void (APIENTRY *v_func)(const char *) = gc->vertexArray.vp_call;
	int i;
	glBegin(mode);
	for (i = 0; i < count; i++) {
	    (*n_func)(np); np += gc->vertexArray.np_stride;
	    (*c_func)(cp); cp += gc->vertexArray.cp_stride;
	    (*v_func)(vp); vp += gc->vertexArray.vp_stride;
	}
	glEnd();
    }
}

void __glDrawArraysTV(GLenum mode, GLint first, GLsizei count)
{
    __GL_SETUP();
    assert(!glIsEnabled(GL_NORMAL_ARRAY_EXT));
    assert(!glIsEnabled(GL_COLOR_ARRAY_EXT));
    assert(glIsEnabled(GL_TEXTURE_COORD_ARRAY_EXT));
    assert(!glIsEnabled(GL_INDEX_ARRAY_EXT));
    assert(!glIsEnabled(GL_EDGE_FLAG_ARRAY_EXT));
    assert(glIsEnabled(GL_VERTEX_ARRAY_EXT));
    {
	const char *tp = (const char *)gc->vertexArray.tex_coord_pointer
		+ first*gc->vertexArray.tp_stride;
	void (APIENTRY *t_func)(const char *) = gc->vertexArray.tp_call;
	const char *vp = (const char *)gc->vertexArray.vertex_pointer
		+ first*gc->vertexArray.vp_stride;
	void (APIENTRY *v_func)(const char *) = gc->vertexArray.vp_call;
	int i;
	glBegin(mode);
	for (i = 0; i < count; i++) {
	    (*t_func)(tp); tp += gc->vertexArray.tp_stride;
	    (*v_func)(vp); vp += gc->vertexArray.vp_stride;
	}
	glEnd();
    }
}

void __glDrawArraysNTV(GLenum mode, GLint first, GLsizei count)
{
    __GL_SETUP();
    assert(glIsEnabled(GL_NORMAL_ARRAY_EXT));
    assert(!glIsEnabled(GL_COLOR_ARRAY_EXT));
    assert(glIsEnabled(GL_TEXTURE_COORD_ARRAY_EXT));
    assert(!glIsEnabled(GL_INDEX_ARRAY_EXT));
    assert(!glIsEnabled(GL_EDGE_FLAG_ARRAY_EXT));
    assert(glIsEnabled(GL_VERTEX_ARRAY_EXT));
    {
	const char *np = (const char *)gc->vertexArray.normal_pointer
		+ first*gc->vertexArray.np_stride;
	void (APIENTRY *n_func)(const char *) = gc->vertexArray.np_call;
	const char *tp = (const char *)gc->vertexArray.tex_coord_pointer
		+ first*gc->vertexArray.tp_stride;
	void (APIENTRY *t_func)(const char *) = gc->vertexArray.tp_call;
	const char *vp = (const char *)gc->vertexArray.vertex_pointer
		+ first*gc->vertexArray.vp_stride;
	void (APIENTRY *v_func)(const char *) = gc->vertexArray.vp_call;
	int i;
	glBegin(mode);
	for (i = 0; i < count; i++) {
	    (*n_func)(np); np += gc->vertexArray.np_stride;
	    (*t_func)(tp); tp += gc->vertexArray.tp_stride;
	    (*v_func)(vp); vp += gc->vertexArray.vp_stride;
	}
	glEnd();
    }
}

void __glDrawArraysCTV(GLenum mode, GLint first, GLsizei count)
{
    __GL_SETUP();
    assert(!glIsEnabled(GL_NORMAL_ARRAY_EXT));
    assert(glIsEnabled(GL_COLOR_ARRAY_EXT));
    assert(glIsEnabled(GL_TEXTURE_COORD_ARRAY_EXT));
    assert(!glIsEnabled(GL_INDEX_ARRAY_EXT));
    assert(!glIsEnabled(GL_EDGE_FLAG_ARRAY_EXT));
    assert(glIsEnabled(GL_VERTEX_ARRAY_EXT));
    {
	const char *cp = (const char *)gc->vertexArray.color_pointer
		+ first*gc->vertexArray.cp_stride;
	void (APIENTRY *c_func)(const char *) = gc->vertexArray.cp_call;
	const char *tp = (const char *)gc->vertexArray.tex_coord_pointer
		+ first*gc->vertexArray.tp_stride;
	void (APIENTRY *t_func)(const char *) = gc->vertexArray.tp_call;
	const char *vp = (const char *)gc->vertexArray.vertex_pointer
		+ first*gc->vertexArray.vp_stride;
	void (APIENTRY *v_func)(const char *) = gc->vertexArray.vp_call;
	int i;
	glBegin(mode);
	for (i = 0; i < count; i++) {
	    (*c_func)(cp); cp += gc->vertexArray.cp_stride;
	    (*t_func)(tp); tp += gc->vertexArray.tp_stride;
	    (*v_func)(vp); vp += gc->vertexArray.vp_stride;
	}
	glEnd();
    }
}

void __glDrawArraysNCTV(GLenum mode, GLint first, GLsizei count)
{
    __GL_SETUP();
    assert(glIsEnabled(GL_NORMAL_ARRAY_EXT));
    assert(glIsEnabled(GL_COLOR_ARRAY_EXT));
    assert(glIsEnabled(GL_TEXTURE_COORD_ARRAY_EXT));
    assert(!glIsEnabled(GL_INDEX_ARRAY_EXT));
    assert(!glIsEnabled(GL_EDGE_FLAG_ARRAY_EXT));
    assert(glIsEnabled(GL_VERTEX_ARRAY_EXT));
    {
	const char *np = (const char *)gc->vertexArray.normal_pointer
		+ first*gc->vertexArray.np_stride;
	void (APIENTRY *n_func)(const char *) = gc->vertexArray.np_call;
	const char *cp = (const char *)gc->vertexArray.color_pointer
		+ first*gc->vertexArray.cp_stride;
	void (APIENTRY *c_func)(const char *) = gc->vertexArray.cp_call;
	const char *tp = (const char *)gc->vertexArray.tex_coord_pointer
		+ first*gc->vertexArray.tp_stride;
	void (APIENTRY *t_func)(const char *) = gc->vertexArray.tp_call;
	const char *vp = (const char *)gc->vertexArray.vertex_pointer
		+ first*gc->vertexArray.vp_stride;
	void (APIENTRY *v_func)(const char *) = gc->vertexArray.vp_call;
	int i;
	glBegin(mode);
	for (i = 0; i < count; i++) {
	    (*n_func)(np); np += gc->vertexArray.np_stride;
	    (*c_func)(cp); cp += gc->vertexArray.cp_stride;
	    (*t_func)(tp); tp += gc->vertexArray.tp_stride;
	    (*v_func)(vp); vp += gc->vertexArray.vp_stride;
	}
	glEnd();
    }
}

void __glDrawArraysIV(GLenum mode, GLint first, GLsizei count)
{
    __GL_SETUP();
    assert(!glIsEnabled(GL_NORMAL_ARRAY_EXT));
    assert(!glIsEnabled(GL_COLOR_ARRAY_EXT));
    assert(!glIsEnabled(GL_TEXTURE_COORD_ARRAY_EXT));
    assert(glIsEnabled(GL_INDEX_ARRAY_EXT));
    assert(!glIsEnabled(GL_EDGE_FLAG_ARRAY_EXT));
    assert(glIsEnabled(GL_VERTEX_ARRAY_EXT));
    {
	const char *ip = (const char *)gc->vertexArray.index_pointer
		+ first*gc->vertexArray.ip_stride;
	void (APIENTRY *i_func)(const char *) = gc->vertexArray.ip_call;
	const char *vp = (const char *)gc->vertexArray.vertex_pointer
		+ first*gc->vertexArray.vp_stride;
	void (APIENTRY *v_func)(const char *) = gc->vertexArray.vp_call;
	int i;
	glBegin(mode);
	for (i = 0; i < count; i++) {
	    (*i_func)(ip); ip += gc->vertexArray.ip_stride;
	    (*v_func)(vp); vp += gc->vertexArray.vp_stride;
	}
	glEnd();
    }
}

void __glDrawArraysNIV(GLenum mode, GLint first, GLsizei count)
{
    __GL_SETUP();
    assert(glIsEnabled(GL_NORMAL_ARRAY_EXT));
    assert(!glIsEnabled(GL_COLOR_ARRAY_EXT));
    assert(!glIsEnabled(GL_TEXTURE_COORD_ARRAY_EXT));
    assert(glIsEnabled(GL_INDEX_ARRAY_EXT));
    assert(!glIsEnabled(GL_EDGE_FLAG_ARRAY_EXT));
    assert(glIsEnabled(GL_VERTEX_ARRAY_EXT));
    {
	const char *np = (const char *)gc->vertexArray.normal_pointer
		+ first*gc->vertexArray.np_stride;
	void (APIENTRY *n_func)(const char *) = gc->vertexArray.np_call;
	const char *ip = (const char *)gc->vertexArray.index_pointer
		+ first*gc->vertexArray.ip_stride;
	void (APIENTRY *i_func)(const char *) = gc->vertexArray.ip_call;
	const char *vp = (const char *)gc->vertexArray.vertex_pointer
		+ first*gc->vertexArray.vp_stride;
	void (APIENTRY *v_func)(const char *) = gc->vertexArray.vp_call;
	int i;
	glBegin(mode);
	for (i = 0; i < count; i++) {
	    (*n_func)(np); np += gc->vertexArray.np_stride;
	    (*i_func)(ip); ip += gc->vertexArray.ip_stride;
	    (*v_func)(vp); vp += gc->vertexArray.vp_stride;
	}
	glEnd();
    }
}

void __glDrawArraysCIV(GLenum mode, GLint first, GLsizei count)
{
    __GL_SETUP();
    assert(!glIsEnabled(GL_NORMAL_ARRAY_EXT));
    assert(glIsEnabled(GL_COLOR_ARRAY_EXT));
    assert(!glIsEnabled(GL_TEXTURE_COORD_ARRAY_EXT));
    assert(glIsEnabled(GL_INDEX_ARRAY_EXT));
    assert(!glIsEnabled(GL_EDGE_FLAG_ARRAY_EXT));
    assert(glIsEnabled(GL_VERTEX_ARRAY_EXT));
    {
	const char *cp = (const char *)gc->vertexArray.color_pointer
		+ first*gc->vertexArray.cp_stride;
	void (APIENTRY *c_func)(const char *) = gc->vertexArray.cp_call;
	const char *ip = (const char *)gc->vertexArray.index_pointer
		+ first*gc->vertexArray.ip_stride;
	void (APIENTRY *i_func)(const char *) = gc->vertexArray.ip_call;
	const char *vp = (const char *)gc->vertexArray.vertex_pointer
		+ first*gc->vertexArray.vp_stride;
	void (APIENTRY *v_func)(const char *) = gc->vertexArray.vp_call;
	int i;
	glBegin(mode);
	for (i = 0; i < count; i++) {
	    (*c_func)(cp); cp += gc->vertexArray.cp_stride;
	    (*i_func)(ip); ip += gc->vertexArray.ip_stride;
	    (*v_func)(vp); vp += gc->vertexArray.vp_stride;
	}
	glEnd();
    }
}

void __glDrawArraysNCIV(GLenum mode, GLint first, GLsizei count)
{
    __GL_SETUP();
    assert(glIsEnabled(GL_NORMAL_ARRAY_EXT));
    assert(glIsEnabled(GL_COLOR_ARRAY_EXT));
    assert(!glIsEnabled(GL_TEXTURE_COORD_ARRAY_EXT));
    assert(glIsEnabled(GL_INDEX_ARRAY_EXT));
    assert(!glIsEnabled(GL_EDGE_FLAG_ARRAY_EXT));
    assert(glIsEnabled(GL_VERTEX_ARRAY_EXT));
    {
	const char *np = (const char *)gc->vertexArray.normal_pointer
		+ first*gc->vertexArray.np_stride;
	void (APIENTRY *n_func)(const char *) = gc->vertexArray.np_call;
	const char *cp = (const char *)gc->vertexArray.color_pointer
		+ first*gc->vertexArray.cp_stride;
	void (APIENTRY *c_func)(const char *) = gc->vertexArray.cp_call;
	const char *ip = (const char *)gc->vertexArray.index_pointer
		+ first*gc->vertexArray.ip_stride;
	void (APIENTRY *i_func)(const char *) = gc->vertexArray.ip_call;
	const char *vp = (const char *)gc->vertexArray.vertex_pointer
		+ first*gc->vertexArray.vp_stride;
	void (APIENTRY *v_func)(const char *) = gc->vertexArray.vp_call;
	int i;
	glBegin(mode);
	for (i = 0; i < count; i++) {
	    (*n_func)(np); np += gc->vertexArray.np_stride;
	    (*c_func)(cp); cp += gc->vertexArray.cp_stride;
	    (*i_func)(ip); ip += gc->vertexArray.ip_stride;
	    (*v_func)(vp); vp += gc->vertexArray.vp_stride;
	}
	glEnd();
    }
}

void __glDrawArraysTIV(GLenum mode, GLint first, GLsizei count)
{
    __GL_SETUP();
    assert(!glIsEnabled(GL_NORMAL_ARRAY_EXT));
    assert(!glIsEnabled(GL_COLOR_ARRAY_EXT));
    assert(glIsEnabled(GL_TEXTURE_COORD_ARRAY_EXT));
    assert(glIsEnabled(GL_INDEX_ARRAY_EXT));
    assert(!glIsEnabled(GL_EDGE_FLAG_ARRAY_EXT));
    assert(glIsEnabled(GL_VERTEX_ARRAY_EXT));
    {
	const char *tp = (const char *)gc->vertexArray.tex_coord_pointer
		+ first*gc->vertexArray.tp_stride;
	void (APIENTRY *t_func)(const char *) = gc->vertexArray.tp_call;
	const char *ip = (const char *)gc->vertexArray.index_pointer
		+ first*gc->vertexArray.ip_stride;
	void (APIENTRY *i_func)(const char *) = gc->vertexArray.ip_call;
	const char *vp = (const char *)gc->vertexArray.vertex_pointer
		+ first*gc->vertexArray.vp_stride;
	void (APIENTRY *v_func)(const char *) = gc->vertexArray.vp_call;
	int i;
	glBegin(mode);
	for (i = 0; i < count; i++) {
	    (*t_func)(tp); tp += gc->vertexArray.tp_stride;
	    (*i_func)(ip); ip += gc->vertexArray.ip_stride;
	    (*v_func)(vp); vp += gc->vertexArray.vp_stride;
	}
	glEnd();
    }
}

void __glDrawArraysNTIV(GLenum mode, GLint first, GLsizei count)
{
    __GL_SETUP();
    assert(glIsEnabled(GL_NORMAL_ARRAY_EXT));
    assert(!glIsEnabled(GL_COLOR_ARRAY_EXT));
    assert(glIsEnabled(GL_TEXTURE_COORD_ARRAY_EXT));
    assert(glIsEnabled(GL_INDEX_ARRAY_EXT));
    assert(!glIsEnabled(GL_EDGE_FLAG_ARRAY_EXT));
    assert(glIsEnabled(GL_VERTEX_ARRAY_EXT));
    {
	const char *np = (const char *)gc->vertexArray.normal_pointer
		+ first*gc->vertexArray.np_stride;
	void (APIENTRY *n_func)(const char *) = gc->vertexArray.np_call;
	const char *tp = (const char *)gc->vertexArray.tex_coord_pointer
		+ first*gc->vertexArray.tp_stride;
	void (APIENTRY *t_func)(const char *) = gc->vertexArray.tp_call;
	const char *ip = (const char *)gc->vertexArray.index_pointer
		+ first*gc->vertexArray.ip_stride;
	void (APIENTRY *i_func)(const char *) = gc->vertexArray.ip_call;
	const char *vp = (const char *)gc->vertexArray.vertex_pointer
		+ first*gc->vertexArray.vp_stride;
	void (APIENTRY *v_func)(const char *) = gc->vertexArray.vp_call;
	int i;
	glBegin(mode);
	for (i = 0; i < count; i++) {
	    (*n_func)(np); np += gc->vertexArray.np_stride;
	    (*t_func)(tp); tp += gc->vertexArray.tp_stride;
	    (*i_func)(ip); ip += gc->vertexArray.ip_stride;
	    (*v_func)(vp); vp += gc->vertexArray.vp_stride;
	}
	glEnd();
    }
}

void __glDrawArraysCTIV(GLenum mode, GLint first, GLsizei count)
{
    __GL_SETUP();
    assert(!glIsEnabled(GL_NORMAL_ARRAY_EXT));
    assert(glIsEnabled(GL_COLOR_ARRAY_EXT));
    assert(glIsEnabled(GL_TEXTURE_COORD_ARRAY_EXT));
    assert(glIsEnabled(GL_INDEX_ARRAY_EXT));
    assert(!glIsEnabled(GL_EDGE_FLAG_ARRAY_EXT));
    assert(glIsEnabled(GL_VERTEX_ARRAY_EXT));
    {
	const char *cp = (const char *)gc->vertexArray.color_pointer
		+ first*gc->vertexArray.cp_stride;
	void (APIENTRY *c_func)(const char *) = gc->vertexArray.cp_call;
	const char *tp = (const char *)gc->vertexArray.tex_coord_pointer
		+ first*gc->vertexArray.tp_stride;
	void (APIENTRY *t_func)(const char *) = gc->vertexArray.tp_call;
	const char *ip = (const char *)gc->vertexArray.index_pointer
		+ first*gc->vertexArray.ip_stride;
	void (APIENTRY *i_func)(const char *) = gc->vertexArray.ip_call;
	const char *vp = (const char *)gc->vertexArray.vertex_pointer
		+ first*gc->vertexArray.vp_stride;
	void (APIENTRY *v_func)(const char *) = gc->vertexArray.vp_call;
	int i;
	glBegin(mode);
	for (i = 0; i < count; i++) {
	    (*c_func)(cp); cp += gc->vertexArray.cp_stride;
	    (*t_func)(tp); tp += gc->vertexArray.tp_stride;
	    (*i_func)(ip); ip += gc->vertexArray.ip_stride;
	    (*v_func)(vp); vp += gc->vertexArray.vp_stride;
	}
	glEnd();
    }
}

void __glDrawArraysNCTIV(GLenum mode, GLint first, GLsizei count)
{
    __GL_SETUP();
    assert(glIsEnabled(GL_NORMAL_ARRAY_EXT));
    assert(glIsEnabled(GL_COLOR_ARRAY_EXT));
    assert(glIsEnabled(GL_TEXTURE_COORD_ARRAY_EXT));
    assert(glIsEnabled(GL_INDEX_ARRAY_EXT));
    assert(!glIsEnabled(GL_EDGE_FLAG_ARRAY_EXT));
    assert(glIsEnabled(GL_VERTEX_ARRAY_EXT));
    {
	const char *np = (const char *)gc->vertexArray.normal_pointer
		+ first*gc->vertexArray.np_stride;
	void (APIENTRY *n_func)(const char *) = gc->vertexArray.np_call;
	const char *cp = (const char *)gc->vertexArray.color_pointer
		+ first*gc->vertexArray.cp_stride;
	void (APIENTRY *c_func)(const char *) = gc->vertexArray.cp_call;
	const char *tp = (const char *)gc->vertexArray.tex_coord_pointer
		+ first*gc->vertexArray.tp_stride;
	void (APIENTRY *t_func)(const char *) = gc->vertexArray.tp_call;
	const char *ip = (const char *)gc->vertexArray.index_pointer
		+ first*gc->vertexArray.ip_stride;
	void (APIENTRY *i_func)(const char *) = gc->vertexArray.ip_call;
	const char *vp = (const char *)gc->vertexArray.vertex_pointer
		+ first*gc->vertexArray.vp_stride;
	void (APIENTRY *v_func)(const char *) = gc->vertexArray.vp_call;
	int i;
	glBegin(mode);
	for (i = 0; i < count; i++) {
	    (*n_func)(np); np += gc->vertexArray.np_stride;
	    (*c_func)(cp); cp += gc->vertexArray.cp_stride;
	    (*t_func)(tp); tp += gc->vertexArray.tp_stride;
	    (*i_func)(ip); ip += gc->vertexArray.ip_stride;
	    (*v_func)(vp); vp += gc->vertexArray.vp_stride;
	}
	glEnd();
    }
}

void __glDrawArraysEV(GLenum mode, GLint first, GLsizei count)
{
    __GL_SETUP();
    assert(!glIsEnabled(GL_NORMAL_ARRAY_EXT));
    assert(!glIsEnabled(GL_COLOR_ARRAY_EXT));
    assert(!glIsEnabled(GL_TEXTURE_COORD_ARRAY_EXT));
    assert(!glIsEnabled(GL_INDEX_ARRAY_EXT));
    assert(glIsEnabled(GL_EDGE_FLAG_ARRAY_EXT));
    assert(glIsEnabled(GL_VERTEX_ARRAY_EXT));
    {
	const char *ep = (const char *)gc->vertexArray.edge_pointer
		+ first*gc->vertexArray.ep_stride;
	void (APIENTRY *e_func)(const char *) = gc->vertexArray.ep_call;
	const char *vp = (const char *)gc->vertexArray.vertex_pointer
		+ first*gc->vertexArray.vp_stride;
	void (APIENTRY *v_func)(const char *) = gc->vertexArray.vp_call;
	int i;
	glBegin(mode);
	for (i = 0; i < count; i++) {
	    (*e_func)(ep); ep += gc->vertexArray.ep_stride;
	    (*v_func)(vp); vp += gc->vertexArray.vp_stride;
	}
	glEnd();
    }
}

void __glDrawArraysNEV(GLenum mode, GLint first, GLsizei count)
{
    __GL_SETUP();
    assert(glIsEnabled(GL_NORMAL_ARRAY_EXT));
    assert(!glIsEnabled(GL_COLOR_ARRAY_EXT));
    assert(!glIsEnabled(GL_TEXTURE_COORD_ARRAY_EXT));
    assert(!glIsEnabled(GL_INDEX_ARRAY_EXT));
    assert(glIsEnabled(GL_EDGE_FLAG_ARRAY_EXT));
    assert(glIsEnabled(GL_VERTEX_ARRAY_EXT));
    {
	const char *np = (const char *)gc->vertexArray.normal_pointer
		+ first*gc->vertexArray.np_stride;
	void (APIENTRY *n_func)(const char *) = gc->vertexArray.np_call;
	const char *ep = (const char *)gc->vertexArray.edge_pointer
		+ first*gc->vertexArray.ep_stride;
	void (APIENTRY *e_func)(const char *) = gc->vertexArray.ep_call;
	const char *vp = (const char *)gc->vertexArray.vertex_pointer
		+ first*gc->vertexArray.vp_stride;
	void (APIENTRY *v_func)(const char *) = gc->vertexArray.vp_call;
	int i;
	glBegin(mode);
	for (i = 0; i < count; i++) {
	    (*n_func)(np); np += gc->vertexArray.np_stride;
	    (*e_func)(ep); ep += gc->vertexArray.ep_stride;
	    (*v_func)(vp); vp += gc->vertexArray.vp_stride;
	}
	glEnd();
    }
}

void __glDrawArraysCEV(GLenum mode, GLint first, GLsizei count)
{
    __GL_SETUP();
    assert(!glIsEnabled(GL_NORMAL_ARRAY_EXT));
    assert(glIsEnabled(GL_COLOR_ARRAY_EXT));
    assert(!glIsEnabled(GL_TEXTURE_COORD_ARRAY_EXT));
    assert(!glIsEnabled(GL_INDEX_ARRAY_EXT));
    assert(glIsEnabled(GL_EDGE_FLAG_ARRAY_EXT));
    assert(glIsEnabled(GL_VERTEX_ARRAY_EXT));
    {
	const char *cp = (const char *)gc->vertexArray.color_pointer
		+ first*gc->vertexArray.cp_stride;
	void (APIENTRY *c_func)(const char *) = gc->vertexArray.cp_call;
	const char *ep = (const char *)gc->vertexArray.edge_pointer
		+ first*gc->vertexArray.ep_stride;
	void (APIENTRY *e_func)(const char *) = gc->vertexArray.ep_call;
	const char *vp = (const char *)gc->vertexArray.vertex_pointer
		+ first*gc->vertexArray.vp_stride;
	void (APIENTRY *v_func)(const char *) = gc->vertexArray.vp_call;
	int i;
	glBegin(mode);
	for (i = 0; i < count; i++) {
	    (*c_func)(cp); cp += gc->vertexArray.cp_stride;
	    (*e_func)(ep); ep += gc->vertexArray.ep_stride;
	    (*v_func)(vp); vp += gc->vertexArray.vp_stride;
	}
	glEnd();
    }
}

void __glDrawArraysNCEV(GLenum mode, GLint first, GLsizei count)
{
    __GL_SETUP();
    assert(glIsEnabled(GL_NORMAL_ARRAY_EXT));
    assert(glIsEnabled(GL_COLOR_ARRAY_EXT));
    assert(!glIsEnabled(GL_TEXTURE_COORD_ARRAY_EXT));
    assert(!glIsEnabled(GL_INDEX_ARRAY_EXT));
    assert(glIsEnabled(GL_EDGE_FLAG_ARRAY_EXT));
    assert(glIsEnabled(GL_VERTEX_ARRAY_EXT));
    {
	const char *np = (const char *)gc->vertexArray.normal_pointer
		+ first*gc->vertexArray.np_stride;
	void (APIENTRY *n_func)(const char *) = gc->vertexArray.np_call;
	const char *cp = (const char *)gc->vertexArray.color_pointer
		+ first*gc->vertexArray.cp_stride;
	void (APIENTRY *c_func)(const char *) = gc->vertexArray.cp_call;
	const char *ep = (const char *)gc->vertexArray.edge_pointer
		+ first*gc->vertexArray.ep_stride;
	void (APIENTRY *e_func)(const char *) = gc->vertexArray.ep_call;
	const char *vp = (const char *)gc->vertexArray.vertex_pointer
		+ first*gc->vertexArray.vp_stride;
	void (APIENTRY *v_func)(const char *) = gc->vertexArray.vp_call;
	int i;
	glBegin(mode);
	for (i = 0; i < count; i++) {
	    (*n_func)(np); np += gc->vertexArray.np_stride;
	    (*c_func)(cp); cp += gc->vertexArray.cp_stride;
	    (*e_func)(ep); ep += gc->vertexArray.ep_stride;
	    (*v_func)(vp); vp += gc->vertexArray.vp_stride;
	}
	glEnd();
    }
}

void __glDrawArraysTEV(GLenum mode, GLint first, GLsizei count)
{
    __GL_SETUP();
    assert(!glIsEnabled(GL_NORMAL_ARRAY_EXT));
    assert(!glIsEnabled(GL_COLOR_ARRAY_EXT));
    assert(glIsEnabled(GL_TEXTURE_COORD_ARRAY_EXT));
    assert(!glIsEnabled(GL_INDEX_ARRAY_EXT));
    assert(glIsEnabled(GL_EDGE_FLAG_ARRAY_EXT));
    assert(glIsEnabled(GL_VERTEX_ARRAY_EXT));
    {
	const char *tp = (const char *)gc->vertexArray.tex_coord_pointer
		+ first*gc->vertexArray.tp_stride;
	void (APIENTRY *t_func)(const char *) = gc->vertexArray.tp_call;
	const char *ep = (const char *)gc->vertexArray.edge_pointer
		+ first*gc->vertexArray.ep_stride;
	void (APIENTRY *e_func)(const char *) = gc->vertexArray.ep_call;
	const char *vp = (const char *)gc->vertexArray.vertex_pointer
		+ first*gc->vertexArray.vp_stride;
	void (APIENTRY *v_func)(const char *) = gc->vertexArray.vp_call;
	int i;
	glBegin(mode);
	for (i = 0; i < count; i++) {
	    (*t_func)(tp); tp += gc->vertexArray.tp_stride;
	    (*e_func)(ep); ep += gc->vertexArray.ep_stride;
	    (*v_func)(vp); vp += gc->vertexArray.vp_stride;
	}
	glEnd();
    }
}

void __glDrawArraysNTEV(GLenum mode, GLint first, GLsizei count)
{
    __GL_SETUP();
    assert(glIsEnabled(GL_NORMAL_ARRAY_EXT));
    assert(!glIsEnabled(GL_COLOR_ARRAY_EXT));
    assert(glIsEnabled(GL_TEXTURE_COORD_ARRAY_EXT));
    assert(!glIsEnabled(GL_INDEX_ARRAY_EXT));
    assert(glIsEnabled(GL_EDGE_FLAG_ARRAY_EXT));
    assert(glIsEnabled(GL_VERTEX_ARRAY_EXT));
    {
	const char *np = (const char *)gc->vertexArray.normal_pointer
		+ first*gc->vertexArray.np_stride;
	void (APIENTRY *n_func)(const char *) = gc->vertexArray.np_call;
	const char *tp = (const char *)gc->vertexArray.tex_coord_pointer
		+ first*gc->vertexArray.tp_stride;
	void (APIENTRY *t_func)(const char *) = gc->vertexArray.tp_call;
	const char *ep = (const char *)gc->vertexArray.edge_pointer
		+ first*gc->vertexArray.ep_stride;
	void (APIENTRY *e_func)(const char *) = gc->vertexArray.ep_call;
	const char *vp = (const char *)gc->vertexArray.vertex_pointer
		+ first*gc->vertexArray.vp_stride;
	void (APIENTRY *v_func)(const char *) = gc->vertexArray.vp_call;
	int i;
	glBegin(mode);
	for (i = 0; i < count; i++) {
	    (*n_func)(np); np += gc->vertexArray.np_stride;
	    (*t_func)(tp); tp += gc->vertexArray.tp_stride;
	    (*e_func)(ep); ep += gc->vertexArray.ep_stride;
	    (*v_func)(vp); vp += gc->vertexArray.vp_stride;
	}
	glEnd();
    }
}

void __glDrawArraysCTEV(GLenum mode, GLint first, GLsizei count)
{
    __GL_SETUP();
    assert(!glIsEnabled(GL_NORMAL_ARRAY_EXT));
    assert(glIsEnabled(GL_COLOR_ARRAY_EXT));
    assert(glIsEnabled(GL_TEXTURE_COORD_ARRAY_EXT));
    assert(!glIsEnabled(GL_INDEX_ARRAY_EXT));
    assert(glIsEnabled(GL_EDGE_FLAG_ARRAY_EXT));
    assert(glIsEnabled(GL_VERTEX_ARRAY_EXT));
    {
	const char *cp = (const char *)gc->vertexArray.color_pointer
		+ first*gc->vertexArray.cp_stride;
	void (APIENTRY *c_func)(const char *) = gc->vertexArray.cp_call;
	const char *tp = (const char *)gc->vertexArray.tex_coord_pointer
		+ first*gc->vertexArray.tp_stride;
	void (APIENTRY *t_func)(const char *) = gc->vertexArray.tp_call;
	const char *ep = (const char *)gc->vertexArray.edge_pointer
		+ first*gc->vertexArray.ep_stride;
	void (APIENTRY *e_func)(const char *) = gc->vertexArray.ep_call;
	const char *vp = (const char *)gc->vertexArray.vertex_pointer
		+ first*gc->vertexArray.vp_stride;
	void (APIENTRY *v_func)(const char *) = gc->vertexArray.vp_call;
	int i;
	glBegin(mode);
	for (i = 0; i < count; i++) {
	    (*c_func)(cp); cp += gc->vertexArray.cp_stride;
	    (*t_func)(tp); tp += gc->vertexArray.tp_stride;
	    (*e_func)(ep); ep += gc->vertexArray.ep_stride;
	    (*v_func)(vp); vp += gc->vertexArray.vp_stride;
	}
	glEnd();
    }
}

void __glDrawArraysNCTEV(GLenum mode, GLint first, GLsizei count)
{
    __GL_SETUP();
    assert(glIsEnabled(GL_NORMAL_ARRAY_EXT));
    assert(glIsEnabled(GL_COLOR_ARRAY_EXT));
    assert(glIsEnabled(GL_TEXTURE_COORD_ARRAY_EXT));
    assert(!glIsEnabled(GL_INDEX_ARRAY_EXT));
    assert(glIsEnabled(GL_EDGE_FLAG_ARRAY_EXT));
    assert(glIsEnabled(GL_VERTEX_ARRAY_EXT));
    {
	const char *np = (const char *)gc->vertexArray.normal_pointer
		+ first*gc->vertexArray.np_stride;
	void (APIENTRY *n_func)(const char *) = gc->vertexArray.np_call;
	const char *cp = (const char *)gc->vertexArray.color_pointer
		+ first*gc->vertexArray.cp_stride;
	void (APIENTRY *c_func)(const char *) = gc->vertexArray.cp_call;
	const char *tp = (const char *)gc->vertexArray.tex_coord_pointer
		+ first*gc->vertexArray.tp_stride;
	void (APIENTRY *t_func)(const char *) = gc->vertexArray.tp_call;
	const char *ep = (const char *)gc->vertexArray.edge_pointer
		+ first*gc->vertexArray.ep_stride;
	void (APIENTRY *e_func)(const char *) = gc->vertexArray.ep_call;
	const char *vp = (const char *)gc->vertexArray.vertex_pointer
		+ first*gc->vertexArray.vp_stride;
	void (APIENTRY *v_func)(const char *) = gc->vertexArray.vp_call;
	int i;
	glBegin(mode);
	for (i = 0; i < count; i++) {
	    (*n_func)(np); np += gc->vertexArray.np_stride;
	    (*c_func)(cp); cp += gc->vertexArray.cp_stride;
	    (*t_func)(tp); tp += gc->vertexArray.tp_stride;
	    (*e_func)(ep); ep += gc->vertexArray.ep_stride;
	    (*v_func)(vp); vp += gc->vertexArray.vp_stride;
	}
	glEnd();
    }
}

void __glDrawArraysIEV(GLenum mode, GLint first, GLsizei count)
{
    __GL_SETUP();
    assert(!glIsEnabled(GL_NORMAL_ARRAY_EXT));
    assert(!glIsEnabled(GL_COLOR_ARRAY_EXT));
    assert(!glIsEnabled(GL_TEXTURE_COORD_ARRAY_EXT));
    assert(glIsEnabled(GL_INDEX_ARRAY_EXT));
    assert(glIsEnabled(GL_EDGE_FLAG_ARRAY_EXT));
    assert(glIsEnabled(GL_VERTEX_ARRAY_EXT));
    {
	const char *ip = (const char *)gc->vertexArray.index_pointer
		+ first*gc->vertexArray.ip_stride;
	void (APIENTRY *i_func)(const char *) = gc->vertexArray.ip_call;
	const char *ep = (const char *)gc->vertexArray.edge_pointer
		+ first*gc->vertexArray.ep_stride;
	void (APIENTRY *e_func)(const char *) = gc->vertexArray.ep_call;
	const char *vp = (const char *)gc->vertexArray.vertex_pointer
		+ first*gc->vertexArray.vp_stride;
	void (APIENTRY *v_func)(const char *) = gc->vertexArray.vp_call;
	int i;
	glBegin(mode);
	for (i = 0; i < count; i++) {
	    (*i_func)(ip); ip += gc->vertexArray.ip_stride;
	    (*e_func)(ep); ep += gc->vertexArray.ep_stride;
	    (*v_func)(vp); vp += gc->vertexArray.vp_stride;
	}
	glEnd();
    }
}

void __glDrawArraysNIEV(GLenum mode, GLint first, GLsizei count)
{
    __GL_SETUP();
    assert(glIsEnabled(GL_NORMAL_ARRAY_EXT));
    assert(!glIsEnabled(GL_COLOR_ARRAY_EXT));
    assert(!glIsEnabled(GL_TEXTURE_COORD_ARRAY_EXT));
    assert(glIsEnabled(GL_INDEX_ARRAY_EXT));
    assert(glIsEnabled(GL_EDGE_FLAG_ARRAY_EXT));
    assert(glIsEnabled(GL_VERTEX_ARRAY_EXT));
    {
	const char *np = (const char *)gc->vertexArray.normal_pointer
		+ first*gc->vertexArray.np_stride;
	void (APIENTRY *n_func)(const char *) = gc->vertexArray.np_call;
	const char *ip = (const char *)gc->vertexArray.index_pointer
		+ first*gc->vertexArray.ip_stride;
	void (APIENTRY *i_func)(const char *) = gc->vertexArray.ip_call;
	const char *ep = (const char *)gc->vertexArray.edge_pointer
		+ first*gc->vertexArray.ep_stride;
	void (APIENTRY *e_func)(const char *) = gc->vertexArray.ep_call;
	const char *vp = (const char *)gc->vertexArray.vertex_pointer
		+ first*gc->vertexArray.vp_stride;
	void (APIENTRY *v_func)(const char *) = gc->vertexArray.vp_call;
	int i;
	glBegin(mode);
	for (i = 0; i < count; i++) {
	    (*n_func)(np); np += gc->vertexArray.np_stride;
	    (*i_func)(ip); ip += gc->vertexArray.ip_stride;
	    (*e_func)(ep); ep += gc->vertexArray.ep_stride;
	    (*v_func)(vp); vp += gc->vertexArray.vp_stride;
	}
	glEnd();
    }
}

void __glDrawArraysCIEV(GLenum mode, GLint first, GLsizei count)
{
    __GL_SETUP();
    assert(!glIsEnabled(GL_NORMAL_ARRAY_EXT));
    assert(glIsEnabled(GL_COLOR_ARRAY_EXT));
    assert(!glIsEnabled(GL_TEXTURE_COORD_ARRAY_EXT));
    assert(glIsEnabled(GL_INDEX_ARRAY_EXT));
    assert(glIsEnabled(GL_EDGE_FLAG_ARRAY_EXT));
    assert(glIsEnabled(GL_VERTEX_ARRAY_EXT));
    {
	const char *cp = (const char *)gc->vertexArray.color_pointer
		+ first*gc->vertexArray.cp_stride;
	void (APIENTRY *c_func)(const char *) = gc->vertexArray.cp_call;
	const char *ip = (const char *)gc->vertexArray.index_pointer
		+ first*gc->vertexArray.ip_stride;
	void (APIENTRY *i_func)(const char *) = gc->vertexArray.ip_call;
	const char *ep = (const char *)gc->vertexArray.edge_pointer
		+ first*gc->vertexArray.ep_stride;
	void (APIENTRY *e_func)(const char *) = gc->vertexArray.ep_call;
	const char *vp = (const char *)gc->vertexArray.vertex_pointer
		+ first*gc->vertexArray.vp_stride;
	void (APIENTRY *v_func)(const char *) = gc->vertexArray.vp_call;
	int i;
	glBegin(mode);
	for (i = 0; i < count; i++) {
	    (*c_func)(cp); cp += gc->vertexArray.cp_stride;
	    (*i_func)(ip); ip += gc->vertexArray.ip_stride;
	    (*e_func)(ep); ep += gc->vertexArray.ep_stride;
	    (*v_func)(vp); vp += gc->vertexArray.vp_stride;
	}
	glEnd();
    }
}

void __glDrawArraysNCIEV(GLenum mode, GLint first, GLsizei count)
{
    __GL_SETUP();
    assert(glIsEnabled(GL_NORMAL_ARRAY_EXT));
    assert(glIsEnabled(GL_COLOR_ARRAY_EXT));
    assert(!glIsEnabled(GL_TEXTURE_COORD_ARRAY_EXT));
    assert(glIsEnabled(GL_INDEX_ARRAY_EXT));
    assert(glIsEnabled(GL_EDGE_FLAG_ARRAY_EXT));
    assert(glIsEnabled(GL_VERTEX_ARRAY_EXT));
    {
	const char *np = (const char *)gc->vertexArray.normal_pointer
		+ first*gc->vertexArray.np_stride;
	void (APIENTRY *n_func)(const char *) = gc->vertexArray.np_call;
	const char *cp = (const char *)gc->vertexArray.color_pointer
		+ first*gc->vertexArray.cp_stride;
	void (APIENTRY *c_func)(const char *) = gc->vertexArray.cp_call;
	const char *ip = (const char *)gc->vertexArray.index_pointer
		+ first*gc->vertexArray.ip_stride;
	void (APIENTRY *i_func)(const char *) = gc->vertexArray.ip_call;
	const char *ep = (const char *)gc->vertexArray.edge_pointer
		+ first*gc->vertexArray.ep_stride;
	void (APIENTRY *e_func)(const char *) = gc->vertexArray.ep_call;
	const char *vp = (const char *)gc->vertexArray.vertex_pointer
		+ first*gc->vertexArray.vp_stride;
	void (APIENTRY *v_func)(const char *) = gc->vertexArray.vp_call;
	int i;
	glBegin(mode);
	for (i = 0; i < count; i++) {
	    (*n_func)(np); np += gc->vertexArray.np_stride;
	    (*c_func)(cp); cp += gc->vertexArray.cp_stride;
	    (*i_func)(ip); ip += gc->vertexArray.ip_stride;
	    (*e_func)(ep); ep += gc->vertexArray.ep_stride;
	    (*v_func)(vp); vp += gc->vertexArray.vp_stride;
	}
	glEnd();
    }
}

void __glDrawArraysTIEV(GLenum mode, GLint first, GLsizei count)
{
    __GL_SETUP();
    assert(!glIsEnabled(GL_NORMAL_ARRAY_EXT));
    assert(!glIsEnabled(GL_COLOR_ARRAY_EXT));
    assert(glIsEnabled(GL_TEXTURE_COORD_ARRAY_EXT));
    assert(glIsEnabled(GL_INDEX_ARRAY_EXT));
    assert(glIsEnabled(GL_EDGE_FLAG_ARRAY_EXT));
    assert(glIsEnabled(GL_VERTEX_ARRAY_EXT));
    {
	const char *tp = (const char *)gc->vertexArray.tex_coord_pointer
		+ first*gc->vertexArray.tp_stride;
	void (APIENTRY *t_func)(const char *) = gc->vertexArray.tp_call;
	const char *ip = (const char *)gc->vertexArray.index_pointer
		+ first*gc->vertexArray.ip_stride;
	void (APIENTRY *i_func)(const char *) = gc->vertexArray.ip_call;
	const char *ep = (const char *)gc->vertexArray.edge_pointer
		+ first*gc->vertexArray.ep_stride;
	void (APIENTRY *e_func)(const char *) = gc->vertexArray.ep_call;
	const char *vp = (const char *)gc->vertexArray.vertex_pointer
		+ first*gc->vertexArray.vp_stride;
	void (APIENTRY *v_func)(const char *) = gc->vertexArray.vp_call;
	int i;
	glBegin(mode);
	for (i = 0; i < count; i++) {
	    (*t_func)(tp); tp += gc->vertexArray.tp_stride;
	    (*i_func)(ip); ip += gc->vertexArray.ip_stride;
	    (*e_func)(ep); ep += gc->vertexArray.ep_stride;
	    (*v_func)(vp); vp += gc->vertexArray.vp_stride;
	}
	glEnd();
    }
}

void __glDrawArraysNTIEV(GLenum mode, GLint first, GLsizei count)
{
    __GL_SETUP();
    assert(glIsEnabled(GL_NORMAL_ARRAY_EXT));
    assert(!glIsEnabled(GL_COLOR_ARRAY_EXT));
    assert(glIsEnabled(GL_TEXTURE_COORD_ARRAY_EXT));
    assert(glIsEnabled(GL_INDEX_ARRAY_EXT));
    assert(glIsEnabled(GL_EDGE_FLAG_ARRAY_EXT));
    assert(glIsEnabled(GL_VERTEX_ARRAY_EXT));
    {
	const char *np = (const char *)gc->vertexArray.normal_pointer
		+ first*gc->vertexArray.np_stride;
	void (APIENTRY *n_func)(const char *) = gc->vertexArray.np_call;
	const char *tp = (const char *)gc->vertexArray.tex_coord_pointer
		+ first*gc->vertexArray.tp_stride;
	void (APIENTRY *t_func)(const char *) = gc->vertexArray.tp_call;
	const char *ip = (const char *)gc->vertexArray.index_pointer
		+ first*gc->vertexArray.ip_stride;
	void (APIENTRY *i_func)(const char *) = gc->vertexArray.ip_call;
	const char *ep = (const char *)gc->vertexArray.edge_pointer
		+ first*gc->vertexArray.ep_stride;
	void (APIENTRY *e_func)(const char *) = gc->vertexArray.ep_call;
	const char *vp = (const char *)gc->vertexArray.vertex_pointer
		+ first*gc->vertexArray.vp_stride;
	void (APIENTRY *v_func)(const char *) = gc->vertexArray.vp_call;
	int i;
	glBegin(mode);
	for (i = 0; i < count; i++) {
	    (*n_func)(np); np += gc->vertexArray.np_stride;
	    (*t_func)(tp); tp += gc->vertexArray.tp_stride;
	    (*i_func)(ip); ip += gc->vertexArray.ip_stride;
	    (*e_func)(ep); ep += gc->vertexArray.ep_stride;
	    (*v_func)(vp); vp += gc->vertexArray.vp_stride;
	}
	glEnd();
    }
}

void __glDrawArraysCTIEV(GLenum mode, GLint first, GLsizei count)
{
    __GL_SETUP();
    assert(!glIsEnabled(GL_NORMAL_ARRAY_EXT));
    assert(glIsEnabled(GL_COLOR_ARRAY_EXT));
    assert(glIsEnabled(GL_TEXTURE_COORD_ARRAY_EXT));
    assert(glIsEnabled(GL_INDEX_ARRAY_EXT));
    assert(glIsEnabled(GL_EDGE_FLAG_ARRAY_EXT));
    assert(glIsEnabled(GL_VERTEX_ARRAY_EXT));
    {
	const char *cp = (const char *)gc->vertexArray.color_pointer
		+ first*gc->vertexArray.cp_stride;
	void (APIENTRY *c_func)(const char *) = gc->vertexArray.cp_call;
	const char *tp = (const char *)gc->vertexArray.tex_coord_pointer
		+ first*gc->vertexArray.tp_stride;
	void (APIENTRY *t_func)(const char *) = gc->vertexArray.tp_call;
	const char *ip = (const char *)gc->vertexArray.index_pointer
		+ first*gc->vertexArray.ip_stride;
	void (APIENTRY *i_func)(const char *) = gc->vertexArray.ip_call;
	const char *ep = (const char *)gc->vertexArray.edge_pointer
		+ first*gc->vertexArray.ep_stride;
	void (APIENTRY *e_func)(const char *) = gc->vertexArray.ep_call;
	const char *vp = (const char *)gc->vertexArray.vertex_pointer
		+ first*gc->vertexArray.vp_stride;
	void (APIENTRY *v_func)(const char *) = gc->vertexArray.vp_call;
	int i;
	glBegin(mode);
	for (i = 0; i < count; i++) {
	    (*c_func)(cp); cp += gc->vertexArray.cp_stride;
	    (*t_func)(tp); tp += gc->vertexArray.tp_stride;
	    (*i_func)(ip); ip += gc->vertexArray.ip_stride;
	    (*e_func)(ep); ep += gc->vertexArray.ep_stride;
	    (*v_func)(vp); vp += gc->vertexArray.vp_stride;
	}
	glEnd();
    }
}

void __glDrawArraysNCTIEV(GLenum mode, GLint first, GLsizei count)
{
    __GL_SETUP();
    assert(glIsEnabled(GL_NORMAL_ARRAY_EXT));
    assert(glIsEnabled(GL_COLOR_ARRAY_EXT));
    assert(glIsEnabled(GL_TEXTURE_COORD_ARRAY_EXT));
    assert(glIsEnabled(GL_INDEX_ARRAY_EXT));
    assert(glIsEnabled(GL_EDGE_FLAG_ARRAY_EXT));
    assert(glIsEnabled(GL_VERTEX_ARRAY_EXT));
    {
	const char *np = (const char *)gc->vertexArray.normal_pointer
		+ first*gc->vertexArray.np_stride;
	void (APIENTRY *n_func)(const char *) = gc->vertexArray.np_call;
	const char *cp = (const char *)gc->vertexArray.color_pointer
		+ first*gc->vertexArray.cp_stride;
	void (APIENTRY *c_func)(const char *) = gc->vertexArray.cp_call;
	const char *tp = (const char *)gc->vertexArray.tex_coord_pointer
		+ first*gc->vertexArray.tp_stride;
	void (APIENTRY *t_func)(const char *) = gc->vertexArray.tp_call;
	const char *ip = (const char *)gc->vertexArray.index_pointer
		+ first*gc->vertexArray.ip_stride;
	void (APIENTRY *i_func)(const char *) = gc->vertexArray.ip_call;
	const char *ep = (const char *)gc->vertexArray.edge_pointer
		+ first*gc->vertexArray.ep_stride;
	void (APIENTRY *e_func)(const char *) = gc->vertexArray.ep_call;
	const char *vp = (const char *)gc->vertexArray.vertex_pointer
		+ first*gc->vertexArray.vp_stride;
	void (APIENTRY *v_func)(const char *) = gc->vertexArray.vp_call;
	int i;
	glBegin(mode);
	for (i = 0; i < count; i++) {
	    (*n_func)(np); np += gc->vertexArray.np_stride;
	    (*c_func)(cp); cp += gc->vertexArray.cp_stride;
	    (*t_func)(tp); tp += gc->vertexArray.tp_stride;
	    (*i_func)(ip); ip += gc->vertexArray.ip_stride;
	    (*e_func)(ep); ep += gc->vertexArray.ep_stride;
	    (*v_func)(vp); vp += gc->vertexArray.vp_stride;
	}
	glEnd();
    }
}

void __glDrawArraysN(GLenum mode, GLint first, GLsizei count)
{
    __GL_SETUP();
    assert(glIsEnabled(GL_NORMAL_ARRAY_EXT));
    assert(!glIsEnabled(GL_COLOR_ARRAY_EXT));
    assert(!glIsEnabled(GL_TEXTURE_COORD_ARRAY_EXT));
    assert(!glIsEnabled(GL_INDEX_ARRAY_EXT));
    assert(!glIsEnabled(GL_EDGE_FLAG_ARRAY_EXT));
    assert(!glIsEnabled(GL_VERTEX_ARRAY_EXT));
    {
	const char *np = (const char *)gc->vertexArray.normal_pointer
		+ first*gc->vertexArray.np_stride;
	void (APIENTRY *n_func)(const char *) = gc->vertexArray.np_call;
	int i;
	glBegin(mode);
	for (i = 0; i < count; i++) {
	    (*n_func)(np); np += gc->vertexArray.np_stride;
	}
	glEnd();
    }
}
void (*__gl_varray_funcs[64])(GLenum, GLint, GLsizei) = {
(void (*)(GLenum, GLint, GLsizei))__glNop,
__glDrawArraysN,
(void (*)(GLenum, GLint, GLsizei))__glNop,
(void (*)(GLenum, GLint, GLsizei))__glNop,
(void (*)(GLenum, GLint, GLsizei))__glNop,
(void (*)(GLenum, GLint, GLsizei))__glNop,
(void (*)(GLenum, GLint, GLsizei))__glNop,
(void (*)(GLenum, GLint, GLsizei))__glNop,
(void (*)(GLenum, GLint, GLsizei))__glNop,
(void (*)(GLenum, GLint, GLsizei))__glNop,
(void (*)(GLenum, GLint, GLsizei))__glNop,
(void (*)(GLenum, GLint, GLsizei))__glNop,
(void (*)(GLenum, GLint, GLsizei))__glNop,
(void (*)(GLenum, GLint, GLsizei))__glNop,
(void (*)(GLenum, GLint, GLsizei))__glNop,
(void (*)(GLenum, GLint, GLsizei))__glNop,
(void (*)(GLenum, GLint, GLsizei))__glNop,
(void (*)(GLenum, GLint, GLsizei))__glNop,
(void (*)(GLenum, GLint, GLsizei))__glNop,
(void (*)(GLenum, GLint, GLsizei))__glNop,
(void (*)(GLenum, GLint, GLsizei))__glNop,
(void (*)(GLenum, GLint, GLsizei))__glNop,
(void (*)(GLenum, GLint, GLsizei))__glNop,
(void (*)(GLenum, GLint, GLsizei))__glNop,
(void (*)(GLenum, GLint, GLsizei))__glNop,
(void (*)(GLenum, GLint, GLsizei))__glNop,
(void (*)(GLenum, GLint, GLsizei))__glNop,
(void (*)(GLenum, GLint, GLsizei))__glNop,
(void (*)(GLenum, GLint, GLsizei))__glNop,
(void (*)(GLenum, GLint, GLsizei))__glNop,
(void (*)(GLenum, GLint, GLsizei))__glNop,
(void (*)(GLenum, GLint, GLsizei))__glNop,
__glDrawArraysV,
__glDrawArraysNV,
__glDrawArraysCV,
__glDrawArraysNCV,
__glDrawArraysTV,
__glDrawArraysNTV,
__glDrawArraysCTV,
__glDrawArraysNCTV,
__glDrawArraysIV,
__glDrawArraysNIV,
__glDrawArraysCIV,
__glDrawArraysNCIV,
__glDrawArraysTIV,
__glDrawArraysNTIV,
__glDrawArraysCTIV,
__glDrawArraysNCTIV,
__glDrawArraysEV,
__glDrawArraysNEV,
__glDrawArraysCEV,
__glDrawArraysNCEV,
__glDrawArraysTEV,
__glDrawArraysNTEV,
__glDrawArraysCTEV,
__glDrawArraysNCTEV,
__glDrawArraysIEV,
__glDrawArraysNIEV,
__glDrawArraysCIEV,
__glDrawArraysNCIEV,
__glDrawArraysTIEV,
__glDrawArraysNTIEV,
__glDrawArraysCTIEV,
__glDrawArraysNCTIEV,
};
