//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by 3DfxSplash.rc
//
#define IDR_ANIM1                       101
#define IDR_WAVE1                       102
#define IDR_PLUG1                       107

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        108
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
