#
# Copyright (c) 1997, 3Dfx Interactive, Inc.
# All Rights Reserved.
#
# This is UNPUBLISHED PROPRIETARY SOURCE CODE of 3Dfx Interactive, Inc.;
# the contents of this file may not be disclosed to third parties, copied or
# duplicated in any form, in whole or in part, without the prior written
# permission of 3Dfx Interactive, Inc.
#
# RESTRICTED RIGHTS LEGEND:
# Use, duplication or disclosure by the Government is subject to restrictions
# as set forth in subdivision (c)(1)(ii) of the Rights in Technical Data
# and Computer Software clause at DFARS 252.227-7013, and/or in similar or
# successor clauses in the FAR, DOD or NASA FAR Supplement. Unpublished  -
# rights reserved under the Copyright Laws of the United States.
#
# $Revision: 11 $
# $Date: 6/24/99 5:20p $
#

# Build Options: define these either in environment or makefile
#
# define HAL_CSIM to include the C simulator and interface into the HAL code
# define HAL_HSIM to include the VCS simulator interface into the HAL code
# define HAL_HW   to include the real HardWare interface into the HAL code
#

!if defined(HAL_HW)
HALDEFS = -DHAL_HW
!else
HALDEFS =

!ifndef KERNEL
LCOPTS = $(LCOPTS) -WX
!endif
!endif

!if ("$(BUILD_DIAGS)" != "")
LCDEFS = $(LCDEFS) -DH3_DIAGS
!endif

# choose the right banshee silicon revision

!if ("$(HR_A0)" != "")
LCDEFS = $(LCDEFS) -DH3_A0
!else if ("$(HR_A1)" != "")
LCDEFS = $(LCDEFS) -DH3_A1
!else if ("$(HR_A2)" != "")
LCDEFS = $(LCDEFS) -DH3_A2
!else
LCDEFS = $(LCDEFS) -DH3_B0
!endif

LCINCS  = -I$(BUILD_ROOT_SWLIBS)\include -I$(BUILD_ROOT)\$(FX_GLIDE_HW)\include

!ifndef KERNEL
PRIVATE_HEADERS=h3cinitdd.h modetabl.h plltable.h memtable.h
!endif

HEADERS = h3cinit.h
CFILES  = h3cinit.c


INSTALL_DESTINATION = $(BUILD_ROOT)\$(FX_GLIDE_HW)

# targets
LIBRARIES= h3cinit.lib


LDIRT = h3csim.lib

!include $(BUILD_ROOT_SWLIBS)/include/nmake/3dfx.mak

