TARGETOS = WINNT

!include <ntwin32.mak>

TARGET = func.lib

CFILES = \
	.\clip-cull\clip\arbcliplin.c \
	.\clip-cull\clip\arbcliptri.c \
	.\clip-cull\clip\cancliplin.c \
	.\clip-cull\clip\cancliptri.c \
	.\clip-cull\clip\clip_edge_flags.c \
	.\clip-cull\clip\clipcolorlin.c \
	.\clip-cull\clip\clipcolorpnt.c \
	.\clip-cull\clip\clipcolortri.c \
	.\clip-cull\clip\cliptextlin.c \
	.\clip-cull\clip\cliptexttri.c \
	.\clip-cull\clip\cmpltcolorlin.c \
	.\clip-cull\clip\cmpltcolorpnt.c \
	.\clip-cull\clip\cmpltcolortri.c \
	.\clip-cull\clip\cmplttextlin.c \
	.\clip-cull\clip\cmplttexttri.c \
	.\clip-cull\clip\complement_one_plane.c \
	.\clip-cull\facecheck\cullface.c \
	.\coords\color\colors.c \
	.\coords\index\index.c \
	.\coords\normals\normals.c \
	.\coords\texcoord\texcoords.c \
	.\coords\vertex\vertexes.c \
	.\corner\bgnend.c \
	.\corner\clamp.c \
	.\corner\errors.c \
	.\enable\edgeflag.c \
	.\eval\eval.c \
	.\eval\evalattrib.c \
	.\eval\evalvertexmix.c \
	.\feedback\nodraw.c \
	.\fog\fog.c \
	.\fragop\alphafunc.c \
	.\fragop\blendfunc.c \
	.\fragop\depthbuf.c \
	.\fragop\depthfunc.c \
	.\fragop\logicop.c \
	.\fragop\rgblogicop.c \
	.\fragop\stencil.c \
	.\fragop\stencilmask.c \
	.\framebuffer\acbuf\accbuf.c \
	.\framebuffer\clear\clear.c \
	.\framebuffer\clear\clearaccum.c \
	.\framebuffer\clear\clearall.c \
	.\framebuffer\clear\cleardepth.c \
	.\framebuffer\clear\clearstencil.c \
	.\framebuffer\drawbuffer\stereobuffer.c \
	.\lighting\light.c \
	.\lighting\lightsimulate.c \
	.\lists\array.c \
	.\lists\calllist.c \
	.\lists\listcov.c \
	.\lists\nest.c \
	.\pixels\ReadPixelsRGBA.c \
	.\pixels\doodle.c \
	.\pixels\extensions\packedpix.c \
	.\pixels\glPixelTransfer.c \
	.\pixels\pixel.c \
	.\pixels\pixelinv.c \
	.\prims\bitmaps\bitmaps.c \
	.\prims\extensions\extvertarray.c \
	.\prims\lines\line.c \
	.\prims\lines\linestrip.c \
	.\prims\meshes\qstrip.c \
	.\prims\meshes\tfans.c \
	.\prims\meshes\tstrip.c \
	.\prims\objects\cyls.c \
	.\prims\objects\disks.c \
	.\prims\objects\pdisks.c \
	.\prims\objects\spheres.c \
	.\prims\points\point.c \
	.\prims\polygons\polys.c \
	.\prims\polygons\polystipple.c \
	.\prims\quads\quads.c \
	.\prims\quads\rect.c \
	.\prims\rasterpos\glRasterPos.c \
	.\prims\tris\tris.c \
	.\prims\vertarray\vertarray.c \
	.\rasterize\aafatlines.c \
	.\rasterize\pointsize.c \
	.\rasterize\shade.c \
	.\rasterize\pgonoffset.c \
	.\state\attrib\pushattrib.c \
	.\state\attrib\transattrib.c \
	.\texture\env\txmodblend.c \
	.\texture\env\txmoddecal.c \
	.\texture\image2d\internalformat.c \
	.\texture\image2d\unsign11.c \
	.\texture\image2d\unsign12.c \
	.\texture\image2d\unsign13.c \
	.\texture\image2d\unsign14.c \
	.\texture\image2d\unsign21.c \
	.\texture\image2d\unsign22.c \
	.\texture\image2d\unsign23.c \
	.\texture\image2d\unsign24.c \
	.\texture\image2d\unsign31.c \
	.\texture\image2d\unsign32.c \
	.\texture\image2d\unsign33.c \
	.\texture\image2d\unsign34.c \
	.\texture\image2d\unsign41.c \
	.\texture\image2d\unsign42.c \
	.\texture\image2d\unsign43.c \
	.\texture\image2d\unsign44.c \
	.\texture\mipmaps\txdl1.c \
	.\texture\mipmaps\txdl1_2.c \
	.\texture\mipmaps\txdl1_3.c \
	.\texture\mipmaps\txdl2.c \
	.\texture\mipmaps\txdl2_2.c \
	.\texture\mipmaps\txdl2_3.c \
	.\texture\mipmaps\txdl3.c \
	.\texture\mipmaps\txdl3_2.c \
	.\texture\mipmaps\txdl3_3.c \
	.\texture\mipmaps\txdl4.c \
	.\texture\mipmaps\txdl4_2.c \
	.\texture\mipmaps\txdl4_3.c \
	.\texture\mipmaps\txdlim1_2.c \
	.\texture\mipmaps\txdlim2.c \
	.\texture\mipmaps\txdlim2_2.c \
	.\texture\mipmaps\txdlim2_3.c \
	.\texture\mipmaps\txdlim3_2.c \
	.\texture\mipmaps\txdlim4.c \
	.\texture\mipmaps\txdlim4_2.c \
	.\texture\mipmaps\txdlim4_3.c \
	.\texture\mipmaps\txim1.c \
	.\texture\mipmaps\txim2.c \
	.\texture\mipmaps\txim3.c \
	.\texture\mipmaps\txim4.c \
	.\texture\copy\copytex.c \
	.\texture\objects\texobj.c \
	.\texture\objects\texobject.c \
	.\texture\objects\textureswap.c \
	.\xform\frustum.c \
	.\xform\getmatrix.c \
	.\xform\getviewport.c \
	.\xform\matrixflow.c \
	.\xform\ortho.c \
	.\xform\popmatrix.c \
	.\xform\rotate.c \
	.\xform\scale.c \
	.\xform\xformsimulate.c \
	.\xform\translate.c \
	.\xform\viewport.c 

OBJECTS = $(CFILES:.c=.obj)

LCINCS = -I..\inc -Ilighting -Istate\attrib -Istress -Ixform
LCDEFS = -D__STDC__ -DWIN32
LCFLAGS = $(LCDEFS) $(LCINCS)

all: $(TARGET)

.c.obj:
    $(cc) $(cdebug) $(LCFLAGS) $(cflags) $(cvars) $(scall) -Fo$*.obj $*.c

$(TARGET): $(OBJECTS)
    $(implib) -out:$*.lib @objs.txt

clean:
    rm -f $(OBJECTS)

clobber: clean
    rm -f $(TARGET)
