//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by browseui.rc
//
#define IDD_DIALOG1                     101
#define IDR_MENU1                       103
#define IDC_TREE                        1000
#define ID_EDITITEM                     40001

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        105
#define _APS_NEXT_COMMAND_VALUE         40010
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
