//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by systray.rc
//
#define IDR_MENU1                       101
#define IDI_ICON1                       103
#define IDI_ICON2                       104
#define IDI_ICON3                       105
#define ID_ACTION_ADDICON               40001
#define ID_ACTION_REMOVEICON            40002
#define ID_OPENGL_ENABLE                40003
#define ID_OPENGL_DISABLE               40004
#define ID_OPENGL_REMOVE                40006

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        106
#define _APS_NEXT_COMMAND_VALUE         40007
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
