##
##  Makefile for Windows NT
##


!include <ntwin32.mak>


#GLUTHOME = ../../../lib/glut
CFLAGS   = -I$(GLUTHOME) -DWIN32 -nologo -W1 -Z7
LIBS     = $(GLUTHOME)/glut.lib glu32.lib opengl32.lib $(guilibs) \
           -nologo -nodefaultlibs:libcd

OBJS     = models.obj walker.obj walkviewer.obj
EXES     = walker.exe


all     : $(EXES)


$(EXES) : $(OBJS)
        $(link) -out:$@ $(OBJS) $(LIBS)

.c.obj:
	$(CC) $(CFLAGS) -c $<

clean:
	rm -f $(EXES) $(OBJS) *.pdb *.ncb *.tpl *.ilk
