#
# Copyright (c) 1995, 3Dfx Interactive, Inc.
# All Rights Reserved.
#
# This is UNPUBLISHED PROPRIETARY SOURCE CODE of 3Dfx Interactive, Inc.;
# the contents of this file may not be disclosed to third parties, copied or
# duplicated in any form, in whole or in part, without the prior written
# permission of 3Dfx Interactive, Inc.
#
# RESTRICTED RIGHTS LEGEND:
# Use, duplication or disclosure by the Government is subject to restrictions
# as set forth in subdivision (c)(1)(ii) of the Rights in Technical Data
# and Computer Software clause at DFARS 252.227-7013, and/or in similar or
# successor clauses in the FAR, DOD or NASA FAR Supplement. Unpublished  -
# rights reserved under the Copyright Laws of the United States.
#

LCINCS  = -I$(BUILD_ROOT_SWLIBS)\include

INSTALL_DESTINATION = $(BUILD_ROOT_SWLIBS)

!ifdef TEST

!if "$(FX_TARGET)" == "DOS"
LLDLIBS = $(BUILD_ROOT_SWLIBS)\lib\fxdpmi.lib
!endif

HEADERS   = atb_net.h
CFILES  = main.c atb_net.c atb_ipx.c
PROGRAM = main.exe

!else

HEADERS   = atb_net.h
CFILES    = atb_ipx.c atb_net.c
LIBRARIES = atb_net.lib

!endif

!include $(BUILD_ROOT_SWLIBS)/include/nmake/3dfx.mak
