/* 
 * echar.h
 *
 */




//	Character codes
#define	CHR_SLINE_UR				191
#define	CHR_SLINE_LL				192
#define	CHR_SLINE_LR				217
#define	CHR_SLINE_UL				218
#define	CHR_SLINE_VERT				179
#define	CHR_SLINE_HORZ				196
#define	CHR_SLINE_DOWNT			194
#define	CHR_SLINE_UPT				193
#define	CHR_SLINE_LEFTT			195
#define	CHR_SLINE_RIGHTT			180
#define	CHR_SLINE_CROSS			197
#define	CHR_DLINE_UR				187
#define	CHR_DLINE_LL				200
#define	CHR_DLINE_LR				188
#define	CHR_DLINE_UL				201
#define	CHR_DLINE_VERT				186
#define	CHR_DLINE_HORZ				205
#define	CHR_DLINE_DOWNT			203
#define	CHR_DLINE_UPT				202
#define	CHR_DLINE_LEFTT			204
#define	CHR_DLINE_RIGHTT			185
#define	CHR_DLINE_CROSS			206

#define	CHR_DLINE_SLEFTT			182
#define	CHR_DLINE_SRIGHTT			199
#define	CHR_DLINE_SUPT				207
#define	CHR_DLINE_SDOWNT			209
#define	CHR_SPACE					32

// Key codes
#define	KEY_BACKSPACE				0x0008
#define	KEY_ESCAPE					0x001B
#define	KEY_F1						0x3B00
#define	KEY_F2						0x3C00
#define	KEY_F3						0x3D00
#define	KEY_HOME						0x4700
#define	KEY_ARROW_UP				0x4800
#define	KEY_ARROW_LF				0x4B00
#define	KEY_ARROW_RT				0x4D00
#define	KEY_END						0x4F00
#define	KEY_ARROW_DN				0x5000
#define	KEY_INS						0x5200
#define	KEY_DEL						0x5300
