##
##  Makefile for Windows NT
##


all     :
        cd atlantis
        nmake -nologo -f Makefile
        cd ..
	cd glutmech
        nmake -nologo -f Makefile
        cd ..
        cd ideas
        nmake -nologo -f Makefile
        cd ..
        cd walker
#        nmake -nologo -f Makefile
        cd ..
        cd yacme
        nmake -nologo -f Makefile
        cd ..


clean   :
        cd atlantis
        nmake -nologo -f Makefile clean
        cd ..
	cd glutmech
        nmake -nologo -f Makefile clean
        cd ..
        cd ideas
        nmake -nologo -f Makefile clean
        cd ..
        cd walker
        nmake -nologo -f Makefile clean
        cd ..
        cd yacme
        nmake -nologo -f Makefile clean
        cd ..
