##
##  Makefile for Windows NT
##


!include <ntwin32.mak>

#GLUTHOME = ../../lib/glut
CFLAGS   = -I$(GLUTHOME) /DWIN32 -nologo -W1 -Z7
LIBS     = $(GLUTHOME)/glut.lib \
           glu32.lib opengl32.lib $(guilibs) \
           -nologo -nodefaultlib:libcd -debug


OBJS     = dinoball.obj trackball.obj
EXES     = abgr.exe bitfont.exe blender.exe dials.exe dials2.exe dinoball.exe \
           dinospin.exe evaltest.exe fogtst.exe fontdemo.exe glpuzzle.exe \
           glutdino.exe glutplane.exe highlight.exe lightlab.exe \
           movelight.exe mjkwarp.exe molehill.exe movelight.exe oclip.exe \
           ohidden.exe olight.exe olympic.exe origami.exe oversphere.exe \
           scene.exe scube.exe sphere.exe sphere2.exe splatlogo.exe spots.exe \
           stars.exe stenciltst.exe stereo.exe stroke.exe subwin.exe \
           surfgrid.exe texenv.exe triselect.exe zoomdino.exe

all             : $(EXES)


dinospin.exe    : trackball.obj
	$(CC) $(CFLAGS) -c dinospin.c
        $(link) -out:$@ trackball.obj dinospin.obj $(LIBS)

glpuzzle.exe    : trackball.obj
        $(CC) $(CFLAGS) -c glpuzzle.c
        $(link) -out:$@ trackball.obj glpuzzle.obj $(LIBS)

mjkimage.c	: 
	gzip -d -c <mjkimage.c.gz >mjkimage.c

mjkwarp.exe     : mjkimage.obj
        $(CC) $(CFLAGS) -c mjkwarp.c
        $(link) -out:$@ mjkwarp.obj mjkimage.obj $(LIBS)

splatlogo.exe     : splatlogo.obj logo.obj
        $(CC) $(CFLAGS) -c splatlogo.c
        $(link) -out:$@ logo.obj splatlogo.obj $(LIBS)

.c.exe:
	$(CC) $(CFLAGS) -c $<
        $(link) -out:$@ $*.obj $(LIBS)

clean:
	rm -f $(EXES) *.obj *.pdb *.ilk *.vtp *.tpl *.ncb
