#include <stdio.h>
#include <stdlib.h>
#include <stddef.h>
#include <string.h>

/* headers needed for printing offsets */
#include "types.h"
#include "g_disp.h"
#include "context.h"
#include "vertex.h"
#include "fr_tri.h"

static const char *initialText =
    "/* DO NOT EDIT - THIS FILE IS AUTOMATICALLY GENERATED */\n"
    "#ifndef __gl_asmoff_h_\n"
    "#define __gl_asmoff_h_\n"
    "\n"
    "";

static const char *finalText =
    "\n"
    "#endif __gl_asmoff_h_\n"
    "";

#define MAX_LABEL_SIZE	32
#define labelPad(label)		(MAX_LABEL_SIZE - strlen(label))

#define PrintOffset(type,label,member) \
    printf("#define %s %*i\n", #label, labelPad(#label), offsetof(type,member));

void
printOffsets(void)
{
    PrintOffset(__GLcontext, __GL_CURRENT_DISPATCH_STATE, currentDispatchState);
}

int __cdecl
main(int argc, char **argv)
{
    printf(initialText);
    printOffsets();
    printf(finalText);

    return EXIT_SUCCESS;
}
