FX_TARGET_MINOR = WIN95

INSTALL_DESTINATION = $(BUILD_ROOT)\$(FX_GLIDE_HW)\glide3\conform

LDIRT= *.exe *.map *.sys *.obj *.lib *.res

LCINCS  = $(LCINCS)  -I$(BUILD_ROOT)\$(FX_GLIDE_HW)\include \
	-I$(MSVC)\include 

LCOPTS = -WX 


GLIDELIB        =       glide3x.lib

PRIVATE_HEADERS =  loginfo.h logcmp.h
DATAFILES = 

# 
# SUPPORT_SRC is a list of files to be linked with all tests
#
SUPPORT_SRC = report.cpp compare.cpp parse.cpp
SUPPORT_OBJ = $(SUPPORT_SRC:.cpp=.obj) 

LLDLIBS = $(SUPPORT_OBJ) \
          $(LIBOBJS) $(BUILD_ROOT)\$(FX_GLIDE_HW)\lib\$(GLIDELIB)\
          $(BUILD_ROOT_SWLIBS)\lib\fxmisc.lib


#
# APPS is a list of applications.
#
APPS   = logcmp.cpp

PROGRAMS = $(APPS:.cpp=.exe)

FX_TARGET_MINOR = dos
!include $(BUILD_ROOT)\swlibs\include\nmake\3dfx.mak


$(PROGRAMS):  $(LLDLIBS)

$(APPS):	$(PRIVATE_HEADERS)
$(SUPPORT_OBJ): $(PRIVATE_HEADERS)

