#
# Copyright (c) 1997, 3Dfx Interactive, Inc.
# All Rights Reserved.
#
# This is UNPUBLISHED PROPRIETARY SOURCE CODE of 3Dfx Interactive, Inc.;
# the contents of this file may not be disclosed to third parties, copied or
# duplicated in any form, in whole or in part, without the prior written
# permission of 3Dfx Interactive, Inc.
#
# RESTRICTED RIGHTS LEGEND:
# Use, duplication or disclosure by the Government is subject to restrictions
# as set forth in subdivision (c)(1)(ii) of the Rights in Technical Data
# and Computer Software clause at DFARS 252.227-7013, and/or in similar or
# successor clauses in the FAR, DOD or NASA FAR Supplement. Unpublished  -
# rights reserved under the Copyright Laws of the United States.
#
# $Revision: 8 $
# $Date: 9/01/99 3:38p $
#

HEADERS=*.h gendate.h

INSTALL_DESTINATION=$(BUILD_ROOT)\$(FX_GLIDE_HW)

LDIRT = gendate.exe gendate.obj gendate.h

!include $(BUILD_ROOT_SWLIBS)/include/nmake/3dfx.mak


gendate.exe: gendate.c
!if "$(FX_COMPILER)" == "MICROSOFT"
	$(CC) gendate.c
!else if "$(FX_COMPILER)" == "WATCOM"
        set WCC386=$(CFLAGS)
        wcl386 gendate.c
!endif

gendate.h: gendate.exe
	gendate.exe > gendate.h
	del gendate.exe

