# This is a Jack generated makefile.

# Setting up NULL
!IF "$(OS)" == "Windows_NT"
NULL=
!ELSE 
NULL=nul
!ENDIF 

# Include directories...
!if "$(CFG)" == "LOCAL"
COMMONINC=..\common
OTHERINC=c:\3dfx\sdk\glide3x\src\include
ALLINCS=/I $(COMMONINC) /I $(OTHERINC)
!else
HEADERS=$(BUILD_ROOT_CVG)\glide3\src
LIBINCLUDE=$(BUILD_ROOT_SWLIBS)\include
CVGINCLUDE=$(BUILD_ROOT_CVG)\include
ALLINCS=/I $(HEADERS) /I $(LIBINCLUDE) /I $(CVGINCLUDE) /I "..\common"
!endif

# Library directories
!if "$(CFG)" == "LOCAL"
GLIDELIB=c:\3dfx\sdk\glide3x\src\lib\win32
ALLLIBS=/libpath:$(GLIDELIB)
!else
GLIDELIB=$(BUILD_ROOT_CVG)\lib
ALLLIBS=/libpath:$(GLIDELIB)
!endif

# Environment...
DLLNAME=3DfxSpl3.dll

# Output dir and intermediate files dir
OUTDIR=.\3DfxSplash 3x
INTDIR=.\3DfxSplash 3x

ALL : "$(OUTDIR)\$(DLLNAME)"

CLEAN : 
	deltree.exe /y "$(INTDIR)"

"$(OUTDIR)":
	if not exist "$(OUTDIR)\$(NULL)" mkdir "$(OUTDIR)"

# Compiling preferences...

CPP=cl.exe
CPP_PROJ=/nologo /ML /W3 /GX /O2 /Ob2 $(ALLINCS)\
 /D "USE_GLIDE3" /D "PLAYBACK" /D "WIN32" /D\
 "_WINDOWS" /D "_MBCS" /D "__MSC__" /D "SPLASH_DLL"\
 /YX /Fo"$(INTDIR)\\" /Fd"$(INTDIR)\\" /FD /c 

CPP_OBJS=".\3DfxSplash 3x/"

.c{$(CPP_OBJS)}.obj::
   $(CPP) @<<
   $(CPP_PROJ) $< 
<<

.cpp{$(CPP_OBJS)}.obj::
   $(CPP) @<<
   $(CPP_PROJ) $< 
<<

# Resources...
RSC=rc.exe
RSC_PROJ=/l 0x409 /fo"$(INTDIR)\3DfxSplash.res" /d "NDEBUG" 

# Linker...

LINK32=link.exe
LINK32_FLAGS=kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib\
 advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib\
 odbccp32.lib largeint.lib winmm.lib glide3x.lib /nologo /dll /incremental:no\
 /machine:I386 /out:"$(OUTDIR)\$(DLLNAME)" /implib:"$(OUTDIR)\3DfxSpl3.lib"\
 $(ALLLIBS)
LINK32_OBJS= \
	"$(INTDIR)\3DfxSplash.res" \
	"$(INTDIR)\convexhull.obj" \
	"$(INTDIR)\GlideGraphics.obj" \
	"$(INTDIR)\Main.obj" \
	"$(INTDIR)\RevPoint.obj" \
	"$(INTDIR)\texcache.obj"

"$(OUTDIR)\$(DLLNAME)" : "$(OUTDIR)" $(DEF_FILE) $(LINK32_OBJS)
    $(LINK32) @<<
  $(LINK32_FLAGS) $(LINK32_OBJS)
<<

# Start doing stuff...
DEP_FILES = \
	".\resource.h"\

SOURCE=.\3DfxSplash.rc
DST=3DfxSplash.res
"$(INTDIR)\$(DST)" : $(SOURCE) "$(INTDIR)"
	$(RSC) $(RSC_PROJ) $(SOURCE)

SOURCE=.\convexhull.cpp
DST=convexhull.obj
"$(INTDIR)\$(DST)" : $(SOURCE) "$(INTDIR)"
	$(CPP) $(CPP_PROJ) $(SOURCE)

SOURCE=..\common\GlideGraphics.cpp
DST=GlideGraphics.obj
"$(INTDIR)\$(DST)" : $(SOURCE) "$(INTDIR)"
	$(CPP) $(CPP_PROJ) $(SOURCE)

SOURCE=.\Main.cpp
DST=Main.obj
"$(INTDIR)\$(DST)" : $(SOURCE) "$(INTDIR)"
	$(CPP) $(CPP_PROJ) $(SOURCE)

SOURCE=..\common\RevPoint.cpp
DST=RevPoint.obj
"$(INTDIR)\$(DST)" : $(SOURCE) "$(INTDIR)"
	$(CPP) $(CPP_PROJ) $(SOURCE)

SOURCE=..\common\texcache.cpp
DST=texcache.obj
"$(INTDIR)\$(DST)" : $(SOURCE) "$(INTDIR)"
	$(CPP) $(CPP_PROJ) $(SOURCE)
