##
##  Makefile for Windows NT
##

!include <ntwin32.mak>

TDHOME   = $(GLHOME)/td

CFLAGS   = -I$(TDHOME) -I$(GLUTHOME) -DWIN32 -nologo -W1 -O2
LIBS     = $(TDHOME)/td.lib $(GLUTHOME)/glut.lib \
           opengl32.lib glu32.lib -nodefaultlib:libcd $(guilibs)

OBJS     = statue.obj
EXES     = statue.exe

all     : $(EXES)

$(EXES) : $(OBJS)
        $(link) -nologo -out:$@ $(OBJS) $(LIBS)

.c.obj  :
	$(CC) $(CFLAGS) -c $<

clean   :
        rm -f *.exe *.obj *.pdb

