##
##  Makefile for AIX
##


GLUTHOME = ../../../lib/glut
TDHOME   = ../td

CC       = cc
CFLAGS   = -g -I$(GLUTHOME) -I$(TDHOME)
LIBS     = -L$(TDHOME) -ltd -L$(GLUTHOME) -lglut -lGLU -lGL \
	   -lXmu -lXext -lX11 -lm

OBJS     = statue.o
EXES     = statue


all	: $(EXES)

$(EXES)	: $(OBJS) 
	$(CC) $(CFLAGS) -o $@ $(OBJS) $(LIBS) 

.c.o	:
	$(CC) $(CFLAGS) -c $<

clean	: 
	rm -f core $(EXES) *.o *~ #*
