##
##  Makefile for HPUX
##


GLUTHOME = ../../../lib/glut
TDHOME   = ../td

CC       = cc
CFLAGS   = -g -Aa -I$(GLUTHOME) -I$(TDHOME)
LIBS     = -L$(TDHOME) -ltd -L$(GLUTHOME) -lglut -lGLU -lGL -lGLb \
	   -L/usr/lib/X11R5 -lXext -lX11 -lXhp11 -lm

OBJS     = statue.o
EXES     = statue


all	: $(EXES)

$(EXES)	: $(OBJS) 
	$(CC) $(CFLAGS) -o $@ $(OBJS) $(LIBS) 
	/usr/lib/GL/apptag $@

.c.o	:
	$(CC) $(CFLAGS) -c $<

clean	: 
	rm -f core $(EXES) *.o *~ #*
