FX_TARGET_MINOR = WIN95

INSTALL_DESTINATION = $(BUILD_ROOT)\$(FX_GLIDE_HW)\glide3\conform

LDIRT= *.exe *.map *.sys *.obj *.lib *.res

LCINCS  = $(LCINCS)  -I$(BUILD_ROOT)\$(FX_GLIDE_HW)\include \
	-I$(MSVC)\mfc\include -I$(MSVC)\include 

LCOPTS = -WX 
LCDEFS = -D_AFXDLL -MD

GLIDELIB        =       glide3x.lib

PRIVATE_HEADERS =  resource.h MainFrm.h Runner.h RunnerDoc.h \
                   RunnerView.h StdAfx.h
DATAFILES = 

RESOURCES = Runner.res
RESOURCE_FILE = Runner.rc
# 
# SUPPORT_SRC is a list of files to be linked with all tests
#
SUPPORT_SRC =  MainFrm.cpp RunnerDoc.cpp RunnerView.cpp \
               StdAfx.cpp
SUPPORT_OBJ = $(SUPPORT_SRC:.cpp=.obj) $(RESOURCES)

LLDLIBS = $(SUPPORT_OBJ) \
          $(LIBOBJS) $(BUILD_ROOT)\$(FX_GLIDE_HW)\lib\$(GLIDELIB)\
          $(BUILD_ROOT_SWLIBS)\lib\fxmisc.lib


#
# APPS is a list of applications.
#
APPS   = Runner.cpp

PROGRAMS = $(APPS:.cpp=.exe)

!include $(BUILD_ROOT)\swlibs\include\nmake\3dfx.mak

$(PROGRAMS):  $(LLDLIBS)
$(RESOURCES): $(RESOURCE_FILE)
	rc $(RESOURCE_FILE)

$(APPS):	$(PRIVATE_HEADERS)
$(SUPPORT_OBJ): $(PRIVATE_HEADERS)

