//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Runner.rc
//
#define IDD_ABOUTBOX                    100
#define IDT_TIMER_1                     101
#define IDT_TIMER_0                     102
#define IDR_MAINFRAME                   128
#define IDR_RUNNERTYPE                  129
#define IDB_BITMAP1                     130
#define IDR_POPUP_MENU                  141
#define ID_RUN_TESTS                    32773
#define ID_STOP_RUNNING_TESTS           32774
#define ID_PROP_PAGE                    32776
#define ID_RUNTESTS                     32777
#define ID_STOPTESTS                    32780
#define ID_LOGTOFILE                    32781
#define ID_TIMEOUT_1                    32784
#define ID_TIMEOUT_2                    32785
#define ID_TIMEOUT_5                    32786
#define ID_TIMEOUT_10                   32787
#define ID_TIMEOUT_NONE                 32788
#define ID_TIMEOUT_30                   32789
#define ID_TIMEOUT_60                   32790
#define ID_STOPCURRENTTEST              32791
#define ID_RUN_TEST                     32792
#define ID_ALWAYS_ON_TOP                32793
#define ID_PAUSE_TESTS                  32795
#define ID_PAUSETESTS                   32796

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        142
#define _APS_NEXT_COMMAND_VALUE         32797
#define _APS_NEXT_CONTROL_VALUE         1004
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
