/* DO NOT EDIT - THIS FILE IS AUTOMATICALLY GENERATED */
#ifndef __g_disp_h_
#define __g_disp_h_

/*
** Copyright 1992-1997 Silicon Graphics, Inc.
** All Rights Reserved.
**
** This is UNPUBLISHED PROPRIETARY SOURCE CODE of Silicon Graphics, Inc.;
** the contents of this file may not be disclosed to third parties, copied or
** duplicated in any form, in whole or in part, without the prior written
** permission of Silicon Graphics, Inc.
**
** RESTRICTED RIGHTS LEGEND:
** Use, duplication or disclosure by the Government is subject to restrictions
** as set forth in subdivision (c)(1)(ii) of the Rights in Technical Data
** and Computer Software clause at DFARS 252.227-7013, and/or in similar or
** successor clauses in the FAR, DOD or NASA FAR Supplement. Unpublished -
** rights reserved under the Copyright Laws of the United States.
*/

#ifdef __GL_ICD
#include "g_disp_icd.h"
#else /* __GL_ICD */


#ifdef _WINDOWS
#define SZPTR (32>>3)
#define SZINT 4
#else
#define SZPTR (_MIPS_SZPTR>>3)
#endif

#define __GL_TAB_NewList 0
#define __GL_TAB_EndList 1
#define __GL_TAB_CallList 2
#define __GL_TAB_CallLists 3
#define __GL_TAB_DeleteLists 4
#define __GL_TAB_GenLists 5
#define __GL_TAB_ListBase 6
#define __GL_TAB_Begin 7
#define __GL_TAB_Bitmap 8
#define __GL_TAB_Color3b 9
#define __GL_TAB_Color3bv 10
#define __GL_TAB_Color3d 11
#define __GL_TAB_Color3dv 12
#define __GL_TAB_Color3f 13
#define __GL_TAB_Color3fv 14
#define __GL_TAB_Color3i 15
#define __GL_TAB_Color3iv 16
#define __GL_TAB_Color3s 17
#define __GL_TAB_Color3sv 18
#define __GL_TAB_Color3ub 19
#define __GL_TAB_Color3ubv 20
#define __GL_TAB_Color3ui 21
#define __GL_TAB_Color3uiv 22
#define __GL_TAB_Color3us 23
#define __GL_TAB_Color3usv 24
#define __GL_TAB_Color4b 25
#define __GL_TAB_Color4bv 26
#define __GL_TAB_Color4d 27
#define __GL_TAB_Color4dv 28
#define __GL_TAB_Color4f 29
#define __GL_TAB_Color4fv 30
#define __GL_TAB_Color4i 31
#define __GL_TAB_Color4iv 32
#define __GL_TAB_Color4s 33
#define __GL_TAB_Color4sv 34
#define __GL_TAB_Color4ub 35
#define __GL_TAB_Color4ubv 36
#define __GL_TAB_Color4ui 37
#define __GL_TAB_Color4uiv 38
#define __GL_TAB_Color4us 39
#define __GL_TAB_Color4usv 40
#define __GL_TAB_EdgeFlag 41
#define __GL_TAB_EdgeFlagv 42
#define __GL_TAB_End 43
#define __GL_TAB_Indexd 44
#define __GL_TAB_Indexdv 45
#define __GL_TAB_Indexf 46
#define __GL_TAB_Indexfv 47
#define __GL_TAB_Indexi 48
#define __GL_TAB_Indexiv 49
#define __GL_TAB_Indexs 50
#define __GL_TAB_Indexsv 51
#define __GL_TAB_Normal3b 52
#define __GL_TAB_Normal3bv 53
#define __GL_TAB_Normal3d 54
#define __GL_TAB_Normal3dv 55
#define __GL_TAB_Normal3f 56
#define __GL_TAB_Normal3fv 57
#define __GL_TAB_Normal3i 58
#define __GL_TAB_Normal3iv 59
#define __GL_TAB_Normal3s 60
#define __GL_TAB_Normal3sv 61
#define __GL_TAB_RasterPos2d 62
#define __GL_TAB_RasterPos2dv 63
#define __GL_TAB_RasterPos2f 64
#define __GL_TAB_RasterPos2fv 65
#define __GL_TAB_RasterPos2i 66
#define __GL_TAB_RasterPos2iv 67
#define __GL_TAB_RasterPos2s 68
#define __GL_TAB_RasterPos2sv 69
#define __GL_TAB_RasterPos3d 70
#define __GL_TAB_RasterPos3dv 71
#define __GL_TAB_RasterPos3f 72
#define __GL_TAB_RasterPos3fv 73
#define __GL_TAB_RasterPos3i 74
#define __GL_TAB_RasterPos3iv 75
#define __GL_TAB_RasterPos3s 76
#define __GL_TAB_RasterPos3sv 77
#define __GL_TAB_RasterPos4d 78
#define __GL_TAB_RasterPos4dv 79
#define __GL_TAB_RasterPos4f 80
#define __GL_TAB_RasterPos4fv 81
#define __GL_TAB_RasterPos4i 82
#define __GL_TAB_RasterPos4iv 83
#define __GL_TAB_RasterPos4s 84
#define __GL_TAB_RasterPos4sv 85
#define __GL_TAB_Rectd 86
#define __GL_TAB_Rectdv 87
#define __GL_TAB_Rectf 88
#define __GL_TAB_Rectfv 89
#define __GL_TAB_Recti 90
#define __GL_TAB_Rectiv 91
#define __GL_TAB_Rects 92
#define __GL_TAB_Rectsv 93
#define __GL_TAB_TexCoord1d 94
#define __GL_TAB_TexCoord1dv 95
#define __GL_TAB_TexCoord1f 96
#define __GL_TAB_TexCoord1fv 97
#define __GL_TAB_TexCoord1i 98
#define __GL_TAB_TexCoord1iv 99
#define __GL_TAB_TexCoord1s 100
#define __GL_TAB_TexCoord1sv 101
#define __GL_TAB_TexCoord2d 102
#define __GL_TAB_TexCoord2dv 103
#define __GL_TAB_TexCoord2f 104
#define __GL_TAB_TexCoord2fv 105
#define __GL_TAB_TexCoord2i 106
#define __GL_TAB_TexCoord2iv 107
#define __GL_TAB_TexCoord2s 108
#define __GL_TAB_TexCoord2sv 109
#define __GL_TAB_TexCoord3d 110
#define __GL_TAB_TexCoord3dv 111
#define __GL_TAB_TexCoord3f 112
#define __GL_TAB_TexCoord3fv 113
#define __GL_TAB_TexCoord3i 114
#define __GL_TAB_TexCoord3iv 115
#define __GL_TAB_TexCoord3s 116
#define __GL_TAB_TexCoord3sv 117
#define __GL_TAB_TexCoord4d 118
#define __GL_TAB_TexCoord4dv 119
#define __GL_TAB_TexCoord4f 120
#define __GL_TAB_TexCoord4fv 121
#define __GL_TAB_TexCoord4i 122
#define __GL_TAB_TexCoord4iv 123
#define __GL_TAB_TexCoord4s 124
#define __GL_TAB_TexCoord4sv 125
#define __GL_TAB_Vertex2d 126
#define __GL_TAB_Vertex2dv 127
#define __GL_TAB_Vertex2f 128
#define __GL_TAB_Vertex2fv 129
#define __GL_TAB_Vertex2i 130
#define __GL_TAB_Vertex2iv 131
#define __GL_TAB_Vertex2s 132
#define __GL_TAB_Vertex2sv 133
#define __GL_TAB_Vertex3d 134
#define __GL_TAB_Vertex3dv 135
#define __GL_TAB_Vertex3f 136
#define __GL_TAB_Vertex3fv 137
#define __GL_TAB_Vertex3i 138
#define __GL_TAB_Vertex3iv 139
#define __GL_TAB_Vertex3s 140
#define __GL_TAB_Vertex3sv 141
#define __GL_TAB_Vertex4d 142
#define __GL_TAB_Vertex4dv 143
#define __GL_TAB_Vertex4f 144
#define __GL_TAB_Vertex4fv 145
#define __GL_TAB_Vertex4i 146
#define __GL_TAB_Vertex4iv 147
#define __GL_TAB_Vertex4s 148
#define __GL_TAB_Vertex4sv 149
#define __GL_TAB_ClipPlane 150
#define __GL_TAB_ColorMaterial 151
#define __GL_TAB_CullFace 152
#define __GL_TAB_Fogf 153
#define __GL_TAB_Fogfv 154
#define __GL_TAB_Fogi 155
#define __GL_TAB_Fogiv 156
#define __GL_TAB_FrontFace 157
#define __GL_TAB_Hint 158
#define __GL_TAB_Lightf 159
#define __GL_TAB_Lightfv 160
#define __GL_TAB_Lighti 161
#define __GL_TAB_Lightiv 162
#define __GL_TAB_LightModelf 163
#define __GL_TAB_LightModelfv 164
#define __GL_TAB_LightModeli 165
#define __GL_TAB_LightModeliv 166
#define __GL_TAB_LineStipple 167
#define __GL_TAB_LineWidth 168
#define __GL_TAB_Materialf 169
#define __GL_TAB_Materialfv 170
#define __GL_TAB_Materiali 171
#define __GL_TAB_Materialiv 172
#define __GL_TAB_PointSize 173
#define __GL_TAB_PolygonMode 174
#define __GL_TAB_PolygonStipple 175
#define __GL_TAB_Scissor 176
#define __GL_TAB_ShadeModel 177
#define __GL_TAB_TexParameterf 178
#define __GL_TAB_TexParameterfv 179
#define __GL_TAB_TexParameteri 180
#define __GL_TAB_TexParameteriv 181
#define __GL_TAB_TexImage1D 182
#define __GL_TAB_TexImage2D 183
#define __GL_TAB_TexEnvf 184
#define __GL_TAB_TexEnvfv 185
#define __GL_TAB_TexEnvi 186
#define __GL_TAB_TexEnviv 187
#define __GL_TAB_TexGend 188
#define __GL_TAB_TexGendv 189
#define __GL_TAB_TexGenf 190
#define __GL_TAB_TexGenfv 191
#define __GL_TAB_TexGeni 192
#define __GL_TAB_TexGeniv 193
#define __GL_TAB_FeedbackBuffer 194
#define __GL_TAB_SelectBuffer 195
#define __GL_TAB_RenderMode 196
#define __GL_TAB_InitNames 197
#define __GL_TAB_LoadName 198
#define __GL_TAB_PassThrough 199
#define __GL_TAB_PopName 200
#define __GL_TAB_PushName 201
#define __GL_TAB_DrawBuffer 202
#define __GL_TAB_Clear 203
#define __GL_TAB_ClearAccum 204
#define __GL_TAB_ClearIndex 205
#define __GL_TAB_ClearColor 206
#define __GL_TAB_ClearStencil 207
#define __GL_TAB_ClearDepth 208
#define __GL_TAB_StencilMask 209
#define __GL_TAB_ColorMask 210
#define __GL_TAB_DepthMask 211
#define __GL_TAB_IndexMask 212
#define __GL_TAB_Accum 213
#define __GL_TAB_Disable 214
#define __GL_TAB_Enable 215
#define __GL_TAB_Finish 216
#define __GL_TAB_Flush 217
#define __GL_TAB_PopAttrib 218
#define __GL_TAB_PushAttrib 219
#define __GL_TAB_Map1d 220
#define __GL_TAB_Map1f 221
#define __GL_TAB_Map2d 222
#define __GL_TAB_Map2f 223
#define __GL_TAB_MapGrid1d 224
#define __GL_TAB_MapGrid1f 225
#define __GL_TAB_MapGrid2d 226
#define __GL_TAB_MapGrid2f 227
#define __GL_TAB_EvalCoord1d 228
#define __GL_TAB_EvalCoord1dv 229
#define __GL_TAB_EvalCoord1f 230
#define __GL_TAB_EvalCoord1fv 231
#define __GL_TAB_EvalCoord2d 232
#define __GL_TAB_EvalCoord2dv 233
#define __GL_TAB_EvalCoord2f 234
#define __GL_TAB_EvalCoord2fv 235
#define __GL_TAB_EvalMesh1 236
#define __GL_TAB_EvalPoint1 237
#define __GL_TAB_EvalMesh2 238
#define __GL_TAB_EvalPoint2 239
#define __GL_TAB_AlphaFunc 240
#define __GL_TAB_BlendFunc 241
#define __GL_TAB_LogicOp 242
#define __GL_TAB_StencilFunc 243
#define __GL_TAB_StencilOp 244
#define __GL_TAB_DepthFunc 245
#define __GL_TAB_PixelZoom 246
#define __GL_TAB_PixelTransferf 247
#define __GL_TAB_PixelTransferi 248
#define __GL_TAB_PixelStoref 249
#define __GL_TAB_PixelStorei 250
#define __GL_TAB_PixelMapfv 251
#define __GL_TAB_PixelMapuiv 252
#define __GL_TAB_PixelMapusv 253
#define __GL_TAB_ReadBuffer 254
#define __GL_TAB_CopyPixels 255
#define __GL_TAB_ReadPixels 256
#define __GL_TAB_DrawPixels 257
#define __GL_TAB_GetBooleanv 258
#define __GL_TAB_GetClipPlane 259
#define __GL_TAB_GetDoublev 260
#define __GL_TAB_GetError 261
#define __GL_TAB_GetFloatv 262
#define __GL_TAB_GetIntegerv 263
#define __GL_TAB_GetLightfv 264
#define __GL_TAB_GetLightiv 265
#define __GL_TAB_GetMapdv 266
#define __GL_TAB_GetMapfv 267
#define __GL_TAB_GetMapiv 268
#define __GL_TAB_GetMaterialfv 269
#define __GL_TAB_GetMaterialiv 270
#define __GL_TAB_GetPixelMapfv 271
#define __GL_TAB_GetPixelMapuiv 272
#define __GL_TAB_GetPixelMapusv 273
#define __GL_TAB_GetPolygonStipple 274
#define __GL_TAB_GetString 275
#define __GL_TAB_GetTexEnvfv 276
#define __GL_TAB_GetTexEnviv 277
#define __GL_TAB_GetTexGendv 278
#define __GL_TAB_GetTexGenfv 279
#define __GL_TAB_GetTexGeniv 280
#define __GL_TAB_GetTexImage 281
#define __GL_TAB_GetTexParameterfv 282
#define __GL_TAB_GetTexParameteriv 283
#define __GL_TAB_GetTexLevelParameterfv 284
#define __GL_TAB_GetTexLevelParameteriv 285
#define __GL_TAB_IsEnabled 286
#define __GL_TAB_IsList 287
#define __GL_TAB_DepthRange 288
#define __GL_TAB_Frustum 289
#define __GL_TAB_LoadIdentity 290
#define __GL_TAB_LoadMatrixf 291
#define __GL_TAB_LoadMatrixd 292
#define __GL_TAB_MatrixMode 293
#define __GL_TAB_MultMatrixf 294
#define __GL_TAB_MultMatrixd 295
#define __GL_TAB_Ortho 296
#define __GL_TAB_PopMatrix 297
#define __GL_TAB_PushMatrix 298
#define __GL_TAB_Rotated 299
#define __GL_TAB_Rotatef 300
#define __GL_TAB_Scaled 301
#define __GL_TAB_Scalef 302
#define __GL_TAB_Translated 303
#define __GL_TAB_Translatef 304
#define __GL_TAB_Viewport 305
#define __GL_TAB_ArrayElement 306
#define __GL_TAB_ColorPointer 307
#define __GL_TAB_DisableClientState 308
#define __GL_TAB_DrawArrays 309
#define __GL_TAB_DrawElements 310
#define __GL_TAB_EdgeFlagPointer 311
#define __GL_TAB_EnableClientState 312
#define __GL_TAB_GetPointerv 313
#define __GL_TAB_IndexPointer 314
#define __GL_TAB_InterleavedArrays 315
#define __GL_TAB_NormalPointer 316
#define __GL_TAB_TexCoordPointer 317
#define __GL_TAB_VertexPointer 318
#define __GL_TAB_PolygonOffset 319
#define __GL_TAB_CopyTexImage1D 320
#define __GL_TAB_CopyTexImage2D 321
#define __GL_TAB_CopyTexSubImage1D 322
#define __GL_TAB_CopyTexSubImage2D 323
#define __GL_TAB_TexSubImage1D 324
#define __GL_TAB_TexSubImage2D 325
#define __GL_TAB_AreTexturesResident 326
#define __GL_TAB_BindTexture 327
#define __GL_TAB_DeleteTextures 328
#define __GL_TAB_GenTextures 329
#define __GL_TAB_IsTexture 330
#define __GL_TAB_PrioritizeTextures 331
#define __GL_TAB_Indexub 332
#define __GL_TAB_Indexubv 333
#define __GL_TAB_PopClientAttrib 334
#define __GL_TAB_PushClientAttrib 335
#define __GL_TAB_SIZE (336*SZPTR)
#define __GL_TAB_ENTRIES 336

#define __GL_EXTTAB_ArrayElementEXT 0
#define __GL_EXTTAB_ColorPointerEXT 1
#define __GL_EXTTAB_DrawArraysEXT 2
#define __GL_EXTTAB_EdgeFlagPointerEXT 3
#define __GL_EXTTAB_GetPointervEXT 4
#define __GL_EXTTAB_IndexPointerEXT 5
#define __GL_EXTTAB_NormalPointerEXT 6
#define __GL_EXTTAB_TexCoordPointerEXT 7
#define __GL_EXTTAB_VertexPointerEXT 8
#define __GL_EXTTAB_ColorSubTableEXT 9
#define __GL_EXTTAB_ColorTableEXT 10
#define __GL_EXTTAB_CopyColorTableEXT 11
#define __GL_EXTTAB_GetColorTableEXT 12
#define __GL_EXTTAB_GetColorTableParameterfvEXT 13
#define __GL_EXTTAB_GetColorTableParameterivEXT 14
#define __GL_EXTTAB_LockArraysSGI 15
#define __GL_EXTTAB_UnlockArraysSGI 16
#define __GL_EXTTAB_CullParameterdvSGI 17
#define __GL_EXTTAB_CullParameterfvSGI 18
#define __GL_EXTTAB_IndexFuncSGI 19
#define __GL_EXTTAB_IndexMaterialSGI 20
#define __GL_EXTTAB_AddSwapHintRectWIN 21
#define __GL_EXTTAB_SIZE (22*SZPTR)
#define __GL_EXTTAB_ENTRIES 22

#if SZPTR == 8
#define __GL_DISPATCHSTATE_SIZE (358*SZPTR+8)
#else
#define __GL_DISPATCHSTATE_SIZE (358*SZPTR+8)
#endif
#if defined(_LANGUAGE_C) || defined(__cplusplus)
struct __GLdispatchTableRec {
    void (APIENTRY*NewList)(GLuint, GLenum);
    void (APIENTRY*EndList)(void);
    void (APIENTRY*CallList)(GLuint);
    void (APIENTRY*CallLists)(GLsizei, GLenum, const GLvoid *);
    void (APIENTRY*DeleteLists)(GLuint, GLsizei);
    GLuint (APIENTRY*GenLists)(GLsizei);
    void (APIENTRY*ListBase)(GLuint);
    void (APIENTRY*Begin)(GLenum);
    void (APIENTRY*Bitmap)(GLsizei, GLsizei, GLfloat, GLfloat, GLfloat, GLfloat, const GLubyte *);
    void (APIENTRY*Color3b)(GLbyte, GLbyte, GLbyte);
    void (APIENTRY*Color3bv)(const GLbyte *);
    void (APIENTRY*Color3d)(GLdouble, GLdouble, GLdouble);
    void (APIENTRY*Color3dv)(const GLdouble *);
    void (APIENTRY*Color3f)(GLfloat, GLfloat, GLfloat);
    void (APIENTRY*Color3fv)(const GLfloat *);
    void (APIENTRY*Color3i)(GLint, GLint, GLint);
    void (APIENTRY*Color3iv)(const GLint *);
    void (APIENTRY*Color3s)(GLshort, GLshort, GLshort);
    void (APIENTRY*Color3sv)(const GLshort *);
    void (APIENTRY*Color3ub)(GLubyte, GLubyte, GLubyte);
    void (APIENTRY*Color3ubv)(const GLubyte *);
    void (APIENTRY*Color3ui)(GLuint, GLuint, GLuint);
    void (APIENTRY*Color3uiv)(const GLuint *);
    void (APIENTRY*Color3us)(GLushort, GLushort, GLushort);
    void (APIENTRY*Color3usv)(const GLushort *);
    void (APIENTRY*Color4b)(GLbyte, GLbyte, GLbyte, GLbyte);
    void (APIENTRY*Color4bv)(const GLbyte *);
    void (APIENTRY*Color4d)(GLdouble, GLdouble, GLdouble, GLdouble);
    void (APIENTRY*Color4dv)(const GLdouble *);
    void (APIENTRY*Color4f)(GLfloat, GLfloat, GLfloat, GLfloat);
    void (APIENTRY*Color4fv)(const GLfloat *);
    void (APIENTRY*Color4i)(GLint, GLint, GLint, GLint);
    void (APIENTRY*Color4iv)(const GLint *);
    void (APIENTRY*Color4s)(GLshort, GLshort, GLshort, GLshort);
    void (APIENTRY*Color4sv)(const GLshort *);
    void (APIENTRY*Color4ub)(GLubyte, GLubyte, GLubyte, GLubyte);
    void (APIENTRY*Color4ubv)(const GLubyte *);
    void (APIENTRY*Color4ui)(GLuint, GLuint, GLuint, GLuint);
    void (APIENTRY*Color4uiv)(const GLuint *);
    void (APIENTRY*Color4us)(GLushort, GLushort, GLushort, GLushort);
    void (APIENTRY*Color4usv)(const GLushort *);
    void (APIENTRY*EdgeFlag)(GLboolean);
    void (APIENTRY*EdgeFlagv)(const GLboolean *);
    void (APIENTRY*End)(void);
    void (APIENTRY*Indexd)(GLdouble);
    void (APIENTRY*Indexdv)(const GLdouble *);
    void (APIENTRY*Indexf)(GLfloat);
    void (APIENTRY*Indexfv)(const GLfloat *);
    void (APIENTRY*Indexi)(GLint);
    void (APIENTRY*Indexiv)(const GLint *);
    void (APIENTRY*Indexs)(GLshort);
    void (APIENTRY*Indexsv)(const GLshort *);
    void (APIENTRY*Normal3b)(GLbyte, GLbyte, GLbyte);
    void (APIENTRY*Normal3bv)(const GLbyte *);
    void (APIENTRY*Normal3d)(GLdouble, GLdouble, GLdouble);
    void (APIENTRY*Normal3dv)(const GLdouble *);
    void (APIENTRY*Normal3f)(GLfloat, GLfloat, GLfloat);
    void (APIENTRY*Normal3fv)(const GLfloat *);
    void (APIENTRY*Normal3i)(GLint, GLint, GLint);
    void (APIENTRY*Normal3iv)(const GLint *);
    void (APIENTRY*Normal3s)(GLshort, GLshort, GLshort);
    void (APIENTRY*Normal3sv)(const GLshort *);
    void (APIENTRY*RasterPos2d)(GLdouble, GLdouble);
    void (APIENTRY*RasterPos2dv)(const GLdouble *);
    void (APIENTRY*RasterPos2f)(GLfloat, GLfloat);
    void (APIENTRY*RasterPos2fv)(const GLfloat *);
    void (APIENTRY*RasterPos2i)(GLint, GLint);
    void (APIENTRY*RasterPos2iv)(const GLint *);
    void (APIENTRY*RasterPos2s)(GLshort, GLshort);
    void (APIENTRY*RasterPos2sv)(const GLshort *);
    void (APIENTRY*RasterPos3d)(GLdouble, GLdouble, GLdouble);
    void (APIENTRY*RasterPos3dv)(const GLdouble *);
    void (APIENTRY*RasterPos3f)(GLfloat, GLfloat, GLfloat);
    void (APIENTRY*RasterPos3fv)(const GLfloat *);
    void (APIENTRY*RasterPos3i)(GLint, GLint, GLint);
    void (APIENTRY*RasterPos3iv)(const GLint *);
    void (APIENTRY*RasterPos3s)(GLshort, GLshort, GLshort);
    void (APIENTRY*RasterPos3sv)(const GLshort *);
    void (APIENTRY*RasterPos4d)(GLdouble, GLdouble, GLdouble, GLdouble);
    void (APIENTRY*RasterPos4dv)(const GLdouble *);
    void (APIENTRY*RasterPos4f)(GLfloat, GLfloat, GLfloat, GLfloat);
    void (APIENTRY*RasterPos4fv)(const GLfloat *);
    void (APIENTRY*RasterPos4i)(GLint, GLint, GLint, GLint);
    void (APIENTRY*RasterPos4iv)(const GLint *);
    void (APIENTRY*RasterPos4s)(GLshort, GLshort, GLshort, GLshort);
    void (APIENTRY*RasterPos4sv)(const GLshort *);
    void (APIENTRY*Rectd)(GLdouble, GLdouble, GLdouble, GLdouble);
    void (APIENTRY*Rectdv)(const GLdouble *, const GLdouble *);
    void (APIENTRY*Rectf)(GLfloat, GLfloat, GLfloat, GLfloat);
    void (APIENTRY*Rectfv)(const GLfloat *, const GLfloat *);
    void (APIENTRY*Recti)(GLint, GLint, GLint, GLint);
    void (APIENTRY*Rectiv)(const GLint *, const GLint *);
    void (APIENTRY*Rects)(GLshort, GLshort, GLshort, GLshort);
    void (APIENTRY*Rectsv)(const GLshort *, const GLshort *);
    void (APIENTRY*TexCoord1d)(GLdouble);
    void (APIENTRY*TexCoord1dv)(const GLdouble *);
    void (APIENTRY*TexCoord1f)(GLfloat);
    void (APIENTRY*TexCoord1fv)(const GLfloat *);
    void (APIENTRY*TexCoord1i)(GLint);
    void (APIENTRY*TexCoord1iv)(const GLint *);
    void (APIENTRY*TexCoord1s)(GLshort);
    void (APIENTRY*TexCoord1sv)(const GLshort *);
    void (APIENTRY*TexCoord2d)(GLdouble, GLdouble);
    void (APIENTRY*TexCoord2dv)(const GLdouble *);
    void (APIENTRY*TexCoord2f)(GLfloat, GLfloat);
    void (APIENTRY*TexCoord2fv)(const GLfloat *);
    void (APIENTRY*TexCoord2i)(GLint, GLint);
    void (APIENTRY*TexCoord2iv)(const GLint *);
    void (APIENTRY*TexCoord2s)(GLshort, GLshort);
    void (APIENTRY*TexCoord2sv)(const GLshort *);
    void (APIENTRY*TexCoord3d)(GLdouble, GLdouble, GLdouble);
    void (APIENTRY*TexCoord3dv)(const GLdouble *);
    void (APIENTRY*TexCoord3f)(GLfloat, GLfloat, GLfloat);
    void (APIENTRY*TexCoord3fv)(const GLfloat *);
    void (APIENTRY*TexCoord3i)(GLint, GLint, GLint);
    void (APIENTRY*TexCoord3iv)(const GLint *);
    void (APIENTRY*TexCoord3s)(GLshort, GLshort, GLshort);
    void (APIENTRY*TexCoord3sv)(const GLshort *);
    void (APIENTRY*TexCoord4d)(GLdouble, GLdouble, GLdouble, GLdouble);
    void (APIENTRY*TexCoord4dv)(const GLdouble *);
    void (APIENTRY*TexCoord4f)(GLfloat, GLfloat, GLfloat, GLfloat);
    void (APIENTRY*TexCoord4fv)(const GLfloat *);
    void (APIENTRY*TexCoord4i)(GLint, GLint, GLint, GLint);
    void (APIENTRY*TexCoord4iv)(const GLint *);
    void (APIENTRY*TexCoord4s)(GLshort, GLshort, GLshort, GLshort);
    void (APIENTRY*TexCoord4sv)(const GLshort *);
    void (APIENTRY*Vertex2d)(GLdouble, GLdouble);
    void (APIENTRY*Vertex2dv)(const GLdouble *);
    void (APIENTRY*Vertex2f)(GLfloat, GLfloat);
    void (APIENTRY*Vertex2fv)(const GLfloat *);
    void (APIENTRY*Vertex2i)(GLint, GLint);
    void (APIENTRY*Vertex2iv)(const GLint *);
    void (APIENTRY*Vertex2s)(GLshort, GLshort);
    void (APIENTRY*Vertex2sv)(const GLshort *);
    void (APIENTRY*Vertex3d)(GLdouble, GLdouble, GLdouble);
    void (APIENTRY*Vertex3dv)(const GLdouble *);
    void (APIENTRY*Vertex3f)(GLfloat, GLfloat, GLfloat);
    void (APIENTRY*Vertex3fv)(const GLfloat *);
    void (APIENTRY*Vertex3i)(GLint, GLint, GLint);
    void (APIENTRY*Vertex3iv)(const GLint *);
    void (APIENTRY*Vertex3s)(GLshort, GLshort, GLshort);
    void (APIENTRY*Vertex3sv)(const GLshort *);
    void (APIENTRY*Vertex4d)(GLdouble, GLdouble, GLdouble, GLdouble);
    void (APIENTRY*Vertex4dv)(const GLdouble *);
    void (APIENTRY*Vertex4f)(GLfloat, GLfloat, GLfloat, GLfloat);
    void (APIENTRY*Vertex4fv)(const GLfloat *);
    void (APIENTRY*Vertex4i)(GLint, GLint, GLint, GLint);
    void (APIENTRY*Vertex4iv)(const GLint *);
    void (APIENTRY*Vertex4s)(GLshort, GLshort, GLshort, GLshort);
    void (APIENTRY*Vertex4sv)(const GLshort *);
    void (APIENTRY*ClipPlane)(GLenum, const GLdouble *);
    void (APIENTRY*ColorMaterial)(GLenum, GLenum);
    void (APIENTRY*CullFace)(GLenum);
    void (APIENTRY*Fogf)(GLenum, GLfloat);
    void (APIENTRY*Fogfv)(GLenum, const GLfloat *);
    void (APIENTRY*Fogi)(GLenum, GLint);
    void (APIENTRY*Fogiv)(GLenum, const GLint *);
    void (APIENTRY*FrontFace)(GLenum);
    void (APIENTRY*Hint)(GLenum, GLenum);
    void (APIENTRY*Lightf)(GLenum, GLenum, GLfloat);
    void (APIENTRY*Lightfv)(GLenum, GLenum, const GLfloat *);
    void (APIENTRY*Lighti)(GLenum, GLenum, GLint);
    void (APIENTRY*Lightiv)(GLenum, GLenum, const GLint *);
    void (APIENTRY*LightModelf)(GLenum, GLfloat);
    void (APIENTRY*LightModelfv)(GLenum, const GLfloat *);
    void (APIENTRY*LightModeli)(GLenum, GLint);
    void (APIENTRY*LightModeliv)(GLenum, const GLint *);
    void (APIENTRY*LineStipple)(GLint, GLushort);
    void (APIENTRY*LineWidth)(GLfloat);
    void (APIENTRY*Materialf)(GLenum, GLenum, GLfloat);
    void (APIENTRY*Materialfv)(GLenum, GLenum, const GLfloat *);
    void (APIENTRY*Materiali)(GLenum, GLenum, GLint);
    void (APIENTRY*Materialiv)(GLenum, GLenum, const GLint *);
    void (APIENTRY*PointSize)(GLfloat);
    void (APIENTRY*PolygonMode)(GLenum, GLenum);
    void (APIENTRY*PolygonStipple)(const GLubyte *);
    void (APIENTRY*Scissor)(GLint, GLint, GLsizei, GLsizei);
    void (APIENTRY*ShadeModel)(GLenum);
    void (APIENTRY*TexParameterf)(GLenum, GLenum, GLfloat);
    void (APIENTRY*TexParameterfv)(GLenum, GLenum, const GLfloat *);
    void (APIENTRY*TexParameteri)(GLenum, GLenum, GLint);
    void (APIENTRY*TexParameteriv)(GLenum, GLenum, const GLint *);
    void (APIENTRY*TexImage1D)(GLenum, GLint, GLint, GLsizei, GLint, GLenum, GLenum, const GLvoid *);
    void (APIENTRY*TexImage2D)(GLenum, GLint, GLint, GLsizei, GLsizei, GLint, GLenum, GLenum, const GLvoid *);
    void (APIENTRY*TexEnvf)(GLenum, GLenum, GLfloat);
    void (APIENTRY*TexEnvfv)(GLenum, GLenum, const GLfloat *);
    void (APIENTRY*TexEnvi)(GLenum, GLenum, GLint);
    void (APIENTRY*TexEnviv)(GLenum, GLenum, const GLint *);
    void (APIENTRY*TexGend)(GLenum, GLenum, GLdouble);
    void (APIENTRY*TexGendv)(GLenum, GLenum, const GLdouble *);
    void (APIENTRY*TexGenf)(GLenum, GLenum, GLfloat);
    void (APIENTRY*TexGenfv)(GLenum, GLenum, const GLfloat *);
    void (APIENTRY*TexGeni)(GLenum, GLenum, GLint);
    void (APIENTRY*TexGeniv)(GLenum, GLenum, const GLint *);
    void (APIENTRY*FeedbackBuffer)(GLsizei, GLenum, GLfloat *);
    void (APIENTRY*SelectBuffer)(GLsizei, GLuint *);
    GLint (APIENTRY*RenderMode)(GLenum);
    void (APIENTRY*InitNames)(void);
    void (APIENTRY*LoadName)(GLuint);
    void (APIENTRY*PassThrough)(GLfloat);
    void (APIENTRY*PopName)(void);
    void (APIENTRY*PushName)(GLuint);
    void (APIENTRY*DrawBuffer)(GLenum);
    void (APIENTRY*Clear)(GLbitfield);
    void (APIENTRY*ClearAccum)(GLfloat, GLfloat, GLfloat, GLfloat);
    void (APIENTRY*ClearIndex)(GLfloat);
    void (APIENTRY*ClearColor)(GLclampf, GLclampf, GLclampf, GLclampf);
    void (APIENTRY*ClearStencil)(GLint);
    void (APIENTRY*ClearDepth)(GLclampd);
    void (APIENTRY*StencilMask)(GLuint);
    void (APIENTRY*ColorMask)(GLboolean, GLboolean, GLboolean, GLboolean);
    void (APIENTRY*DepthMask)(GLboolean);
    void (APIENTRY*IndexMask)(GLuint);
    void (APIENTRY*Accum)(GLenum, GLfloat);
    void (APIENTRY*Disable)(GLenum);
    void (APIENTRY*Enable)(GLenum);
    void (APIENTRY*Finish)(void);
    void (APIENTRY*Flush)(void);
    void (APIENTRY*PopAttrib)(void);
    void (APIENTRY*PushAttrib)(GLbitfield);
    void (APIENTRY*Map1d)(GLenum, GLdouble, GLdouble, GLint, GLint, const GLdouble *);
    void (APIENTRY*Map1f)(GLenum, GLfloat, GLfloat, GLint, GLint, const GLfloat *);
    void (APIENTRY*Map2d)(GLenum, GLdouble, GLdouble, GLint, GLint, GLdouble, GLdouble, GLint, GLint, const GLdouble *);
    void (APIENTRY*Map2f)(GLenum, GLfloat, GLfloat, GLint, GLint, GLfloat, GLfloat, GLint, GLint, const GLfloat *);
    void (APIENTRY*MapGrid1d)(GLint, GLdouble, GLdouble);
    void (APIENTRY*MapGrid1f)(GLint, GLfloat, GLfloat);
    void (APIENTRY*MapGrid2d)(GLint, GLdouble, GLdouble, GLint, GLdouble, GLdouble);
    void (APIENTRY*MapGrid2f)(GLint, GLfloat, GLfloat, GLint, GLfloat, GLfloat);
    void (APIENTRY*EvalCoord1d)(GLdouble);
    void (APIENTRY*EvalCoord1dv)(const GLdouble *);
    void (APIENTRY*EvalCoord1f)(GLfloat);
    void (APIENTRY*EvalCoord1fv)(const GLfloat *);
    void (APIENTRY*EvalCoord2d)(GLdouble, GLdouble);
    void (APIENTRY*EvalCoord2dv)(const GLdouble *);
    void (APIENTRY*EvalCoord2f)(GLfloat, GLfloat);
    void (APIENTRY*EvalCoord2fv)(const GLfloat *);
    void (APIENTRY*EvalMesh1)(GLenum, GLint, GLint);
    void (APIENTRY*EvalPoint1)(GLint);
    void (APIENTRY*EvalMesh2)(GLenum, GLint, GLint, GLint, GLint);
    void (APIENTRY*EvalPoint2)(GLint, GLint);
    void (APIENTRY*AlphaFunc)(GLenum, GLclampf);
    void (APIENTRY*BlendFunc)(GLenum, GLenum);
    void (APIENTRY*LogicOp)(GLenum);
    void (APIENTRY*StencilFunc)(GLenum, GLint, GLuint);
    void (APIENTRY*StencilOp)(GLenum, GLenum, GLenum);
    void (APIENTRY*DepthFunc)(GLenum);
    void (APIENTRY*PixelZoom)(GLfloat, GLfloat);
    void (APIENTRY*PixelTransferf)(GLenum, GLfloat);
    void (APIENTRY*PixelTransferi)(GLenum, GLint);
    void (APIENTRY*PixelStoref)(GLenum, GLfloat);
    void (APIENTRY*PixelStorei)(GLenum, GLint);
    void (APIENTRY*PixelMapfv)(GLenum, GLint, const GLfloat *);
    void (APIENTRY*PixelMapuiv)(GLenum, GLint, const GLuint *);
    void (APIENTRY*PixelMapusv)(GLenum, GLint, const GLushort *);
    void (APIENTRY*ReadBuffer)(GLenum);
    void (APIENTRY*CopyPixels)(GLint, GLint, GLsizei, GLsizei, GLenum);
    void (APIENTRY*ReadPixels)(GLint, GLint, GLsizei, GLsizei, GLenum, GLenum, GLvoid *);
    void (APIENTRY*DrawPixels)(GLsizei, GLsizei, GLenum, GLenum, const GLvoid *);
    void (APIENTRY*GetBooleanv)(GLenum, GLboolean *);
    void (APIENTRY*GetClipPlane)(GLenum, GLdouble *);
    void (APIENTRY*GetDoublev)(GLenum, GLdouble *);
    GLenum (APIENTRY*GetError)(void);
    void (APIENTRY*GetFloatv)(GLenum, GLfloat *);
    void (APIENTRY*GetIntegerv)(GLenum, GLint *);
    void (APIENTRY*GetLightfv)(GLenum, GLenum, GLfloat *);
    void (APIENTRY*GetLightiv)(GLenum, GLenum, GLint *);
    void (APIENTRY*GetMapdv)(GLenum, GLenum, GLdouble *);
    void (APIENTRY*GetMapfv)(GLenum, GLenum, GLfloat *);
    void (APIENTRY*GetMapiv)(GLenum, GLenum, GLint *);
    void (APIENTRY*GetMaterialfv)(GLenum, GLenum, GLfloat *);
    void (APIENTRY*GetMaterialiv)(GLenum, GLenum, GLint *);
    void (APIENTRY*GetPixelMapfv)(GLenum, GLfloat *);
    void (APIENTRY*GetPixelMapuiv)(GLenum, GLuint *);
    void (APIENTRY*GetPixelMapusv)(GLenum, GLushort *);
    void (APIENTRY*GetPolygonStipple)(GLubyte *);
    const GLubyte * (APIENTRY*GetString)(GLenum);
    void (APIENTRY*GetTexEnvfv)(GLenum, GLenum, GLfloat *);
    void (APIENTRY*GetTexEnviv)(GLenum, GLenum, GLint *);
    void (APIENTRY*GetTexGendv)(GLenum, GLenum, GLdouble *);
    void (APIENTRY*GetTexGenfv)(GLenum, GLenum, GLfloat *);
    void (APIENTRY*GetTexGeniv)(GLenum, GLenum, GLint *);
    void (APIENTRY*GetTexImage)(GLenum, GLint, GLenum, GLenum, GLvoid *);
    void (APIENTRY*GetTexParameterfv)(GLenum, GLenum, GLfloat *);
    void (APIENTRY*GetTexParameteriv)(GLenum, GLenum, GLint *);
    void (APIENTRY*GetTexLevelParameterfv)(GLenum, GLint, GLenum, GLfloat *);
    void (APIENTRY*GetTexLevelParameteriv)(GLenum, GLint, GLenum, GLint *);
    GLboolean (APIENTRY*IsEnabled)(GLenum);
    GLboolean (APIENTRY*IsList)(GLuint);
    void (APIENTRY*DepthRange)(GLclampd, GLclampd);
    void (APIENTRY*Frustum)(GLdouble, GLdouble, GLdouble, GLdouble, GLdouble, GLdouble);
    void (APIENTRY*LoadIdentity)(void);
    void (APIENTRY*LoadMatrixf)(const GLfloat *);
    void (APIENTRY*LoadMatrixd)(const GLdouble *);
    void (APIENTRY*MatrixMode)(GLenum);
    void (APIENTRY*MultMatrixf)(const GLfloat *);
    void (APIENTRY*MultMatrixd)(const GLdouble *);
    void (APIENTRY*Ortho)(GLdouble, GLdouble, GLdouble, GLdouble, GLdouble, GLdouble);
    void (APIENTRY*PopMatrix)(void);
    void (APIENTRY*PushMatrix)(void);
    void (APIENTRY*Rotated)(GLdouble, GLdouble, GLdouble, GLdouble);
    void (APIENTRY*Rotatef)(GLfloat, GLfloat, GLfloat, GLfloat);
    void (APIENTRY*Scaled)(GLdouble, GLdouble, GLdouble);
    void (APIENTRY*Scalef)(GLfloat, GLfloat, GLfloat);
    void (APIENTRY*Translated)(GLdouble, GLdouble, GLdouble);
    void (APIENTRY*Translatef)(GLfloat, GLfloat, GLfloat);
    void (APIENTRY*Viewport)(GLint, GLint, GLsizei, GLsizei);
    void (APIENTRY*ArrayElement)(GLint);
    void (APIENTRY*ColorPointer)(GLint, GLenum, GLsizei, const GLvoid *);
    void (APIENTRY*DisableClientState)(GLenum);
    void (APIENTRY*DrawArrays)(GLenum, GLint, GLsizei);
    void (APIENTRY*DrawElements)(GLenum, GLsizei, GLenum, const GLvoid *);
    void (APIENTRY*EdgeFlagPointer)(GLsizei, const GLboolean *);
    void (APIENTRY*EnableClientState)(GLenum);
    void (APIENTRY*GetPointerv)(GLenum, GLvoid* *);
    void (APIENTRY*IndexPointer)(GLenum, GLsizei, const GLvoid *);
    void (APIENTRY*InterleavedArrays)(GLenum, GLsizei, const GLvoid *);
    void (APIENTRY*NormalPointer)(GLenum, GLsizei, const GLvoid *);
    void (APIENTRY*TexCoordPointer)(GLint, GLenum, GLsizei, const GLvoid *);
    void (APIENTRY*VertexPointer)(GLint, GLenum, GLsizei, const GLvoid *);
    void (APIENTRY*PolygonOffset)(GLfloat, GLfloat);
    void (APIENTRY*CopyTexImage1D)(GLenum, GLint, GLenum, GLint, GLint, GLsizei, GLint);
    void (APIENTRY*CopyTexImage2D)(GLenum, GLint, GLenum, GLint, GLint, GLsizei, GLsizei, GLint);
    void (APIENTRY*CopyTexSubImage1D)(GLenum, GLint, GLint, GLint, GLint, GLsizei);
    void (APIENTRY*CopyTexSubImage2D)(GLenum, GLint, GLint, GLint, GLint, GLint, GLsizei, GLsizei);
    void (APIENTRY*TexSubImage1D)(GLenum, GLint, GLint, GLsizei, GLenum, GLenum, const GLvoid *);
    void (APIENTRY*TexSubImage2D)(GLenum, GLint, GLint, GLint, GLsizei, GLsizei, GLenum, GLenum, const GLvoid *);
    GLboolean (APIENTRY*AreTexturesResident)(GLsizei, const GLuint *, GLboolean *);
    void (APIENTRY*BindTexture)(GLenum, GLuint);
    void (APIENTRY*DeleteTextures)(GLsizei, const GLuint *);
    void (APIENTRY*GenTextures)(GLsizei, GLuint *);
    GLboolean (APIENTRY*IsTexture)(GLuint);
    void (APIENTRY*PrioritizeTextures)(GLsizei, const GLuint *, const GLclampf *);
    void (APIENTRY*Indexub)(GLubyte);
    void (APIENTRY*Indexubv)(const GLubyte *);
    void (APIENTRY*PopClientAttrib)(void);
    void (APIENTRY*PushClientAttrib)(GLbitfield);
};

struct __GLextensionsDispatchTableRec {
    void (APIENTRY*ArrayElementEXT)(GLint);
    void (APIENTRY*ColorPointerEXT)(GLint, GLenum, GLsizei, GLsizei, const GLvoid *);
    void (APIENTRY*DrawArraysEXT)(GLenum, GLint, GLsizei);
    void (APIENTRY*EdgeFlagPointerEXT)(GLsizei, GLsizei, const GLboolean *);
    void (APIENTRY*GetPointervEXT)(GLenum, GLvoid* *);
    void (APIENTRY*IndexPointerEXT)(GLenum, GLsizei, GLsizei, const GLvoid *);
    void (APIENTRY*NormalPointerEXT)(GLenum, GLsizei, GLsizei, const GLvoid *);
    void (APIENTRY*TexCoordPointerEXT)(GLint, GLenum, GLsizei, GLsizei, const GLvoid *);
    void (APIENTRY*VertexPointerEXT)(GLint, GLenum, GLsizei, GLsizei, const GLvoid *);
    void (APIENTRY*ColorSubTableEXT)(GLenum, GLsizei, GLsizei, GLenum, GLenum, const GLvoid *);
    void (APIENTRY*ColorTableEXT)(GLenum, GLenum, GLsizei, GLenum, GLenum, const GLvoid *);
    void (APIENTRY*CopyColorTableEXT)(GLenum, GLenum, GLint, GLint, GLsizei);
    void (APIENTRY*GetColorTableEXT)(GLenum, GLenum, GLenum, GLvoid *);
    void (APIENTRY*GetColorTableParameterfvEXT)(GLenum, GLenum, GLfloat *);
    void (APIENTRY*GetColorTableParameterivEXT)(GLenum, GLenum, GLint *);
    void (APIENTRY*LockArraysSGI)(GLint, GLsizei);
    void (APIENTRY*UnlockArraysSGI)(void);
    void (APIENTRY*CullParameterdvSGI)(GLenum, GLdouble*);
    void (APIENTRY*CullParameterfvSGI)(GLenum, GLfloat*);
    void (APIENTRY*IndexFuncSGI)(GLenum, GLclampf);
    void (APIENTRY*IndexMaterialSGI)(GLenum, GLenum);
    void (APIENTRY*AddSwapHintRectWIN)(GLint, GLint, GLsizei, GLsizei);
};



typedef struct __GLdispatchTableRec __GLdispatchTable;
typedef struct __GLextensionsDispatchTableRec __GLextensionsDispatchTable;

struct __GLdispatchStateRec {
    int nEntries;
    __GLdispatchTable dispatch;
    __GLextensionsDispatchTable extensions;
    double align;
};

#endif /* _LANGUAGE_C || __cplusplus */

#endif /* __GL_ICD */

#endif /* __g_disp_h_ */
