/* DO NOT EDIT - THIS FILE IS AUTOMATICALLY GENERATED */
#ifndef __g_disp_icd_h_
#define __g_disp_icd_h_

/*
** Copyright 1992-1997 Silicon Graphics, Inc.
** All Rights Reserved.
**
** This is UNPUBLISHED PROPRIETARY SOURCE CODE of Silicon Graphics, Inc.;
** the contents of this file may not be disclosed to third parties, copied or
** duplicated in any form, in whole or in part, without the prior written
** permission of Silicon Graphics, Inc.
**
** RESTRICTED RIGHTS LEGEND:
** Use, duplication or disclosure by the Government is subject to restrictions
** as set forth in subdivision (c)(1)(ii) of the Rights in Technical Data
** and Computer Software clause at DFARS 252.227-7013, and/or in similar or
** successor clauses in the FAR, DOD or NASA FAR Supplement. Unpublished -
** rights reserved under the Copyright Laws of the United States.
*/

#define __GL_EXTTAB_ArrayElementEXT 0
#define __GL_EXTTAB_ColorPointerEXT 1
#define __GL_EXTTAB_DrawArraysEXT 2
#define __GL_EXTTAB_EdgeFlagPointerEXT 3
#define __GL_EXTTAB_GetPointervEXT 4
#define __GL_EXTTAB_IndexPointerEXT 5
#define __GL_EXTTAB_NormalPointerEXT 6
#define __GL_EXTTAB_TexCoordPointerEXT 7
#define __GL_EXTTAB_VertexPointerEXT 8
#define __GL_EXTTAB_ColorSubTableEXT 9
#define __GL_EXTTAB_ColorTableEXT 10
#define __GL_EXTTAB_CopyColorTableEXT 11
#define __GL_EXTTAB_GetColorTableEXT 12
#define __GL_EXTTAB_GetColorTableParameterfvEXT 13
#define __GL_EXTTAB_GetColorTableParameterivEXT 14
#define __GL_EXTTAB_LockArraysSGI 15
#define __GL_EXTTAB_UnlockArraysSGI 16
#define __GL_EXTTAB_CullParameterdvSGI 17
#define __GL_EXTTAB_CullParameterfvSGI 18
#define __GL_EXTTAB_IndexFuncSGI 19
#define __GL_EXTTAB_IndexMaterialSGI 20
#define __GL_EXTTAB_AddSwapHintRectWIN 21
#define __GL_EXTTAB_SIZE (22*SZPTR)
#define __GL_EXTTAB_ENTRIES 22

#if defined(_LANGUAGE_C) || defined(__cplusplus)
struct __GLextensionsDispatchTableRec {
    void (APIENTRY*ArrayElementEXT)(GLint);
    void (APIENTRY*ColorPointerEXT)(GLint, GLenum, GLsizei, GLsizei, const GLvoid *);
    void (APIENTRY*DrawArraysEXT)(GLenum, GLint, GLsizei);
    void (APIENTRY*EdgeFlagPointerEXT)(GLsizei, GLsizei, const GLboolean *);
    void (APIENTRY*GetPointervEXT)(GLenum, GLvoid* *);
    void (APIENTRY*IndexPointerEXT)(GLenum, GLsizei, GLsizei, const GLvoid *);
    void (APIENTRY*NormalPointerEXT)(GLenum, GLsizei, GLsizei, const GLvoid *);
    void (APIENTRY*TexCoordPointerEXT)(GLint, GLenum, GLsizei, GLsizei, const GLvoid *);
    void (APIENTRY*VertexPointerEXT)(GLint, GLenum, GLsizei, GLsizei, const GLvoid *);
    void (APIENTRY*ColorSubTableEXT)(GLenum, GLsizei, GLsizei, GLenum, GLenum, const GLvoid *);
    void (APIENTRY*ColorTableEXT)(GLenum, GLenum, GLsizei, GLenum, GLenum, const GLvoid *);
    void (APIENTRY*CopyColorTableEXT)(GLenum, GLenum, GLint, GLint, GLsizei);
    void (APIENTRY*GetColorTableEXT)(GLenum, GLenum, GLenum, GLvoid *);
    void (APIENTRY*GetColorTableParameterfvEXT)(GLenum, GLenum, GLfloat *);
    void (APIENTRY*GetColorTableParameterivEXT)(GLenum, GLenum, GLint *);
    void (APIENTRY*LockArraysSGI)(GLint, GLsizei);
    void (APIENTRY*UnlockArraysSGI)(void);
    void (APIENTRY*CullParameterdvSGI)(GLenum, GLdouble*);
    void (APIENTRY*CullParameterfvSGI)(GLenum, GLfloat*);
    void (APIENTRY*IndexFuncSGI)(GLenum, GLclampf);
    void (APIENTRY*IndexMaterialSGI)(GLenum, GLenum);
    void (APIENTRY*AddSwapHintRectWIN)(GLint, GLint, GLsizei, GLsizei);
};


#include "g_disp_dt.h"


typedef struct __GLdispatchTableRec __GLdispatchTable;
typedef struct __GLextensionsDispatchTableRec __GLextensionsDispatchTable;

struct __GLdispatchStateRec {
    int nEntries;
    __GLdispatchTable dispatch;
    __GLextensionsDispatchTable extensions;
    double align;
};

#endif /* _LANGUAGE_C || __cplusplus */

#endif /* __g_disp_icd_h_ */
