##
##  Makefile for Windows NT
##


!include <ntwin32.mak>

#GLUTHOME = ../../lib/glut
CFLAGS   = -I$(GLUTHOME) -DWIN32 -nologo -W1 -Z7
LIBS     = $(GLUTHOME)/glut.lib glu32.lib opengl32.lib $(guilibs) \
           -nologo -nodefaultlib:libcd -debug


EXES     = accanti.exe anti.exe bezmesh.exe checker.exe depthcue.exe dof.exe \
           fog.exe fogindex.exe material.exe mipmap.exe nurbs.exe \
           pickdepth.exe plane.exe polys.exe sccolorlight.exe scene.exe \
           scenebamb.exe sceneflat.exe stencil.exe stroke.exe surface.exe \
           teaambient.exe teapots.exe texturesurf.exe

all             : $(EXES)


.c.exe:
	$(CC) $(CFLAGS) -c $<
        $(link) -out:$@ $*.obj $(LIBS)

clean:
	rm -f $(EXES) *.obj *.pdb *.ilk *.vtp *.tpl *.ncb
