#
# This is the list of tests we've been using to generate images from.
#
# Feed this to runner.exe, or copy it to a .bat file to run.
#

set ARGS= -res 512x384 -wid 200 -hei 200 -orig ul

# self checking tests
state\color-combine %ARGS
state\alpha-combine %ARGS
state\depth-wbuffer-sc %ARGS
state\depth-zbuffer-sc %ARGS
state\depth-wbias %ARGS
state\depth-zbias %ARGS
state\lfb -cf ARGB  %ARGS
raster\ras-tri  %ARGS
raster\ras-tri-2  %ARGS
raster\ras-tri-2 -wc  %ARGS
# raster\ras-tri -aa  %ARGS                 # -aa self checking not yet supported
# raster\ras-tri -cw  %ARGS                 # -cw self-checking not yet supported
# raster\ras-tri -aa -cw  %ARGS
# raster\ras-tri-2 -aa  %ARGS
# raster\ras-tri-2 -cw  %ARGS
# raster\ras-tri-2 -aa -cw  %ARGS
# raster\ras-tri-2 -wc -aa  %ARGS
# raster\ras-tri-2 -wc -cw  %ARGS
# raster\ras-tri-2 -wc -aa -cw  %ARGS
raster\ras-line  %ARGS
# raster\ras-line -aa  %ARGS
# raster\ras-line -cw  %ARGS
# raster\ras-line -cw -aa  %ARGS
raster\ras-point   %ARGS
# raster\ras-point -aa  %ARGS
control\query %ARGS
control\query-state %ARGS%
state\lfb-region %ARGS

# image based tests
control\error-callback  %ARGS
control\simple-clear  %ARGS
control\clear  %ARGS
raster\simple-ras  %ARGS
raster\simple-ras -aa  %ARGS
raster\simple-ras -wc  %ARGS
raster\simple-ras -wc -aa  %ARGS
interp\simple-interp-alpha  %ARGS
interp\simple-interp-depth  %ARGS
interp\simple-interp-depth -z  %ARGS
interp\simple-interp-rgb  %ARGS
interp\simple-interp-rgb -aa  %ARGS
interp\simple-interp-tex  %ARGS
interp\simple-interp-tex -aa  %ARGS
interp\simple-interp-tex -wc  %ARGS
interp\simple-interp-tex -wc -aa  %ARGS
raster\ras-va -mode points  %ARGS
raster\ras-va -mode points -aa  %ARGS
raster\ras-va -mode points -cw  %ARGS
raster\ras-va -mode points -aa -cw  %ARGS
raster\ras-va -mode lines  %ARGS
raster\ras-va -mode lines -aa  %ARGS
raster\ras-va -mode lines -cw  %ARGS
raster\ras-va -mode lines -aa -cw  %ARGS
raster\ras-va -mode line_strip  %ARGS
raster\ras-va -mode line_strip -aa  %ARGS
raster\ras-va -mode line_strip -cw  %ARGS
raster\ras-va -mode line_strip -aa -cw  %ARGS
raster\ras-va -mode triangles  %ARGS
raster\ras-va -mode triangles -aa  %ARGS
raster\ras-va -mode triangles -cw  %ARGS
raster\ras-va -mode triangles -aa -cw  %ARGS
raster\ras-va -mode triangle_strip  %ARGS
raster\ras-va -mode triangle_strip -aa  %ARGS
raster\ras-va -mode triangle_strip -cw  %ARGS
raster\ras-va -mode triangle_strip -aa -cw  %ARGS
raster\ras-va -mode triangle_strip -wc  %ARGS
raster\ras-va -mode triangle_strip -wc -aa  %ARGS
raster\ras-va -mode triangle_strip -wc -cw  %ARGS
raster\ras-va -mode triangle_strip -wc -aa -cw  %ARGS
raster\ras-va -mode triangle_fan  %ARGS
raster\ras-va -mode triangle_fan -aa  %ARGS
raster\ras-va -mode triangle_fan -cw  %ARGS
raster\ras-va -mode triangle_fan -aa -cw  %ARGS
raster\ras-va -mode polygon  %ARGS
raster\ras-va -mode polygon -aa  %ARGS
raster\ras-va -mode polygon -cw  %ARGS
raster\ras-va -mode polygon -aa -cw  %ARGS
raster\ras-va -contig -mode points  %ARGS
raster\ras-va -contig -mode points -aa  %ARGS
raster\ras-va -contig -mode points -cw  %ARGS
raster\ras-va -contig -mode lines  %ARGS
raster\ras-va -contig -mode lines -aa  %ARGS
raster\ras-va -contig -mode lines -cw  %ARGS
raster\ras-va -contig -mode lines -aa -cw  %ARGS
raster\ras-va -contig -mode line_strip  %ARGS
raster\ras-va -contig -mode line_strip -aa  %ARGS
raster\ras-va -contig -mode line_strip -cw  %ARGS
raster\ras-va -contig -mode line_strip -aa -cw  %ARGS
raster\ras-va -contig -mode triangles  %ARGS
raster\ras-va -contig -mode triangles -aa  %ARGS
raster\ras-va -contig -mode triangles -cw  %ARGS
raster\ras-va -contig -mode triangles -aa -cw  %ARGS
raster\ras-va -contig -mode triangle_strip  %ARGS
raster\ras-va -contig -mode triangle_strip -aa  %ARGS
raster\ras-va -contig -mode triangle_strip -cw  %ARGS
raster\ras-va -contig -mode triangle_strip -aa -cw  %ARGS
raster\ras-va -contig -mode triangle_fan  %ARGS
raster\ras-va -contig -mode triangle_fan -aa  %ARGS
raster\ras-va -contig -mode triangle_fan -cw  %ARGS
raster\ras-va -contig -mode triangle_fan -aa -cw  %ARGS
raster\ras-va -contig -mode polygon  %ARGS
raster\ras-va -contig -mode polygon -aa  %ARGS
raster\ras-va -contig -mode polygon -cw  %ARGS
raster\ras-va -contig -mode polygon -aa -cw  %ARGS
raster\ras-va-cont -mode strip  %ARGS
raster\ras-va-cont -mode strip -aa  %ARGS
raster\ras-va-cont -mode strip -cw  %ARGS
raster\ras-va-cont -mode strip -aa -cw  %ARGS
raster\ras-va-cont -mode fan  %ARGS
raster\ras-va-cont -mode fan -aa  %ARGS
raster\ras-va-cont -mode fan -cw  %ARGS
raster\ras-va-cont -mode fan -aa -cw  %ARGS
raster\ras-va-cont -contig -mode strip  %ARGS
raster\ras-va-cont -contig -mode strip -aa  %ARGS
raster\ras-va-cont -contig -mode strip -cw  %ARGS
raster\ras-va-cont -contig -mode strip -aa -cw  %ARGS
raster\ras-va-cont -contig -mode fan  %ARGS
raster\ras-va-cont -contig -mode fan -aa  %ARGS
raster\ras-va-cont -contig -mode fan -cw  %ARGS
raster\ras-va-cont -contig -mode fan -aa -cw  %ARGS
texture\texture-lod   %ARGS
texture\texture-bias   %ARGS
texture\texture-load-mip  %ARGS
texture\texture-load-level  %ARGS
texture\texture-load-partial  %ARGS
texture\texture-load-format  %ARGS
texture\texture-load-palette  %ARGS
texture\texture-load-simple  %ARGS
texture\texture-load-multi  %ARGS
texture\texture-load-ncc.exe  %ARGS
texture\texture-interp  %ARGS
texture\texture-interp -atc  %ARGS
texture\texture-interp-large  %ARGS
texture\texture-interp-large -atc  %ARGS
texture\texture-interp-2tmu  %ARGS
texture\texture-interp-2tmu -atc  %ARGS
texture\texture-interp-2tmu -cw  %ARGS
texture\texture-interp-2tmu -cw -atc  %ARGS
texture\texture-interp-2tmu-large  %ARGS
texture\texture-interp-2tmu-large -atc  %ARGS
texture\texture-interp-3df  %ARGS
state\backface-cull  %ARGS
state\flex-coords  %ARGS
state\flex-coords -wc  %ARGS
state\flex-coords-depth-color  %ARGS
state\flex-coords-depth-color -z  %ARGS
state\flex-coords-depth-color -wc  %ARGS
state\flex-coords-depth-color -wc -z  %ARGS
state\flex-coords-texture  %ARGS
state\flex-coords-texture -2tmus  %ARGS
state\flex-coords-texture -wc  %ARGS
state\flex-coords-texture -wc -2tmus  %ARGS
state\flex-coords-texture-fog  %ARGS
state\flex-coords-texture-fog -2tmus  %ARGS
state\flex-coords-texture-fog -wc  %ARGS
state\flex-coords-texture-fog -wc -2tmus  %ARGS
state\color-constant  %ARGS
state\color-dither  %ARGS
state\color-chroma  %ARGS
state\fog  %ARGS
state\depth-wbuffer   %ARGS
state\depth-zbuffer   %ARGS
state\alpha-blend   %ARGS
state\alpha-buffer   %ARGS
state\alpha-test   %ARGS
state\alpha-funky   %ARGS
extensions\ext-chroma   %ARGS
extensions\ext-fogcoord   %ARGS
extensions\ext-palette   %ARGS
extensions\ext-tex-chroma   %ARGS
extensions\ext-texture-mirror   %ARGS
state\buffer-swap  %ARGS
state\disable-effects  %ARGS


