#
# This is the list of tests we've been using to generate images from.
#
# Feed this to runner.exe, or copy it to a .bat file to run.
#

set ARGS= -res 512x384 -wid 200 -hei 200 -orig ul

# self checking tests
color-combine %ARGS
alpha-combine %ARGS
depth-wbuffer-sc %ARGS
depth-zbuffer-sc %ARGS
depth-wbias %ARGS
depth-zbias %ARGS
lfb -cf ARGB  %ARGS
ras-tri  %ARGS
ras-tri-2  %ARGS
ras-tri-2 -wc  %ARGS
# ras-tri -aa  %ARGS                 # -aa self checking not yet supported
# ras-tri -cw  %ARGS                 # -cw self-checking not yet supported
# ras-tri -aa -cw  %ARGS
# ras-tri-2 -aa  %ARGS
# ras-tri-2 -cw  %ARGS
# ras-tri-2 -aa -cw  %ARGS
# ras-tri-2 -wc -aa  %ARGS
# ras-tri-2 -wc -cw  %ARGS
# ras-tri-2 -wc -aa -cw  %ARGS
ras-line  %ARGS
# ras-line -aa  %ARGS
# ras-line -cw  %ARGS
# ras-line -cw -aa  %ARGS
ras-point   %ARGS
# ras-point -aa  %ARGS
query %ARGS
query-state %ARGS%

# image based tests
error-callback  %ARGS
lfb-region -cf ARGB  %ARGS
simple-clear  %ARGS
clear  %ARGS
simple-ras  %ARGS
simple-ras -aa  %ARGS
simple-ras -wc  %ARGS
simple-ras -wc -aa  %ARGS
simple-interp-alpha  %ARGS
simple-interp-depth  %ARGS
simple-interp-depth -z  %ARGS
simple-interp-rgb  %ARGS
simple-interp-rgb -aa  %ARGS
simple-interp-tex  %ARGS
simple-interp-tex -aa  %ARGS
simple-interp-tex -wc  %ARGS
simple-interp-tex -wc -aa  %ARGS
ras-va -mode points  %ARGS
ras-va -mode points -aa  %ARGS
ras-va -mode points -cw  %ARGS
ras-va -mode points -aa -cw  %ARGS
ras-va -mode lines  %ARGS
ras-va -mode lines -aa  %ARGS
ras-va -mode lines -cw  %ARGS
ras-va -mode lines -aa -cw  %ARGS
ras-va -mode line_strip  %ARGS
ras-va -mode line_strip -aa  %ARGS
ras-va -mode line_strip -cw  %ARGS
ras-va -mode line_strip -aa -cw  %ARGS
ras-va -mode triangles  %ARGS
ras-va -mode triangles -aa  %ARGS
ras-va -mode triangles -cw  %ARGS
ras-va -mode triangles -aa -cw  %ARGS
ras-va -mode triangle_strip  %ARGS
ras-va -mode triangle_strip -aa  %ARGS
ras-va -mode triangle_strip -cw  %ARGS
ras-va -mode triangle_strip -aa -cw  %ARGS
ras-va -mode triangle_strip -wc  %ARGS
ras-va -mode triangle_strip -wc -aa  %ARGS
ras-va -mode triangle_strip -wc -cw  %ARGS
ras-va -mode triangle_strip -wc -aa -cw  %ARGS
ras-va -mode triangle_fan  %ARGS
ras-va -mode triangle_fan -aa  %ARGS
ras-va -mode triangle_fan -cw  %ARGS
ras-va -mode triangle_fan -aa -cw  %ARGS
ras-va -mode polygon  %ARGS
ras-va -mode polygon -aa  %ARGS
ras-va -mode polygon -cw  %ARGS
ras-va -mode polygon -aa -cw  %ARGS
ras-va -contig -mode points  %ARGS
ras-va -contig -mode points -aa  %ARGS
ras-va -contig -mode points -cw  %ARGS
ras-va -contig -mode lines  %ARGS
ras-va -contig -mode lines -aa  %ARGS
ras-va -contig -mode lines -cw  %ARGS
ras-va -contig -mode lines -aa -cw  %ARGS
ras-va -contig -mode line_strip  %ARGS
ras-va -contig -mode line_strip -aa  %ARGS
ras-va -contig -mode line_strip -cw  %ARGS
ras-va -contig -mode line_strip -aa -cw  %ARGS
ras-va -contig -mode triangles  %ARGS
ras-va -contig -mode triangles -aa  %ARGS
ras-va -contig -mode triangles -cw  %ARGS
ras-va -contig -mode triangles -aa -cw  %ARGS
ras-va -contig -mode triangle_strip  %ARGS
ras-va -contig -mode triangle_strip -aa  %ARGS
ras-va -contig -mode triangle_strip -cw  %ARGS
ras-va -contig -mode triangle_strip -aa -cw  %ARGS
ras-va -contig -mode triangle_fan  %ARGS
ras-va -contig -mode triangle_fan -aa  %ARGS
ras-va -contig -mode triangle_fan -cw  %ARGS
ras-va -contig -mode triangle_fan -aa -cw  %ARGS
ras-va -contig -mode polygon  %ARGS
ras-va -contig -mode polygon -aa  %ARGS
ras-va -contig -mode polygon -cw  %ARGS
ras-va -contig -mode polygon -aa -cw  %ARGS
ras-va-cont -mode strip  %ARGS
ras-va-cont -mode strip -aa  %ARGS
ras-va-cont -mode strip -cw  %ARGS
ras-va-cont -mode strip -aa -cw  %ARGS
ras-va-cont -mode fan  %ARGS
ras-va-cont -mode fan -aa  %ARGS
ras-va-cont -mode fan -cw  %ARGS
ras-va-cont -mode fan -aa -cw  %ARGS
ras-va-cont -contig -mode strip  %ARGS
ras-va-cont -contig -mode strip -aa  %ARGS
ras-va-cont -contig -mode strip -cw  %ARGS
ras-va-cont -contig -mode strip -aa -cw  %ARGS
ras-va-cont -contig -mode fan  %ARGS
ras-va-cont -contig -mode fan -aa  %ARGS
ras-va-cont -contig -mode fan -cw  %ARGS
ras-va-cont -contig -mode fan -aa -cw  %ARGS
texture-lod   %ARGS
texture-bias   %ARGS
texture-load-mip  %ARGS
texture-load-level  %ARGS
texture-load-partial  %ARGS
texture-load-format  %ARGS
texture-load-palette  %ARGS
texture-load-simple  %ARGS
texture-load-multi  %ARGS
texture-load-ncc.exe  %ARGS
texture-interp  %ARGS
texture-interp -atc  %ARGS
texture-interp-large  %ARGS
texture-interp-large -atc  %ARGS
texture-interp-2tmu  %ARGS
texture-interp-2tmu -atc  %ARGS
texture-interp-2tmu -cw  %ARGS
texture-interp-2tmu -cw -atc  %ARGS
texture-interp-2tmu-large  %ARGS
texture-interp-2tmu-large -atc  %ARGS
texture-interp-3df  %ARGS
backface-cull  %ARGS
flex-coords  %ARGS
flex-coords -wc  %ARGS
flex-coords-depth-color  %ARGS
flex-coords-depth-color -z  %ARGS
flex-coords-depth-color -wc  %ARGS
flex-coords-depth-color -wc -z  %ARGS
flex-coords-texture  %ARGS
flex-coords-texture -2tmus  %ARGS
flex-coords-texture -wc  %ARGS
flex-coords-texture -wc -2tmus  %ARGS
flex-coords-texture-fog  %ARGS
flex-coords-texture-fog -2tmus  %ARGS
flex-coords-texture-fog -wc  %ARGS
flex-coords-texture-fog -wc -2tmus  %ARGS
color-constant  %ARGS
color-dither  %ARGS
color-chroma  %ARGS
fog  %ARGS
depth-wbuffer   %ARGS
depth-zbuffer   %ARGS
alpha-blend   %ARGS
alpha-buffer   %ARGS
alpha-test   %ARGS
alpha-funky   %ARGS
ext-chroma   %ARGS
ext-fogcoord   %ARGS
ext-palette   %ARGS
ext-tex-chroma   %ARGS
ext-texture-mirror   %ARGS
buffer-swap  %ARGS
disable-effects  %ARGS


