#
# Copyright (c) 1998, 3Dfx Interactive, Inc.
# All Rights Reserved.
#
# This is UNPUBLISHED PROPRIETARY SOURCE CODE of 3Dfx Interactive, Inc.;
# the contents of this file may not be disclosed to third parties, copied or
# duplicated in any form, in whole or in part, without the prior written
# permission of 3Dfx Interactive, Inc.
#
# RESTRICTED RIGHTS LEGEND:
# Use, duplication or disclosure by the Government is subject to restrictions
# as set forth in subdivision (c)(1)(ii) of the Rights in Technical Data
# and Computer Software clause at DFARS 252.227-7013, and/or in similar or
# successor clauses in the FAR, DOD or NASA FAR Supplement. Unpublished  -
# rights reserved under the Copyright Laws of the United States.
#
#

LDIRT= *.exe *.map *.sys *.obj *.lib

!if "$(HWC_CSIM)" == "1"
LCDEFS  = -DHWC_CSIM
!endif

LCOPTS = -WX
LCINCS  = $(LCINCS)  -I$(BUILD_ROOT)\$(FX_GLIDE_HW)\include \
	-I$(BUILD_ROOT)\$(FX_GLIDE_HW)\glide3\conform\include 


GLIDELIB        =       glide3x.lib

INSTALL_DESTINATION = $(BUILD_ROOT)\$(FX_GLIDE_HW)\glide3\conform

PRIVATE_HEADERS = 
DATAFILES = 

#
# SUPPORT_SRC is a list of files to be linked with all tests
#
SUPPORT_SRC =  
SUPPORT_OBJ = $(SUPPORT_SRC:.cpp=.obj)

!ifdef DXSDKROOT
DXLIBS  = $(DXSDKROOT)\lib\dxguid.lib \
          $(DXSDKROOT)\lib\ddraw.lib
!endif


LLDLIBS = $(SUPPORT_OBJ) \
          $(LIBOBJS) $(BUILD_ROOT)\$(FX_GLIDE_HW)\lib\$(GLIDELIB)\
          $(LIBOBJS) $(BUILD_ROOT)\$(FX_GLIDE_HW)\glide3\conform\lib\conform.lib \
          $(BUILD_ROOT_SWLIBS)\lib\fxmisc.lib \
          $(DXLIBS)

#
# TESTS is the list of tests.
#
TESTS   = ext-chroma.cpp \
          ext-fogcoord.cpp \
          ext-palette.cpp \
          ext-surface.cpp \
          ext-tex-chroma.cpp \
          ext-texture-mirror.cpp 

PROGRAMS = $(TESTS:.cpp=.exe)

!include $(BUILD_ROOT)\swlibs/include/nmake/3dfx.mak

$(PROGRAMS):  $(LLDLIBS)

$(TESTS):	$(PRIVATE_HEADERS)

