/****************************************************************************/
/*
** Copyright© 1999 STB Systems Inc.  All rights reserved.
** Project			: Edge Tools
** Target Name		: 
** Author #1		: Paul Magee
** Author #2		: 
** Purpose			: Defines calls and structures for information api
** Uses Libraries	: 
** Date Started		: February 99
** Date Completed	: 
** Update History #1: 
**
** File Name              : infoapi.h
** Source Safe Location   : \edgetools\common\; \3dfx\voodoo3\dd16
** Checked in by          : pmagee
*/
/****************************************************************************/

#ifndef STB_INFO__H
#define STB_INFO__H


#define STB_GETDRIVER_INFO		1


int InfoAPIGetProperty(void * pInData,void *pOutData);








#endif /* STB_INFO__H */



