#############################################################################
#       Copyright (C) Microsoft Corporation 1991-1997
#       All Rights Reserved.
#
#       MINI project makefile include
#
#############################################################################

#--------------------------------------------------------------------
# Define all macros

!ifndef VERBOSE
.SILENT :
!ifndef LOGO
LOGO = /nologo
!endif
!else
LOGO =
!endif

!if "$(V3TV)" == "1"
CFLAGS = $(CFLAGS) -DV3TV -Zi
!endif

!if "$(PN)" == "1"
COPT32 = $(COPT32) -DPERFNOP
PERFNOPECHO = (pn=1) ENABLED
!else #!if "$(PN)" == "1"
PERFNOPECHO = (pn=0) DISABLED
!endif #!if "$(PN)" == "1"

!if "$(ND)" == "1"
COPT32 = $(COPT32) -DNULLDRIVER
NULLDRIVEREHCO = (nd=1) ENABLED
!else #!if "$(ND)" == "1"
COPT32 = $(COPT32)
NULLDRIVEREHCO = (nd=0) DISABLED
!endif #!if "$(ND)" == "1"

!if "$(ACF)" == "1"
AGPCMDFIFOECHO = (acf=1) ENABLED
!else #!if "$(ACF)" == "1"
AGPCMDFIFOECHO = (acf=0) DISABLED
!endif #!if "$(ACF)" == "1"

!if "$(MMI)" == "1"
MMI_ECHO = (mmi=1) YES
!else
MMI_ECHO = (mmi=0) NO
!endif

!if "$(CF)" == "1"
CMDFIFOECHO = ON
!else #!if "$(CF)" == "1"
CMDFIFOECHO = OFF
!endif #!if "$(CF)" == "1"

!if "$(DF)" == "1"
DBGFIFOECHO = ON
!else
DBGFIFOECHO = OFF
!endif

!if "$(SSB)" == "1"
SSB_ECHO = (ssb=1) YES
!else
SSB_ECHO = (ssb=0) NO
!endif

!if "$(IFB)" == "1"
IFB_ECHO = (ifb=1) YES
!else
IFB_ECHO = (ifb=0) NO
!endif

!if "$(DDR)" == "1"
DDR_ECHO = (ddr=1) YES
!else
DDR_ECHO = (ddr=0) NO
!endif

!if "$(MT)" == "1"
MODE_ECHO = (mt=1) GLOP RESOLUTIONS
MODE_TYPE = -DGLOP
!else
MODE_ECHO = (mt=0) TOT RESOLUTIONS
MODE_TYPE = 
!endif

!if ("$(SW_TNL)" == "1")
DEFTARGET = $(DEFTARGET) -DTnL_HAL=1
!endif


HWREV = hwrev_undefined_is_an_error
HWREV_ECHO = hwrev_undefined_is_an_error

!if ("$(HR)" == "B0")
HWREV = -DH3_B0
HWREV_ECHO = (hr=$(HR)) B0
!elseif "$(HR)" == "A2"
HWREV = -DH3_A2
HWREV_ECHO = (hr=$(HR)) A2
!elseif "$(HR)" != "A0"
HWREV = -DH3_A1
HWREV_ECHO = (hr=$(HR)) A1
!else
HWREV = -DH3_A0
HWREV_ECHO = (hr=$(HR)) A0
!endif #!if "$(HR)" == "A2"

!if ("$(HP)" == "H5" || "$(HP)" == "h5")
DESCRIPTION = DIB Engine based 3Dfx VSA display driver
HWPRODUCT = -DH5 $(DEFTARGET)
HWPRODUCT_ECHO = (hp=$(HP)) VSA
!elseif ("$(HP)" == "H4" || "$(HP)" == "h4")
DESCRIPTION = DIB Engine based 3Dfx Voodoo3 display driver
HWPRODUCT = -DH4 $(DEFTARGET)
HWPRODUCT_ECHO = (hp=$(HP)) Voodoo3
!else
DESCRIPTION = DIB Engine based 3Dfx Banshee display driver
HWPRODUCT = -DH3 $(DEFTARGET)
HWPRODUCT_ECHO = (hp=$(HP)) Banshee
!endif

!if "$(WCS)" == "1"
WINSIM = (wcs=1) YES
!else
WINSIM = (wcs=0) NO
!endif

!if "$(SA)" == "1"
SLI_STUFF = (SA=1) YES
!else
SLI_STUFF = (SA=0) NO
!endif

!if "$(RA)" == "1"
RA_STUFF = (RA=1) YES
!else
RA_STUFF = (RA=0) NO
!endif

!if "$(RN)" == "1"
RN_STUFF = (RN=1) YES
!else
RN_STUFF = (RN=0) NO
!endif

!if "$(STEREO)" == "1"
STEREO_STUFF = (STEREO=1) YES
!else
STEREO_STUFF = (STEREO=0) NO
!endif

# DirectX version ...
!if ("$(DX)" == "")
DX = 6
!endif
DXTXT = (dx=$(DX))
DXDEF = -DDX=$(DX)


DRVNAME     = display

MY_CFLAGS = /DDEBUG /c /Zp /Zi /G3s /u /Oxat /AMnw 
DRVDEF  = display.def


#############################################################################
#
#   16bit driver files
#
#############################################################################

SOURCES = \
    diblink.asm \
    reg16.asm \
    colinfo.asm \
# STB Begin Changes
	text16.asm \
	fifo16.asm \
        polyline.asm \
        bitblt16.asm \
   rbo.c\
# STB End Changes
    dbg.c \
    dddrv16.c \
    dib.c \
    h3.c \
#STB_EDGETOOLS Stuff
   dfpapi.c \
	edgeesc.c \
	funcapi.c \
	colorapi.c \
	infoapi.c \
	monitorapi.c \
#STB_EDGETOOLS end
        hwcext.c \
        xhwcext.asm \
    setmode.c \
        realize.c \
    thunk16.asm \
        cursor.c \
        mode.c  \
        qmodes.c  \
        tvout.c \
        monitor.c \
        convert.asm \
        gmath.asm \
!if ("$(DF)" == "1")
        hardware.c \
!endif
        drv2.c \
        ccursor.asm \
        gramp.c \
        memmgr16.c \
#!if ("$(SSB)" == "1")
        ssb.c
#!endif

#strchblt.c \
#text.c \
#reg32.asm \
#bitblt.c \
#output.c \


## include common mini driver include file
!include ..\mini.mk

AFLAGS = $(AFLAGS) $(DXDEF)

# Treat warnings as errors
CFLAGS = $(CFLAGS) -WX

# Remove unwanted flags for h2inc
H2FLAGS=$(CFLAGS)
H2FLAGS=$(H2FLAGS:-Z7i=)
H2FLAGS=$(H2FLAGS:-Gf3s=)

h2inc:
#############################################################################
#
#   ALWAYS build all dependent INC Files (On every compile)
#
#############################################################################
HFILES:
        $(MASM)\bin\h2inc $(H2FLAGS) /Fa..\..\inc\shared.inc ..\..\inc\shared.h 
        $(MASM)\bin\h2inc $(H2FLAGS) /Fa..\..\inc\h3g.inc ..\..\inc\h3g.h 
        $(MASM)\bin\h2inc $(H2FLAGS) /Fa..\..\inc\h3gdefs.inc ..\..\inc\h3gdefs.h 
        $(MASM)\bin\h2inc $(H2FLAGS) /Fa..\..\inc\h3regs.inc ..\..\inc\h3regs.h 

echo_target:
    @echo ----------------------------------------------------
    @echo Target hardware revision .. $(HWREV_ECHO)
    @echo Target hardware product ... $(HWPRODUCT_ECHO)
    @echo Save Screen Bitmap ........ $(SSB_ECHO)
    @echo Memory Integrity Check .... $(MMI_ECHO)
    @echo Infinite Frame Buffer ..... $(IFB_ECHO)
    @echo Command Fifo .............. $(CMDFIFOECHO)
    @echo Debug Fifo ................ $(DBGFIFOECHO)
    @echo Give DD Refresh Rates...... $(DDR_ECHO)
    @echo NULL Driver testing is .... $(NULLDRIVEREHCO)
    @echo Perf NOP command is ....... $(PERFNOPECHO)
    @Echo AGP command fifo is ....... $(AGPCMDFIFOECHO)
    @Echo Mode Type is        ....... $(MODE_ECHO)
    @Echo Win CSIM  ................. $(WINSIM)
    @Echo SLI AA  ................... $(SLI_STUFF)
    @Echo Read Abort Error  ......... $(RA_STUFF)
    @Echo Real Networks   ........... $(RN_STUFF)
    @Echo Stereo glasses support..... $(STEREO_STUFF)
    @echo ( Remember to disable MMI and IFB for retail build )
    @echo ----------------------------------------------------

all: debug retail 

#############################################################################
#
#  dependancy lists
#
#############################################################################

reg16.obj: ..\cmacros.inc

# STB Begin Changes
# STB-SR 1/13/98 Adding code for bj
thunk16.obj: ..\..\inc\shared.h
# STB End Changes

dbg.obj: ..\..\inc\3dfx.h ..\..\inc\fifomgr.h ..\..\inc\fxdll.h \
     ..\..\inc\fxhal.h ..\..\inc\fxpci.h ..\..\inc\fxvid.h \
     ..\..\inc\gdebug.h ..\..\inc\h3.h ..\..\inc\h3defs.h \
     ..\..\inc\h3g.h ..\..\inc\h3gdefs.h ..\..\inc\h3info.h \
     ..\..\inc\h3regs.h ..\..\inc\header.h ..\..\inc\shared.h \
     ..\..\inc\sst1vid.h ..\..\inc\vector.h

dddrv16.obj: ..\..\inc\3dfx.h ..\..\inc\fifomgr.h ..\..\inc\fxdll.h \
     ..\..\inc\fxhal.h ..\..\inc\fxpci.h ..\..\inc\fxvid.h \
     ..\..\inc\gdebug.h ..\..\inc\h3.h ..\..\inc\h3defs.h \
     ..\..\inc\h3g.h ..\..\inc\h3gdefs.h ..\..\inc\h3info.h \
     ..\..\inc\h3regs.h ..\..\inc\header.h ..\..\inc\shared.h \
     ..\..\inc\sst1vid.h ..\..\inc\vector.h

dib.obj: ..\..\inc\3dfx.h ..\..\inc\fifomgr.h ..\..\inc\fxdll.h \
     ..\..\inc\fxhal.h ..\..\inc\fxpci.h ..\..\inc\fxvid.h \
     ..\..\inc\gdebug.h ..\..\inc\h3.h ..\..\inc\h3defs.h \
     ..\..\inc\h3g.h ..\..\inc\h3gdefs.h ..\..\inc\h3info.h \
     ..\..\inc\h3regs.h ..\..\inc\header.h ..\..\inc\shared.h \
     ..\..\inc\sst1vid.h ..\..\inc\vector.h

h3.obj:  ..\..\inc\3dfx.h ..\..\inc\fifomgr.h ..\..\inc\fxdll.h \
     ..\..\inc\fxhal.h ..\..\inc\fxpci.h ..\..\inc\fxvid.h \
     ..\..\inc\gdebug.h ..\..\inc\h3.h ..\..\inc\h3defs.h \
     ..\..\inc\h3g.h ..\..\inc\h3gdefs.h ..\..\inc\h3info.h \
     ..\..\inc\h3regs.h ..\..\inc\header.h ..\..\inc\shared.h \
     ..\..\inc\sst1vid.h ..\..\inc\vector.h

setmode.obj: ..\..\inc\3dfx.h ..\..\inc\fifomgr.h ..\..\inc\fxdll.h \
     ..\..\inc\fxhal.h ..\..\inc\fxpci.h ..\..\inc\fxvid.h \
     ..\..\inc\gdebug.h ..\..\inc\h3.h ..\..\inc\h3defs.h \
     ..\..\inc\h3g.h ..\..\inc\h3gdefs.h ..\..\inc\h3info.h \
     ..\..\inc\h3regs.h ..\..\inc\header.h ..\..\inc\shared.h \
     ..\..\inc\sst1vid.h ..\..\inc\vector.h

realize.obj: ..\..\inc\3dfx.h ..\..\inc\fifomgr.h ..\..\inc\fxdll.h \
     ..\..\inc\fxhal.h ..\..\inc\fxpci.h ..\..\inc\fxvid.h \
     ..\..\inc\gdebug.h ..\..\inc\h3.h ..\..\inc\h3defs.h \
     ..\..\inc\h3g.h ..\..\inc\h3gdefs.h ..\..\inc\h3info.h \
     ..\..\inc\h3regs.h ..\..\inc\header.h ..\..\inc\shared.h \
     ..\..\inc\sst1vid.h ..\..\inc\vector.h ..\devbits.h ..\dispinfo.h \
     ..\dqueue.h

cursor.obj: ..\..\inc\3dfx.h ..\..\inc\fifomgr.h ..\..\inc\fxdll.h \
     ..\..\inc\fxhal.h ..\..\inc\fxpci.h ..\..\inc\fxvid.h \
     ..\..\inc\gdebug.h ..\..\inc\h3.h ..\..\inc\h3defs.h \
     ..\..\inc\h3g.h ..\..\inc\h3gdefs.h ..\..\inc\h3info.h \
     ..\..\inc\h3regs.h ..\..\inc\header.h ..\..\inc\shared.h \
     ..\..\inc\sst1vid.h ..\..\inc\vector.h ..\cursor.h

bitmap.obj: ..\..\inc\3dfx.h ..\..\inc\fifomgr.h ..\..\inc\fxdll.h \
     ..\..\inc\fxhal.h ..\..\inc\fxpci.h ..\..\inc\fxvid.h \
     ..\..\inc\gdebug.h ..\..\inc\h3.h ..\..\inc\h3defs.h \
     ..\..\inc\h3g.h ..\..\inc\h3gdefs.h ..\..\inc\h3info.h \
     ..\..\inc\h3regs.h ..\..\inc\header.h ..\..\inc\shared.h \
     ..\..\inc\sst1vid.h ..\..\inc\vector.h ..\devbits.h

memmgr16.obj: ..\..\inc\3dfx.h ..\..\inc\fifomgr.h ..\..\inc\fxdll.h \
     ..\..\inc\fxhal.h ..\..\inc\fxpci.h ..\..\inc\fxvid.h \
     ..\..\inc\gdebug.h ..\..\inc\h3.h ..\..\inc\h3defs.h \
     ..\..\inc\h3g.h ..\..\inc\h3gdefs.h ..\..\inc\h3info.h \
     ..\..\inc\h3regs.h ..\..\inc\header.h ..\..\inc\shared.h \
     ..\..\inc\sst1vid.h ..\..\inc\vector.h ..\memmgr16.h

ssb.obj: ..\..\inc\3dfx.h ..\..\inc\fifomgr.h ..\..\inc\fxdll.h \
     ..\..\inc\fxhal.h ..\..\inc\fxpci.h ..\..\inc\fxvid.h \
     ..\..\inc\gdebug.h ..\..\inc\h3.h ..\..\inc\h3defs.h \
     ..\..\inc\h3g.h ..\..\inc\h3gdefs.h ..\..\inc\h3info.h \
     ..\..\inc\h3regs.h ..\..\inc\header.h ..\..\inc\shared.h \
     ..\..\inc\sst1vid.h ..\..\inc\vector.h ..\memmgr16.h

rbo.obj: ..\..\inc\3dfx.h ..\..\inc\fifomgr.h ..\..\inc\fxdll.h \
     ..\..\inc\fxhal.h ..\..\inc\fxpci.h ..\..\inc\fxvid.h \
     ..\..\inc\gdebug.h ..\..\inc\h3.h ..\..\inc\h3defs.h \
     ..\..\inc\h3g.h ..\..\inc\h3gdefs.h ..\..\inc\h3info.h \
     ..\..\inc\h3regs.h ..\..\inc\header.h ..\..\inc\shared.h \
     ..\..\inc\sst1vid.h ..\..\inc\vector.h ..\memmgr16.h ..\robject.h
