//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by testapp1.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_TESTAPTYPE                  129
#define ID_SYSTEM_CSCLEANUPRESOURCESFORPROCESS 32773
#define ID_DEVICECONTEXT_CSGETPROTOCOLREVISION 32775
#define ID_GRAPHICALCONTEXT_CSGETGRAPHICALCONTEXT 32777
#define ID_GRAPHICALCONTEXT_CSRELEASEGRAPHICALCONTEXT 32778
#define ID_GRAPHICALCONTEXT_CREATEWINDOW 32779
#define ID_MEMORY_CSALLOC               32780
#define ID_MEMORY_CSFREE                32781
#define ID_OVERLAY_CSACQUIREOVLERAY     32782
#define ID_MEMORY_CSSWAPBUFFERTODISPLAY 32784
#define ID_VIDEOMODE_CSSETVIDEOMODE     32785
#define ID_MEMORY_CSLOCK                32786
#define ID_MEMORY_CSUNLOCK              32787
#define ID_COMMANDS_BUILDCOMMAND        32788
#define ID_REGISTERS_CSREGISTERREAD     32790
#define ID_REGISTERS_CSREGISTERWRITE    32791
#define ID_COMMANDS_EXECUTECOMMANDS     32794
#define ID_RUN_COMPLETEINIT             32795
#define ID_RUN_COMPLETEUNINIT           32796
#define ID_RUN_STARTRENDER              32797
#define ID_RUN_STOPRENDERING            32798
#define ID_RUN_RENDERTOSENTINEL         32799

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32800
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
