; CLW file contains information for the MFC ClassWizard

[General Info]
Version=1
LastClass=CMainFrame
LastTemplate=CDialog
NewFileInclude1=#include "stdafx.h"
NewFileInclude2=#include "testapp1.h"
LastPage=0

ClassCount=5
Class1=CTestapp1App
Class2=CTestapp1Doc
Class3=CTestapp1View
Class4=CMainFrame

ResourceCount=2
Resource1=IDD_ABOUTBOX
Class5=CAboutDlg
Resource2=IDR_MAINFRAME

[CLS:CTestapp1App]
Type=0
HeaderFile=testapp1.h
ImplementationFile=testapp1.cpp
Filter=N

[CLS:CTestapp1Doc]
Type=0
HeaderFile=testapp1Doc.h
ImplementationFile=testapp1Doc.cpp
Filter=N

[CLS:CTestapp1View]
Type=0
HeaderFile=testapp1View.h
ImplementationFile=testapp1View.cpp
Filter=C

[CLS:CMainFrame]
Type=0
HeaderFile=MainFrm.h
ImplementationFile=MainFrm.cpp
Filter=T
LastObject=ID_RUN_RENDERTOSENTINEL
BaseClass=CFrameWnd
VirtualFilter=fWC



[CLS:CAboutDlg]
Type=0
HeaderFile=testapp1.cpp
ImplementationFile=testapp1.cpp
Filter=D

[DLG:IDD_ABOUTBOX]
Type=1
Class=CAboutDlg
ControlCount=4
Control1=IDC_STATIC,static,1342177283
Control2=IDC_STATIC,static,1342308480
Control3=IDC_STATIC,static,1342308352
Control4=IDOK,button,1342373889

[MNU:IDR_MAINFRAME]
Type=1
Class=CMainFrame
Command1=ID_FILE_NEW
Command2=ID_FILE_OPEN
Command3=ID_FILE_SAVE
Command4=ID_FILE_SAVE_AS
Command5=ID_FILE_MRU_FILE1
Command6=ID_APP_EXIT
Command7=ID_DEVICECONTEXT_CSGETPROTOCOLREVISION
Command8=ID_GRAPHICALCONTEXT_CREATEWINDOW
Command9=ID_GRAPHICALCONTEXT_CSGETGRAPHICALCONTEXT
Command10=ID_GRAPHICALCONTEXT_CSRELEASEGRAPHICALCONTEXT
Command11=ID_MEMORY_CSALLOC
Command12=ID_MEMORY_CSFREE
Command13=ID_MEMORY_CSSWAPBUFFERTODISPLAY
Command14=ID_MEMORY_CSLOCK
Command15=ID_MEMORY_CSUNLOCK
Command16=ID_OVERLAY_CSACQUIREOVLERAY
Command17=ID_VIDEOMODE_CSSETVIDEOMODE
Command18=ID_COMMANDS_BUILDCOMMAND
Command19=ID_COMMANDS_EXECUTECOMMANDS
Command20=ID_REGISTERS_CSREGISTERREAD
Command21=ID_REGISTERS_CSREGISTERWRITE
Command22=ID_RUN_COMPLETEINIT
Command23=ID_RUN_COMPLETEUNINIT
Command24=ID_RUN_STARTRENDER
Command25=ID_RUN_STOPRENDERING
Command26=ID_RUN_RENDERTOSENTINEL
Command27=ID_APP_ABOUT
CommandCount=27

[ACL:IDR_MAINFRAME]
Type=1
Class=CMainFrame
Command1=ID_FILE_NEW
Command2=ID_FILE_OPEN
Command3=ID_FILE_SAVE
Command4=ID_EDIT_UNDO
Command5=ID_EDIT_CUT
Command6=ID_EDIT_COPY
Command7=ID_EDIT_PASTE
Command8=ID_EDIT_UNDO
Command9=ID_EDIT_CUT
Command10=ID_EDIT_COPY
Command11=ID_EDIT_PASTE
Command12=ID_NEXT_PANE
Command13=ID_PREV_PANE
CommandCount=13

