LDIRT= *.exe *.map *.sys *.obj *.lib

LCINCS  = $(LCINCS)  -I$(BUILD_ROOT_SST1)\include

#!if "$(FX_TARGET)"=="WIN32"
#FX_TARGET_MINOR=WIN95
#!endif

LIBOBJS = winutil.obj clock.obj

LLDLIBS = $(LLDLIBS) $(BUILD_ROOT_SST1)\lib\glide2x.lib $(LIB)\opengl32.lib $(LIB)\glu32.lib $(LIBOBJS)

CFILES = \
	simple.c \
	trispeed.c \
	bindspeed.c \
	$(NULL)

PROGRAMS = $(CFILES:.c=.exe)

!include $(BUILD_ROOT_SWLIBS)/include/nmake/3dfx.mak

$(PROGRAMS):  $(LLDLIBS)

