#
# Copyright (c) 1996, 3Dfx Interactive, Inc.
# All Rights Reserved.
#
# This is UNPUBLISHED PROPRIETARY SOURCE CODE of 3Dfx Interactive, Inc.;
# the contents of this file may not be disclosed to third parties, copied or
# duplicated in any form, in whole or in part, without the prior written
# permission of 3Dfx Interactive, Inc.
#
# RESTRICTED RIGHTS LEGEND:
# Use, duplication or disclosure by the Government is subject to restrictions
# as set forth in subdivision (c)(1)(ii) of the Rights in Technical Data
# and Computer Software clause at DFARS 252.227-7013, and/or in similar or
# successor clauses in the FAR, DOD or NASA FAR Supplement. Unpublished  -
# rights reserved under the Copyright Laws of the United States.
#
# $Revision: 6 $
# $Date: 10/15/98 5:41p $

# local defines, options, includes
LCDEFS  = 
LCOPTS  =
LCINCS  = -I$(BUILD_ROOT_SWLIBS)\include

# sources
CFILES   = detect.c ptltest.c pcirw.c 

PROGRAMS = $(CFILES:.c=.exe)

INSTALL_DESTINATION = $(BUILD_ROOT_SWLIBS)

LLDLIBS = $(BUILD_ROOT_SWLIBS)\lib\fxpci.lib $(BUILD_ROOT_SWLIBS)\lib\fxremap.lib

!include $(BUILD_ROOT_SWLIBS)\include\nmake\3dfx.mak
