#
# Copyright (c) 1997, 3Dfx Interactive, Inc.
# All Rights Reserved.
#
# This is UNPUBLISHED PROPRIETARY SOURCE CODE of 3Dfx Interactive, Inc.;
# the contents of this file may not be disclosed to third parties, copied or
# duplicated in any form, in whole or in part, without the prior written
# permission of 3Dfx Interactive, Inc.
#
# RESTRICTED RIGHTS LEGEND:
# Use, duplication or disclosure by the Government is subject to restrictions
# as set forth in subdivision (c)(1)(ii) of the Rights in Technical Data
# and Computer Software clause at DFARS 252.227-7013, and/or in similar or
# successor clauses in the FAR, DOD or NASA FAR Supplement. Unpublished  -
# rights reserved under the Copyright Laws of the United States.
#
# $Revision: 5 $
# $Date: 9/03/95 8:15p $
#

# local defines, options, includes
DBGOPTS = -DHWC_DEBUG -DGDBG_INFO_ON -g
LCDEFS	= -DGLIDE_LIB -DHWC_CSIM -DGLIDE3 -DGLIDE3_ALPHA -DGLIDE_DEBUG
LCOPTS = $(DBGOPTS) 
LADEFS	= -DIS_32
LCOPTS	=
LCINCS	:= $(LCINCS) -I$(BUILD_ROOT_SST2)/build \
           -I$(BUILD_ROOT)/$(FX_GLIDE_HW)/include \
	       -I$(BUILD_ROOT)/$(FX_GLIDE_HW)/glide3/conform/include \
	       -I$(BUILD_ROOT)/$(FX_GLIDE_HW)/glide3/src

# sources
HEADERS = 
PRIVATE_HEADERS = 

WINDOWING_FILES = xlib.cpp

SURFACE_FILES  = surface_stubs.cpp # hwc_surf.cpp

CPPFILES              = utility.cpp main.cpp log.cpp mode.cpp image.cpp \
                        matrix.cpp data.cpp intrface.cpp checksum.cpp \
                        vmglide.cpp \
                        $(WINDOWING_FILES) \
                        $(SURFACE_FILES)
        
INSTALL_DESTINATION = $(BUILD_ROOT)/$(FX_GLIDE_HW)/glide3/conform

# targets
LIBRARIES= conform.a

FX_DLL_LIBRARY=1

include $(BUILD_ROOT_SWLIBS)/include/make/3dfx.mak

.SUFFIXES: .cpp

.cpp.o: fred
	$(CC) $(CFLAGS) -c $*.cpp
