/* DO NOT EDIT - THIS FILE IS AUTOMATICALLY GENERATED */

/*
** Copyright 1992-1997 Silicon Graphics, Inc.
** All Rights Reserved.
**
** This is UNPUBLISHED PROPRIETARY SOURCE CODE of Silicon Graphics, Inc.;
** the contents of this file may not be disclosed to third parties, copied or
** duplicated in any form, in whole or in part, without the prior written
** permission of Silicon Graphics, Inc.
**
** RESTRICTED RIGHTS LEGEND:
** Use, duplication or disclosure by the Government is subject to restrictions
** as set forth in subdivision (c)(1)(ii) of the Rights in Technical Data
** and Computer Software clause at DFARS 252.227-7013, and/or in similar or
** successor clauses in the FAR, DOD or NASA FAR Supplement. Unpublished -
** rights reserved under the Copyright Laws of the United States.
*/

#include "types.h"
#include "GL/gl.h"
#include "GL/glthread.h"
#include "g_disp.h"
#include "g_asmoff.h"

#define __GL_CX_DA __GL_CURRENT_DISPATCH_STATE
#define __gltp_dispatch __GL_CX_DA+SZINT
#define __gltp_extensions __GL_CX_DA+SZINT+__GL_TAB_SIZE

#pragma warning ( disable : 4273 )
#pragma warning ( disable : 4035 )
#pragma warning ( disable : 4409 )
#pragma warning ( disable : 4410 )


__declspec(naked)
void APIENTRY glNewList( GLuint list, GLenum mode)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_NewList*SZPTR]
}

__declspec(naked)
void APIENTRY glEndList( void)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_EndList*SZPTR]
}

__declspec(naked)
void APIENTRY glCallList( GLuint list)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_CallList*SZPTR]
}

__declspec(naked)
void APIENTRY glCallLists( GLsizei n, GLenum type, const GLvoid *lists)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_CallLists*SZPTR]
}

__declspec(naked)
void APIENTRY glDeleteLists( GLuint list, GLsizei range)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_DeleteLists*SZPTR]
}

__declspec(naked)
GLuint APIENTRY glGenLists( GLsizei range)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_GenLists*SZPTR]
}

__declspec(naked)
void APIENTRY glListBase( GLuint base)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_ListBase*SZPTR]
}

__declspec(naked)
void APIENTRY glBegin( GLenum mode)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Begin*SZPTR]
}

__declspec(naked)
void APIENTRY glBitmap( GLsizei width, GLsizei height, GLfloat xorig, GLfloat yorig, GLfloat xmove, GLfloat ymove, const GLubyte *bitmap)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Bitmap*SZPTR]
}

__declspec(naked)
void APIENTRY glColor3b( GLbyte red, GLbyte green, GLbyte blue)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Color3b*SZPTR]
}

__declspec(naked)
void APIENTRY glColor3bv( const GLbyte *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Color3bv*SZPTR]
}

__declspec(naked)
void APIENTRY glColor3d( GLdouble red, GLdouble green, GLdouble blue)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Color3d*SZPTR]
}

__declspec(naked)
void APIENTRY glColor3dv( const GLdouble *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Color3dv*SZPTR]
}

__declspec(naked)
void APIENTRY glColor3f( GLfloat red, GLfloat green, GLfloat blue)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Color3f*SZPTR]
}

__declspec(naked)
void APIENTRY glColor3fv( const GLfloat *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Color3fv*SZPTR]
}

__declspec(naked)
void APIENTRY glColor3i( GLint red, GLint green, GLint blue)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Color3i*SZPTR]
}

__declspec(naked)
void APIENTRY glColor3iv( const GLint *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Color3iv*SZPTR]
}

__declspec(naked)
void APIENTRY glColor3s( GLshort red, GLshort green, GLshort blue)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Color3s*SZPTR]
}

__declspec(naked)
void APIENTRY glColor3sv( const GLshort *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Color3sv*SZPTR]
}

__declspec(naked)
void APIENTRY glColor3ub( GLubyte red, GLubyte green, GLubyte blue)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Color3ub*SZPTR]
}

__declspec(naked)
void APIENTRY glColor3ubv( const GLubyte *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Color3ubv*SZPTR]
}

__declspec(naked)
void APIENTRY glColor3ui( GLuint red, GLuint green, GLuint blue)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Color3ui*SZPTR]
}

__declspec(naked)
void APIENTRY glColor3uiv( const GLuint *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Color3uiv*SZPTR]
}

__declspec(naked)
void APIENTRY glColor3us( GLushort red, GLushort green, GLushort blue)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Color3us*SZPTR]
}

__declspec(naked)
void APIENTRY glColor3usv( const GLushort *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Color3usv*SZPTR]
}

__declspec(naked)
void APIENTRY glColor4b( GLbyte red, GLbyte green, GLbyte blue, GLbyte alpha)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Color4b*SZPTR]
}

__declspec(naked)
void APIENTRY glColor4bv( const GLbyte *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Color4bv*SZPTR]
}

__declspec(naked)
void APIENTRY glColor4d( GLdouble red, GLdouble green, GLdouble blue, GLdouble alpha)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Color4d*SZPTR]
}

__declspec(naked)
void APIENTRY glColor4dv( const GLdouble *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Color4dv*SZPTR]
}

__declspec(naked)
void APIENTRY glColor4f( GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Color4f*SZPTR]
}

__declspec(naked)
void APIENTRY glColor4fv( const GLfloat *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Color4fv*SZPTR]
}

__declspec(naked)
void APIENTRY glColor4i( GLint red, GLint green, GLint blue, GLint alpha)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Color4i*SZPTR]
}

__declspec(naked)
void APIENTRY glColor4iv( const GLint *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Color4iv*SZPTR]
}

__declspec(naked)
void APIENTRY glColor4s( GLshort red, GLshort green, GLshort blue, GLshort alpha)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Color4s*SZPTR]
}

__declspec(naked)
void APIENTRY glColor4sv( const GLshort *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Color4sv*SZPTR]
}

__declspec(naked)
void APIENTRY glColor4ub( GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Color4ub*SZPTR]
}

__declspec(naked)
void APIENTRY glColor4ubv( const GLubyte *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Color4ubv*SZPTR]
}

__declspec(naked)
void APIENTRY glColor4ui( GLuint red, GLuint green, GLuint blue, GLuint alpha)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Color4ui*SZPTR]
}

__declspec(naked)
void APIENTRY glColor4uiv( const GLuint *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Color4uiv*SZPTR]
}

__declspec(naked)
void APIENTRY glColor4us( GLushort red, GLushort green, GLushort blue, GLushort alpha)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Color4us*SZPTR]
}

__declspec(naked)
void APIENTRY glColor4usv( const GLushort *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Color4usv*SZPTR]
}

__declspec(naked)
void APIENTRY glEdgeFlag( GLboolean flag)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_EdgeFlag*SZPTR]
}

__declspec(naked)
void APIENTRY glEdgeFlagv( const GLboolean *flag)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_EdgeFlagv*SZPTR]
}

__declspec(naked)
void APIENTRY glEnd( void)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_End*SZPTR]
}

__declspec(naked)
void APIENTRY glIndexd( GLdouble c)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Indexd*SZPTR]
}

__declspec(naked)
void APIENTRY glIndexdv( const GLdouble *c)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Indexdv*SZPTR]
}

__declspec(naked)
void APIENTRY glIndexf( GLfloat c)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Indexf*SZPTR]
}

__declspec(naked)
void APIENTRY glIndexfv( const GLfloat *c)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Indexfv*SZPTR]
}

__declspec(naked)
void APIENTRY glIndexi( GLint c)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Indexi*SZPTR]
}

__declspec(naked)
void APIENTRY glIndexiv( const GLint *c)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Indexiv*SZPTR]
}

__declspec(naked)
void APIENTRY glIndexs( GLshort c)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Indexs*SZPTR]
}

__declspec(naked)
void APIENTRY glIndexsv( const GLshort *c)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Indexsv*SZPTR]
}

__declspec(naked)
void APIENTRY glNormal3b( GLbyte nx, GLbyte ny, GLbyte nz)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Normal3b*SZPTR]
}

__declspec(naked)
void APIENTRY glNormal3bv( const GLbyte *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Normal3bv*SZPTR]
}

__declspec(naked)
void APIENTRY glNormal3d( GLdouble nx, GLdouble ny, GLdouble nz)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Normal3d*SZPTR]
}

__declspec(naked)
void APIENTRY glNormal3dv( const GLdouble *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Normal3dv*SZPTR]
}

__declspec(naked)
void APIENTRY glNormal3f( GLfloat nx, GLfloat ny, GLfloat nz)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Normal3f*SZPTR]
}

__declspec(naked)
void APIENTRY glNormal3fv( const GLfloat *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Normal3fv*SZPTR]
}

__declspec(naked)
void APIENTRY glNormal3i( GLint nx, GLint ny, GLint nz)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Normal3i*SZPTR]
}

__declspec(naked)
void APIENTRY glNormal3iv( const GLint *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Normal3iv*SZPTR]
}

__declspec(naked)
void APIENTRY glNormal3s( GLshort nx, GLshort ny, GLshort nz)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Normal3s*SZPTR]
}

__declspec(naked)
void APIENTRY glNormal3sv( const GLshort *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Normal3sv*SZPTR]
}

__declspec(naked)
void APIENTRY glRasterPos2d( GLdouble x, GLdouble y)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_RasterPos2d*SZPTR]
}

__declspec(naked)
void APIENTRY glRasterPos2dv( const GLdouble *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_RasterPos2dv*SZPTR]
}

__declspec(naked)
void APIENTRY glRasterPos2f( GLfloat x, GLfloat y)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_RasterPos2f*SZPTR]
}

__declspec(naked)
void APIENTRY glRasterPos2fv( const GLfloat *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_RasterPos2fv*SZPTR]
}

__declspec(naked)
void APIENTRY glRasterPos2i( GLint x, GLint y)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_RasterPos2i*SZPTR]
}

__declspec(naked)
void APIENTRY glRasterPos2iv( const GLint *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_RasterPos2iv*SZPTR]
}

__declspec(naked)
void APIENTRY glRasterPos2s( GLshort x, GLshort y)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_RasterPos2s*SZPTR]
}

__declspec(naked)
void APIENTRY glRasterPos2sv( const GLshort *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_RasterPos2sv*SZPTR]
}

__declspec(naked)
void APIENTRY glRasterPos3d( GLdouble x, GLdouble y, GLdouble z)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_RasterPos3d*SZPTR]
}

__declspec(naked)
void APIENTRY glRasterPos3dv( const GLdouble *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_RasterPos3dv*SZPTR]
}

__declspec(naked)
void APIENTRY glRasterPos3f( GLfloat x, GLfloat y, GLfloat z)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_RasterPos3f*SZPTR]
}

__declspec(naked)
void APIENTRY glRasterPos3fv( const GLfloat *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_RasterPos3fv*SZPTR]
}

__declspec(naked)
void APIENTRY glRasterPos3i( GLint x, GLint y, GLint z)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_RasterPos3i*SZPTR]
}

__declspec(naked)
void APIENTRY glRasterPos3iv( const GLint *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_RasterPos3iv*SZPTR]
}

__declspec(naked)
void APIENTRY glRasterPos3s( GLshort x, GLshort y, GLshort z)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_RasterPos3s*SZPTR]
}

__declspec(naked)
void APIENTRY glRasterPos3sv( const GLshort *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_RasterPos3sv*SZPTR]
}

__declspec(naked)
void APIENTRY glRasterPos4d( GLdouble x, GLdouble y, GLdouble z, GLdouble w)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_RasterPos4d*SZPTR]
}

__declspec(naked)
void APIENTRY glRasterPos4dv( const GLdouble *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_RasterPos4dv*SZPTR]
}

__declspec(naked)
void APIENTRY glRasterPos4f( GLfloat x, GLfloat y, GLfloat z, GLfloat w)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_RasterPos4f*SZPTR]
}

__declspec(naked)
void APIENTRY glRasterPos4fv( const GLfloat *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_RasterPos4fv*SZPTR]
}

__declspec(naked)
void APIENTRY glRasterPos4i( GLint x, GLint y, GLint z, GLint w)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_RasterPos4i*SZPTR]
}

__declspec(naked)
void APIENTRY glRasterPos4iv( const GLint *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_RasterPos4iv*SZPTR]
}

__declspec(naked)
void APIENTRY glRasterPos4s( GLshort x, GLshort y, GLshort z, GLshort w)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_RasterPos4s*SZPTR]
}

__declspec(naked)
void APIENTRY glRasterPos4sv( const GLshort *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_RasterPos4sv*SZPTR]
}

__declspec(naked)
void APIENTRY glRectd( GLdouble x1, GLdouble y1, GLdouble x2, GLdouble y2)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Rectd*SZPTR]
}

__declspec(naked)
void APIENTRY glRectdv( const GLdouble *v1, const GLdouble *v2)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Rectdv*SZPTR]
}

__declspec(naked)
void APIENTRY glRectf( GLfloat x1, GLfloat y1, GLfloat x2, GLfloat y2)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Rectf*SZPTR]
}

__declspec(naked)
void APIENTRY glRectfv( const GLfloat *v1, const GLfloat *v2)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Rectfv*SZPTR]
}

__declspec(naked)
void APIENTRY glRecti( GLint x1, GLint y1, GLint x2, GLint y2)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Recti*SZPTR]
}

__declspec(naked)
void APIENTRY glRectiv( const GLint *v1, const GLint *v2)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Rectiv*SZPTR]
}

__declspec(naked)
void APIENTRY glRects( GLshort x1, GLshort y1, GLshort x2, GLshort y2)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Rects*SZPTR]
}

__declspec(naked)
void APIENTRY glRectsv( const GLshort *v1, const GLshort *v2)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Rectsv*SZPTR]
}

__declspec(naked)
void APIENTRY glTexCoord1d( GLdouble s)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_TexCoord1d*SZPTR]
}

__declspec(naked)
void APIENTRY glTexCoord1dv( const GLdouble *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_TexCoord1dv*SZPTR]
}

__declspec(naked)
void APIENTRY glTexCoord1f( GLfloat s)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_TexCoord1f*SZPTR]
}

__declspec(naked)
void APIENTRY glTexCoord1fv( const GLfloat *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_TexCoord1fv*SZPTR]
}

__declspec(naked)
void APIENTRY glTexCoord1i( GLint s)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_TexCoord1i*SZPTR]
}

__declspec(naked)
void APIENTRY glTexCoord1iv( const GLint *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_TexCoord1iv*SZPTR]
}

__declspec(naked)
void APIENTRY glTexCoord1s( GLshort s)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_TexCoord1s*SZPTR]
}

__declspec(naked)
void APIENTRY glTexCoord1sv( const GLshort *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_TexCoord1sv*SZPTR]
}

__declspec(naked)
void APIENTRY glTexCoord2d( GLdouble s, GLdouble t)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_TexCoord2d*SZPTR]
}

__declspec(naked)
void APIENTRY glTexCoord2dv( const GLdouble *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_TexCoord2dv*SZPTR]
}

__declspec(naked)
void APIENTRY glTexCoord2f( GLfloat s, GLfloat t)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_TexCoord2f*SZPTR]
}

__declspec(naked)
void APIENTRY glTexCoord2fv( const GLfloat *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_TexCoord2fv*SZPTR]
}

__declspec(naked)
void APIENTRY glTexCoord2i( GLint s, GLint t)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_TexCoord2i*SZPTR]
}

__declspec(naked)
void APIENTRY glTexCoord2iv( const GLint *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_TexCoord2iv*SZPTR]
}

__declspec(naked)
void APIENTRY glTexCoord2s( GLshort s, GLshort t)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_TexCoord2s*SZPTR]
}

__declspec(naked)
void APIENTRY glTexCoord2sv( const GLshort *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_TexCoord2sv*SZPTR]
}

__declspec(naked)
void APIENTRY glTexCoord3d( GLdouble s, GLdouble t, GLdouble r)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_TexCoord3d*SZPTR]
}

__declspec(naked)
void APIENTRY glTexCoord3dv( const GLdouble *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_TexCoord3dv*SZPTR]
}

__declspec(naked)
void APIENTRY glTexCoord3f( GLfloat s, GLfloat t, GLfloat r)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_TexCoord3f*SZPTR]
}

__declspec(naked)
void APIENTRY glTexCoord3fv( const GLfloat *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_TexCoord3fv*SZPTR]
}

__declspec(naked)
void APIENTRY glTexCoord3i( GLint s, GLint t, GLint r)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_TexCoord3i*SZPTR]
}

__declspec(naked)
void APIENTRY glTexCoord3iv( const GLint *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_TexCoord3iv*SZPTR]
}

__declspec(naked)
void APIENTRY glTexCoord3s( GLshort s, GLshort t, GLshort r)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_TexCoord3s*SZPTR]
}

__declspec(naked)
void APIENTRY glTexCoord3sv( const GLshort *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_TexCoord3sv*SZPTR]
}

__declspec(naked)
void APIENTRY glTexCoord4d( GLdouble s, GLdouble t, GLdouble r, GLdouble q)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_TexCoord4d*SZPTR]
}

__declspec(naked)
void APIENTRY glTexCoord4dv( const GLdouble *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_TexCoord4dv*SZPTR]
}

__declspec(naked)
void APIENTRY glTexCoord4f( GLfloat s, GLfloat t, GLfloat r, GLfloat q)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_TexCoord4f*SZPTR]
}

__declspec(naked)
void APIENTRY glTexCoord4fv( const GLfloat *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_TexCoord4fv*SZPTR]
}

__declspec(naked)
void APIENTRY glTexCoord4i( GLint s, GLint t, GLint r, GLint q)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_TexCoord4i*SZPTR]
}

__declspec(naked)
void APIENTRY glTexCoord4iv( const GLint *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_TexCoord4iv*SZPTR]
}

__declspec(naked)
void APIENTRY glTexCoord4s( GLshort s, GLshort t, GLshort r, GLshort q)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_TexCoord4s*SZPTR]
}

__declspec(naked)
void APIENTRY glTexCoord4sv( const GLshort *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_TexCoord4sv*SZPTR]
}

__declspec(naked)
void APIENTRY glVertex2d( GLdouble x, GLdouble y)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Vertex2d*SZPTR]
}

__declspec(naked)
void APIENTRY glVertex2dv( const GLdouble *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Vertex2dv*SZPTR]
}

__declspec(naked)
void APIENTRY glVertex2f( GLfloat x, GLfloat y)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Vertex2f*SZPTR]
}

__declspec(naked)
void APIENTRY glVertex2fv( const GLfloat *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Vertex2fv*SZPTR]
}

__declspec(naked)
void APIENTRY glVertex2i( GLint x, GLint y)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Vertex2i*SZPTR]
}

__declspec(naked)
void APIENTRY glVertex2iv( const GLint *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Vertex2iv*SZPTR]
}

__declspec(naked)
void APIENTRY glVertex2s( GLshort x, GLshort y)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Vertex2s*SZPTR]
}

__declspec(naked)
void APIENTRY glVertex2sv( const GLshort *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Vertex2sv*SZPTR]
}

__declspec(naked)
void APIENTRY glVertex3d( GLdouble x, GLdouble y, GLdouble z)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Vertex3d*SZPTR]
}

__declspec(naked)
void APIENTRY glVertex3dv( const GLdouble *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Vertex3dv*SZPTR]
}

__declspec(naked)
void APIENTRY glVertex3f( GLfloat x, GLfloat y, GLfloat z)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Vertex3f*SZPTR]
}

__declspec(naked)
void APIENTRY glVertex3fv( const GLfloat *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Vertex3fv*SZPTR]
}

__declspec(naked)
void APIENTRY glVertex3i( GLint x, GLint y, GLint z)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Vertex3i*SZPTR]
}

__declspec(naked)
void APIENTRY glVertex3iv( const GLint *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Vertex3iv*SZPTR]
}

__declspec(naked)
void APIENTRY glVertex3s( GLshort x, GLshort y, GLshort z)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Vertex3s*SZPTR]
}

__declspec(naked)
void APIENTRY glVertex3sv( const GLshort *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Vertex3sv*SZPTR]
}

__declspec(naked)
void APIENTRY glVertex4d( GLdouble x, GLdouble y, GLdouble z, GLdouble w)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Vertex4d*SZPTR]
}

__declspec(naked)
void APIENTRY glVertex4dv( const GLdouble *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Vertex4dv*SZPTR]
}

__declspec(naked)
void APIENTRY glVertex4f( GLfloat x, GLfloat y, GLfloat z, GLfloat w)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Vertex4f*SZPTR]
}

__declspec(naked)
void APIENTRY glVertex4fv( const GLfloat *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Vertex4fv*SZPTR]
}

__declspec(naked)
void APIENTRY glVertex4i( GLint x, GLint y, GLint z, GLint w)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Vertex4i*SZPTR]
}

__declspec(naked)
void APIENTRY glVertex4iv( const GLint *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Vertex4iv*SZPTR]
}

__declspec(naked)
void APIENTRY glVertex4s( GLshort x, GLshort y, GLshort z, GLshort w)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Vertex4s*SZPTR]
}

__declspec(naked)
void APIENTRY glVertex4sv( const GLshort *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Vertex4sv*SZPTR]
}

__declspec(naked)
void APIENTRY glClipPlane( GLenum plane, const GLdouble *equation)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_ClipPlane*SZPTR]
}

__declspec(naked)
void APIENTRY glColorMaterial( GLenum face, GLenum mode)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_ColorMaterial*SZPTR]
}

__declspec(naked)
void APIENTRY glCullFace( GLenum mode)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_CullFace*SZPTR]
}

__declspec(naked)
void APIENTRY glFogf( GLenum pname, GLfloat param)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Fogf*SZPTR]
}

__declspec(naked)
void APIENTRY glFogfv( GLenum pname, const GLfloat *params)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Fogfv*SZPTR]
}

__declspec(naked)
void APIENTRY glFogi( GLenum pname, GLint param)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Fogi*SZPTR]
}

__declspec(naked)
void APIENTRY glFogiv( GLenum pname, const GLint *params)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Fogiv*SZPTR]
}

__declspec(naked)
void APIENTRY glFrontFace( GLenum mode)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_FrontFace*SZPTR]
}

__declspec(naked)
void APIENTRY glHint( GLenum target, GLenum mode)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Hint*SZPTR]
}

__declspec(naked)
void APIENTRY glLightf( GLenum light, GLenum pname, GLfloat param)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Lightf*SZPTR]
}

__declspec(naked)
void APIENTRY glLightfv( GLenum light, GLenum pname, const GLfloat *params)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Lightfv*SZPTR]
}

__declspec(naked)
void APIENTRY glLighti( GLenum light, GLenum pname, GLint param)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Lighti*SZPTR]
}

__declspec(naked)
void APIENTRY glLightiv( GLenum light, GLenum pname, const GLint *params)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Lightiv*SZPTR]
}

__declspec(naked)
void APIENTRY glLightModelf( GLenum pname, GLfloat param)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_LightModelf*SZPTR]
}

__declspec(naked)
void APIENTRY glLightModelfv( GLenum pname, const GLfloat *params)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_LightModelfv*SZPTR]
}

__declspec(naked)
void APIENTRY glLightModeli( GLenum pname, GLint param)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_LightModeli*SZPTR]
}

__declspec(naked)
void APIENTRY glLightModeliv( GLenum pname, const GLint *params)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_LightModeliv*SZPTR]
}

__declspec(naked)
void APIENTRY glLineStipple( GLint factor, GLushort pattern)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_LineStipple*SZPTR]
}

__declspec(naked)
void APIENTRY glLineWidth( GLfloat width)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_LineWidth*SZPTR]
}

__declspec(naked)
void APIENTRY glMaterialf( GLenum face, GLenum pname, GLfloat param)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Materialf*SZPTR]
}

__declspec(naked)
void APIENTRY glMaterialfv( GLenum face, GLenum pname, const GLfloat *params)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Materialfv*SZPTR]
}

__declspec(naked)
void APIENTRY glMateriali( GLenum face, GLenum pname, GLint param)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Materiali*SZPTR]
}

__declspec(naked)
void APIENTRY glMaterialiv( GLenum face, GLenum pname, const GLint *params)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Materialiv*SZPTR]
}

__declspec(naked)
void APIENTRY glPointSize( GLfloat size)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_PointSize*SZPTR]
}

__declspec(naked)
void APIENTRY glPolygonMode( GLenum face, GLenum mode)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_PolygonMode*SZPTR]
}

__declspec(naked)
void APIENTRY glPolygonStipple( const GLubyte *mask)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_PolygonStipple*SZPTR]
}

__declspec(naked)
void APIENTRY glScissor( GLint x, GLint y, GLsizei width, GLsizei height)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Scissor*SZPTR]
}

__declspec(naked)
void APIENTRY glShadeModel( GLenum mode)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_ShadeModel*SZPTR]
}

__declspec(naked)
void APIENTRY glTexParameterf( GLenum target, GLenum pname, GLfloat param)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_TexParameterf*SZPTR]
}

__declspec(naked)
void APIENTRY glTexParameterfv( GLenum target, GLenum pname, const GLfloat *params)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_TexParameterfv*SZPTR]
}

__declspec(naked)
void APIENTRY glTexParameteri( GLenum target, GLenum pname, GLint param)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_TexParameteri*SZPTR]
}

__declspec(naked)
void APIENTRY glTexParameteriv( GLenum target, GLenum pname, const GLint *params)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_TexParameteriv*SZPTR]
}

__declspec(naked)
void APIENTRY glTexImage1D( GLenum target, GLint level, GLint components, GLsizei width, GLint border, GLenum format, GLenum type, const GLvoid *pixels)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_TexImage1D*SZPTR]
}

__declspec(naked)
void APIENTRY glTexImage2D( GLenum target, GLint level, GLint components, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid *pixels)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_TexImage2D*SZPTR]
}

__declspec(naked)
void APIENTRY glTexEnvf( GLenum target, GLenum pname, GLfloat param)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_TexEnvf*SZPTR]
}

__declspec(naked)
void APIENTRY glTexEnvfv( GLenum target, GLenum pname, const GLfloat *params)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_TexEnvfv*SZPTR]
}

__declspec(naked)
void APIENTRY glTexEnvi( GLenum target, GLenum pname, GLint param)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_TexEnvi*SZPTR]
}

__declspec(naked)
void APIENTRY glTexEnviv( GLenum target, GLenum pname, const GLint *params)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_TexEnviv*SZPTR]
}

__declspec(naked)
void APIENTRY glTexGend( GLenum coord, GLenum pname, GLdouble param)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_TexGend*SZPTR]
}

__declspec(naked)
void APIENTRY glTexGendv( GLenum coord, GLenum pname, const GLdouble *params)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_TexGendv*SZPTR]
}

__declspec(naked)
void APIENTRY glTexGenf( GLenum coord, GLenum pname, GLfloat param)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_TexGenf*SZPTR]
}

__declspec(naked)
void APIENTRY glTexGenfv( GLenum coord, GLenum pname, const GLfloat *params)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_TexGenfv*SZPTR]
}

__declspec(naked)
void APIENTRY glTexGeni( GLenum coord, GLenum pname, GLint param)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_TexGeni*SZPTR]
}

__declspec(naked)
void APIENTRY glTexGeniv( GLenum coord, GLenum pname, const GLint *params)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_TexGeniv*SZPTR]
}

__declspec(naked)
void APIENTRY glFeedbackBuffer( GLsizei size, GLenum type, GLfloat *buffer)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_FeedbackBuffer*SZPTR]
}

__declspec(naked)
void APIENTRY glSelectBuffer( GLsizei size, GLuint *buffer)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_SelectBuffer*SZPTR]
}

__declspec(naked)
GLint APIENTRY glRenderMode( GLenum mode)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_RenderMode*SZPTR]
}

__declspec(naked)
void APIENTRY glInitNames( void)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_InitNames*SZPTR]
}

__declspec(naked)
void APIENTRY glLoadName( GLuint name)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_LoadName*SZPTR]
}

__declspec(naked)
void APIENTRY glPassThrough( GLfloat token)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_PassThrough*SZPTR]
}

__declspec(naked)
void APIENTRY glPopName( void)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_PopName*SZPTR]
}

__declspec(naked)
void APIENTRY glPushName( GLuint name)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_PushName*SZPTR]
}

__declspec(naked)
void APIENTRY glDrawBuffer( GLenum mode)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_DrawBuffer*SZPTR]
}

__declspec(naked)
void APIENTRY glClear( GLbitfield mask)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Clear*SZPTR]
}

__declspec(naked)
void APIENTRY glClearAccum( GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_ClearAccum*SZPTR]
}

__declspec(naked)
void APIENTRY glClearIndex( GLfloat c)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_ClearIndex*SZPTR]
}

__declspec(naked)
void APIENTRY glClearColor( GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_ClearColor*SZPTR]
}

__declspec(naked)
void APIENTRY glClearStencil( GLint s)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_ClearStencil*SZPTR]
}

__declspec(naked)
void APIENTRY glClearDepth( GLclampd depth)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_ClearDepth*SZPTR]
}

__declspec(naked)
void APIENTRY glStencilMask( GLuint mask)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_StencilMask*SZPTR]
}

__declspec(naked)
void APIENTRY glColorMask( GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_ColorMask*SZPTR]
}

__declspec(naked)
void APIENTRY glDepthMask( GLboolean flag)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_DepthMask*SZPTR]
}

__declspec(naked)
void APIENTRY glIndexMask( GLuint mask)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_IndexMask*SZPTR]
}

__declspec(naked)
void APIENTRY glAccum( GLenum op, GLfloat value)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Accum*SZPTR]
}

__declspec(naked)
void APIENTRY glDisable( GLenum cap)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Disable*SZPTR]
}

__declspec(naked)
void APIENTRY glEnable( GLenum cap)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Enable*SZPTR]
}

__declspec(naked)
void APIENTRY glFinish( void)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Finish*SZPTR]
}

__declspec(naked)
void APIENTRY glFlush( void)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Flush*SZPTR]
}

__declspec(naked)
void APIENTRY glPopAttrib( void)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_PopAttrib*SZPTR]
}

__declspec(naked)
void APIENTRY glPushAttrib( GLbitfield mask)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_PushAttrib*SZPTR]
}

__declspec(naked)
void APIENTRY glMap1d( GLenum target, GLdouble u1, GLdouble u2, GLint stride, GLint order, const GLdouble *points)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Map1d*SZPTR]
}

__declspec(naked)
void APIENTRY glMap1f( GLenum target, GLfloat u1, GLfloat u2, GLint stride, GLint order, const GLfloat *points)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Map1f*SZPTR]
}

__declspec(naked)
void APIENTRY glMap2d( GLenum target, GLdouble u1, GLdouble u2, GLint ustride, GLint uorder, GLdouble v1, GLdouble v2, GLint vstride, GLint vorder, const GLdouble *points)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Map2d*SZPTR]
}

__declspec(naked)
void APIENTRY glMap2f( GLenum target, GLfloat u1, GLfloat u2, GLint ustride, GLint uorder, GLfloat v1, GLfloat v2, GLint vstride, GLint vorder, const GLfloat *points)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Map2f*SZPTR]
}

__declspec(naked)
void APIENTRY glMapGrid1d( GLint un, GLdouble u1, GLdouble u2)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_MapGrid1d*SZPTR]
}

__declspec(naked)
void APIENTRY glMapGrid1f( GLint un, GLfloat u1, GLfloat u2)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_MapGrid1f*SZPTR]
}

__declspec(naked)
void APIENTRY glMapGrid2d( GLint un, GLdouble u1, GLdouble u2, GLint vn, GLdouble v1, GLdouble v2)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_MapGrid2d*SZPTR]
}

__declspec(naked)
void APIENTRY glMapGrid2f( GLint un, GLfloat u1, GLfloat u2, GLint vn, GLfloat v1, GLfloat v2)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_MapGrid2f*SZPTR]
}

__declspec(naked)
void APIENTRY glEvalCoord1d( GLdouble u)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_EvalCoord1d*SZPTR]
}

__declspec(naked)
void APIENTRY glEvalCoord1dv( const GLdouble *u)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_EvalCoord1dv*SZPTR]
}

__declspec(naked)
void APIENTRY glEvalCoord1f( GLfloat u)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_EvalCoord1f*SZPTR]
}

__declspec(naked)
void APIENTRY glEvalCoord1fv( const GLfloat *u)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_EvalCoord1fv*SZPTR]
}

__declspec(naked)
void APIENTRY glEvalCoord2d( GLdouble u, GLdouble v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_EvalCoord2d*SZPTR]
}

__declspec(naked)
void APIENTRY glEvalCoord2dv( const GLdouble *u)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_EvalCoord2dv*SZPTR]
}

__declspec(naked)
void APIENTRY glEvalCoord2f( GLfloat u, GLfloat v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_EvalCoord2f*SZPTR]
}

__declspec(naked)
void APIENTRY glEvalCoord2fv( const GLfloat *u)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_EvalCoord2fv*SZPTR]
}

__declspec(naked)
void APIENTRY glEvalMesh1( GLenum mode, GLint i1, GLint i2)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_EvalMesh1*SZPTR]
}

__declspec(naked)
void APIENTRY glEvalPoint1( GLint i)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_EvalPoint1*SZPTR]
}

__declspec(naked)
void APIENTRY glEvalMesh2( GLenum mode, GLint i1, GLint i2, GLint j1, GLint j2)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_EvalMesh2*SZPTR]
}

__declspec(naked)
void APIENTRY glEvalPoint2( GLint i, GLint j)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_EvalPoint2*SZPTR]
}

__declspec(naked)
void APIENTRY glAlphaFunc( GLenum func, GLclampf ref)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_AlphaFunc*SZPTR]
}

__declspec(naked)
void APIENTRY glBlendFunc( GLenum sfactor, GLenum dfactor)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_BlendFunc*SZPTR]
}

__declspec(naked)
void APIENTRY glLogicOp( GLenum opcode)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_LogicOp*SZPTR]
}

__declspec(naked)
void APIENTRY glStencilFunc( GLenum func, GLint ref, GLuint mask)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_StencilFunc*SZPTR]
}

__declspec(naked)
void APIENTRY glStencilOp( GLenum fail, GLenum zfail, GLenum zpass)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_StencilOp*SZPTR]
}

__declspec(naked)
void APIENTRY glDepthFunc( GLenum func)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_DepthFunc*SZPTR]
}

__declspec(naked)
void APIENTRY glPixelZoom( GLfloat xfactor, GLfloat yfactor)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_PixelZoom*SZPTR]
}

__declspec(naked)
void APIENTRY glPixelTransferf( GLenum pname, GLfloat param)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_PixelTransferf*SZPTR]
}

__declspec(naked)
void APIENTRY glPixelTransferi( GLenum pname, GLint param)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_PixelTransferi*SZPTR]
}

__declspec(naked)
void APIENTRY glPixelStoref( GLenum pname, GLfloat param)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_PixelStoref*SZPTR]
}

__declspec(naked)
void APIENTRY glPixelStorei( GLenum pname, GLint param)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_PixelStorei*SZPTR]
}

__declspec(naked)
void APIENTRY glPixelMapfv( GLenum map, GLint mapsize, const GLfloat *values)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_PixelMapfv*SZPTR]
}

__declspec(naked)
void APIENTRY glPixelMapuiv( GLenum map, GLint mapsize, const GLuint *values)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_PixelMapuiv*SZPTR]
}

__declspec(naked)
void APIENTRY glPixelMapusv( GLenum map, GLint mapsize, const GLushort *values)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_PixelMapusv*SZPTR]
}

__declspec(naked)
void APIENTRY glReadBuffer( GLenum mode)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_ReadBuffer*SZPTR]
}

__declspec(naked)
void APIENTRY glCopyPixels( GLint x, GLint y, GLsizei width, GLsizei height, GLenum type)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_CopyPixels*SZPTR]
}

__declspec(naked)
void APIENTRY glReadPixels( GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid *pixels)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_ReadPixels*SZPTR]
}

__declspec(naked)
void APIENTRY glDrawPixels( GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_DrawPixels*SZPTR]
}

__declspec(naked)
void APIENTRY glGetBooleanv( GLenum pname, GLboolean *params)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_GetBooleanv*SZPTR]
}

__declspec(naked)
void APIENTRY glGetClipPlane( GLenum plane, GLdouble *equation)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_GetClipPlane*SZPTR]
}

__declspec(naked)
void APIENTRY glGetDoublev( GLenum pname, GLdouble *params)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_GetDoublev*SZPTR]
}

__declspec(naked)
GLenum APIENTRY glGetError( void)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_GetError*SZPTR]
}

__declspec(naked)
void APIENTRY glGetFloatv( GLenum pname, GLfloat *params)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_GetFloatv*SZPTR]
}

__declspec(naked)
void APIENTRY glGetIntegerv( GLenum pname, GLint *params)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_GetIntegerv*SZPTR]
}

__declspec(naked)
void APIENTRY glGetLightfv( GLenum light, GLenum pname, GLfloat *params)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_GetLightfv*SZPTR]
}

__declspec(naked)
void APIENTRY glGetLightiv( GLenum light, GLenum pname, GLint *params)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_GetLightiv*SZPTR]
}

__declspec(naked)
void APIENTRY glGetMapdv( GLenum target, GLenum query, GLdouble *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_GetMapdv*SZPTR]
}

__declspec(naked)
void APIENTRY glGetMapfv( GLenum target, GLenum query, GLfloat *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_GetMapfv*SZPTR]
}

__declspec(naked)
void APIENTRY glGetMapiv( GLenum target, GLenum query, GLint *v)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_GetMapiv*SZPTR]
}

__declspec(naked)
void APIENTRY glGetMaterialfv( GLenum face, GLenum pname, GLfloat *params)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_GetMaterialfv*SZPTR]
}

__declspec(naked)
void APIENTRY glGetMaterialiv( GLenum face, GLenum pname, GLint *params)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_GetMaterialiv*SZPTR]
}

__declspec(naked)
void APIENTRY glGetPixelMapfv( GLenum map, GLfloat *values)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_GetPixelMapfv*SZPTR]
}

__declspec(naked)
void APIENTRY glGetPixelMapuiv( GLenum map, GLuint *values)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_GetPixelMapuiv*SZPTR]
}

__declspec(naked)
void APIENTRY glGetPixelMapusv( GLenum map, GLushort *values)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_GetPixelMapusv*SZPTR]
}

__declspec(naked)
void APIENTRY glGetPolygonStipple( GLubyte *mask)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_GetPolygonStipple*SZPTR]
}

__declspec(naked)
const GLubyte * APIENTRY glGetString( GLenum name)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_GetString*SZPTR]
}

__declspec(naked)
void APIENTRY glGetTexEnvfv( GLenum target, GLenum pname, GLfloat *params)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_GetTexEnvfv*SZPTR]
}

__declspec(naked)
void APIENTRY glGetTexEnviv( GLenum target, GLenum pname, GLint *params)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_GetTexEnviv*SZPTR]
}

__declspec(naked)
void APIENTRY glGetTexGendv( GLenum coord, GLenum pname, GLdouble *params)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_GetTexGendv*SZPTR]
}

__declspec(naked)
void APIENTRY glGetTexGenfv( GLenum coord, GLenum pname, GLfloat *params)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_GetTexGenfv*SZPTR]
}

__declspec(naked)
void APIENTRY glGetTexGeniv( GLenum coord, GLenum pname, GLint *params)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_GetTexGeniv*SZPTR]
}

__declspec(naked)
void APIENTRY glGetTexImage( GLenum target, GLint level, GLenum format, GLenum type, GLvoid *pixels)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_GetTexImage*SZPTR]
}

__declspec(naked)
void APIENTRY glGetTexParameterfv( GLenum target, GLenum pname, GLfloat *params)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_GetTexParameterfv*SZPTR]
}

__declspec(naked)
void APIENTRY glGetTexParameteriv( GLenum target, GLenum pname, GLint *params)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_GetTexParameteriv*SZPTR]
}

__declspec(naked)
void APIENTRY glGetTexLevelParameterfv( GLenum target, GLint level, GLenum pname, GLfloat *params)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_GetTexLevelParameterfv*SZPTR]
}

__declspec(naked)
void APIENTRY glGetTexLevelParameteriv( GLenum target, GLint level, GLenum pname, GLint *params)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_GetTexLevelParameteriv*SZPTR]
}

__declspec(naked)
GLboolean APIENTRY glIsEnabled( GLenum cap)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_IsEnabled*SZPTR]
}

__declspec(naked)
GLboolean APIENTRY glIsList( GLuint list)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_IsList*SZPTR]
}

__declspec(naked)
void APIENTRY glDepthRange( GLclampd zNear, GLclampd zFar)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_DepthRange*SZPTR]
}

__declspec(naked)
void APIENTRY glFrustum( GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble zNear, GLdouble zFar)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Frustum*SZPTR]
}

__declspec(naked)
void APIENTRY glLoadIdentity( void)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_LoadIdentity*SZPTR]
}

__declspec(naked)
void APIENTRY glLoadMatrixf( const GLfloat *m)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_LoadMatrixf*SZPTR]
}

__declspec(naked)
void APIENTRY glLoadMatrixd( const GLdouble *m)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_LoadMatrixd*SZPTR]
}

__declspec(naked)
void APIENTRY glMatrixMode( GLenum mode)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_MatrixMode*SZPTR]
}

__declspec(naked)
void APIENTRY glMultMatrixf( const GLfloat *m)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_MultMatrixf*SZPTR]
}

__declspec(naked)
void APIENTRY glMultMatrixd( const GLdouble *m)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_MultMatrixd*SZPTR]
}

__declspec(naked)
void APIENTRY glOrtho( GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble zNear, GLdouble zFar)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Ortho*SZPTR]
}

__declspec(naked)
void APIENTRY glPopMatrix( void)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_PopMatrix*SZPTR]
}

__declspec(naked)
void APIENTRY glPushMatrix( void)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_PushMatrix*SZPTR]
}

__declspec(naked)
void APIENTRY glRotated( GLdouble angle, GLdouble x, GLdouble y, GLdouble z)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Rotated*SZPTR]
}

__declspec(naked)
void APIENTRY glRotatef( GLfloat angle, GLfloat x, GLfloat y, GLfloat z)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Rotatef*SZPTR]
}

__declspec(naked)
void APIENTRY glScaled( GLdouble x, GLdouble y, GLdouble z)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Scaled*SZPTR]
}

__declspec(naked)
void APIENTRY glScalef( GLfloat x, GLfloat y, GLfloat z)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Scalef*SZPTR]
}

__declspec(naked)
void APIENTRY glTranslated( GLdouble x, GLdouble y, GLdouble z)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Translated*SZPTR]
}

__declspec(naked)
void APIENTRY glTranslatef( GLfloat x, GLfloat y, GLfloat z)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Translatef*SZPTR]
}

__declspec(naked)
void APIENTRY glViewport( GLint x, GLint y, GLsizei width, GLsizei height)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Viewport*SZPTR]
}

__declspec(naked)
void APIENTRY glArrayElementEXT( GLint i)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_extensions+__GL_EXTTAB_ArrayElementEXT*SZPTR]
}

__declspec(naked)
void APIENTRY glColorPointerEXT( GLint size, GLenum type, GLsizei stride, GLsizei count, const GLvoid *pointer)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_extensions+__GL_EXTTAB_ColorPointerEXT*SZPTR]
}

__declspec(naked)
void APIENTRY glDrawArraysEXT( GLenum mode, GLint first, GLsizei count)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_extensions+__GL_EXTTAB_DrawArraysEXT*SZPTR]
}

__declspec(naked)
void APIENTRY glEdgeFlagPointerEXT( GLsizei stride, GLsizei count, const GLboolean *pointer)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_extensions+__GL_EXTTAB_EdgeFlagPointerEXT*SZPTR]
}

__declspec(naked)
void APIENTRY glGetPointervEXT( GLenum pname, GLvoid* *params)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_extensions+__GL_EXTTAB_GetPointervEXT*SZPTR]
}

__declspec(naked)
void APIENTRY glIndexPointerEXT( GLenum type, GLsizei stride, GLsizei count, const GLvoid *pointer)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_extensions+__GL_EXTTAB_IndexPointerEXT*SZPTR]
}

__declspec(naked)
void APIENTRY glNormalPointerEXT( GLenum type, GLsizei stride, GLsizei count, const GLvoid *pointer)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_extensions+__GL_EXTTAB_NormalPointerEXT*SZPTR]
}

__declspec(naked)
void APIENTRY glTexCoordPointerEXT( GLint size, GLenum type, GLsizei stride, GLsizei count, const GLvoid *pointer)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_extensions+__GL_EXTTAB_TexCoordPointerEXT*SZPTR]
}

__declspec(naked)
void APIENTRY glVertexPointerEXT( GLint size, GLenum type, GLsizei stride, GLsizei count, const GLvoid *pointer)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_extensions+__GL_EXTTAB_VertexPointerEXT*SZPTR]
}

__declspec(naked)
void APIENTRY glColorSubTableEXT( GLenum target, GLsizei start, GLsizei count, GLenum format, GLenum type, const GLvoid *table)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_extensions+__GL_EXTTAB_ColorSubTableEXT*SZPTR]
}

__declspec(naked)
void APIENTRY glColorTableEXT( GLenum target, GLenum internalformat, GLsizei width, GLenum format, GLenum type, const GLvoid *table)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_extensions+__GL_EXTTAB_ColorTableEXT*SZPTR]
}

__declspec(naked)
void APIENTRY glCopyColorTableEXT( GLenum target, GLenum internalformat, GLint x, GLint y, GLsizei width)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_extensions+__GL_EXTTAB_CopyColorTableEXT*SZPTR]
}

__declspec(naked)
void APIENTRY glGetColorTableEXT( GLenum target, GLenum format, GLenum type, GLvoid *table)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_extensions+__GL_EXTTAB_GetColorTableEXT*SZPTR]
}

__declspec(naked)
void APIENTRY glGetColorTableParameterfvEXT( GLenum target, GLenum pname, GLfloat *params)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_extensions+__GL_EXTTAB_GetColorTableParameterfvEXT*SZPTR]
}

__declspec(naked)
void APIENTRY glGetColorTableParameterivEXT( GLenum target, GLenum pname, GLint *params)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_extensions+__GL_EXTTAB_GetColorTableParameterivEXT*SZPTR]
}

__declspec(naked)
void APIENTRY glArrayElement( GLint i)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_ArrayElement*SZPTR]
}

__declspec(naked)
void APIENTRY glColorPointer( GLint size, GLenum type, GLsizei stride, const GLvoid *pointer)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_ColorPointer*SZPTR]
}

__declspec(naked)
void APIENTRY glDisableClientState( GLenum array)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_DisableClientState*SZPTR]
}

__declspec(naked)
void APIENTRY glDrawArrays( GLenum mode, GLint first, GLsizei count)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_DrawArrays*SZPTR]
}

__declspec(naked)
void APIENTRY glDrawElements( GLenum mode, GLsizei count, GLenum type, const GLvoid *indices)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_DrawElements*SZPTR]
}

__declspec(naked)
void APIENTRY glEdgeFlagPointer( GLsizei stride, const GLboolean *pointer)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_EdgeFlagPointer*SZPTR]
}

__declspec(naked)
void APIENTRY glEnableClientState( GLenum array)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_EnableClientState*SZPTR]
}

__declspec(naked)
void APIENTRY glGetPointerv( GLenum pname, GLvoid* *params)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_GetPointerv*SZPTR]
}

__declspec(naked)
void APIENTRY glIndexPointer( GLenum type, GLsizei stride, const GLvoid *pointer)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_IndexPointer*SZPTR]
}

__declspec(naked)
void APIENTRY glInterleavedArrays( GLenum format, GLsizei stride, const GLvoid *pointer)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_InterleavedArrays*SZPTR]
}

__declspec(naked)
void APIENTRY glNormalPointer( GLenum type, GLsizei stride, const GLvoid *pointer)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_NormalPointer*SZPTR]
}

__declspec(naked)
void APIENTRY glTexCoordPointer( GLint size, GLenum type, GLsizei stride, const GLvoid *pointer)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_TexCoordPointer*SZPTR]
}

__declspec(naked)
void APIENTRY glVertexPointer( GLint size, GLenum type, GLsizei stride, const GLvoid *pointer)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_VertexPointer*SZPTR]
}

__declspec(naked)
void APIENTRY glPolygonOffset( GLfloat factor, GLfloat units)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_PolygonOffset*SZPTR]
}

__declspec(naked)
void APIENTRY glCopyTexImage1D( GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLint border)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_CopyTexImage1D*SZPTR]
}

__declspec(naked)
void APIENTRY glCopyTexImage2D( GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_CopyTexImage2D*SZPTR]
}

__declspec(naked)
void APIENTRY glCopyTexSubImage1D( GLenum target, GLint level, GLint xoffset, GLint x, GLint y, GLsizei width)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_CopyTexSubImage1D*SZPTR]
}

__declspec(naked)
void APIENTRY glCopyTexSubImage2D( GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_CopyTexSubImage2D*SZPTR]
}

__declspec(naked)
void APIENTRY glTexSubImage1D( GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const GLvoid *pixels)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_TexSubImage1D*SZPTR]
}

__declspec(naked)
void APIENTRY glTexSubImage2D( GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_TexSubImage2D*SZPTR]
}

__declspec(naked)
GLboolean APIENTRY glAreTexturesResident( GLsizei n, const GLuint *textures, GLboolean *residences)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_AreTexturesResident*SZPTR]
}

__declspec(naked)
void APIENTRY glBindTexture( GLenum target, GLuint texture)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_BindTexture*SZPTR]
}

__declspec(naked)
void APIENTRY glDeleteTextures( GLsizei n, const GLuint *textures)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_DeleteTextures*SZPTR]
}

__declspec(naked)
void APIENTRY glGenTextures( GLsizei n, GLuint *textures)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_GenTextures*SZPTR]
}

__declspec(naked)
GLboolean APIENTRY glIsTexture( GLuint texture)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_IsTexture*SZPTR]
}

__declspec(naked)
void APIENTRY glPrioritizeTextures( GLsizei n, const GLuint *textures, const GLclampf *priorities)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_PrioritizeTextures*SZPTR]
}

__declspec(naked)
void APIENTRY glIndexub( GLubyte c)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Indexub*SZPTR]
}

__declspec(naked)
void APIENTRY glIndexubv( const GLubyte *c)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_Indexubv*SZPTR]
}

__declspec(naked)
void APIENTRY glPopClientAttrib( void)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_PopClientAttrib*SZPTR]
}

__declspec(naked)
void APIENTRY glPushClientAttrib( GLbitfield mask)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_dispatch+__GL_TAB_PushClientAttrib*SZPTR]
}

__declspec(naked)
void APIENTRY glLockArraysSGI( GLint first, GLsizei count)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_extensions+__GL_EXTTAB_LockArraysSGI*SZPTR]
}

__declspec(naked)
void APIENTRY glUnlockArraysSGI( void)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_extensions+__GL_EXTTAB_UnlockArraysSGI*SZPTR]
}

__declspec(naked)
void APIENTRY glCullParameterdvSGI( GLenum pname, GLdouble* params)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_extensions+__GL_EXTTAB_CullParameterdvSGI*SZPTR]
}

__declspec(naked)
void APIENTRY glCullParameterfvSGI( GLenum pname, GLfloat* params)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_extensions+__GL_EXTTAB_CullParameterfvSGI*SZPTR]
}

__declspec(naked)
void APIENTRY glIndexFuncSGI( GLenum func, GLclampf ref)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_extensions+__GL_EXTTAB_IndexFuncSGI*SZPTR]
}

__declspec(naked)
void APIENTRY glIndexMaterialSGI( GLenum face, GLenum mode)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_extensions+__GL_EXTTAB_IndexMaterialSGI*SZPTR]
}

__declspec(naked)
void APIENTRY glAddSwapHintRectWIN( GLint x, GLint y, GLsizei width, GLsizei height)
{
    __GL_GET_TLSCX_VALUE()
    __asm jmp [eax+__gltp_extensions+__GL_EXTTAB_AddSwapHintRectWIN*SZPTR]
}

