
/* DO NOT EDIT - THIS FILE IS AUTOMATICALLY GENERATED */

/*
** Copyright 1992-1997 Silicon Graphics, Inc.
** All Rights Reserved.
**
** This is UNPUBLISHED PROPRIETARY SOURCE CODE of Silicon Graphics, Inc.;
** the contents of this file may not be disclosed to third parties, copied or
** duplicated in any form, in whole or in part, without the prior written
** permission of Silicon Graphics, Inc.
**
** RESTRICTED RIGHTS LEGEND:
** Use, duplication or disclosure by the Government is subject to restrictions
** as set forth in subdivision (c)(1)(ii) of the Rights in Technical Data
** and Computer Software clause at DFARS 252.227-7013, and/or in similar or
** successor clauses in the FAR, DOD or NASA FAR Supplement. Unpublished -
** rights reserved under the Copyright Laws of the United States.
*/

/* This file generated by dlist.ls -- DO NOT EDIT! */
#include "context.h"
#include "global.h"
#include "dlist.h"
#include "dlistopt.h"
#include "g_lcomp.h"
#include "g_listop.h"
#include "imports.h"

void APIENTRY __glce_NewList(GLuint list, GLenum mode);
void APIENTRY __glce_EndList(void);
void APIENTRY __glce_CallList(GLuint list);
void APIENTRY __glce_CallLists(GLsizei n, GLenum type, const GLvoid *lists);
void APIENTRY __glce_DeleteLists(GLuint list, GLsizei range);
GLuint APIENTRY __glce_GenLists(GLsizei range);
void APIENTRY __glce_ListBase(GLuint base);
const GLubyte *__glle_ListBase(const GLubyte *PC)
{
    struct __gllc_ListBase_Rec *data;

    data = (struct __gllc_ListBase_Rec *) PC;
    (*__gl_dispatch.dispatch.ListBase)(data->base);
    return PC + sizeof(struct __gllc_ListBase_Rec);
}

void APIENTRY __glce_Begin(GLenum mode);
void APIENTRY __glce_Bitmap(GLsizei width, GLsizei height, GLfloat xorig, GLfloat yorig, GLfloat xmove, GLfloat ymove, const GLubyte *bitmap);
void APIENTRY __glce_Color3b(GLbyte red, GLbyte green, GLbyte blue);
void APIENTRY __glce_Color3bv(const GLbyte *v);
const GLubyte *__glle_Color3bv(const GLubyte *PC)
{
    struct __gllc_Color3bv_Rec *data;

    data = (struct __gllc_Color3bv_Rec *) PC;
    (*__gl_dispatch.dispatch.Color3bv)(data->v);
    return PC + sizeof(struct __gllc_Color3bv_Rec);
}

void APIENTRY __glce_Color3d(GLdouble red, GLdouble green, GLdouble blue);
void APIENTRY __glce_Color3dv(const GLdouble *v);
const GLubyte *__glle_Color3dv(const GLubyte *PC)
{
    struct __gllc_Color3dv_Rec *data;

    data = (struct __gllc_Color3dv_Rec *) PC;
    (*__gl_dispatch.dispatch.Color3dv)(data->v);
    return PC + sizeof(struct __gllc_Color3dv_Rec);
}

void APIENTRY __glce_Color3f(GLfloat red, GLfloat green, GLfloat blue);
void APIENTRY __glce_Color3fv(const GLfloat *v);
const GLubyte *__glle_Color3fv(const GLubyte *PC)
{
    struct __gllc_Color3fv_Rec *data;

    data = (struct __gllc_Color3fv_Rec *) PC;
    (*__gl_dispatch.dispatch.Color3fv)(data->v);
    return PC + sizeof(struct __gllc_Color3fv_Rec);
}

void APIENTRY __glce_Color3i(GLint red, GLint green, GLint blue);
void APIENTRY __glce_Color3iv(const GLint *v);
const GLubyte *__glle_Color3iv(const GLubyte *PC)
{
    struct __gllc_Color3iv_Rec *data;

    data = (struct __gllc_Color3iv_Rec *) PC;
    (*__gl_dispatch.dispatch.Color3iv)(data->v);
    return PC + sizeof(struct __gllc_Color3iv_Rec);
}

void APIENTRY __glce_Color3s(GLshort red, GLshort green, GLshort blue);
void APIENTRY __glce_Color3sv(const GLshort *v);
const GLubyte *__glle_Color3sv(const GLubyte *PC)
{
    struct __gllc_Color3sv_Rec *data;

    data = (struct __gllc_Color3sv_Rec *) PC;
    (*__gl_dispatch.dispatch.Color3sv)(data->v);
    return PC + sizeof(struct __gllc_Color3sv_Rec);
}

void APIENTRY __glce_Color3ub(GLubyte red, GLubyte green, GLubyte blue);
void APIENTRY __glce_Color3ubv(const GLubyte *v);
const GLubyte *__glle_Color3ubv(const GLubyte *PC)
{
    struct __gllc_Color3ubv_Rec *data;

    data = (struct __gllc_Color3ubv_Rec *) PC;
    (*__gl_dispatch.dispatch.Color3ubv)(data->v);
    return PC + sizeof(struct __gllc_Color3ubv_Rec);
}

void APIENTRY __glce_Color3ui(GLuint red, GLuint green, GLuint blue);
void APIENTRY __glce_Color3uiv(const GLuint *v);
const GLubyte *__glle_Color3uiv(const GLubyte *PC)
{
    struct __gllc_Color3uiv_Rec *data;

    data = (struct __gllc_Color3uiv_Rec *) PC;
    (*__gl_dispatch.dispatch.Color3uiv)(data->v);
    return PC + sizeof(struct __gllc_Color3uiv_Rec);
}

void APIENTRY __glce_Color3us(GLushort red, GLushort green, GLushort blue);
void APIENTRY __glce_Color3usv(const GLushort *v);
const GLubyte *__glle_Color3usv(const GLubyte *PC)
{
    struct __gllc_Color3usv_Rec *data;

    data = (struct __gllc_Color3usv_Rec *) PC;
    (*__gl_dispatch.dispatch.Color3usv)(data->v);
    return PC + sizeof(struct __gllc_Color3usv_Rec);
}

void APIENTRY __glce_Color4b(GLbyte red, GLbyte green, GLbyte blue, GLbyte alpha);
void APIENTRY __glce_Color4bv(const GLbyte *v);
const GLubyte *__glle_Color4bv(const GLubyte *PC)
{
    struct __gllc_Color4bv_Rec *data;

    data = (struct __gllc_Color4bv_Rec *) PC;
    (*__gl_dispatch.dispatch.Color4bv)(data->v);
    return PC + sizeof(struct __gllc_Color4bv_Rec);
}

void APIENTRY __glce_Color4d(GLdouble red, GLdouble green, GLdouble blue, GLdouble alpha);
void APIENTRY __glce_Color4dv(const GLdouble *v);
const GLubyte *__glle_Color4dv(const GLubyte *PC)
{
    struct __gllc_Color4dv_Rec *data;

    data = (struct __gllc_Color4dv_Rec *) PC;
    (*__gl_dispatch.dispatch.Color4dv)(data->v);
    return PC + sizeof(struct __gllc_Color4dv_Rec);
}

void APIENTRY __glce_Color4f(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
void APIENTRY __glce_Color4fv(const GLfloat *v);
const GLubyte *__glle_Color4fv(const GLubyte *PC)
{
    struct __gllc_Color4fv_Rec *data;

    data = (struct __gllc_Color4fv_Rec *) PC;
    (*__gl_dispatch.dispatch.Color4fv)(data->v);
    return PC + sizeof(struct __gllc_Color4fv_Rec);
}

void APIENTRY __glce_Color4i(GLint red, GLint green, GLint blue, GLint alpha);
void APIENTRY __glce_Color4iv(const GLint *v);
const GLubyte *__glle_Color4iv(const GLubyte *PC)
{
    struct __gllc_Color4iv_Rec *data;

    data = (struct __gllc_Color4iv_Rec *) PC;
    (*__gl_dispatch.dispatch.Color4iv)(data->v);
    return PC + sizeof(struct __gllc_Color4iv_Rec);
}

void APIENTRY __glce_Color4s(GLshort red, GLshort green, GLshort blue, GLshort alpha);
void APIENTRY __glce_Color4sv(const GLshort *v);
const GLubyte *__glle_Color4sv(const GLubyte *PC)
{
    struct __gllc_Color4sv_Rec *data;

    data = (struct __gllc_Color4sv_Rec *) PC;
    (*__gl_dispatch.dispatch.Color4sv)(data->v);
    return PC + sizeof(struct __gllc_Color4sv_Rec);
}

void APIENTRY __glce_Color4ub(GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha);
void APIENTRY __glce_Color4ubv(const GLubyte *v);
const GLubyte *__glle_Color4ubv(const GLubyte *PC)
{
    struct __gllc_Color4ubv_Rec *data;

    data = (struct __gllc_Color4ubv_Rec *) PC;
    (*__gl_dispatch.dispatch.Color4ubv)(data->v);
    return PC + sizeof(struct __gllc_Color4ubv_Rec);
}

void APIENTRY __glce_Color4ui(GLuint red, GLuint green, GLuint blue, GLuint alpha);
void APIENTRY __glce_Color4uiv(const GLuint *v);
const GLubyte *__glle_Color4uiv(const GLubyte *PC)
{
    struct __gllc_Color4uiv_Rec *data;

    data = (struct __gllc_Color4uiv_Rec *) PC;
    (*__gl_dispatch.dispatch.Color4uiv)(data->v);
    return PC + sizeof(struct __gllc_Color4uiv_Rec);
}

void APIENTRY __glce_Color4us(GLushort red, GLushort green, GLushort blue, GLushort alpha);
void APIENTRY __glce_Color4usv(const GLushort *v);
const GLubyte *__glle_Color4usv(const GLubyte *PC)
{
    struct __gllc_Color4usv_Rec *data;

    data = (struct __gllc_Color4usv_Rec *) PC;
    (*__gl_dispatch.dispatch.Color4usv)(data->v);
    return PC + sizeof(struct __gllc_Color4usv_Rec);
}

void APIENTRY __glce_EdgeFlag(GLboolean flag);
void APIENTRY __glce_EdgeFlagv(const GLboolean *flag);
const GLubyte *__glle_EdgeFlagv(const GLubyte *PC)
{
    struct __gllc_EdgeFlagv_Rec *data;

    data = (struct __gllc_EdgeFlagv_Rec *) PC;
    (*__gl_dispatch.dispatch.EdgeFlagv)(data->flag);
    return PC + sizeof(struct __gllc_EdgeFlagv_Rec);
}

void APIENTRY __glce_End(void);
const GLubyte *__glle_End(const GLubyte *PC)
{

    (*__gl_dispatch.dispatch.End)();
    return PC;
}

void APIENTRY __glce_Indexd(GLdouble c);
void APIENTRY __glce_Indexdv(const GLdouble *c);
const GLubyte *__glle_Indexdv(const GLubyte *PC)
{
    struct __gllc_Indexdv_Rec *data;

    data = (struct __gllc_Indexdv_Rec *) PC;
    (*__gl_dispatch.dispatch.Indexdv)(data->c);
    return PC + sizeof(struct __gllc_Indexdv_Rec);
}

void APIENTRY __glce_Indexf(GLfloat c);
void APIENTRY __glce_Indexfv(const GLfloat *c);
const GLubyte *__glle_Indexfv(const GLubyte *PC)
{
    struct __gllc_Indexfv_Rec *data;

    data = (struct __gllc_Indexfv_Rec *) PC;
    (*__gl_dispatch.dispatch.Indexfv)(data->c);
    return PC + sizeof(struct __gllc_Indexfv_Rec);
}

void APIENTRY __glce_Indexi(GLint c);
void APIENTRY __glce_Indexiv(const GLint *c);
const GLubyte *__glle_Indexiv(const GLubyte *PC)
{
    struct __gllc_Indexiv_Rec *data;

    data = (struct __gllc_Indexiv_Rec *) PC;
    (*__gl_dispatch.dispatch.Indexiv)(data->c);
    return PC + sizeof(struct __gllc_Indexiv_Rec);
}

void APIENTRY __glce_Indexs(GLshort c);
void APIENTRY __glce_Indexsv(const GLshort *c);
const GLubyte *__glle_Indexsv(const GLubyte *PC)
{
    struct __gllc_Indexsv_Rec *data;

    data = (struct __gllc_Indexsv_Rec *) PC;
    (*__gl_dispatch.dispatch.Indexsv)(data->c);
    return PC + sizeof(struct __gllc_Indexsv_Rec);
}

void APIENTRY __glce_Normal3b(GLbyte nx, GLbyte ny, GLbyte nz);
void APIENTRY __glce_Normal3bv(const GLbyte *v);
const GLubyte *__glle_Normal3bv(const GLubyte *PC)
{
    struct __gllc_Normal3bv_Rec *data;

    data = (struct __gllc_Normal3bv_Rec *) PC;
    (*__gl_dispatch.dispatch.Normal3bv)(data->v);
    return PC + sizeof(struct __gllc_Normal3bv_Rec);
}

void APIENTRY __glce_Normal3d(GLdouble nx, GLdouble ny, GLdouble nz);
void APIENTRY __glce_Normal3dv(const GLdouble *v);
const GLubyte *__glle_Normal3dv(const GLubyte *PC)
{
    struct __gllc_Normal3dv_Rec *data;

    data = (struct __gllc_Normal3dv_Rec *) PC;
    (*__gl_dispatch.dispatch.Normal3dv)(data->v);
    return PC + sizeof(struct __gllc_Normal3dv_Rec);
}

void APIENTRY __glce_Normal3f(GLfloat nx, GLfloat ny, GLfloat nz);
void APIENTRY __glce_Normal3fv(const GLfloat *v);
const GLubyte *__glle_Normal3fv(const GLubyte *PC)
{
    struct __gllc_Normal3fv_Rec *data;

    data = (struct __gllc_Normal3fv_Rec *) PC;
    (*__gl_dispatch.dispatch.Normal3fv)(data->v);
    return PC + sizeof(struct __gllc_Normal3fv_Rec);
}

void APIENTRY __glce_Normal3i(GLint nx, GLint ny, GLint nz);
void APIENTRY __glce_Normal3iv(const GLint *v);
const GLubyte *__glle_Normal3iv(const GLubyte *PC)
{
    struct __gllc_Normal3iv_Rec *data;

    data = (struct __gllc_Normal3iv_Rec *) PC;
    (*__gl_dispatch.dispatch.Normal3iv)(data->v);
    return PC + sizeof(struct __gllc_Normal3iv_Rec);
}

void APIENTRY __glce_Normal3s(GLshort nx, GLshort ny, GLshort nz);
void APIENTRY __glce_Normal3sv(const GLshort *v);
const GLubyte *__glle_Normal3sv(const GLubyte *PC)
{
    struct __gllc_Normal3sv_Rec *data;

    data = (struct __gllc_Normal3sv_Rec *) PC;
    (*__gl_dispatch.dispatch.Normal3sv)(data->v);
    return PC + sizeof(struct __gllc_Normal3sv_Rec);
}

void APIENTRY __glce_RasterPos2d(GLdouble x, GLdouble y);
void APIENTRY __glce_RasterPos2dv(const GLdouble *v);
const GLubyte *__glle_RasterPos2dv(const GLubyte *PC)
{
    struct __gllc_RasterPos2dv_Rec *data;

    data = (struct __gllc_RasterPos2dv_Rec *) PC;
    (*__gl_dispatch.dispatch.RasterPos2dv)(data->v);
    return PC + sizeof(struct __gllc_RasterPos2dv_Rec);
}

void APIENTRY __glce_RasterPos2f(GLfloat x, GLfloat y);
void APIENTRY __glce_RasterPos2fv(const GLfloat *v);
const GLubyte *__glle_RasterPos2fv(const GLubyte *PC)
{
    struct __gllc_RasterPos2fv_Rec *data;

    data = (struct __gllc_RasterPos2fv_Rec *) PC;
    (*__gl_dispatch.dispatch.RasterPos2fv)(data->v);
    return PC + sizeof(struct __gllc_RasterPos2fv_Rec);
}

void APIENTRY __glce_RasterPos2i(GLint x, GLint y);
void APIENTRY __glce_RasterPos2iv(const GLint *v);
const GLubyte *__glle_RasterPos2iv(const GLubyte *PC)
{
    struct __gllc_RasterPos2iv_Rec *data;

    data = (struct __gllc_RasterPos2iv_Rec *) PC;
    (*__gl_dispatch.dispatch.RasterPos2iv)(data->v);
    return PC + sizeof(struct __gllc_RasterPos2iv_Rec);
}

void APIENTRY __glce_RasterPos2s(GLshort x, GLshort y);
void APIENTRY __glce_RasterPos2sv(const GLshort *v);
const GLubyte *__glle_RasterPos2sv(const GLubyte *PC)
{
    struct __gllc_RasterPos2sv_Rec *data;

    data = (struct __gllc_RasterPos2sv_Rec *) PC;
    (*__gl_dispatch.dispatch.RasterPos2sv)(data->v);
    return PC + sizeof(struct __gllc_RasterPos2sv_Rec);
}

void APIENTRY __glce_RasterPos3d(GLdouble x, GLdouble y, GLdouble z);
void APIENTRY __glce_RasterPos3dv(const GLdouble *v);
const GLubyte *__glle_RasterPos3dv(const GLubyte *PC)
{
    struct __gllc_RasterPos3dv_Rec *data;

    data = (struct __gllc_RasterPos3dv_Rec *) PC;
    (*__gl_dispatch.dispatch.RasterPos3dv)(data->v);
    return PC + sizeof(struct __gllc_RasterPos3dv_Rec);
}

void APIENTRY __glce_RasterPos3f(GLfloat x, GLfloat y, GLfloat z);
void APIENTRY __glce_RasterPos3fv(const GLfloat *v);
const GLubyte *__glle_RasterPos3fv(const GLubyte *PC)
{
    struct __gllc_RasterPos3fv_Rec *data;

    data = (struct __gllc_RasterPos3fv_Rec *) PC;
    (*__gl_dispatch.dispatch.RasterPos3fv)(data->v);
    return PC + sizeof(struct __gllc_RasterPos3fv_Rec);
}

void APIENTRY __glce_RasterPos3i(GLint x, GLint y, GLint z);
void APIENTRY __glce_RasterPos3iv(const GLint *v);
const GLubyte *__glle_RasterPos3iv(const GLubyte *PC)
{
    struct __gllc_RasterPos3iv_Rec *data;

    data = (struct __gllc_RasterPos3iv_Rec *) PC;
    (*__gl_dispatch.dispatch.RasterPos3iv)(data->v);
    return PC + sizeof(struct __gllc_RasterPos3iv_Rec);
}

void APIENTRY __glce_RasterPos3s(GLshort x, GLshort y, GLshort z);
void APIENTRY __glce_RasterPos3sv(const GLshort *v);
const GLubyte *__glle_RasterPos3sv(const GLubyte *PC)
{
    struct __gllc_RasterPos3sv_Rec *data;

    data = (struct __gllc_RasterPos3sv_Rec *) PC;
    (*__gl_dispatch.dispatch.RasterPos3sv)(data->v);
    return PC + sizeof(struct __gllc_RasterPos3sv_Rec);
}

void APIENTRY __glce_RasterPos4d(GLdouble x, GLdouble y, GLdouble z, GLdouble w);
void APIENTRY __glce_RasterPos4dv(const GLdouble *v);
const GLubyte *__glle_RasterPos4dv(const GLubyte *PC)
{
    struct __gllc_RasterPos4dv_Rec *data;

    data = (struct __gllc_RasterPos4dv_Rec *) PC;
    (*__gl_dispatch.dispatch.RasterPos4dv)(data->v);
    return PC + sizeof(struct __gllc_RasterPos4dv_Rec);
}

void APIENTRY __glce_RasterPos4f(GLfloat x, GLfloat y, GLfloat z, GLfloat w);
void APIENTRY __glce_RasterPos4fv(const GLfloat *v);
const GLubyte *__glle_RasterPos4fv(const GLubyte *PC)
{
    struct __gllc_RasterPos4fv_Rec *data;

    data = (struct __gllc_RasterPos4fv_Rec *) PC;
    (*__gl_dispatch.dispatch.RasterPos4fv)(data->v);
    return PC + sizeof(struct __gllc_RasterPos4fv_Rec);
}

void APIENTRY __glce_RasterPos4i(GLint x, GLint y, GLint z, GLint w);
void APIENTRY __glce_RasterPos4iv(const GLint *v);
const GLubyte *__glle_RasterPos4iv(const GLubyte *PC)
{
    struct __gllc_RasterPos4iv_Rec *data;

    data = (struct __gllc_RasterPos4iv_Rec *) PC;
    (*__gl_dispatch.dispatch.RasterPos4iv)(data->v);
    return PC + sizeof(struct __gllc_RasterPos4iv_Rec);
}

void APIENTRY __glce_RasterPos4s(GLshort x, GLshort y, GLshort z, GLshort w);
void APIENTRY __glce_RasterPos4sv(const GLshort *v);
const GLubyte *__glle_RasterPos4sv(const GLubyte *PC)
{
    struct __gllc_RasterPos4sv_Rec *data;

    data = (struct __gllc_RasterPos4sv_Rec *) PC;
    (*__gl_dispatch.dispatch.RasterPos4sv)(data->v);
    return PC + sizeof(struct __gllc_RasterPos4sv_Rec);
}

void APIENTRY __glce_Rectd(GLdouble x1, GLdouble y1, GLdouble x2, GLdouble y2);
void APIENTRY __glce_Rectdv(const GLdouble *v1, const GLdouble *v2);
const GLubyte *__glle_Rectdv(const GLubyte *PC)
{
    struct __gllc_Rectdv_Rec *data;

    data = (struct __gllc_Rectdv_Rec *) PC;
    (*__gl_dispatch.dispatch.Rectdv)(data->v1, data->v2);
    return PC + sizeof(struct __gllc_Rectdv_Rec);
}

void APIENTRY __glce_Rectf(GLfloat x1, GLfloat y1, GLfloat x2, GLfloat y2);
void APIENTRY __glce_Rectfv(const GLfloat *v1, const GLfloat *v2);
const GLubyte *__glle_Rectfv(const GLubyte *PC)
{
    struct __gllc_Rectfv_Rec *data;

    data = (struct __gllc_Rectfv_Rec *) PC;
    (*__gl_dispatch.dispatch.Rectfv)(data->v1, data->v2);
    return PC + sizeof(struct __gllc_Rectfv_Rec);
}

void APIENTRY __glce_Recti(GLint x1, GLint y1, GLint x2, GLint y2);
void APIENTRY __glce_Rectiv(const GLint *v1, const GLint *v2);
const GLubyte *__glle_Rectiv(const GLubyte *PC)
{
    struct __gllc_Rectiv_Rec *data;

    data = (struct __gllc_Rectiv_Rec *) PC;
    (*__gl_dispatch.dispatch.Rectiv)(data->v1, data->v2);
    return PC + sizeof(struct __gllc_Rectiv_Rec);
}

void APIENTRY __glce_Rects(GLshort x1, GLshort y1, GLshort x2, GLshort y2);
void APIENTRY __glce_Rectsv(const GLshort *v1, const GLshort *v2);
const GLubyte *__glle_Rectsv(const GLubyte *PC)
{
    struct __gllc_Rectsv_Rec *data;

    data = (struct __gllc_Rectsv_Rec *) PC;
    (*__gl_dispatch.dispatch.Rectsv)(data->v1, data->v2);
    return PC + sizeof(struct __gllc_Rectsv_Rec);
}

void APIENTRY __glce_TexCoord1d(GLdouble s);
void APIENTRY __glce_TexCoord1dv(const GLdouble *v);
const GLubyte *__glle_TexCoord1dv(const GLubyte *PC)
{
    struct __gllc_TexCoord1dv_Rec *data;

    data = (struct __gllc_TexCoord1dv_Rec *) PC;
    (*__gl_dispatch.dispatch.TexCoord1dv)(data->v);
    return PC + sizeof(struct __gllc_TexCoord1dv_Rec);
}

void APIENTRY __glce_TexCoord1f(GLfloat s);
void APIENTRY __glce_TexCoord1fv(const GLfloat *v);
const GLubyte *__glle_TexCoord1fv(const GLubyte *PC)
{
    struct __gllc_TexCoord1fv_Rec *data;

    data = (struct __gllc_TexCoord1fv_Rec *) PC;
    (*__gl_dispatch.dispatch.TexCoord1fv)(data->v);
    return PC + sizeof(struct __gllc_TexCoord1fv_Rec);
}

void APIENTRY __glce_TexCoord1i(GLint s);
void APIENTRY __glce_TexCoord1iv(const GLint *v);
const GLubyte *__glle_TexCoord1iv(const GLubyte *PC)
{
    struct __gllc_TexCoord1iv_Rec *data;

    data = (struct __gllc_TexCoord1iv_Rec *) PC;
    (*__gl_dispatch.dispatch.TexCoord1iv)(data->v);
    return PC + sizeof(struct __gllc_TexCoord1iv_Rec);
}

void APIENTRY __glce_TexCoord1s(GLshort s);
void APIENTRY __glce_TexCoord1sv(const GLshort *v);
const GLubyte *__glle_TexCoord1sv(const GLubyte *PC)
{
    struct __gllc_TexCoord1sv_Rec *data;

    data = (struct __gllc_TexCoord1sv_Rec *) PC;
    (*__gl_dispatch.dispatch.TexCoord1sv)(data->v);
    return PC + sizeof(struct __gllc_TexCoord1sv_Rec);
}

void APIENTRY __glce_TexCoord2d(GLdouble s, GLdouble t);
void APIENTRY __glce_TexCoord2dv(const GLdouble *v);
const GLubyte *__glle_TexCoord2dv(const GLubyte *PC)
{
    struct __gllc_TexCoord2dv_Rec *data;

    data = (struct __gllc_TexCoord2dv_Rec *) PC;
    (*__gl_dispatch.dispatch.TexCoord2dv)(data->v);
    return PC + sizeof(struct __gllc_TexCoord2dv_Rec);
}

void APIENTRY __glce_TexCoord2f(GLfloat s, GLfloat t);
void APIENTRY __glce_TexCoord2fv(const GLfloat *v);
const GLubyte *__glle_TexCoord2fv(const GLubyte *PC)
{
    struct __gllc_TexCoord2fv_Rec *data;

    data = (struct __gllc_TexCoord2fv_Rec *) PC;
    (*__gl_dispatch.dispatch.TexCoord2fv)(data->v);
    return PC + sizeof(struct __gllc_TexCoord2fv_Rec);
}

void APIENTRY __glce_TexCoord2i(GLint s, GLint t);
void APIENTRY __glce_TexCoord2iv(const GLint *v);
const GLubyte *__glle_TexCoord2iv(const GLubyte *PC)
{
    struct __gllc_TexCoord2iv_Rec *data;

    data = (struct __gllc_TexCoord2iv_Rec *) PC;
    (*__gl_dispatch.dispatch.TexCoord2iv)(data->v);
    return PC + sizeof(struct __gllc_TexCoord2iv_Rec);
}

void APIENTRY __glce_TexCoord2s(GLshort s, GLshort t);
void APIENTRY __glce_TexCoord2sv(const GLshort *v);
const GLubyte *__glle_TexCoord2sv(const GLubyte *PC)
{
    struct __gllc_TexCoord2sv_Rec *data;

    data = (struct __gllc_TexCoord2sv_Rec *) PC;
    (*__gl_dispatch.dispatch.TexCoord2sv)(data->v);
    return PC + sizeof(struct __gllc_TexCoord2sv_Rec);
}

void APIENTRY __glce_TexCoord3d(GLdouble s, GLdouble t, GLdouble r);
void APIENTRY __glce_TexCoord3dv(const GLdouble *v);
const GLubyte *__glle_TexCoord3dv(const GLubyte *PC)
{
    struct __gllc_TexCoord3dv_Rec *data;

    data = (struct __gllc_TexCoord3dv_Rec *) PC;
    (*__gl_dispatch.dispatch.TexCoord3dv)(data->v);
    return PC + sizeof(struct __gllc_TexCoord3dv_Rec);
}

void APIENTRY __glce_TexCoord3f(GLfloat s, GLfloat t, GLfloat r);
void APIENTRY __glce_TexCoord3fv(const GLfloat *v);
const GLubyte *__glle_TexCoord3fv(const GLubyte *PC)
{
    struct __gllc_TexCoord3fv_Rec *data;

    data = (struct __gllc_TexCoord3fv_Rec *) PC;
    (*__gl_dispatch.dispatch.TexCoord3fv)(data->v);
    return PC + sizeof(struct __gllc_TexCoord3fv_Rec);
}

void APIENTRY __glce_TexCoord3i(GLint s, GLint t, GLint r);
void APIENTRY __glce_TexCoord3iv(const GLint *v);
const GLubyte *__glle_TexCoord3iv(const GLubyte *PC)
{
    struct __gllc_TexCoord3iv_Rec *data;

    data = (struct __gllc_TexCoord3iv_Rec *) PC;
    (*__gl_dispatch.dispatch.TexCoord3iv)(data->v);
    return PC + sizeof(struct __gllc_TexCoord3iv_Rec);
}

void APIENTRY __glce_TexCoord3s(GLshort s, GLshort t, GLshort r);
void APIENTRY __glce_TexCoord3sv(const GLshort *v);
const GLubyte *__glle_TexCoord3sv(const GLubyte *PC)
{
    struct __gllc_TexCoord3sv_Rec *data;

    data = (struct __gllc_TexCoord3sv_Rec *) PC;
    (*__gl_dispatch.dispatch.TexCoord3sv)(data->v);
    return PC + sizeof(struct __gllc_TexCoord3sv_Rec);
}

void APIENTRY __glce_TexCoord4d(GLdouble s, GLdouble t, GLdouble r, GLdouble q);
void APIENTRY __glce_TexCoord4dv(const GLdouble *v);
const GLubyte *__glle_TexCoord4dv(const GLubyte *PC)
{
    struct __gllc_TexCoord4dv_Rec *data;

    data = (struct __gllc_TexCoord4dv_Rec *) PC;
    (*__gl_dispatch.dispatch.TexCoord4dv)(data->v);
    return PC + sizeof(struct __gllc_TexCoord4dv_Rec);
}

void APIENTRY __glce_TexCoord4f(GLfloat s, GLfloat t, GLfloat r, GLfloat q);
void APIENTRY __glce_TexCoord4fv(const GLfloat *v);
const GLubyte *__glle_TexCoord4fv(const GLubyte *PC)
{
    struct __gllc_TexCoord4fv_Rec *data;

    data = (struct __gllc_TexCoord4fv_Rec *) PC;
    (*__gl_dispatch.dispatch.TexCoord4fv)(data->v);
    return PC + sizeof(struct __gllc_TexCoord4fv_Rec);
}

void APIENTRY __glce_TexCoord4i(GLint s, GLint t, GLint r, GLint q);
void APIENTRY __glce_TexCoord4iv(const GLint *v);
const GLubyte *__glle_TexCoord4iv(const GLubyte *PC)
{
    struct __gllc_TexCoord4iv_Rec *data;

    data = (struct __gllc_TexCoord4iv_Rec *) PC;
    (*__gl_dispatch.dispatch.TexCoord4iv)(data->v);
    return PC + sizeof(struct __gllc_TexCoord4iv_Rec);
}

void APIENTRY __glce_TexCoord4s(GLshort s, GLshort t, GLshort r, GLshort q);
void APIENTRY __glce_TexCoord4sv(const GLshort *v);
const GLubyte *__glle_TexCoord4sv(const GLubyte *PC)
{
    struct __gllc_TexCoord4sv_Rec *data;

    data = (struct __gllc_TexCoord4sv_Rec *) PC;
    (*__gl_dispatch.dispatch.TexCoord4sv)(data->v);
    return PC + sizeof(struct __gllc_TexCoord4sv_Rec);
}

void APIENTRY __glce_Vertex2d(GLdouble x, GLdouble y);
void APIENTRY __glce_Vertex2dv(const GLdouble *v);
const GLubyte *__glle_Vertex2dv(const GLubyte *PC)
{
    struct __gllc_Vertex2dv_Rec *data;

    data = (struct __gllc_Vertex2dv_Rec *) PC;
    (*__gl_dispatch.dispatch.Vertex2dv)(data->v);
    return PC + sizeof(struct __gllc_Vertex2dv_Rec);
}

void APIENTRY __glce_Vertex2f(GLfloat x, GLfloat y);
void APIENTRY __glce_Vertex2fv(const GLfloat *v);
const GLubyte *__glle_Vertex2fv(const GLubyte *PC)
{
    struct __gllc_Vertex2fv_Rec *data;

    data = (struct __gllc_Vertex2fv_Rec *) PC;
    (*__gl_dispatch.dispatch.Vertex2fv)(data->v);
    return PC + sizeof(struct __gllc_Vertex2fv_Rec);
}

void APIENTRY __glce_Vertex2i(GLint x, GLint y);
void APIENTRY __glce_Vertex2iv(const GLint *v);
const GLubyte *__glle_Vertex2iv(const GLubyte *PC)
{
    struct __gllc_Vertex2iv_Rec *data;

    data = (struct __gllc_Vertex2iv_Rec *) PC;
    (*__gl_dispatch.dispatch.Vertex2iv)(data->v);
    return PC + sizeof(struct __gllc_Vertex2iv_Rec);
}

void APIENTRY __glce_Vertex2s(GLshort x, GLshort y);
void APIENTRY __glce_Vertex2sv(const GLshort *v);
const GLubyte *__glle_Vertex2sv(const GLubyte *PC)
{
    struct __gllc_Vertex2sv_Rec *data;

    data = (struct __gllc_Vertex2sv_Rec *) PC;
    (*__gl_dispatch.dispatch.Vertex2sv)(data->v);
    return PC + sizeof(struct __gllc_Vertex2sv_Rec);
}

void APIENTRY __glce_Vertex3d(GLdouble x, GLdouble y, GLdouble z);
void APIENTRY __glce_Vertex3dv(const GLdouble *v);
const GLubyte *__glle_Vertex3dv(const GLubyte *PC)
{
    struct __gllc_Vertex3dv_Rec *data;

    data = (struct __gllc_Vertex3dv_Rec *) PC;
    (*__gl_dispatch.dispatch.Vertex3dv)(data->v);
    return PC + sizeof(struct __gllc_Vertex3dv_Rec);
}

void APIENTRY __glce_Vertex3f(GLfloat x, GLfloat y, GLfloat z);
void APIENTRY __glce_Vertex3fv(const GLfloat *v);
const GLubyte *__glle_Vertex3fv(const GLubyte *PC)
{
    struct __gllc_Vertex3fv_Rec *data;

    data = (struct __gllc_Vertex3fv_Rec *) PC;
    (*__gl_dispatch.dispatch.Vertex3fv)(data->v);
    return PC + sizeof(struct __gllc_Vertex3fv_Rec);
}

void APIENTRY __glce_Vertex3i(GLint x, GLint y, GLint z);
void APIENTRY __glce_Vertex3iv(const GLint *v);
const GLubyte *__glle_Vertex3iv(const GLubyte *PC)
{
    struct __gllc_Vertex3iv_Rec *data;

    data = (struct __gllc_Vertex3iv_Rec *) PC;
    (*__gl_dispatch.dispatch.Vertex3iv)(data->v);
    return PC + sizeof(struct __gllc_Vertex3iv_Rec);
}

void APIENTRY __glce_Vertex3s(GLshort x, GLshort y, GLshort z);
void APIENTRY __glce_Vertex3sv(const GLshort *v);
const GLubyte *__glle_Vertex3sv(const GLubyte *PC)
{
    struct __gllc_Vertex3sv_Rec *data;

    data = (struct __gllc_Vertex3sv_Rec *) PC;
    (*__gl_dispatch.dispatch.Vertex3sv)(data->v);
    return PC + sizeof(struct __gllc_Vertex3sv_Rec);
}

void APIENTRY __glce_Vertex4d(GLdouble x, GLdouble y, GLdouble z, GLdouble w);
void APIENTRY __glce_Vertex4dv(const GLdouble *v);
const GLubyte *__glle_Vertex4dv(const GLubyte *PC)
{
    struct __gllc_Vertex4dv_Rec *data;

    data = (struct __gllc_Vertex4dv_Rec *) PC;
    (*__gl_dispatch.dispatch.Vertex4dv)(data->v);
    return PC + sizeof(struct __gllc_Vertex4dv_Rec);
}

void APIENTRY __glce_Vertex4f(GLfloat x, GLfloat y, GLfloat z, GLfloat w);
void APIENTRY __glce_Vertex4fv(const GLfloat *v);
const GLubyte *__glle_Vertex4fv(const GLubyte *PC)
{
    struct __gllc_Vertex4fv_Rec *data;

    data = (struct __gllc_Vertex4fv_Rec *) PC;
    (*__gl_dispatch.dispatch.Vertex4fv)(data->v);
    return PC + sizeof(struct __gllc_Vertex4fv_Rec);
}

void APIENTRY __glce_Vertex4i(GLint x, GLint y, GLint z, GLint w);
void APIENTRY __glce_Vertex4iv(const GLint *v);
const GLubyte *__glle_Vertex4iv(const GLubyte *PC)
{
    struct __gllc_Vertex4iv_Rec *data;

    data = (struct __gllc_Vertex4iv_Rec *) PC;
    (*__gl_dispatch.dispatch.Vertex4iv)(data->v);
    return PC + sizeof(struct __gllc_Vertex4iv_Rec);
}

void APIENTRY __glce_Vertex4s(GLshort x, GLshort y, GLshort z, GLshort w);
void APIENTRY __glce_Vertex4sv(const GLshort *v);
const GLubyte *__glle_Vertex4sv(const GLubyte *PC)
{
    struct __gllc_Vertex4sv_Rec *data;

    data = (struct __gllc_Vertex4sv_Rec *) PC;
    (*__gl_dispatch.dispatch.Vertex4sv)(data->v);
    return PC + sizeof(struct __gllc_Vertex4sv_Rec);
}

void APIENTRY __glce_ClipPlane(GLenum plane, const GLdouble *equation);
const GLubyte *__glle_ClipPlane(const GLubyte *PC)
{
    struct __gllc_ClipPlane_Rec *data;

    data = (struct __gllc_ClipPlane_Rec *) PC;
    (*__gl_dispatch.dispatch.ClipPlane)(data->plane, data->equation);
    return PC + sizeof(struct __gllc_ClipPlane_Rec);
}

void APIENTRY __glce_ColorMaterial(GLenum face, GLenum mode);
const GLubyte *__glle_ColorMaterial(const GLubyte *PC)
{
    struct __gllc_ColorMaterial_Rec *data;

    data = (struct __gllc_ColorMaterial_Rec *) PC;
    (*__gl_dispatch.dispatch.ColorMaterial)(data->face, data->mode);
    return PC + sizeof(struct __gllc_ColorMaterial_Rec);
}

void APIENTRY __glce_CullFace(GLenum mode);
const GLubyte *__glle_CullFace(const GLubyte *PC)
{
    struct __gllc_CullFace_Rec *data;

    data = (struct __gllc_CullFace_Rec *) PC;
    (*__gl_dispatch.dispatch.CullFace)(data->mode);
    return PC + sizeof(struct __gllc_CullFace_Rec);
}

void APIENTRY __glce_Fogf(GLenum pname, GLfloat param);
const GLubyte *__glle_Fogf(const GLubyte *PC)
{
    struct __gllc_Fogf_Rec *data;

    data = (struct __gllc_Fogf_Rec *) PC;
    (*__gl_dispatch.dispatch.Fogf)(data->pname, data->param);
    return PC + sizeof(struct __gllc_Fogf_Rec);
}

void APIENTRY __glce_Fogfv(GLenum pname, const GLfloat *params);
const GLubyte *__glle_Fogfv(const GLubyte *PC)
{
    GLuint size;
    GLuint arraySize;
    struct __gllc_Fogfv_Rec *data;

    data = (struct __gllc_Fogfv_Rec *) PC;
    (*__gl_dispatch.dispatch.Fogfv)(data->pname, 
	    (GLfloat *) (PC + sizeof(struct __gllc_Fogfv_Rec)));
    arraySize = __GL64PAD(__glFogfv_size(data->pname) * 4);
    size = (GLuint)sizeof(struct __gllc_Fogfv_Rec) + arraySize;
    return PC + size;
}

void APIENTRY __glce_Fogi(GLenum pname, GLint param);
const GLubyte *__glle_Fogi(const GLubyte *PC)
{
    struct __gllc_Fogi_Rec *data;

    data = (struct __gllc_Fogi_Rec *) PC;
    (*__gl_dispatch.dispatch.Fogi)(data->pname, data->param);
    return PC + sizeof(struct __gllc_Fogi_Rec);
}

void APIENTRY __glce_Fogiv(GLenum pname, const GLint *params);
const GLubyte *__glle_Fogiv(const GLubyte *PC)
{
    GLuint size;
    GLuint arraySize;
    struct __gllc_Fogiv_Rec *data;

    data = (struct __gllc_Fogiv_Rec *) PC;
    (*__gl_dispatch.dispatch.Fogiv)(data->pname, 
	    (GLint *) (PC + sizeof(struct __gllc_Fogiv_Rec)));
    arraySize = __GL64PAD(__glFogiv_size(data->pname) * 4);
    size = (GLuint)sizeof(struct __gllc_Fogiv_Rec) + arraySize;
    return PC + size;
}

void APIENTRY __glce_FrontFace(GLenum mode);
const GLubyte *__glle_FrontFace(const GLubyte *PC)
{
    struct __gllc_FrontFace_Rec *data;

    data = (struct __gllc_FrontFace_Rec *) PC;
    (*__gl_dispatch.dispatch.FrontFace)(data->mode);
    return PC + sizeof(struct __gllc_FrontFace_Rec);
}

void APIENTRY __glce_Hint(GLenum target, GLenum mode);
const GLubyte *__glle_Hint(const GLubyte *PC)
{
    struct __gllc_Hint_Rec *data;

    data = (struct __gllc_Hint_Rec *) PC;
    (*__gl_dispatch.dispatch.Hint)(data->target, data->mode);
    return PC + sizeof(struct __gllc_Hint_Rec);
}

void APIENTRY __glce_Lightf(GLenum light, GLenum pname, GLfloat param);
void APIENTRY __glce_Lightfv(GLenum light, GLenum pname, const GLfloat *params);
const GLubyte *__glle_Lightfv(const GLubyte *PC)
{
    GLuint size;
    GLuint arraySize;
    struct __gllc_Lightfv_Rec *data;

    data = (struct __gllc_Lightfv_Rec *) PC;
    (*__gl_dispatch.dispatch.Lightfv)(data->light, data->pname, 
	    (GLfloat *) (PC + sizeof(struct __gllc_Lightfv_Rec)));
    arraySize = __GL64PAD(__glLightfv_size(data->pname) * 4);
    size = (GLuint)sizeof(struct __gllc_Lightfv_Rec) + arraySize;
    return PC + size;
}

void APIENTRY __glce_Lighti(GLenum light, GLenum pname, GLint param);
void APIENTRY __glce_Lightiv(GLenum light, GLenum pname, const GLint *params);
const GLubyte *__glle_Lightiv(const GLubyte *PC)
{
    GLuint size;
    GLuint arraySize;
    struct __gllc_Lightiv_Rec *data;

    data = (struct __gllc_Lightiv_Rec *) PC;
    (*__gl_dispatch.dispatch.Lightiv)(data->light, data->pname, 
	    (GLint *) (PC + sizeof(struct __gllc_Lightiv_Rec)));
    arraySize = __GL64PAD(__glLightiv_size(data->pname) * 4);
    size = (GLuint)sizeof(struct __gllc_Lightiv_Rec) + arraySize;
    return PC + size;
}

void APIENTRY __glce_LightModelf(GLenum pname, GLfloat param);
void APIENTRY __glce_LightModelfv(GLenum pname, const GLfloat *params);
const GLubyte *__glle_LightModelfv(const GLubyte *PC)
{
    GLuint size;
    GLuint arraySize;
    struct __gllc_LightModelfv_Rec *data;

    data = (struct __gllc_LightModelfv_Rec *) PC;
    (*__gl_dispatch.dispatch.LightModelfv)(data->pname, 
	    (GLfloat *) (PC + sizeof(struct __gllc_LightModelfv_Rec)));
    arraySize = __GL64PAD(__glLightModelfv_size(data->pname) * 4);
    size = (GLuint)sizeof(struct __gllc_LightModelfv_Rec) + arraySize;
    return PC + size;
}

void APIENTRY __glce_LightModeli(GLenum pname, GLint param);
void APIENTRY __glce_LightModeliv(GLenum pname, const GLint *params);
const GLubyte *__glle_LightModeliv(const GLubyte *PC)
{
    GLuint size;
    GLuint arraySize;
    struct __gllc_LightModeliv_Rec *data;

    data = (struct __gllc_LightModeliv_Rec *) PC;
    (*__gl_dispatch.dispatch.LightModeliv)(data->pname, 
	    (GLint *) (PC + sizeof(struct __gllc_LightModeliv_Rec)));
    arraySize = __GL64PAD(__glLightModeliv_size(data->pname) * 4);
    size = (GLuint)sizeof(struct __gllc_LightModeliv_Rec) + arraySize;
    return PC + size;
}

void APIENTRY __glce_LineStipple(GLint factor, GLushort pattern);
const GLubyte *__glle_LineStipple(const GLubyte *PC)
{
    struct __gllc_LineStipple_Rec *data;

    data = (struct __gllc_LineStipple_Rec *) PC;
    (*__gl_dispatch.dispatch.LineStipple)(data->factor, data->pattern);
    return PC + sizeof(struct __gllc_LineStipple_Rec);
}

void APIENTRY __glce_LineWidth(GLfloat width);
const GLubyte *__glle_LineWidth(const GLubyte *PC)
{
    struct __gllc_LineWidth_Rec *data;

    data = (struct __gllc_LineWidth_Rec *) PC;
    (*__gl_dispatch.dispatch.LineWidth)(data->width);
    return PC + sizeof(struct __gllc_LineWidth_Rec);
}

void APIENTRY __glce_Materialf(GLenum face, GLenum pname, GLfloat param);
void APIENTRY __glce_Materialfv(GLenum face, GLenum pname, const GLfloat *params);
const GLubyte *__glle_Materialfv(const GLubyte *PC)
{
    GLuint size;
    GLuint arraySize;
    struct __gllc_Materialfv_Rec *data;

    data = (struct __gllc_Materialfv_Rec *) PC;
    (*__gl_dispatch.dispatch.Materialfv)(data->face, data->pname, 
	    (GLfloat *) (PC + sizeof(struct __gllc_Materialfv_Rec)));
    arraySize = __GL64PAD(__glMaterialfv_size(data->pname) * 4);
    size = (GLuint)sizeof(struct __gllc_Materialfv_Rec) + arraySize;
    return PC + size;
}

void APIENTRY __glce_Materiali(GLenum face, GLenum pname, GLint param);
void APIENTRY __glce_Materialiv(GLenum face, GLenum pname, const GLint *params);
const GLubyte *__glle_Materialiv(const GLubyte *PC)
{
    GLuint size;
    GLuint arraySize;
    struct __gllc_Materialiv_Rec *data;

    data = (struct __gllc_Materialiv_Rec *) PC;
    (*__gl_dispatch.dispatch.Materialiv)(data->face, data->pname, 
	    (GLint *) (PC + sizeof(struct __gllc_Materialiv_Rec)));
    arraySize = __GL64PAD(__glMaterialiv_size(data->pname) * 4);
    size = (GLuint)sizeof(struct __gllc_Materialiv_Rec) + arraySize;
    return PC + size;
}

void APIENTRY __glce_PointSize(GLfloat size);
const GLubyte *__glle_PointSize(const GLubyte *PC)
{
    struct __gllc_PointSize_Rec *data;

    data = (struct __gllc_PointSize_Rec *) PC;
    (*__gl_dispatch.dispatch.PointSize)(data->size);
    return PC + sizeof(struct __gllc_PointSize_Rec);
}

void APIENTRY __glce_PolygonMode(GLenum face, GLenum mode);
const GLubyte *__glle_PolygonMode(const GLubyte *PC)
{
    struct __gllc_PolygonMode_Rec *data;

    data = (struct __gllc_PolygonMode_Rec *) PC;
    (*__gl_dispatch.dispatch.PolygonMode)(data->face, data->mode);
    return PC + sizeof(struct __gllc_PolygonMode_Rec);
}

void APIENTRY __glce_PolygonStipple(const GLubyte *mask);
void APIENTRY __glce_Scissor(GLint x, GLint y, GLsizei width, GLsizei height);
const GLubyte *__glle_Scissor(const GLubyte *PC)
{
    struct __gllc_Scissor_Rec *data;

    data = (struct __gllc_Scissor_Rec *) PC;
    (*__gl_dispatch.dispatch.Scissor)(data->x, data->y, data->width, data->height);
    return PC + sizeof(struct __gllc_Scissor_Rec);
}

void APIENTRY __glce_ShadeModel(GLenum mode);
const GLubyte *__glle_ShadeModel(const GLubyte *PC)
{
    struct __gllc_ShadeModel_Rec *data;

    data = (struct __gllc_ShadeModel_Rec *) PC;
    (*__gl_dispatch.dispatch.ShadeModel)(data->mode);
    return PC + sizeof(struct __gllc_ShadeModel_Rec);
}

void APIENTRY __glce_TexParameterf(GLenum target, GLenum pname, GLfloat param);
void APIENTRY __glce_TexParameterfv(GLenum target, GLenum pname, const GLfloat *params);
const GLubyte *__glle_TexParameterfv(const GLubyte *PC)
{
    GLuint size;
    GLuint arraySize;
    struct __gllc_TexParameterfv_Rec *data;

    data = (struct __gllc_TexParameterfv_Rec *) PC;
    (*__gl_dispatch.dispatch.TexParameterfv)(data->target, data->pname, 
	    (GLfloat *) (PC + sizeof(struct __gllc_TexParameterfv_Rec)));
    arraySize = __GL64PAD(__glTexParameterfv_size(data->pname) * 4);
    size = (GLuint)sizeof(struct __gllc_TexParameterfv_Rec) + arraySize;
    return PC + size;
}

void APIENTRY __glce_TexParameteri(GLenum target, GLenum pname, GLint param);
void APIENTRY __glce_TexParameteriv(GLenum target, GLenum pname, const GLint *params);
const GLubyte *__glle_TexParameteriv(const GLubyte *PC)
{
    GLuint size;
    GLuint arraySize;
    struct __gllc_TexParameteriv_Rec *data;

    data = (struct __gllc_TexParameteriv_Rec *) PC;
    (*__gl_dispatch.dispatch.TexParameteriv)(data->target, data->pname, 
	    (GLint *) (PC + sizeof(struct __gllc_TexParameteriv_Rec)));
    arraySize = __GL64PAD(__glTexParameteriv_size(data->pname) * 4);
    size = (GLuint)sizeof(struct __gllc_TexParameteriv_Rec) + arraySize;
    return PC + size;
}

void APIENTRY __glce_TexImage1D(GLenum target, GLint level, GLint components, GLsizei width, GLint border, GLenum format, GLenum type, const GLvoid *pixels);
void APIENTRY __glce_TexImage2D(GLenum target, GLint level, GLint components, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid *pixels);
void APIENTRY __glce_TexEnvf(GLenum target, GLenum pname, GLfloat param);
void APIENTRY __glce_TexEnvfv(GLenum target, GLenum pname, const GLfloat *params);
const GLubyte *__glle_TexEnvfv(const GLubyte *PC)
{
    GLuint size;
    GLuint arraySize;
    struct __gllc_TexEnvfv_Rec *data;

    data = (struct __gllc_TexEnvfv_Rec *) PC;
    (*__gl_dispatch.dispatch.TexEnvfv)(data->target, data->pname, 
	    (GLfloat *) (PC + sizeof(struct __gllc_TexEnvfv_Rec)));
    arraySize = __GL64PAD(__glTexEnvfv_size(data->pname) * 4);
    size = (GLuint)sizeof(struct __gllc_TexEnvfv_Rec) + arraySize;
    return PC + size;
}

void APIENTRY __glce_TexEnvi(GLenum target, GLenum pname, GLint param);
void APIENTRY __glce_TexEnviv(GLenum target, GLenum pname, const GLint *params);
const GLubyte *__glle_TexEnviv(const GLubyte *PC)
{
    GLuint size;
    GLuint arraySize;
    struct __gllc_TexEnviv_Rec *data;

    data = (struct __gllc_TexEnviv_Rec *) PC;
    (*__gl_dispatch.dispatch.TexEnviv)(data->target, data->pname, 
	    (GLint *) (PC + sizeof(struct __gllc_TexEnviv_Rec)));
    arraySize = __GL64PAD(__glTexEnviv_size(data->pname) * 4);
    size = (GLuint)sizeof(struct __gllc_TexEnviv_Rec) + arraySize;
    return PC + size;
}

void APIENTRY __glce_TexGend(GLenum coord, GLenum pname, GLdouble param);
void APIENTRY __glce_TexGendv(GLenum coord, GLenum pname, const GLdouble *params);
const GLubyte *__glle_TexGendv(const GLubyte *PC)
{
    GLuint size;
    GLuint arraySize;
    struct __gllc_TexGendv_Rec *data;

    data = (struct __gllc_TexGendv_Rec *) PC;
    (*__gl_dispatch.dispatch.TexGendv)(data->coord, data->pname, 
	    (GLdouble *) (PC + sizeof(struct __gllc_TexGendv_Rec)));
    arraySize = __GL64PAD(__glTexGendv_size(data->pname) * 8);
    size = (GLuint)sizeof(struct __gllc_TexGendv_Rec) + arraySize;
    return PC + size;
}

void APIENTRY __glce_TexGenf(GLenum coord, GLenum pname, GLfloat param);
void APIENTRY __glce_TexGenfv(GLenum coord, GLenum pname, const GLfloat *params);
const GLubyte *__glle_TexGenfv(const GLubyte *PC)
{
    GLuint size;
    GLuint arraySize;
    struct __gllc_TexGenfv_Rec *data;

    data = (struct __gllc_TexGenfv_Rec *) PC;
    (*__gl_dispatch.dispatch.TexGenfv)(data->coord, data->pname, 
	    (GLfloat *) (PC + sizeof(struct __gllc_TexGenfv_Rec)));
    arraySize = __GL64PAD(__glTexGenfv_size(data->pname) * 4);
    size = (GLuint)sizeof(struct __gllc_TexGenfv_Rec) + arraySize;
    return PC + size;
}

void APIENTRY __glce_TexGeni(GLenum coord, GLenum pname, GLint param);
void APIENTRY __glce_TexGeniv(GLenum coord, GLenum pname, const GLint *params);
const GLubyte *__glle_TexGeniv(const GLubyte *PC)
{
    GLuint size;
    GLuint arraySize;
    struct __gllc_TexGeniv_Rec *data;

    data = (struct __gllc_TexGeniv_Rec *) PC;
    (*__gl_dispatch.dispatch.TexGeniv)(data->coord, data->pname, 
	    (GLint *) (PC + sizeof(struct __gllc_TexGeniv_Rec)));
    arraySize = __GL64PAD(__glTexGeniv_size(data->pname) * 4);
    size = (GLuint)sizeof(struct __gllc_TexGeniv_Rec) + arraySize;
    return PC + size;
}

void APIENTRY __glce_FeedbackBuffer(GLsizei size, GLenum type, GLfloat *buffer);
void APIENTRY __glce_SelectBuffer(GLsizei size, GLuint *buffer);
GLint APIENTRY __glce_RenderMode(GLenum mode);
void APIENTRY __glce_InitNames(void);
const GLubyte *__glle_InitNames(const GLubyte *PC)
{

    (*__gl_dispatch.dispatch.InitNames)();
    return PC;
}

void APIENTRY __glce_LoadName(GLuint name);
const GLubyte *__glle_LoadName(const GLubyte *PC)
{
    struct __gllc_LoadName_Rec *data;

    data = (struct __gllc_LoadName_Rec *) PC;
    (*__gl_dispatch.dispatch.LoadName)(data->name);
    return PC + sizeof(struct __gllc_LoadName_Rec);
}

void APIENTRY __glce_PassThrough(GLfloat token);
const GLubyte *__glle_PassThrough(const GLubyte *PC)
{
    struct __gllc_PassThrough_Rec *data;

    data = (struct __gllc_PassThrough_Rec *) PC;
    (*__gl_dispatch.dispatch.PassThrough)(data->token);
    return PC + sizeof(struct __gllc_PassThrough_Rec);
}

void APIENTRY __glce_PopName(void);
const GLubyte *__glle_PopName(const GLubyte *PC)
{

    (*__gl_dispatch.dispatch.PopName)();
    return PC;
}

void APIENTRY __glce_PushName(GLuint name);
const GLubyte *__glle_PushName(const GLubyte *PC)
{
    struct __gllc_PushName_Rec *data;

    data = (struct __gllc_PushName_Rec *) PC;
    (*__gl_dispatch.dispatch.PushName)(data->name);
    return PC + sizeof(struct __gllc_PushName_Rec);
}

void APIENTRY __glce_DrawBuffer(GLenum mode);
const GLubyte *__glle_DrawBuffer(const GLubyte *PC)
{
    struct __gllc_DrawBuffer_Rec *data;

    data = (struct __gllc_DrawBuffer_Rec *) PC;
    (*__gl_dispatch.dispatch.DrawBuffer)(data->mode);
    return PC + sizeof(struct __gllc_DrawBuffer_Rec);
}

void APIENTRY __glce_Clear(GLbitfield mask);
const GLubyte *__glle_Clear(const GLubyte *PC)
{
    struct __gllc_Clear_Rec *data;

    data = (struct __gllc_Clear_Rec *) PC;
    (*__gl_dispatch.dispatch.Clear)(data->mask);
    return PC + sizeof(struct __gllc_Clear_Rec);
}

void APIENTRY __glce_ClearAccum(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
const GLubyte *__glle_ClearAccum(const GLubyte *PC)
{
    struct __gllc_ClearAccum_Rec *data;

    data = (struct __gllc_ClearAccum_Rec *) PC;
    (*__gl_dispatch.dispatch.ClearAccum)(data->red, data->green, data->blue, data->alpha);
    return PC + sizeof(struct __gllc_ClearAccum_Rec);
}

void APIENTRY __glce_ClearIndex(GLfloat c);
const GLubyte *__glle_ClearIndex(const GLubyte *PC)
{
    struct __gllc_ClearIndex_Rec *data;

    data = (struct __gllc_ClearIndex_Rec *) PC;
    (*__gl_dispatch.dispatch.ClearIndex)(data->c);
    return PC + sizeof(struct __gllc_ClearIndex_Rec);
}

void APIENTRY __glce_ClearColor(GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha);
const GLubyte *__glle_ClearColor(const GLubyte *PC)
{
    struct __gllc_ClearColor_Rec *data;

    data = (struct __gllc_ClearColor_Rec *) PC;
    (*__gl_dispatch.dispatch.ClearColor)(data->red, data->green, data->blue, data->alpha);
    return PC + sizeof(struct __gllc_ClearColor_Rec);
}

void APIENTRY __glce_ClearStencil(GLint s);
const GLubyte *__glle_ClearStencil(const GLubyte *PC)
{
    struct __gllc_ClearStencil_Rec *data;

    data = (struct __gllc_ClearStencil_Rec *) PC;
    (*__gl_dispatch.dispatch.ClearStencil)(data->s);
    return PC + sizeof(struct __gllc_ClearStencil_Rec);
}

void APIENTRY __glce_ClearDepth(GLclampd depth);
const GLubyte *__glle_ClearDepth(const GLubyte *PC)
{
    struct __gllc_ClearDepth_Rec *data;

    data = (struct __gllc_ClearDepth_Rec *) PC;
    (*__gl_dispatch.dispatch.ClearDepth)(data->depth);
    return PC + sizeof(struct __gllc_ClearDepth_Rec);
}

void APIENTRY __glce_StencilMask(GLuint mask);
const GLubyte *__glle_StencilMask(const GLubyte *PC)
{
    struct __gllc_StencilMask_Rec *data;

    data = (struct __gllc_StencilMask_Rec *) PC;
    (*__gl_dispatch.dispatch.StencilMask)(data->mask);
    return PC + sizeof(struct __gllc_StencilMask_Rec);
}

void APIENTRY __glce_ColorMask(GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha);
const GLubyte *__glle_ColorMask(const GLubyte *PC)
{
    struct __gllc_ColorMask_Rec *data;

    data = (struct __gllc_ColorMask_Rec *) PC;
    (*__gl_dispatch.dispatch.ColorMask)(data->red, data->green, data->blue, data->alpha);
    return PC + sizeof(struct __gllc_ColorMask_Rec);
}

void APIENTRY __glce_DepthMask(GLboolean flag);
const GLubyte *__glle_DepthMask(const GLubyte *PC)
{
    struct __gllc_DepthMask_Rec *data;

    data = (struct __gllc_DepthMask_Rec *) PC;
    (*__gl_dispatch.dispatch.DepthMask)(data->flag);
    return PC + sizeof(struct __gllc_DepthMask_Rec);
}

void APIENTRY __glce_IndexMask(GLuint mask);
const GLubyte *__glle_IndexMask(const GLubyte *PC)
{
    struct __gllc_IndexMask_Rec *data;

    data = (struct __gllc_IndexMask_Rec *) PC;
    (*__gl_dispatch.dispatch.IndexMask)(data->mask);
    return PC + sizeof(struct __gllc_IndexMask_Rec);
}

void APIENTRY __glce_Accum(GLenum op, GLfloat value);
const GLubyte *__glle_Accum(const GLubyte *PC)
{
    struct __gllc_Accum_Rec *data;

    data = (struct __gllc_Accum_Rec *) PC;
    (*__gl_dispatch.dispatch.Accum)(data->op, data->value);
    return PC + sizeof(struct __gllc_Accum_Rec);
}

void APIENTRY __glce_Disable(GLenum cap);
void APIENTRY __glce_Enable(GLenum cap);
void APIENTRY __glce_Finish(void);
void APIENTRY __glce_Flush(void);
void APIENTRY __glce_PopAttrib(void);
const GLubyte *__glle_PopAttrib(const GLubyte *PC)
{

    (*__gl_dispatch.dispatch.PopAttrib)();
    return PC;
}

void APIENTRY __glce_PushAttrib(GLbitfield mask);
const GLubyte *__glle_PushAttrib(const GLubyte *PC)
{
    struct __gllc_PushAttrib_Rec *data;

    data = (struct __gllc_PushAttrib_Rec *) PC;
    (*__gl_dispatch.dispatch.PushAttrib)(data->mask);
    return PC + sizeof(struct __gllc_PushAttrib_Rec);
}

void APIENTRY __glce_Map1d(GLenum target, GLdouble u1, GLdouble u2, GLint stride, GLint order, const GLdouble *points);
void APIENTRY __glce_Map1f(GLenum target, GLfloat u1, GLfloat u2, GLint stride, GLint order, const GLfloat *points);
void APIENTRY __glce_Map2d(GLenum target, GLdouble u1, GLdouble u2, GLint ustride, GLint uorder, GLdouble v1, GLdouble v2, GLint vstride, GLint vorder, const GLdouble *points);
void APIENTRY __glce_Map2f(GLenum target, GLfloat u1, GLfloat u2, GLint ustride, GLint uorder, GLfloat v1, GLfloat v2, GLint vstride, GLint vorder, const GLfloat *points);
void APIENTRY __glce_MapGrid1d(GLint un, GLdouble u1, GLdouble u2);
const GLubyte *__glle_MapGrid1d(const GLubyte *PC)
{
    struct __gllc_MapGrid1d_Rec *data;

    data = (struct __gllc_MapGrid1d_Rec *) PC;
    (*__gl_dispatch.dispatch.MapGrid1d)(data->un, data->u1, data->u2);
    return PC + sizeof(struct __gllc_MapGrid1d_Rec);
}

void APIENTRY __glce_MapGrid1f(GLint un, GLfloat u1, GLfloat u2);
const GLubyte *__glle_MapGrid1f(const GLubyte *PC)
{
    struct __gllc_MapGrid1f_Rec *data;

    data = (struct __gllc_MapGrid1f_Rec *) PC;
    (*__gl_dispatch.dispatch.MapGrid1f)(data->un, data->u1, data->u2);
    return PC + sizeof(struct __gllc_MapGrid1f_Rec);
}

void APIENTRY __glce_MapGrid2d(GLint un, GLdouble u1, GLdouble u2, GLint vn, GLdouble v1, GLdouble v2);
const GLubyte *__glle_MapGrid2d(const GLubyte *PC)
{
    struct __gllc_MapGrid2d_Rec *data;

    data = (struct __gllc_MapGrid2d_Rec *) PC;
    (*__gl_dispatch.dispatch.MapGrid2d)(data->un, data->u1, data->u2, data->vn, 
	    data->v1, data->v2);
    return PC + sizeof(struct __gllc_MapGrid2d_Rec);
}

void APIENTRY __glce_MapGrid2f(GLint un, GLfloat u1, GLfloat u2, GLint vn, GLfloat v1, GLfloat v2);
const GLubyte *__glle_MapGrid2f(const GLubyte *PC)
{
    struct __gllc_MapGrid2f_Rec *data;

    data = (struct __gllc_MapGrid2f_Rec *) PC;
    (*__gl_dispatch.dispatch.MapGrid2f)(data->un, data->u1, data->u2, data->vn, 
	    data->v1, data->v2);
    return PC + sizeof(struct __gllc_MapGrid2f_Rec);
}

void APIENTRY __glce_EvalCoord1d(GLdouble u);
void APIENTRY __glce_EvalCoord1dv(const GLdouble *u);
const GLubyte *__glle_EvalCoord1dv(const GLubyte *PC)
{
    struct __gllc_EvalCoord1dv_Rec *data;

    data = (struct __gllc_EvalCoord1dv_Rec *) PC;
    (*__gl_dispatch.dispatch.EvalCoord1dv)(data->u);
    return PC + sizeof(struct __gllc_EvalCoord1dv_Rec);
}

void APIENTRY __glce_EvalCoord1f(GLfloat u);
void APIENTRY __glce_EvalCoord1fv(const GLfloat *u);
const GLubyte *__glle_EvalCoord1fv(const GLubyte *PC)
{
    struct __gllc_EvalCoord1fv_Rec *data;

    data = (struct __gllc_EvalCoord1fv_Rec *) PC;
    (*__gl_dispatch.dispatch.EvalCoord1fv)(data->u);
    return PC + sizeof(struct __gllc_EvalCoord1fv_Rec);
}

void APIENTRY __glce_EvalCoord2d(GLdouble u, GLdouble v);
void APIENTRY __glce_EvalCoord2dv(const GLdouble *u);
const GLubyte *__glle_EvalCoord2dv(const GLubyte *PC)
{
    struct __gllc_EvalCoord2dv_Rec *data;

    data = (struct __gllc_EvalCoord2dv_Rec *) PC;
    (*__gl_dispatch.dispatch.EvalCoord2dv)(data->u);
    return PC + sizeof(struct __gllc_EvalCoord2dv_Rec);
}

void APIENTRY __glce_EvalCoord2f(GLfloat u, GLfloat v);
void APIENTRY __glce_EvalCoord2fv(const GLfloat *u);
const GLubyte *__glle_EvalCoord2fv(const GLubyte *PC)
{
    struct __gllc_EvalCoord2fv_Rec *data;

    data = (struct __gllc_EvalCoord2fv_Rec *) PC;
    (*__gl_dispatch.dispatch.EvalCoord2fv)(data->u);
    return PC + sizeof(struct __gllc_EvalCoord2fv_Rec);
}

void APIENTRY __glce_EvalMesh1(GLenum mode, GLint i1, GLint i2);
const GLubyte *__glle_EvalMesh1(const GLubyte *PC)
{
    struct __gllc_EvalMesh1_Rec *data;

    data = (struct __gllc_EvalMesh1_Rec *) PC;
    (*__gl_dispatch.dispatch.EvalMesh1)(data->mode, data->i1, data->i2);
    return PC + sizeof(struct __gllc_EvalMesh1_Rec);
}

void APIENTRY __glce_EvalPoint1(GLint i);
const GLubyte *__glle_EvalPoint1(const GLubyte *PC)
{
    struct __gllc_EvalPoint1_Rec *data;

    data = (struct __gllc_EvalPoint1_Rec *) PC;
    (*__gl_dispatch.dispatch.EvalPoint1)(data->i);
    return PC + sizeof(struct __gllc_EvalPoint1_Rec);
}

void APIENTRY __glce_EvalMesh2(GLenum mode, GLint i1, GLint i2, GLint j1, GLint j2);
const GLubyte *__glle_EvalMesh2(const GLubyte *PC)
{
    struct __gllc_EvalMesh2_Rec *data;

    data = (struct __gllc_EvalMesh2_Rec *) PC;
    (*__gl_dispatch.dispatch.EvalMesh2)(data->mode, data->i1, data->i2, data->j1, 
	    data->j2);
    return PC + sizeof(struct __gllc_EvalMesh2_Rec);
}

void APIENTRY __glce_EvalPoint2(GLint i, GLint j);
const GLubyte *__glle_EvalPoint2(const GLubyte *PC)
{
    struct __gllc_EvalPoint2_Rec *data;

    data = (struct __gllc_EvalPoint2_Rec *) PC;
    (*__gl_dispatch.dispatch.EvalPoint2)(data->i, data->j);
    return PC + sizeof(struct __gllc_EvalPoint2_Rec);
}

void APIENTRY __glce_AlphaFunc(GLenum func, GLclampf ref);
const GLubyte *__glle_AlphaFunc(const GLubyte *PC)
{
    struct __gllc_AlphaFunc_Rec *data;

    data = (struct __gllc_AlphaFunc_Rec *) PC;
    (*__gl_dispatch.dispatch.AlphaFunc)(data->func, data->ref);
    return PC + sizeof(struct __gllc_AlphaFunc_Rec);
}

void APIENTRY __glce_BlendFunc(GLenum sfactor, GLenum dfactor);
const GLubyte *__glle_BlendFunc(const GLubyte *PC)
{
    struct __gllc_BlendFunc_Rec *data;

    data = (struct __gllc_BlendFunc_Rec *) PC;
    (*__gl_dispatch.dispatch.BlendFunc)(data->sfactor, data->dfactor);
    return PC + sizeof(struct __gllc_BlendFunc_Rec);
}

void APIENTRY __glce_LogicOp(GLenum opcode);
const GLubyte *__glle_LogicOp(const GLubyte *PC)
{
    struct __gllc_LogicOp_Rec *data;

    data = (struct __gllc_LogicOp_Rec *) PC;
    (*__gl_dispatch.dispatch.LogicOp)(data->opcode);
    return PC + sizeof(struct __gllc_LogicOp_Rec);
}

void APIENTRY __glce_StencilFunc(GLenum func, GLint ref, GLuint mask);
const GLubyte *__glle_StencilFunc(const GLubyte *PC)
{
    struct __gllc_StencilFunc_Rec *data;

    data = (struct __gllc_StencilFunc_Rec *) PC;
    (*__gl_dispatch.dispatch.StencilFunc)(data->func, data->ref, data->mask);
    return PC + sizeof(struct __gllc_StencilFunc_Rec);
}

void APIENTRY __glce_StencilOp(GLenum fail, GLenum zfail, GLenum zpass);
const GLubyte *__glle_StencilOp(const GLubyte *PC)
{
    struct __gllc_StencilOp_Rec *data;

    data = (struct __gllc_StencilOp_Rec *) PC;
    (*__gl_dispatch.dispatch.StencilOp)(data->fail, data->zfail, data->zpass);
    return PC + sizeof(struct __gllc_StencilOp_Rec);
}

void APIENTRY __glce_DepthFunc(GLenum func);
const GLubyte *__glle_DepthFunc(const GLubyte *PC)
{
    struct __gllc_DepthFunc_Rec *data;

    data = (struct __gllc_DepthFunc_Rec *) PC;
    (*__gl_dispatch.dispatch.DepthFunc)(data->func);
    return PC + sizeof(struct __gllc_DepthFunc_Rec);
}

void APIENTRY __glce_PixelZoom(GLfloat xfactor, GLfloat yfactor);
const GLubyte *__glle_PixelZoom(const GLubyte *PC)
{
    struct __gllc_PixelZoom_Rec *data;

    data = (struct __gllc_PixelZoom_Rec *) PC;
    (*__gl_dispatch.dispatch.PixelZoom)(data->xfactor, data->yfactor);
    return PC + sizeof(struct __gllc_PixelZoom_Rec);
}

void APIENTRY __glce_PixelTransferf(GLenum pname, GLfloat param);
const GLubyte *__glle_PixelTransferf(const GLubyte *PC)
{
    struct __gllc_PixelTransferf_Rec *data;

    data = (struct __gllc_PixelTransferf_Rec *) PC;
    (*__gl_dispatch.dispatch.PixelTransferf)(data->pname, data->param);
    return PC + sizeof(struct __gllc_PixelTransferf_Rec);
}

void APIENTRY __glce_PixelTransferi(GLenum pname, GLint param);
const GLubyte *__glle_PixelTransferi(const GLubyte *PC)
{
    struct __gllc_PixelTransferi_Rec *data;

    data = (struct __gllc_PixelTransferi_Rec *) PC;
    (*__gl_dispatch.dispatch.PixelTransferi)(data->pname, data->param);
    return PC + sizeof(struct __gllc_PixelTransferi_Rec);
}

void APIENTRY __glce_PixelStoref(GLenum pname, GLfloat param);
void APIENTRY __glce_PixelStorei(GLenum pname, GLint param);
void APIENTRY __glce_PixelMapfv(GLenum map, GLint mapsize, const GLfloat *values);
const GLubyte *__glle_PixelMapfv(const GLubyte *PC)
{
    GLuint size;
    GLuint arraySize;
    struct __gllc_PixelMapfv_Rec *data;

    data = (struct __gllc_PixelMapfv_Rec *) PC;
    (*__gl_dispatch.dispatch.PixelMapfv)(data->map, data->mapsize, 
	    (GLfloat *) (PC + sizeof(struct __gllc_PixelMapfv_Rec)));
    arraySize = __GL64PAD(data->mapsize * 4);
    size = (GLuint)sizeof(struct __gllc_PixelMapfv_Rec) + arraySize;
    return PC + size;
}

void APIENTRY __glce_PixelMapuiv(GLenum map, GLint mapsize, const GLuint *values);
const GLubyte *__glle_PixelMapuiv(const GLubyte *PC)
{
    GLuint size;
    GLuint arraySize;
    struct __gllc_PixelMapuiv_Rec *data;

    data = (struct __gllc_PixelMapuiv_Rec *) PC;
    (*__gl_dispatch.dispatch.PixelMapuiv)(data->map, data->mapsize, 
	    (GLuint *) (PC + sizeof(struct __gllc_PixelMapuiv_Rec)));
    arraySize = __GL64PAD(data->mapsize * 4);
    size = (GLuint)sizeof(struct __gllc_PixelMapuiv_Rec) + arraySize;
    return PC + size;
}

void APIENTRY __glce_PixelMapusv(GLenum map, GLint mapsize, const GLushort *values);
const GLubyte *__glle_PixelMapusv(const GLubyte *PC)
{
    GLuint size;
    GLuint arraySize;
    struct __gllc_PixelMapusv_Rec *data;

    data = (struct __gllc_PixelMapusv_Rec *) PC;
    (*__gl_dispatch.dispatch.PixelMapusv)(data->map, data->mapsize, 
	    (GLushort *) (PC + sizeof(struct __gllc_PixelMapusv_Rec)));
    arraySize = __GL_PAD(data->mapsize * 2);
    size = (GLuint)sizeof(struct __gllc_PixelMapusv_Rec) + arraySize;
    return PC + size;
}

void APIENTRY __glce_ReadBuffer(GLenum mode);
const GLubyte *__glle_ReadBuffer(const GLubyte *PC)
{
    struct __gllc_ReadBuffer_Rec *data;

    data = (struct __gllc_ReadBuffer_Rec *) PC;
    (*__gl_dispatch.dispatch.ReadBuffer)(data->mode);
    return PC + sizeof(struct __gllc_ReadBuffer_Rec);
}

void APIENTRY __glce_CopyPixels(GLint x, GLint y, GLsizei width, GLsizei height, GLenum type);
const GLubyte *__glle_CopyPixels(const GLubyte *PC)
{
    struct __gllc_CopyPixels_Rec *data;

    data = (struct __gllc_CopyPixels_Rec *) PC;
    (*__gl_dispatch.dispatch.CopyPixels)(data->x, data->y, data->width, data->height, 
	    data->type);
    return PC + sizeof(struct __gllc_CopyPixels_Rec);
}

void APIENTRY __glce_ReadPixels(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid *pixels);
void APIENTRY __glce_DrawPixels(GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels);
void APIENTRY __glce_GetBooleanv(GLenum pname, GLboolean *params);
void APIENTRY __glce_GetClipPlane(GLenum plane, GLdouble *equation);
void APIENTRY __glce_GetDoublev(GLenum pname, GLdouble *params);
GLenum APIENTRY __glce_GetError(void);
void APIENTRY __glce_GetFloatv(GLenum pname, GLfloat *params);
void APIENTRY __glce_GetIntegerv(GLenum pname, GLint *params);
void APIENTRY __glce_GetLightfv(GLenum light, GLenum pname, GLfloat *params);
void APIENTRY __glce_GetLightiv(GLenum light, GLenum pname, GLint *params);
void APIENTRY __glce_GetMapdv(GLenum target, GLenum query, GLdouble *v);
void APIENTRY __glce_GetMapfv(GLenum target, GLenum query, GLfloat *v);
void APIENTRY __glce_GetMapiv(GLenum target, GLenum query, GLint *v);
void APIENTRY __glce_GetMaterialfv(GLenum face, GLenum pname, GLfloat *params);
void APIENTRY __glce_GetMaterialiv(GLenum face, GLenum pname, GLint *params);
void APIENTRY __glce_GetPixelMapfv(GLenum map, GLfloat *values);
void APIENTRY __glce_GetPixelMapuiv(GLenum map, GLuint *values);
void APIENTRY __glce_GetPixelMapusv(GLenum map, GLushort *values);
void APIENTRY __glce_GetPolygonStipple(GLubyte *mask);
const GLubyte * APIENTRY __glce_GetString(GLenum name);
void APIENTRY __glce_GetTexEnvfv(GLenum target, GLenum pname, GLfloat *params);
void APIENTRY __glce_GetTexEnviv(GLenum target, GLenum pname, GLint *params);
void APIENTRY __glce_GetTexGendv(GLenum coord, GLenum pname, GLdouble *params);
void APIENTRY __glce_GetTexGenfv(GLenum coord, GLenum pname, GLfloat *params);
void APIENTRY __glce_GetTexGeniv(GLenum coord, GLenum pname, GLint *params);
void APIENTRY __glce_GetTexImage(GLenum target, GLint level, GLenum format, GLenum type, GLvoid *pixels);
void APIENTRY __glce_GetTexParameterfv(GLenum target, GLenum pname, GLfloat *params);
void APIENTRY __glce_GetTexParameteriv(GLenum target, GLenum pname, GLint *params);
void APIENTRY __glce_GetTexLevelParameterfv(GLenum target, GLint level, GLenum pname, GLfloat *params);
void APIENTRY __glce_GetTexLevelParameteriv(GLenum target, GLint level, GLenum pname, GLint *params);
GLboolean APIENTRY __glce_IsEnabled(GLenum cap);
GLboolean APIENTRY __glce_IsList(GLuint list);
void APIENTRY __glce_DepthRange(GLclampd zNear, GLclampd zFar);
const GLubyte *__glle_DepthRange(const GLubyte *PC)
{
    struct __gllc_DepthRange_Rec *data;

    data = (struct __gllc_DepthRange_Rec *) PC;
    (*__gl_dispatch.dispatch.DepthRange)(data->zNear, data->zFar);
    return PC + sizeof(struct __gllc_DepthRange_Rec);
}

void APIENTRY __glce_Frustum(GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble zNear, GLdouble zFar);
const GLubyte *__glle_Frustum(const GLubyte *PC)
{
    struct __gllc_Frustum_Rec *data;

    data = (struct __gllc_Frustum_Rec *) PC;
    (*__gl_dispatch.dispatch.Frustum)(data->left, data->right, data->bottom, data->top, 
	    data->zNear, data->zFar);
    return PC + sizeof(struct __gllc_Frustum_Rec);
}

void APIENTRY __glce_LoadIdentity(void);
const GLubyte *__glle_LoadIdentity(const GLubyte *PC)
{

    (*__gl_dispatch.dispatch.LoadIdentity)();
    return PC;
}

void APIENTRY __glce_LoadMatrixf(const GLfloat *m);
const GLubyte *__glle_LoadMatrixf(const GLubyte *PC)
{
    struct __gllc_LoadMatrixf_Rec *data;

    data = (struct __gllc_LoadMatrixf_Rec *) PC;
    (*__gl_dispatch.dispatch.LoadMatrixf)(data->m);
    return PC + sizeof(struct __gllc_LoadMatrixf_Rec);
}

void APIENTRY __glce_LoadMatrixd(const GLdouble *m);
const GLubyte *__glle_LoadMatrixd(const GLubyte *PC)
{
    struct __gllc_LoadMatrixd_Rec *data;

    data = (struct __gllc_LoadMatrixd_Rec *) PC;
    (*__gl_dispatch.dispatch.LoadMatrixd)(data->m);
    return PC + sizeof(struct __gllc_LoadMatrixd_Rec);
}

void APIENTRY __glce_MatrixMode(GLenum mode);
const GLubyte *__glle_MatrixMode(const GLubyte *PC)
{
    struct __gllc_MatrixMode_Rec *data;

    data = (struct __gllc_MatrixMode_Rec *) PC;
    (*__gl_dispatch.dispatch.MatrixMode)(data->mode);
    return PC + sizeof(struct __gllc_MatrixMode_Rec);
}

void APIENTRY __glce_MultMatrixf(const GLfloat *m);
const GLubyte *__glle_MultMatrixf(const GLubyte *PC)
{
    struct __gllc_MultMatrixf_Rec *data;

    data = (struct __gllc_MultMatrixf_Rec *) PC;
    (*__gl_dispatch.dispatch.MultMatrixf)(data->m);
    return PC + sizeof(struct __gllc_MultMatrixf_Rec);
}

void APIENTRY __glce_MultMatrixd(const GLdouble *m);
const GLubyte *__glle_MultMatrixd(const GLubyte *PC)
{
    struct __gllc_MultMatrixd_Rec *data;

    data = (struct __gllc_MultMatrixd_Rec *) PC;
    (*__gl_dispatch.dispatch.MultMatrixd)(data->m);
    return PC + sizeof(struct __gllc_MultMatrixd_Rec);
}

void APIENTRY __glce_Ortho(GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble zNear, GLdouble zFar);
const GLubyte *__glle_Ortho(const GLubyte *PC)
{
    struct __gllc_Ortho_Rec *data;

    data = (struct __gllc_Ortho_Rec *) PC;
    (*__gl_dispatch.dispatch.Ortho)(data->left, data->right, data->bottom, data->top, 
	    data->zNear, data->zFar);
    return PC + sizeof(struct __gllc_Ortho_Rec);
}

void APIENTRY __glce_PopMatrix(void);
const GLubyte *__glle_PopMatrix(const GLubyte *PC)
{

    (*__gl_dispatch.dispatch.PopMatrix)();
    return PC;
}

void APIENTRY __glce_PushMatrix(void);
const GLubyte *__glle_PushMatrix(const GLubyte *PC)
{

    (*__gl_dispatch.dispatch.PushMatrix)();
    return PC;
}

void APIENTRY __glce_Rotated(GLdouble angle, GLdouble x, GLdouble y, GLdouble z);
const GLubyte *__glle_Rotated(const GLubyte *PC)
{
    struct __gllc_Rotated_Rec *data;

    data = (struct __gllc_Rotated_Rec *) PC;
    (*__gl_dispatch.dispatch.Rotated)(data->angle, data->x, data->y, data->z);
    return PC + sizeof(struct __gllc_Rotated_Rec);
}

void APIENTRY __glce_Rotatef(GLfloat angle, GLfloat x, GLfloat y, GLfloat z);
const GLubyte *__glle_Rotatef(const GLubyte *PC)
{
    struct __gllc_Rotatef_Rec *data;

    data = (struct __gllc_Rotatef_Rec *) PC;
    (*__gl_dispatch.dispatch.Rotatef)(data->angle, data->x, data->y, data->z);
    return PC + sizeof(struct __gllc_Rotatef_Rec);
}

void APIENTRY __glce_Scaled(GLdouble x, GLdouble y, GLdouble z);
const GLubyte *__glle_Scaled(const GLubyte *PC)
{
    struct __gllc_Scaled_Rec *data;

    data = (struct __gllc_Scaled_Rec *) PC;
    (*__gl_dispatch.dispatch.Scaled)(data->x, data->y, data->z);
    return PC + sizeof(struct __gllc_Scaled_Rec);
}

void APIENTRY __glce_Scalef(GLfloat x, GLfloat y, GLfloat z);
const GLubyte *__glle_Scalef(const GLubyte *PC)
{
    struct __gllc_Scalef_Rec *data;

    data = (struct __gllc_Scalef_Rec *) PC;
    (*__gl_dispatch.dispatch.Scalef)(data->x, data->y, data->z);
    return PC + sizeof(struct __gllc_Scalef_Rec);
}

void APIENTRY __glce_Translated(GLdouble x, GLdouble y, GLdouble z);
const GLubyte *__glle_Translated(const GLubyte *PC)
{
    struct __gllc_Translated_Rec *data;

    data = (struct __gllc_Translated_Rec *) PC;
    (*__gl_dispatch.dispatch.Translated)(data->x, data->y, data->z);
    return PC + sizeof(struct __gllc_Translated_Rec);
}

void APIENTRY __glce_Translatef(GLfloat x, GLfloat y, GLfloat z);
const GLubyte *__glle_Translatef(const GLubyte *PC)
{
    struct __gllc_Translatef_Rec *data;

    data = (struct __gllc_Translatef_Rec *) PC;
    (*__gl_dispatch.dispatch.Translatef)(data->x, data->y, data->z);
    return PC + sizeof(struct __gllc_Translatef_Rec);
}

void APIENTRY __glce_Viewport(GLint x, GLint y, GLsizei width, GLsizei height);
const GLubyte *__glle_Viewport(const GLubyte *PC)
{
    struct __gllc_Viewport_Rec *data;

    data = (struct __gllc_Viewport_Rec *) PC;
    (*__gl_dispatch.dispatch.Viewport)(data->x, data->y, data->width, data->height);
    return PC + sizeof(struct __gllc_Viewport_Rec);
}

void APIENTRY __glce_ArrayElementEXT(GLint i);
void APIENTRY __glce_ColorPointerEXT(GLint size, GLenum type, GLsizei stride, GLsizei count, const GLvoid *pointer);
void APIENTRY __glce_DrawArraysEXT(GLenum mode, GLint first, GLsizei count);
void APIENTRY __glce_EdgeFlagPointerEXT(GLsizei stride, GLsizei count, const GLboolean *pointer);
void APIENTRY __glce_GetPointervEXT(GLenum pname, GLvoid* *params);
void APIENTRY __glce_IndexPointerEXT(GLenum type, GLsizei stride, GLsizei count, const GLvoid *pointer);
void APIENTRY __glce_NormalPointerEXT(GLenum type, GLsizei stride, GLsizei count, const GLvoid *pointer);
void APIENTRY __glce_TexCoordPointerEXT(GLint size, GLenum type, GLsizei stride, GLsizei count, const GLvoid *pointer);
void APIENTRY __glce_VertexPointerEXT(GLint size, GLenum type, GLsizei stride, GLsizei count, const GLvoid *pointer);
void APIENTRY __glce_ColorSubTableEXT(GLenum target, GLsizei start, GLsizei count, GLenum format, GLenum type, const GLvoid *table);
void APIENTRY __glce_ColorTableEXT(GLenum target, GLenum internalformat, GLsizei width, GLenum format, GLenum type, const GLvoid *table);
void APIENTRY __glce_CopyColorTableEXT(GLenum target, GLenum internalformat, GLint x, GLint y, GLsizei width);
const GLubyte *__glle_CopyColorTableEXT(const GLubyte *PC)
{
    struct __gllc_CopyColorTableEXT_Rec *data;

    data = (struct __gllc_CopyColorTableEXT_Rec *) PC;
    (*__gl_dispatch.extensions.CopyColorTableEXT)(data->target, data->internalformat, data->x, data->y, 
	    data->width);
    return PC + sizeof(struct __gllc_CopyColorTableEXT_Rec);
}

void APIENTRY __glce_GetColorTableEXT(GLenum target, GLenum format, GLenum type, GLvoid *table);
void APIENTRY __glce_GetColorTableParameterfvEXT(GLenum target, GLenum pname, GLfloat *params);
void APIENTRY __glce_GetColorTableParameterivEXT(GLenum target, GLenum pname, GLint *params);
void APIENTRY __glce_ArrayElement(GLint i);
void APIENTRY __glce_ColorPointer(GLint size, GLenum type, GLsizei stride, const GLvoid *pointer);
void APIENTRY __glce_DisableClientState(GLenum array);
void APIENTRY __glce_DrawArrays(GLenum mode, GLint first, GLsizei count);
void APIENTRY __glce_DrawElements(GLenum mode, GLsizei count, GLenum type, const GLvoid *indices);
void APIENTRY __glce_EdgeFlagPointer(GLsizei stride, const GLboolean *pointer);
void APIENTRY __glce_EnableClientState(GLenum array);
void APIENTRY __glce_GetPointerv(GLenum pname, GLvoid* *params);
void APIENTRY __glce_IndexPointer(GLenum type, GLsizei stride, const GLvoid *pointer);
void APIENTRY __glce_InterleavedArrays(GLenum format, GLsizei stride, const GLvoid *pointer);
void APIENTRY __glce_NormalPointer(GLenum type, GLsizei stride, const GLvoid *pointer);
void APIENTRY __glce_TexCoordPointer(GLint size, GLenum type, GLsizei stride, const GLvoid *pointer);
void APIENTRY __glce_VertexPointer(GLint size, GLenum type, GLsizei stride, const GLvoid *pointer);
void APIENTRY __glce_PolygonOffset(GLfloat factor, GLfloat units);
const GLubyte *__glle_PolygonOffset(const GLubyte *PC)
{
    struct __gllc_PolygonOffset_Rec *data;

    data = (struct __gllc_PolygonOffset_Rec *) PC;
    (*__gl_dispatch.dispatch.PolygonOffset)(data->factor, data->units);
    return PC + sizeof(struct __gllc_PolygonOffset_Rec);
}

void APIENTRY __glce_CopyTexImage1D(GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLint border);
const GLubyte *__glle_CopyTexImage1D(const GLubyte *PC)
{
    struct __gllc_CopyTexImage1D_Rec *data;

    data = (struct __gllc_CopyTexImage1D_Rec *) PC;
    (*__gl_dispatch.dispatch.CopyTexImage1D)(data->target, data->level, data->internalformat, data->x, 
	    data->y, data->width, data->border);
    return PC + sizeof(struct __gllc_CopyTexImage1D_Rec);
}

void APIENTRY __glce_CopyTexImage2D(GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border);
const GLubyte *__glle_CopyTexImage2D(const GLubyte *PC)
{
    struct __gllc_CopyTexImage2D_Rec *data;

    data = (struct __gllc_CopyTexImage2D_Rec *) PC;
    (*__gl_dispatch.dispatch.CopyTexImage2D)(data->target, data->level, data->internalformat, data->x, 
	    data->y, data->width, data->height, data->border);
    return PC + sizeof(struct __gllc_CopyTexImage2D_Rec);
}

void APIENTRY __glce_CopyTexSubImage1D(GLenum target, GLint level, GLint xoffset, GLint x, GLint y, GLsizei width);
const GLubyte *__glle_CopyTexSubImage1D(const GLubyte *PC)
{
    struct __gllc_CopyTexSubImage1D_Rec *data;

    data = (struct __gllc_CopyTexSubImage1D_Rec *) PC;
    (*__gl_dispatch.dispatch.CopyTexSubImage1D)(data->target, data->level, data->xoffset, data->x, 
	    data->y, data->width);
    return PC + sizeof(struct __gllc_CopyTexSubImage1D_Rec);
}

void APIENTRY __glce_CopyTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height);
const GLubyte *__glle_CopyTexSubImage2D(const GLubyte *PC)
{
    struct __gllc_CopyTexSubImage2D_Rec *data;

    data = (struct __gllc_CopyTexSubImage2D_Rec *) PC;
    (*__gl_dispatch.dispatch.CopyTexSubImage2D)(data->target, data->level, data->xoffset, data->yoffset, 
	    data->x, data->y, data->width, data->height);
    return PC + sizeof(struct __gllc_CopyTexSubImage2D_Rec);
}

void APIENTRY __glce_TexSubImage1D(GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const GLvoid *pixels);
void APIENTRY __glce_TexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels);
GLboolean APIENTRY __glce_AreTexturesResident(GLsizei n, const GLuint *textures, GLboolean *residences);
void APIENTRY __glce_BindTexture(GLenum target, GLuint texture);
const GLubyte *__glle_BindTexture(const GLubyte *PC)
{
    struct __gllc_BindTexture_Rec *data;

    data = (struct __gllc_BindTexture_Rec *) PC;
    (*__gl_dispatch.dispatch.BindTexture)(data->target, data->texture);
    return PC + sizeof(struct __gllc_BindTexture_Rec);
}

void APIENTRY __glce_DeleteTextures(GLsizei n, const GLuint *textures);
void APIENTRY __glce_GenTextures(GLsizei n, GLuint *textures);
GLboolean APIENTRY __glce_IsTexture(GLuint texture);
void APIENTRY __glce_PrioritizeTextures(GLsizei n, const GLuint *textures, const GLclampf *priorities);
const GLubyte *__glle_PrioritizeTextures(const GLubyte *PC)
{
    GLuint size;
    GLuint arraySize0;
    GLuint arraySize1;
    struct __gllc_PrioritizeTextures_Rec *data;

    data = (struct __gllc_PrioritizeTextures_Rec *) PC;
    arraySize0 = __GL64PAD(data->n * 4);
    arraySize1 = __GL64PAD(data->n * 4);
    size = (GLuint)sizeof(struct __gllc_PrioritizeTextures_Rec) + arraySize0 + arraySize1;
    (*__gl_dispatch.dispatch.PrioritizeTextures)(data->n, 
	    (GLuint *) (PC + sizeof(struct __gllc_PrioritizeTextures_Rec)), 
	    (GLclampf *) (PC + sizeof(struct __gllc_PrioritizeTextures_Rec) + arraySize0));
    return PC + size;
}

void APIENTRY __glce_Indexub(GLubyte c);
void APIENTRY __glce_Indexubv(const GLubyte *c);
const GLubyte *__glle_Indexubv(const GLubyte *PC)
{
    struct __gllc_Indexubv_Rec *data;

    data = (struct __gllc_Indexubv_Rec *) PC;
    (*__gl_dispatch.dispatch.Indexubv)(data->c);
    return PC + sizeof(struct __gllc_Indexubv_Rec);
}

void APIENTRY __glce_PopClientAttrib(void);
void APIENTRY __glce_PushClientAttrib(GLbitfield mask);
void APIENTRY __glce_LockArraysSGI(GLint first, GLsizei count);
void APIENTRY __glce_UnlockArraysSGI(void);
void APIENTRY __glce_CullParameterdvSGI(GLenum pname, GLdouble* params);
void APIENTRY __glce_CullParameterfvSGI(GLenum pname, GLfloat* params);
void APIENTRY __glce_IndexFuncSGI(GLenum func, GLclampf ref);
const GLubyte *__glle_IndexFuncSGI(const GLubyte *PC)
{
    struct __gllc_IndexFuncSGI_Rec *data;

    data = (struct __gllc_IndexFuncSGI_Rec *) PC;
    (*__gl_dispatch.extensions.IndexFuncSGI)(data->func, data->ref);
    return PC + sizeof(struct __gllc_IndexFuncSGI_Rec);
}

void APIENTRY __glce_IndexMaterialSGI(GLenum face, GLenum mode);
const GLubyte *__glle_IndexMaterialSGI(const GLubyte *PC)
{
    struct __gllc_IndexMaterialSGI_Rec *data;

    data = (struct __gllc_IndexMaterialSGI_Rec *) PC;
    (*__gl_dispatch.extensions.IndexMaterialSGI)(data->face, data->mode);
    return PC + sizeof(struct __gllc_IndexMaterialSGI_Rec);
}

void APIENTRY __glce_AddSwapHintRectWIN(GLint x, GLint y, GLsizei width, GLsizei height);

