/* DO NOT EDIT - THIS FILE IS AUTOMATICALLY GENERATED */

/*
** Copyright 1992-1997 Silicon Graphics, Inc.
** All Rights Reserved.
**
** This is UNPUBLISHED PROPRIETARY SOURCE CODE of Silicon Graphics, Inc.;
** the contents of this file may not be disclosed to third parties, copied or
** duplicated in any form, in whole or in part, without the prior written
** permission of Silicon Graphics, Inc.
**
** RESTRICTED RIGHTS LEGEND:
** Use, duplication or disclosure by the Government is subject to restrictions
** as set forth in subdivision (c)(1)(ii) of the Rights in Technical Data
** and Computer Software clause at DFARS 252.227-7013, and/or in similar or
** successor clauses in the FAR, DOD or NASA FAR Supplement. Unpublished -
** rights reserved under the Copyright Laws of the United States.
*/

#include "types.h"
#include "GL/gl.h"
#include "g_disp.h"

GLint APIENTRY __glnop_Nop2(GLint i1, GLint i2)
{
    return 0;
}

GLint APIENTRY __glnop_Nop0(void)
{
    return 0;
}

GLint APIENTRY __glnop_Nop1(GLint i1)
{
    return 0;
}

GLint APIENTRY __glnop_Nop3(GLint i1, GLint i2, GLint i3)
{
    return 0;
}

GLint APIENTRY __glnop_Nop7(GLint i1, GLint i2, GLint i3, GLint i4, GLint i5, GLint i6, GLint i7)
{
    return 0;
}

GLint APIENTRY __glnop_Nop6(GLint i1, GLint i2, GLint i3, GLint i4, GLint i5, GLint i6)
{
    return 0;
}

GLint APIENTRY __glnop_Nop4(GLint i1, GLint i2, GLint i3, GLint i4)
{
    return 0;
}

GLint APIENTRY __glnop_Nop8(GLint i1, GLint i2, GLint i3, GLint i4, GLint i5, GLint i6, GLint i7, GLint i8)
{
    return 0;
}

GLint APIENTRY __glnop_Nop9(GLint i1, GLint i2, GLint i3, GLint i4, GLint i5, GLint i6, GLint i7, GLint i8, GLint i9)
{
    return 0;
}

GLint APIENTRY __glnop_Nop14(GLint i1, GLint i2, GLint i3, GLint i4, GLint i5, GLint i6, GLint i7, GLint i8, GLint i9, GLint i10, GLint i11, GLint i12, GLint i13, GLint i14)
{
    return 0;
}

GLint APIENTRY __glnop_Nop10(GLint i1, GLint i2, GLint i3, GLint i4, GLint i5, GLint i6, GLint i7, GLint i8, GLint i9, GLint i10)
{
    return 0;
}

GLint APIENTRY __glnop_Nop5(GLint i1, GLint i2, GLint i3, GLint i4, GLint i5)
{
    return 0;
}

GLint APIENTRY __glnop_Nop12(GLint i1, GLint i2, GLint i3, GLint i4, GLint i5, GLint i6, GLint i7, GLint i8, GLint i9, GLint i10, GLint i11, GLint i12)
{
    return 0;
}

__GLdispatchState __glNopDispatchState = {
    /*
    ** number of entries
    */
    __GL_TAB_ENTRIES,

    /*
    ** dispatch
    */
    {
    (void *) __glnop_Nop2,		/* NewList */
    (void *) __glnop_Nop0,		/* EndList */
    (void *) __glnop_Nop1,		/* CallList */
    (void *) __glnop_Nop3,		/* CallLists */
    (void *) __glnop_Nop2,		/* DeleteLists */
    (void *) __glnop_Nop1,		/* GenLists */
    (void *) __glnop_Nop1,		/* ListBase */
    (void *) __glnop_Nop1,		/* Begin */
    (void *) __glnop_Nop7,		/* Bitmap */
    (void *) __glnop_Nop3,		/* Color3b */
    (void *) __glnop_Nop1,		/* Color3bv */
    (void *) __glnop_Nop6,		/* Color3d */
    (void *) __glnop_Nop1,		/* Color3dv */
    (void *) __glnop_Nop3,		/* Color3f */
    (void *) __glnop_Nop1,		/* Color3fv */
    (void *) __glnop_Nop3,		/* Color3i */
    (void *) __glnop_Nop1,		/* Color3iv */
    (void *) __glnop_Nop3,		/* Color3s */
    (void *) __glnop_Nop1,		/* Color3sv */
    (void *) __glnop_Nop3,		/* Color3ub */
    (void *) __glnop_Nop1,		/* Color3ubv */
    (void *) __glnop_Nop3,		/* Color3ui */
    (void *) __glnop_Nop1,		/* Color3uiv */
    (void *) __glnop_Nop3,		/* Color3us */
    (void *) __glnop_Nop1,		/* Color3usv */
    (void *) __glnop_Nop4,		/* Color4b */
    (void *) __glnop_Nop1,		/* Color4bv */
    (void *) __glnop_Nop8,		/* Color4d */
    (void *) __glnop_Nop1,		/* Color4dv */
    (void *) __glnop_Nop4,		/* Color4f */
    (void *) __glnop_Nop1,		/* Color4fv */
    (void *) __glnop_Nop4,		/* Color4i */
    (void *) __glnop_Nop1,		/* Color4iv */
    (void *) __glnop_Nop4,		/* Color4s */
    (void *) __glnop_Nop1,		/* Color4sv */
    (void *) __glnop_Nop4,		/* Color4ub */
    (void *) __glnop_Nop1,		/* Color4ubv */
    (void *) __glnop_Nop4,		/* Color4ui */
    (void *) __glnop_Nop1,		/* Color4uiv */
    (void *) __glnop_Nop4,		/* Color4us */
    (void *) __glnop_Nop1,		/* Color4usv */
    (void *) __glnop_Nop1,		/* EdgeFlag */
    (void *) __glnop_Nop1,		/* EdgeFlagv */
    (void *) __glnop_Nop0,		/* End */
    (void *) __glnop_Nop2,		/* Indexd */
    (void *) __glnop_Nop1,		/* Indexdv */
    (void *) __glnop_Nop1,		/* Indexf */
    (void *) __glnop_Nop1,		/* Indexfv */
    (void *) __glnop_Nop1,		/* Indexi */
    (void *) __glnop_Nop1,		/* Indexiv */
    (void *) __glnop_Nop1,		/* Indexs */
    (void *) __glnop_Nop1,		/* Indexsv */
    (void *) __glnop_Nop3,		/* Normal3b */
    (void *) __glnop_Nop1,		/* Normal3bv */
    (void *) __glnop_Nop6,		/* Normal3d */
    (void *) __glnop_Nop1,		/* Normal3dv */
    (void *) __glnop_Nop3,		/* Normal3f */
    (void *) __glnop_Nop1,		/* Normal3fv */
    (void *) __glnop_Nop3,		/* Normal3i */
    (void *) __glnop_Nop1,		/* Normal3iv */
    (void *) __glnop_Nop3,		/* Normal3s */
    (void *) __glnop_Nop1,		/* Normal3sv */
    (void *) __glnop_Nop4,		/* RasterPos2d */
    (void *) __glnop_Nop1,		/* RasterPos2dv */
    (void *) __glnop_Nop2,		/* RasterPos2f */
    (void *) __glnop_Nop1,		/* RasterPos2fv */
    (void *) __glnop_Nop2,		/* RasterPos2i */
    (void *) __glnop_Nop1,		/* RasterPos2iv */
    (void *) __glnop_Nop2,		/* RasterPos2s */
    (void *) __glnop_Nop1,		/* RasterPos2sv */
    (void *) __glnop_Nop6,		/* RasterPos3d */
    (void *) __glnop_Nop1,		/* RasterPos3dv */
    (void *) __glnop_Nop3,		/* RasterPos3f */
    (void *) __glnop_Nop1,		/* RasterPos3fv */
    (void *) __glnop_Nop3,		/* RasterPos3i */
    (void *) __glnop_Nop1,		/* RasterPos3iv */
    (void *) __glnop_Nop3,		/* RasterPos3s */
    (void *) __glnop_Nop1,		/* RasterPos3sv */
    (void *) __glnop_Nop8,		/* RasterPos4d */
    (void *) __glnop_Nop1,		/* RasterPos4dv */
    (void *) __glnop_Nop4,		/* RasterPos4f */
    (void *) __glnop_Nop1,		/* RasterPos4fv */
    (void *) __glnop_Nop4,		/* RasterPos4i */
    (void *) __glnop_Nop1,		/* RasterPos4iv */
    (void *) __glnop_Nop4,		/* RasterPos4s */
    (void *) __glnop_Nop1,		/* RasterPos4sv */
    (void *) __glnop_Nop8,		/* Rectd */
    (void *) __glnop_Nop2,		/* Rectdv */
    (void *) __glnop_Nop4,		/* Rectf */
    (void *) __glnop_Nop2,		/* Rectfv */
    (void *) __glnop_Nop4,		/* Recti */
    (void *) __glnop_Nop2,		/* Rectiv */
    (void *) __glnop_Nop4,		/* Rects */
    (void *) __glnop_Nop2,		/* Rectsv */
    (void *) __glnop_Nop2,		/* TexCoord1d */
    (void *) __glnop_Nop1,		/* TexCoord1dv */
    (void *) __glnop_Nop1,		/* TexCoord1f */
    (void *) __glnop_Nop1,		/* TexCoord1fv */
    (void *) __glnop_Nop1,		/* TexCoord1i */
    (void *) __glnop_Nop1,		/* TexCoord1iv */
    (void *) __glnop_Nop1,		/* TexCoord1s */
    (void *) __glnop_Nop1,		/* TexCoord1sv */
    (void *) __glnop_Nop4,		/* TexCoord2d */
    (void *) __glnop_Nop1,		/* TexCoord2dv */
    (void *) __glnop_Nop2,		/* TexCoord2f */
    (void *) __glnop_Nop1,		/* TexCoord2fv */
    (void *) __glnop_Nop2,		/* TexCoord2i */
    (void *) __glnop_Nop1,		/* TexCoord2iv */
    (void *) __glnop_Nop2,		/* TexCoord2s */
    (void *) __glnop_Nop1,		/* TexCoord2sv */
    (void *) __glnop_Nop6,		/* TexCoord3d */
    (void *) __glnop_Nop1,		/* TexCoord3dv */
    (void *) __glnop_Nop3,		/* TexCoord3f */
    (void *) __glnop_Nop1,		/* TexCoord3fv */
    (void *) __glnop_Nop3,		/* TexCoord3i */
    (void *) __glnop_Nop1,		/* TexCoord3iv */
    (void *) __glnop_Nop3,		/* TexCoord3s */
    (void *) __glnop_Nop1,		/* TexCoord3sv */
    (void *) __glnop_Nop8,		/* TexCoord4d */
    (void *) __glnop_Nop1,		/* TexCoord4dv */
    (void *) __glnop_Nop4,		/* TexCoord4f */
    (void *) __glnop_Nop1,		/* TexCoord4fv */
    (void *) __glnop_Nop4,		/* TexCoord4i */
    (void *) __glnop_Nop1,		/* TexCoord4iv */
    (void *) __glnop_Nop4,		/* TexCoord4s */
    (void *) __glnop_Nop1,		/* TexCoord4sv */
    (void *) __glnop_Nop4,		/* Vertex2d */
    (void *) __glnop_Nop1,		/* Vertex2dv */
    (void *) __glnop_Nop2,		/* Vertex2f */
    (void *) __glnop_Nop1,		/* Vertex2fv */
    (void *) __glnop_Nop2,		/* Vertex2i */
    (void *) __glnop_Nop1,		/* Vertex2iv */
    (void *) __glnop_Nop2,		/* Vertex2s */
    (void *) __glnop_Nop1,		/* Vertex2sv */
    (void *) __glnop_Nop6,		/* Vertex3d */
    (void *) __glnop_Nop1,		/* Vertex3dv */
    (void *) __glnop_Nop3,		/* Vertex3f */
    (void *) __glnop_Nop1,		/* Vertex3fv */
    (void *) __glnop_Nop3,		/* Vertex3i */
    (void *) __glnop_Nop1,		/* Vertex3iv */
    (void *) __glnop_Nop3,		/* Vertex3s */
    (void *) __glnop_Nop1,		/* Vertex3sv */
    (void *) __glnop_Nop8,		/* Vertex4d */
    (void *) __glnop_Nop1,		/* Vertex4dv */
    (void *) __glnop_Nop4,		/* Vertex4f */
    (void *) __glnop_Nop1,		/* Vertex4fv */
    (void *) __glnop_Nop4,		/* Vertex4i */
    (void *) __glnop_Nop1,		/* Vertex4iv */
    (void *) __glnop_Nop4,		/* Vertex4s */
    (void *) __glnop_Nop1,		/* Vertex4sv */
    (void *) __glnop_Nop2,		/* ClipPlane */
    (void *) __glnop_Nop2,		/* ColorMaterial */
    (void *) __glnop_Nop1,		/* CullFace */
    (void *) __glnop_Nop2,		/* Fogf */
    (void *) __glnop_Nop2,		/* Fogfv */
    (void *) __glnop_Nop2,		/* Fogi */
    (void *) __glnop_Nop2,		/* Fogiv */
    (void *) __glnop_Nop1,		/* FrontFace */
    (void *) __glnop_Nop2,		/* Hint */
    (void *) __glnop_Nop3,		/* Lightf */
    (void *) __glnop_Nop3,		/* Lightfv */
    (void *) __glnop_Nop3,		/* Lighti */
    (void *) __glnop_Nop3,		/* Lightiv */
    (void *) __glnop_Nop2,		/* LightModelf */
    (void *) __glnop_Nop2,		/* LightModelfv */
    (void *) __glnop_Nop2,		/* LightModeli */
    (void *) __glnop_Nop2,		/* LightModeliv */
    (void *) __glnop_Nop2,		/* LineStipple */
    (void *) __glnop_Nop1,		/* LineWidth */
    (void *) __glnop_Nop3,		/* Materialf */
    (void *) __glnop_Nop3,		/* Materialfv */
    (void *) __glnop_Nop3,		/* Materiali */
    (void *) __glnop_Nop3,		/* Materialiv */
    (void *) __glnop_Nop1,		/* PointSize */
    (void *) __glnop_Nop2,		/* PolygonMode */
    (void *) __glnop_Nop1,		/* PolygonStipple */
    (void *) __glnop_Nop4,		/* Scissor */
    (void *) __glnop_Nop1,		/* ShadeModel */
    (void *) __glnop_Nop3,		/* TexParameterf */
    (void *) __glnop_Nop3,		/* TexParameterfv */
    (void *) __glnop_Nop3,		/* TexParameteri */
    (void *) __glnop_Nop3,		/* TexParameteriv */
    (void *) __glnop_Nop8,		/* TexImage1D */
    (void *) __glnop_Nop9,		/* TexImage2D */
    (void *) __glnop_Nop3,		/* TexEnvf */
    (void *) __glnop_Nop3,		/* TexEnvfv */
    (void *) __glnop_Nop3,		/* TexEnvi */
    (void *) __glnop_Nop3,		/* TexEnviv */
    (void *) __glnop_Nop4,		/* TexGend */
    (void *) __glnop_Nop3,		/* TexGendv */
    (void *) __glnop_Nop3,		/* TexGenf */
    (void *) __glnop_Nop3,		/* TexGenfv */
    (void *) __glnop_Nop3,		/* TexGeni */
    (void *) __glnop_Nop3,		/* TexGeniv */
    (void *) __glnop_Nop3,		/* FeedbackBuffer */
    (void *) __glnop_Nop2,		/* SelectBuffer */
    (void *) __glnop_Nop1,		/* RenderMode */
    (void *) __glnop_Nop0,		/* InitNames */
    (void *) __glnop_Nop1,		/* LoadName */
    (void *) __glnop_Nop1,		/* PassThrough */
    (void *) __glnop_Nop0,		/* PopName */
    (void *) __glnop_Nop1,		/* PushName */
    (void *) __glnop_Nop1,		/* DrawBuffer */
    (void *) __glnop_Nop1,		/* Clear */
    (void *) __glnop_Nop4,		/* ClearAccum */
    (void *) __glnop_Nop1,		/* ClearIndex */
    (void *) __glnop_Nop4,		/* ClearColor */
    (void *) __glnop_Nop1,		/* ClearStencil */
    (void *) __glnop_Nop2,		/* ClearDepth */
    (void *) __glnop_Nop1,		/* StencilMask */
    (void *) __glnop_Nop4,		/* ColorMask */
    (void *) __glnop_Nop1,		/* DepthMask */
    (void *) __glnop_Nop1,		/* IndexMask */
    (void *) __glnop_Nop2,		/* Accum */
    (void *) __glnop_Nop1,		/* Disable */
    (void *) __glnop_Nop1,		/* Enable */
    (void *) __glnop_Nop0,		/* Finish */
    (void *) __glnop_Nop0,		/* Flush */
    (void *) __glnop_Nop0,		/* PopAttrib */
    (void *) __glnop_Nop1,		/* PushAttrib */
    (void *) __glnop_Nop8,		/* Map1d */
    (void *) __glnop_Nop6,		/* Map1f */
    (void *) __glnop_Nop14,		/* Map2d */
    (void *) __glnop_Nop10,		/* Map2f */
    (void *) __glnop_Nop5,		/* MapGrid1d */
    (void *) __glnop_Nop3,		/* MapGrid1f */
    (void *) __glnop_Nop10,		/* MapGrid2d */
    (void *) __glnop_Nop6,		/* MapGrid2f */
    (void *) __glnop_Nop2,		/* EvalCoord1d */
    (void *) __glnop_Nop1,		/* EvalCoord1dv */
    (void *) __glnop_Nop1,		/* EvalCoord1f */
    (void *) __glnop_Nop1,		/* EvalCoord1fv */
    (void *) __glnop_Nop4,		/* EvalCoord2d */
    (void *) __glnop_Nop1,		/* EvalCoord2dv */
    (void *) __glnop_Nop2,		/* EvalCoord2f */
    (void *) __glnop_Nop1,		/* EvalCoord2fv */
    (void *) __glnop_Nop3,		/* EvalMesh1 */
    (void *) __glnop_Nop1,		/* EvalPoint1 */
    (void *) __glnop_Nop5,		/* EvalMesh2 */
    (void *) __glnop_Nop2,		/* EvalPoint2 */
    (void *) __glnop_Nop2,		/* AlphaFunc */
    (void *) __glnop_Nop2,		/* BlendFunc */
    (void *) __glnop_Nop1,		/* LogicOp */
    (void *) __glnop_Nop3,		/* StencilFunc */
    (void *) __glnop_Nop3,		/* StencilOp */
    (void *) __glnop_Nop1,		/* DepthFunc */
    (void *) __glnop_Nop2,		/* PixelZoom */
    (void *) __glnop_Nop2,		/* PixelTransferf */
    (void *) __glnop_Nop2,		/* PixelTransferi */
    (void *) __glnop_Nop2,		/* PixelStoref */
    (void *) __glnop_Nop2,		/* PixelStorei */
    (void *) __glnop_Nop3,		/* PixelMapfv */
    (void *) __glnop_Nop3,		/* PixelMapuiv */
    (void *) __glnop_Nop3,		/* PixelMapusv */
    (void *) __glnop_Nop1,		/* ReadBuffer */
    (void *) __glnop_Nop5,		/* CopyPixels */
    (void *) __glnop_Nop7,		/* ReadPixels */
    (void *) __glnop_Nop5,		/* DrawPixels */
    (void *) __glnop_Nop2,		/* GetBooleanv */
    (void *) __glnop_Nop2,		/* GetClipPlane */
    (void *) __glnop_Nop2,		/* GetDoublev */
    (void *) __glnop_Nop0,		/* GetError */
    (void *) __glnop_Nop2,		/* GetFloatv */
    (void *) __glnop_Nop2,		/* GetIntegerv */
    (void *) __glnop_Nop3,		/* GetLightfv */
    (void *) __glnop_Nop3,		/* GetLightiv */
    (void *) __glnop_Nop3,		/* GetMapdv */
    (void *) __glnop_Nop3,		/* GetMapfv */
    (void *) __glnop_Nop3,		/* GetMapiv */
    (void *) __glnop_Nop3,		/* GetMaterialfv */
    (void *) __glnop_Nop3,		/* GetMaterialiv */
    (void *) __glnop_Nop2,		/* GetPixelMapfv */
    (void *) __glnop_Nop2,		/* GetPixelMapuiv */
    (void *) __glnop_Nop2,		/* GetPixelMapusv */
    (void *) __glnop_Nop1,		/* GetPolygonStipple */
    (void *) __glnop_Nop1,		/* GetString */
    (void *) __glnop_Nop3,		/* GetTexEnvfv */
    (void *) __glnop_Nop3,		/* GetTexEnviv */
    (void *) __glnop_Nop3,		/* GetTexGendv */
    (void *) __glnop_Nop3,		/* GetTexGenfv */
    (void *) __glnop_Nop3,		/* GetTexGeniv */
    (void *) __glnop_Nop5,		/* GetTexImage */
    (void *) __glnop_Nop3,		/* GetTexParameterfv */
    (void *) __glnop_Nop3,		/* GetTexParameteriv */
    (void *) __glnop_Nop4,		/* GetTexLevelParameterfv */
    (void *) __glnop_Nop4,		/* GetTexLevelParameteriv */
    (void *) __glnop_Nop1,		/* IsEnabled */
    (void *) __glnop_Nop1,		/* IsList */
    (void *) __glnop_Nop4,		/* DepthRange */
    (void *) __glnop_Nop12,		/* Frustum */
    (void *) __glnop_Nop0,		/* LoadIdentity */
    (void *) __glnop_Nop1,		/* LoadMatrixf */
    (void *) __glnop_Nop1,		/* LoadMatrixd */
    (void *) __glnop_Nop1,		/* MatrixMode */
    (void *) __glnop_Nop1,		/* MultMatrixf */
    (void *) __glnop_Nop1,		/* MultMatrixd */
    (void *) __glnop_Nop12,		/* Ortho */
    (void *) __glnop_Nop0,		/* PopMatrix */
    (void *) __glnop_Nop0,		/* PushMatrix */
    (void *) __glnop_Nop8,		/* Rotated */
    (void *) __glnop_Nop4,		/* Rotatef */
    (void *) __glnop_Nop6,		/* Scaled */
    (void *) __glnop_Nop3,		/* Scalef */
    (void *) __glnop_Nop6,		/* Translated */
    (void *) __glnop_Nop3,		/* Translatef */
    (void *) __glnop_Nop4,		/* Viewport */
    (void *) __glnop_Nop1,		/* ArrayElement */
    (void *) __glnop_Nop4,		/* ColorPointer */
    (void *) __glnop_Nop1,		/* DisableClientState */
    (void *) __glnop_Nop3,		/* DrawArrays */
    (void *) __glnop_Nop4,		/* DrawElements */
    (void *) __glnop_Nop2,		/* EdgeFlagPointer */
    (void *) __glnop_Nop1,		/* EnableClientState */
    (void *) __glnop_Nop2,		/* GetPointerv */
    (void *) __glnop_Nop3,		/* IndexPointer */
    (void *) __glnop_Nop3,		/* InterleavedArrays */
    (void *) __glnop_Nop3,		/* NormalPointer */
    (void *) __glnop_Nop4,		/* TexCoordPointer */
    (void *) __glnop_Nop4,		/* VertexPointer */
    (void *) __glnop_Nop2,		/* PolygonOffset */
    (void *) __glnop_Nop7,		/* CopyTexImage1D */
    (void *) __glnop_Nop8,		/* CopyTexImage2D */
    (void *) __glnop_Nop6,		/* CopyTexSubImage1D */
    (void *) __glnop_Nop8,		/* CopyTexSubImage2D */
    (void *) __glnop_Nop7,		/* TexSubImage1D */
    (void *) __glnop_Nop9,		/* TexSubImage2D */
    (void *) __glnop_Nop3,		/* AreTexturesResident */
    (void *) __glnop_Nop2,		/* BindTexture */
    (void *) __glnop_Nop2,		/* DeleteTextures */
    (void *) __glnop_Nop2,		/* GenTextures */
    (void *) __glnop_Nop1,		/* IsTexture */
    (void *) __glnop_Nop3,		/* PrioritizeTextures */
    (void *) __glnop_Nop1,		/* Indexub */
    (void *) __glnop_Nop1,		/* Indexubv */
    (void *) __glnop_Nop0,		/* PopClientAttrib */
    (void *) __glnop_Nop1,		/* PushClientAttrib */
    },

    /*
    ** extensions
    */
    {
    (void *) __glnop_Nop1,		/* ArrayElementEXT */
    (void *) __glnop_Nop5,		/* ColorPointerEXT */
    (void *) __glnop_Nop3,		/* DrawArraysEXT */
    (void *) __glnop_Nop3,		/* EdgeFlagPointerEXT */
    (void *) __glnop_Nop2,		/* GetPointervEXT */
    (void *) __glnop_Nop4,		/* IndexPointerEXT */
    (void *) __glnop_Nop4,		/* NormalPointerEXT */
    (void *) __glnop_Nop5,		/* TexCoordPointerEXT */
    (void *) __glnop_Nop5,		/* VertexPointerEXT */
    (void *) __glnop_Nop6,		/* ColorSubTableEXT */
    (void *) __glnop_Nop6,		/* ColorTableEXT */
    (void *) __glnop_Nop5,		/* CopyColorTableEXT */
    (void *) __glnop_Nop4,		/* GetColorTableEXT */
    (void *) __glnop_Nop3,		/* GetColorTableParameterfvEXT */
    (void *) __glnop_Nop3,		/* GetColorTableParameterivEXT */
    (void *) __glnop_Nop2,		/* LockArraysSGI */
    (void *) __glnop_Nop0,		/* UnlockArraysSGI */
    (void *) __glnop_Nop1,		/* CullParameterdvSGI */
    (void *) __glnop_Nop1,		/* CullParameterfvSGI */
    (void *) __glnop_Nop2,		/* IndexFuncSGI */
    (void *) __glnop_Nop2,		/* IndexMaterialSGI */
    (void *) __glnop_Nop4,		/* AddSwapHintRectWIN */
    },
};


