#! smake

AG		= ..\tools\ag\ag.exe

# Assembler Generator files 
AGFILES		= geom_og.c

# Targets
TARGETS		= $(AGFILES)

LDIRT		= *.tmp *~

#default: $(TARGETS)

!include $(BUILD_ROOT_SWLIBS)/include/nmake/3dfx.mak

#include $(COMMONRULES)

geom_og.c: geom_og.ag $(AG)
	$(AG) < geom_og.ag > geom_og.c

