#
# Copyright (c) 1997, 3Dfx Interactive, Inc.
# All Rights Reserved.
#
# This is UNPUBLISHED PROPRIETARY SOURCE CODE of 3Dfx Interactive, Inc.;
# the contents of this file may not be disclosed to third parties, copied or
# duplicated in any form, in whole or in part, without the prior written
# permission of 3Dfx Interactive, Inc.
#
# RESTRICTED RIGHTS LEGEND:
# Use, duplication or disclosure by the Government is subject to restrictions
# as set forth in subdivision (c)(1)(ii) of the Rights in Technical Data
# and Computer Software clause at DFARS 252.227-7013, and/or in similar or
# successor clauses in the FAR, DOD or NASA FAR Supplement. Unpublished  -
# rights reserved under the Copyright Laws of the United States.
#
# $Revision: 5 $
# $Date: 9/03/95 8:15p $
#

# Build Options: define these either in environment or makefile
#
# define HAL_CSIM to include the C simulator and interface into the HAL code
# define HAL_HSIM to include the VCS simulator interface into the HAL code
# define HAL_HW   to include the real HardWare interface into the HAL code
#

# on unix machines, compile for CSIM and HSIM
HAL_CSIM=1
HAL_HSIM=1
#HAL_HW=1

ifdef HAL_HW
HALDEFS = -DHAL_HW
else
HALDEFS =
endif

ifdef HAL_HSIM
HALDEFS := $(HALDEFS) -DHAL_HSIM
# the HSIM requires the CSIM also
HAL_CSIM=1
endif

ifdef HAL_CSIM
HALDEFS := $(HALDEFS) -DHAL_CSIM
endif

# local defines, options, includes
LCDEFS	= -DBUILD_HAL $(HALDEFS)
#LCDEFS	= -DBUILD_HAL $(HALDEFS) -DGUI=WIN32
LCDEFS  = -DH4 -DBUILD_HAL $(HALDEFS) 
LADEFS	= -DIS_32
LCOPTS	=
LCINCS	= -I$(BUILD_ROOT_SWLIBS)/include -I$(BUILD_ROOT)/$(FX_GLIDE_HW)/include -I$(TDFX_COMMONROOT)/src/tests/diags

# sources
#HEADERS	= 
PRIVATE_HEADERS = gui.h init.h ../incsrc/fxhal.h ../csim/csim.h
CFILES	= dllmain.c gdebug.c fxhal.c halio.c agpio.c info.c guim.c guiv.c util.c video.c
RCFILE	= init.rc
RCFILE  = gui.rc


INSTALL_DESTINATION = $(BUILD_ROOT)/$(FX_GLIDE_HW)

# targets
LIBRARIES= h4hal.a

FX_DLL_LIBRARY=1

include $(BUILD_ROOT_SWLIBS)/include/make/3dfx.mak

