PROGRAM = view.exe

FX_TARGET_MINOR=WIN32

!include $(BUILD_ROOT_ARCADE)\include\atdemo.mak

CFILES = view.c flip.c strview.c material.c triset.c nodeedit.c bldmesh.c \
         about.c loadpath.c image.c process.c

RCFILE = view.rc

LCINCS  = -I$(MGSDK)\dist\inc $(LCINCS) \
          -I$(BUILD_ROOT_ARCADE)\src\atd

!include $(BUILD_ROOT_SWLIBS)\include\nmake\3dfx.mak
