#
# Copyright (c) 1997, 3Dfx Interactive, Inc.
# All Rights Reserved.
#
# This is UNPUBLISHED PROPRIETARY SOURCE CODE of 3Dfx Interactive, Inc.;
# the contents of this file may not be disclosed to third parties, copied or
# duplicated in any form, in whole or in part, without the prior written
# permission of 3Dfx Interactive, Inc.
#
# RESTRICTED RIGHTS LEGEND:
# Use, duplication or disclosure by the Government is subject to restrictions
# as set forth in subdivision (c)(1)(ii) of the Rights in Technical Data
# and Computer Software clause at DFARS 252.227-7013, and/or in similar or
# successor clauses in the FAR, DOD or NASA FAR Supplement. Unpublished  -
# rights reserved under the Copyright Laws of the United States.
#
# $Revision: 28 $
# $Date: 7/02/98 3:13p $
#

CFILES	=	bgblock1.c	\
		bgblock2.c	\
		block.c		\
		blt.c		\
		clip1.c		\
		clip2.c		\
		clip3.c		\
		cmd1.c		\
		destread.c	\
		greg.c		\
		gst1.c		\
		guinop.c	\
		guiperf.c	\
		hang_hblt.c	\
		hblt.c		\
		jsr.c		\
		gline.c		\
		linerev.c	\
		lstip.c		\
		pattern.c	\
		poly.c		\
		poly2.c		\
		poly3.c		\
		randpoly.c	\
		rblt.c		\
		rect.c		\
		sblt.c		\
		scr2scr.c	\
		sgram_reg.c	\
		stress_bw.c	\
		stress2d.c	\
		updatexy.c	\
		align.c		\
		hbltalgn.c

!include ../diags.mak
