//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by atdemo.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_ATB                         128
#define IDR_DEMOMENU                    128
#define IDR_DEMOTYPE                    129
#define IDI_ICON1                       130
#define IDD_ERROR                       131
#define ID_END_TASK                     1000
#define IDC_ERROR_ICON                  1001
#define IDC_ERROR_MESSAGE               1002
#define IDC_DRIVER_NAME                 1003
#define IDC_FB_MEM                      1004
#define IDC_TFX0_MEM                    1005
#define IDC_TFX1_MEM                    1006
#define IDC_LABEL_TMU1                  1007
#define ID_SCREENPRINT                  32771
#define ID_EVENT_RESET                  32772
#define ID_EVENT_PLAYBACK               32773
#define ID_EVENT_RECORD                 32774
#define ID_MISC_PERFORMANCE             32775
#define ID_MISC_PERFORMANCEFULL         32776
#define ID_MISC_VSYNC                   32777
#define ID_MISC_SOUND                   32778
#define ID_RENDER_FOG                   40016
#define ID_RENDER_BILINEAR              40017
#define ID_RENDER_MIPMAPPING            40018
#define ID_RENDER_WIREFRAME             40019
#define ID_RENDER_TEXTURING             40020
#define ID_JOYCAL                       40025

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32779
#define _APS_NEXT_CONTROL_VALUE         1008
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
