#
# Copyright (c) 1995, 3Dfx Interactive, Inc.
# All Rights Reserved.
#
# This is UNPUBLISHED PROPRIETARY SOURCE CODE of 3Dfx Interactive, Inc.;
# the contents of this file may not be disclosed to third parties, copied or
# duplicated in any form, in whole or in part, without the prior written
# permission of 3Dfx Interactive, Inc.
#
# RESTRICTED RIGHTS LEGEND:
# Use, duplication or disclosure by the Government is subject to restrictions
# as set forth in subdivision (c)(1)(ii) of the Rights in Technical Data
# and Computer Software clause at DFARS 252.227-7013, and/or in similar or
# successor clauses in the FAR, DOD or NASA FAR Supplement. Unpublished  -
# rights reserved under the Copyright Laws of the United States.
#


# ARCADE TOOLBOX COMPILATION FLAGS
#
# -DAT_BUILD_LIBRARY - Defined when building the library
#
# -DAT_DEBUGGING  - Enable parameter checking and bug catching code.
# -DAT_PRODUCTION - Disable parameter checking and debugging code.
#                   Use this with optimized builds

# Preprocessor Defines
LCDEFS  = -DAT_BUILD_LIBRARY
LCINCS  = -I. -I$(BUILD_ROOT_ARCADE)\include -I$(BUILD_ROOT_GCI)\include \
          -I$(BUILD_ROOT)\$(FX_GLIDE_HW)\include
LCOPTS  =


!if "$(DEBUG)"=="1"
VCDEFS  = -DAT_DEBUGGING $(VCDEFS) 
!else
VCDEFS  = -DAT_PRODUCTION $(VCDEFS)
!endif

!if "$(BENCHMARK)"=="1"
VCDEFS  = -DBENCHMARK $(VCDEFS)
!endif

# sources
INSTALL_DESTINATION = $(BUILD_ROOT_ARCADE)
HEADERS             = atdemo.h atdemo.rc atdres.h atdemop.h
!if "$(FX_TARGET)"=="WIN32"
CFILES              = $(CFILES) appwin.c appdos.c about.c
!else if "$(FX_TARGET)"=="DOS"
CFILES              = $(CFILES) appdos.c
!endif
CFILES              = $(CFILES) atdemo.c gfxinit.c standard.c dump.c joystick.c

# targets
LIBRARIES    = atd.lib

!include $(BUILD_ROOT_SWLIBS)/include/nmake/3dfx.mak

