#
# Copyright (c) 1995, 3Dfx Interactive, Inc.
# All Rights Reserved.
#
# This is UNPUBLISHED PROPRIETARY SOURCE CODE of 3Dfx Interactive, Inc.;
# the contents of this file may not be disclosed to third parties, copied or
# duplicated in any form, in whole or in part, without the prior written
# permission of 3Dfx Interactive, Inc.
#
# RESTRICTED RIGHTS LEGEND:
# Use, duplication or disclosure by the Government is subject to restrictions
# as set forth in subdivision (c)(1)(ii) of the Rights in Technical Data
# and Computer Software clause at DFARS 252.227-7013, and/or in similar or
# successor clauses in the FAR, DOD or NASA FAR Supplement. Unpublished  -
# rights reserved under the Copyright Laws of the United States.
#
# $Revision: 7 $
# $Date: 9/03/95 11:58a $
#

CFILES	=	ablend.c	\
		aclamp.c	\
		acu.c		\
		afunc.c		\
		aiter.c		\
		altmap.c	\
		amask.c		\
		awmask.c	\
		ccu.c		\
		ccurand.c	\
		chip.c		\
		chroma.c	\
		dither2.c	\
		dither4.c	\
		fastfill.c	\
		faststate.c	\
		fogmodes.c	\
		fogtable.c	\
		freg.c		\
		ioreg.c		\
		lfbread.c	\
		lfbread1.c	\
		lfbwrite.c	\
		lines.c		\
		lines1.c	\
		mcrawlfb.c	\
		nop.c		\
		nop1.c		\
                nothing.c       \
		packets.c       \
		peter.c		\
		pixreg.c	\
		point.c		\
		rawlfb.c	\
		rectclip.c	\
		register.c	\
		rgbclamp.c	\
		rgbiter.c	\
		rgbmask.c	\
		rgbtri.c	\
		rgbtri1.c	\
		rgbatri.c	\
		rgbztri.c	\
		stipple.c	\
		stfunc.c	\
		stmask.c	\
		stop.c		\
		stress1.c	\
		stress2.c	\
		stress3.c	\
		stress4.c	\
		stress5.c	\
		stress7.c	\
		stress8.c	\
		stress9.c	\
		swap2.c		\
		triangle.c	\
		tsu.c		\
		tsubench.c	\
		wbuffer.c	\
		wbias.c		\
		wclamp.c	\
		yorigin.c	\
		yuv.c		\
		zbias.c		\
		zclamp.c	\
		zfbuffer.c	\
		zfunc.c		\
		ziter.c		\
		zmask.c		\
		ztri.c          \
                touchmemory.c  

include ../diagsu.mak
