LDIRT= *.exe *.map *.sys *.obj *.lib

LCINCS  = $(LCINCS)  -I$(BUILD_ROOT_SST1)\include

WINUTIL = winutil.obj
LLDLIBS = $(LLDLIBS) $(BUILD_ROOT_SST1)\lib\glide2x.lib $(LIB)\opengl32.lib $(LIB)\glu32.lib $(WINUTIL)

CFILES   = \
	depth.c \
	drawpix.c \
	enable.c \
	polymode.c \
	proxy.c \
	readpix.c \
	simple.c \
	texalloc.c \
	texenv.c \
	texpersp.c \
	texparam.c \
	texsize.c \
	texture.c \
	$(NULL)

PROGRAMS = $(CFILES:.c=.exe)

!include $(BUILD_ROOT_SWLIBS)/include/nmake/3dfx.mak

$(PROGRAMS):  $(LLDLIBS)

wperlin: wperlin.obj winutil.obj
	$(LINK) -o wperlin.exe wperlin.obj winutil.obj $(LDFLAGS) $(LDLIBS)

