# GLD Interface Functions

# glr_version.c
gldGetVersion
gldGetString

# glr_format.c
gldChoosePixelFormat
gldDestroyPixelFormat

# glr_info.c
gldGetRendererInfo

# glr_context.c
gldCreateContext
gldDestroyContext

# glr_drawable.c
gldAttachDrawable

# glr_accessors.c
gldSetInteger
gldGetInteger

# glr_dispatch.c
gldGetRenderDispatch
gldGetSystemDispatch

# glr_texture_managment.c
gldCreateTexture
gldModifyTexture
gldDeleteTexture
gldBindTexture
gldIsTextureResident

# glr_vertex_buffers.c
gldAllocVertexBuffer
gldCompleteVertexBuffer
gldFreeVertexBuffer
gldBeginPrimitiveBuffer

# glr_error.c
gldGetError

# glr_buffer.c
# (obsolete) gldLockBuffers
# (obsolete) gldUnlockBuffers

