#
# Copyright (c) 1995, 3Dfx Interactive, Inc.
# All Rights Reserved.
#
# This is UNPUBLISHED PROPRIETARY SOURCE CODE of 3Dfx Interactive, Inc.;
# the contents of this file may not be disclosed to third parties, copied or
# duplicated in any form, in whole or in part, without the prior written
# permission of 3Dfx Interactive, Inc.
#
# RESTRICTED RIGHTS LEGEND:
# Use, duplication or disclosure by the Government is subject to restrictions
# as set forth in subdivision (c)(1)(ii) of the Rights in Technical Data
# and Computer Software clause at DFARS 252.227-7013, and/or in similar or
# successor clauses in the FAR, DOD or NASA FAR Supplement. Unpublished  -
# rights reserved under the Copyright Laws of the United States.
#


# ARCADE TOOLBOX COMPILATION FLAGS
#
# -DAT_BUILD_LIBRARY - Defined when building the library
#
# -DAT_DEBUGGING  - Enable parameter checking and bug catching code.
# -DAT_PRODUCTION - Disable parameter checking and debugging code.
#                   Use this with optimized builds
# -DAT_STATISTICS       - Include statistic tracking code.
# -DAT_PENTIUM_ASSEMBLY - Use pentium optimized assembly routines
# -DAT_CHECK_TRIS       - Check every triangle against screen
#

# Preprocessor Defines
LCDEFS  = -DAT_BUILD_LIBRARY
LCINCS  = -I. -I$(BUILD_ROOT_ARCADE)\include -I$(BUILD_ROOT_GCI)\include
LCOPTS  = 

!if "$(DEBUG)"=="1"
VCDEFS  = -DAT_DEBUGGING $(VCDEFS) 
!else
VCDEFS  = -DAT_PRODUCTION $(VCDEFS)
!endif

# sources
HEADERS             = atinput.h joy.h resource.h
INSTALL_DESTINATION = $(BUILD_ROOT_ARCADE)
CFILES              = atinput.c
!if "$(FX_TARGET)"=="WIN32"
LCDEFS  = -DAT_INPUT_DIRECTX $(LCDEFS)
CFILES = $(CFILES) inpwin.c
!else
!if "$(FX_COMPILER)" != "DJGPP"
CFILES = $(CFILES) joy.c inpdos.c
!endif
!endif

!if "$(FX_COMPILER)" != "DJGPP"
SUBLIBRARIES = $(BUILD_ROOT_GCI)\lib\gci.lib \
!endif

# targets
LIBRARIES    = ati.lib

!include $(BUILD_ROOT_SWLIBS)/include/nmake/3dfx.mak
