TOP=..

include ../make.config

vpath %.obj $(OBJDIR)

SRCS= \
	g_ztest.c \
	g_texel.c  \
	fr_pick.c  \
	g_citri.c  \
	g_rgbtri.c  \
	g_cipix.c  \
	g_cicmb.c  \
	g_ciclr.c  \
	g_rgbpx5.c  \
	g_rgbpx4.c  \
	g_rgbpx2.c  \
	g_rgbpxa.c  \
	g_rgbcba.c  \
	g_rgbcl2.c  \
	g_rgbcla.c  \
	g_rgbcb4.c  \
	g_rgbcl4.c  \
	g_rgbcl5.c  \
	g_rgbcb5.c  \
	g_rgbcb2.c  \
	fr_og.c  \
	fr_tex.c  \
	fr_stncl.c  \
	og.c  \
	fr_sqrs.c  \
	ras_og.c  \
	og_cache.c  \
	fr_setup.c  \
	fr_store.c

ICDSRCS=
STANDSRCS=

OBJS=$(SRCS:.c=.obj)
ICDOBJS=$(ICDSRCS:.c=.obj)
STANDOBJS=$(STANDSRCS:.c=.obj)

ifeq ($(MODEL),icd)
OBJS += $(ICDOBJS)
else
OBJS += $(STANDOBJS)
endif

all: $(OBJS)

$(OBJS): %.obj : %.c
	$(CC) $(CFLAGS) /Fo$(OBJDIR)/$*.obj -c $*.c

clean:
	$(RM) $(OBJS:%=$(OBJDIR)/%) $(STANDOBJS:%=$(OBJDIR)/%) $(ICDOBJS:%=$(OBJDIR)/%)

depend:
	$(MKDEPEND) .depend $(SRCS) $(STANDSRCS) $(ICDSRCS)

sinclude .depend
