##########################
#                        #
#  User settable macros  #
#                        #
##########################

Compiler         = wcc
Compiler_Options = -zw /g /s /3
                  
Obj = altgdi.obj dpmi.obj gdientry.obj


####################
#                  #
#  Makefile rules  #
#                  #
####################

altgdi.exe : $(Obj) altgdi.lnk
    wlink @altgdi.lnk

.c.obj:
    *$(Compiler) $(Compiler_Options) $<

